Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: RetryAction Class Reference
RetryAction Class Reference
Public Member Functions
None __init__ (self, t.SupportsFloat sleep)
Public Member Functions inherited from BaseAction
str __repr__ (self)
str __str__ (self)
Data Fields
sleep = float(sleep)
Additional Inherited Members
Static Public Attributes inherited from BaseAction
tuple REPR_FIELDS = ()
t NAME = None
Detailed Description
Definition at line 136 of file __init__.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, t.SupportsFloat sleep)
Definition at line 140 of file __init__.py.
    def __init__(self, sleep: t.SupportsFloat) -> None:
        self.sleep = float(sleep)
Field Documentation
sleep
sleep = float(sleep)
Definition at line 141 of file __init__.py.
Referenced by AsyncRetrying.__anext__(), AsyncRetrying.__call__(), Retrying.__call__(), TornadoRetrying.__call__(), AsyncRetrying.__init__(), BaseRetrying.__iter__(), and BaseRetrying.copy().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/tenacity/__init__.py