Let us walk on the 3-isogeny graph: BaseAdapter Class Reference
BaseAdapter Class Reference
Public Member Functions
__init__ (self)
send (self, request, stream=False, timeout=None, verify=True, cert=None, proxies=None)
close (self)
Detailed Description
The Base Transport Adapter
Definition at line 70 of file adapters.py.
Constructor & Destructor Documentation
__init__()
__init__ (self)
Reimplemented in CacheControlAdapter, and HTTPAdapter.
Definition at line 73 of file adapters.py.
    def __init__(self):
        super().__init__()
Referenced by Protocol.__init_subclass__().
Member Function Documentation
close()
close (self)
Cleans up adapter specific items.
Reimplemented in CacheControlAdapter, and HTTPAdapter.
Definition at line 95 of file adapters.py.
    def close(self):
        """Cleans up adapter specific items."""
        raise NotImplementedError
Referenced by SSLTransport.__exit__(), Response.__exit__(), Session.__exit__(), ZipExtFile.__exit__(), ZipFile.__exit__(), ConnectionPool.__exit__(), _Reader.__exit__(), WrappedSocket._custom_validate(), WrappedSocket._decref_socketios(), WrappedSocket._drop(), WrappedSocket._raise_on_error(), HTTPResponse._update_chunk_length(), and WrappedSocket.recv_into().
send()
send (self, request, stream = False, timeout = None, verify = True, cert = None, proxies = None)
Sends PreparedRequest object. Returns Response object.
:param request: The :class:`PreparedRequest <PreparedRequest>` being sent.
:param stream: (optional) Whether to stream the request content.
:param timeout: (optional) How long to wait for the server to send
    data before giving up, as a float, or a :ref:`(connect timeout,
    read timeout) <timeouts>` tuple.
:type timeout: float or tuple
:param verify: (optional) Either a boolean, in which case it controls whether we verify
    the server's TLS certificate, or a string, in which case it must be a path
    to a CA bundle to use
:param cert: (optional) Any user-provided SSL certificate to be trusted.
:param proxies: (optional) The proxies dictionary to apply to the request.
Reimplemented in CacheControlAdapter, and HTTPAdapter.
Definition at line 76 of file adapters.py.
    ):
        """Sends PreparedRequest object. Returns Response object.
        :param request: The :class:`PreparedRequest <PreparedRequest>` being sent.
        :param stream: (optional) Whether to stream the request content.
        :param timeout: (optional) How long to wait for the server to send
            data before giving up, as a float, or a :ref:`(connect timeout,
            read timeout) <timeouts>` tuple.
        :type timeout: float or tuple
        :param verify: (optional) Either a boolean, in which case it controls whether we verify
            the server's TLS certificate, or a string, in which case it must be a path
            to a CA bundle to use
        :param cert: (optional) Any user-provided SSL certificate to be trusted.
        :param proxies: (optional) The proxies dictionary to apply to the request.
        """
        raise NotImplementedError
Referenced by Session.request(), HTTPConnection.request_chunked(), WrappedSocket.sendall(), and SSLTransport.sendall().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/requests/adapters.py