Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Requirement Class Reference
Requirement Class Reference
Public Member Functions
__init__ (self, requirement_string)
__eq__ (self, other)
__ne__ (self, other)
__contains__ (self, item)
__hash__ (self)
__repr__ (self)
Public Member Functions inherited from Requirement
None __init__ (self, str requirement_string)
str __str__ (self)
str __repr__ (self)
Static Public Member Functions
parse (s)
Data Fields
unsafe_name = self.name
project_name
key = project_name, project_name.lower()
list specs = [(spec.operator, spec.version) for spec in self.specifier]
tuple hashCmp
Data Fields inherited from Requirement
str name = req.name
TOptional[str] url = req.url
Set[str] extras = set(req.extras.asList() if req.extras else [])
SpecifierSet specifier = SpecifierSet(req.specifier)
TOptional[Marker] marker = req.marker if req.marker else None
Detailed Description
Definition at line 3171 of file __init__.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, requirement_string)
DO NOT CALL THIS UNDOCUMENTED METHOD; use Requirement.parse()!
Definition at line 3172 of file __init__.py.
    def __init__(self, requirement_string):
        """DO NOT CALL THIS UNDOCUMENTED METHOD; use Requirement.parse()!"""
        super(Requirement, self).__init__(requirement_string)
        self.unsafe_name = self.name
        project_name = safe_name(self.name)
        self.project_name, self.key = project_name, project_name.lower()
        self.specs = [(spec.operator, spec.version) for spec in self.specifier]
        self.extras = tuple(map(safe_extra, self.extras))
        self.hashCmp = (
            self.key,
            self.url,
            self.specifier,
            frozenset(self.extras),
            str(self.marker) if self.marker else None,
        )
        self.__hash = hash(self.hashCmp)
Member Function Documentation
__contains__()
__contains__ (self, item)
Definition at line 3195 of file __init__.py.
    def __contains__(self, item):
        if isinstance(item, Distribution):
            if item.key != self.key:
                return False
            item = item.version
        # Allow prereleases always in order to match the previous behavior of
        # this method. In the future this should be smarter and follow PEP 440
        # more accurately.
        return self.specifier.contains(item, prereleases=True)
__eq__()
__eq__ (self, other)
Definition at line 3189 of file __init__.py.
    def __eq__(self, other):
        return isinstance(other, Requirement) and self.hashCmp == other.hashCmp
Referenced by HTTPHeaderDict.__ne__().
__hash__()
__hash__ (self)
Definition at line 3207 of file __init__.py.
    def __hash__(self):
        return self.__hash
Referenced by Style.__eq__(), and Style.__ne__().
__ne__()
__ne__ (self, other)
Definition at line 3192 of file __init__.py.
    def __ne__(self, other):
        return not self == other
__repr__()
__repr__ (self)
Definition at line 3210 of file __init__.py.
    def __repr__(self):
        return "Requirement.parse(%r)" % str(self)
parse()
parse (s) static
Definition at line 3214 of file __init__.py.
    def parse(s):
        (req,) = parse_requirements(s)
        return req
Referenced by Style.normalize().
Field Documentation
hashCmp
tuple hashCmp
Initial value:
=  (
            self.key,
            self.url,
            self.specifier,
            frozenset(self.extras),
            str(self.marker) if self.marker else None,
        )
Definition at line 3180 of file __init__.py.
key
key = project_name, project_name.lower()
Definition at line 3177 of file __init__.py.
Referenced by SelfCheckState.set().
project_name
project_name
Definition at line 3177 of file __init__.py.
Referenced by _InstallRequirementBackedCandidate.name(), and AlreadyInstalledCandidate.name().
specs
list specs = [(spec.operator, spec.version) for spec in self.specifier]
Definition at line 3178 of file __init__.py.
unsafe_name
unsafe_name = self.name
Definition at line 3175 of file __init__.py.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py