Let us walk on the 3-isogeny graph: LegacyMatcher Class Reference
LegacyMatcher Class Reference
Static Public Attributes
version_class = LegacyVersion
numeric_re = re.compile(r'^(\d+(\.\d+)*)')
Static Public Attributes inherited from Matcher
version_class = None
Protected Member Functions
_match_compatible (self, version, constraint, prefix)
Protected Member Functions inherited from Matcher
_check_compatible (self, other)
Static Protected Attributes
_operators = dict(Matcher._operators)
Static Protected Attributes inherited from Matcher
dict _operators
Additional Inherited Members
Public Member Functions inherited from Matcher
parse_requirement (self, s)
__init__ (self, s)
match (self, version)
exact_version (self)
__eq__ (self, other)
__ne__ (self, other)
__hash__ (self)
__repr__ (self)
__str__ (self)
Data Fields inherited from Matcher
name
key
Protected Attributes inherited from Matcher
_string
_parts
Detailed Description
Definition at line 619 of file version.py.
Member Function Documentation
_match_compatible()
_match_compatible (self, version, constraint, prefix) protected
Definition at line 627 of file version.py.
    def _match_compatible(self, version, constraint, prefix):
        if version < constraint:
            return False
        m = self.numeric_re.match(str(constraint))
        if not m:
            logger.warning('Cannot compute compatible match for version %s '
                           ' and constraint %s', version, constraint)
            return True
        s = m.groups()[0]
        if '.' in s:
            s = s.rsplit('.', 1)[0]
        return _match_prefix(version, s)
#
#   Semantic versioning
#
References pip._vendor.distlib.version._match_prefix(), i, Matcher.match(), and LegacyMatcher.numeric_re.
Field Documentation
_operators
_operators = dict(Matcher._operators) static protected
Definition at line 622 of file version.py.
Referenced by Matcher.match().
numeric_re
numeric_re = re.compile(r'^(\d+(\.\d+)*)') static
Definition at line 625 of file version.py.
Referenced by LegacyMatcher._match_compatible().
version_class
version_class = LegacyVersion static
Definition at line 620 of file version.py.
Referenced by Matcher.__init__(), NormalizedMatcher._adjust_local(), and Matcher.match().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/version.py