Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: MockRequest Class Reference
MockRequest Class Reference
Public Member Functions
__init__ (self, request)
get_type (self)
get_host (self)
get_origin_req_host (self)
get_full_url (self)
is_unverifiable (self)
has_header (self, name)
get_header (self, name, default=None)
add_header (self, key, val)
add_unredirected_header (self, name, value)
get_new_headers (self)
unverifiable (self)
origin_req_host (self)
host (self)
Data Fields
type = urlparse(self._r.url).scheme
Protected Attributes
_r = request
dict _new_headers = {}
Detailed Description
Wraps a `requests.Request` to mimic a `urllib2.Request`.
The code in `cookielib.CookieJar` expects this interface in order to correctly
manage cookie policies, i.e., determine whether a cookie can be set, given the
domains of the request and the cookie.
The original request object is read-only. The client is responsible for collecting
the new headers via `get_new_headers()` and interpreting them appropriately. You
probably want `get_cookie_header`, defined below.
Definition at line 23 of file cookies.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, request)
Definition at line 35 of file cookies.py.
    def __init__(self, request):
        self._r = request
        self._new_headers = {}
        self.type = urlparse(self._r.url).scheme
Member Function Documentation
add_header()
add_header (self, key, val)
cookielib has no legitimate use for this method; add it back if you find one.
Definition at line 78 of file cookies.py.
    def add_header(self, key, val):
        """cookielib has no legitimate use for this method; add it back if you find one."""
        raise NotImplementedError(
            "Cookie headers should be added with add_unredirected_header()"
        )
add_unredirected_header()
add_unredirected_header (self, name, value)
Definition at line 84 of file cookies.py.
    def add_unredirected_header(self, name, value):
        self._new_headers[name] = value
References _new_headers.
get_full_url()
get_full_url (self)
Definition at line 49 of file cookies.py.
    def get_full_url(self):
        # Only return the response's URL if the user hadn't set the Host
        # header
        if not self._r.headers.get("Host"):
            return self._r.url
        # If they did set it, retrieve it and reconstruct the expected domain
        host = to_native_string(self._r.headers["Host"], encoding="utf-8")
        parsed = urlparse(self._r.url)
        # Reconstruct the URL as we expect it
        return urlunparse(
            [
                parsed.scheme,
                host,
                parsed.path,
                parsed.params,
                parsed.query,
                parsed.fragment,
            ]
        )
References _r.
get_header()
get_header (self, name, default = None)
Definition at line 75 of file cookies.py.
    def get_header(self, name, default=None):
        return self._r.headers.get(name, self._new_headers.get(name, default))
References _new_headers, and _r.
get_host()
get_host (self)
Definition at line 43 of file cookies.py.
    def get_host(self):
        return urlparse(self._r.url).netloc
References _r.
Referenced by get_origin_req_host(), and host().
get_new_headers()
get_new_headers (self)
Definition at line 87 of file cookies.py.
    def get_new_headers(self):
        return self._new_headers
References _new_headers.
get_origin_req_host()
get_origin_req_host (self)
Definition at line 46 of file cookies.py.
    def get_origin_req_host(self):
        return self.get_host()
References get_host().
Referenced by origin_req_host().
get_type()
get_type (self)
Definition at line 40 of file cookies.py.
    def get_type(self):
        return self.type
References type.
has_header()
has_header (self, name)
Definition at line 72 of file cookies.py.
    def has_header(self, name):
        return name in self._r.headers or name in self._new_headers
References _new_headers, and _r.
host()
host (self)
Definition at line 99 of file cookies.py.
    def host(self):
        return self.get_host()
References get_host().
is_unverifiable()
is_unverifiable (self)
Definition at line 69 of file cookies.py.
    def is_unverifiable(self):
        return True
Referenced by unverifiable().
origin_req_host()
origin_req_host (self)
Definition at line 95 of file cookies.py.
    def origin_req_host(self):
        return self.get_origin_req_host()
References get_origin_req_host().
unverifiable()
unverifiable (self)
Definition at line 91 of file cookies.py.
    def unverifiable(self):
        return self.is_unverifiable()
References is_unverifiable().
Field Documentation
_new_headers
dict _new_headers = {} protected
Definition at line 37 of file cookies.py.
Referenced by add_unredirected_header(), get_header(), get_new_headers(), and has_header().
_r
_r = request protected
Definition at line 36 of file cookies.py.
Referenced by Resolution._add_to_criteria(), Resolution._attempt_to_pin_criterion(), get_full_url(), get_header(), get_host(), has_header(), and Resolution.resolve().
type
type = urlparse(self._r.url).scheme
Definition at line 38 of file cookies.py.
Referenced by Color.__rich_repr__(), Color.downgrade(), Color.get_ansi_codes(), Color.get_truecolor(), get_type(), and Color.is_default().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/requests/cookies.py