Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Marker Class Reference
Marker Class Reference
Public Member Functions
None __init__ (self, str marker)
str __str__ (self)
str __repr__ (self)
bool evaluate (self, Optional[Dict[str, str]] environment=None)
Protected Attributes
_markers = _coerce_parse_result(MARKER.parseString(marker))
Detailed Description
Definition at line 275 of file markers.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, str marker)
Definition at line 276 of file markers.py.
    def __init__(self, marker: str) -> None:
        try:
            self._markers = _coerce_parse_result(MARKER.parseString(marker))
        except ParseException as e:
            raise InvalidMarker(
                f"Invalid marker: {marker!r}, parse error at "
                f"{marker[e.loc : e.loc + 8]!r}"
            )
Member Function Documentation
__repr__()
str __repr__ (self)
Definition at line 288 of file markers.py.
    def __repr__(self) -> str:
        return f"<Marker('{self}')>"
__str__()
str __str__ (self)
Definition at line 285 of file markers.py.
    def __str__(self) -> str:
        return _format_marker(self._markers)
References pip._vendor.packaging.markers._format_marker(), and _markers.
evaluate()
bool evaluate (self, Optional[Dict[str, str]] environment = None)
Evaluate a marker.
Return the boolean from evaluating the given marker against the
environment. environment is an optional argument to override all or
part of the determined environment.
The environment is determined from the current Python process.
Definition at line 291 of file markers.py.
    def evaluate(self, environment: Optional[Dict[str, str]] = None) -> bool:
        """Evaluate a marker.
        Return the boolean from evaluating the given marker against the
        environment. environment is an optional argument to override all or
        part of the determined environment.
        The environment is determined from the current Python process.
        """
        current_environment = default_environment()
        if environment is not None:
            current_environment.update(environment)
        return _evaluate_markers(self._markers, current_environment)
References pip._vendor.packaging.markers._evaluate_markers(), _markers, and pip._vendor.packaging.markers.default_environment().
Field Documentation
_markers
_markers = _coerce_parse_result(MARKER.parseString(marker)) protected
Definition at line 278 of file markers.py.
Referenced by __str__(), and evaluate().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/packaging/markers.py