Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: ParseBaseException Class Reference
ParseBaseException Class Reference
Public Member Functions
__init__ (self, str pstr, int loc=0, typing.Optional[str] msg=None, elem=None)
str line (self)
int lineno (self)
int col (self)
int column (self)
parserElement (self)
parserElement (self, elem)
str __str__ (self)
__repr__ (self)
str mark_input_line (self, typing.Optional[str] marker_string=None, *, str markerString=">!<")
str explain (self, depth=16)
markInputline (self)
Static Public Member Functions
explain_exception (exc, depth=16)
Data Fields
loc = loc
msg = pstr
str pstr = ""
Static Public Attributes
typing parser_element .Any
typing args .Tuple[str, int, typing.Optional[str]]
Protected Member Functions
_from_exception (cls, pe)
Detailed Description
base exception class for all parsing runtime exceptions
Definition at line 25 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, str pstr, int loc = 0, typing.Optional[str] msg = None, elem = None)
Definition at line 44 of file exceptions.py.
    ):
        self.loc = loc
        if msg is None:
            self.msg = pstr
            self.pstr = ""
        else:
            self.msg = msg
            self.pstr = pstr
        self.parser_element = elem
        self.args = (pstr, loc, msg)
Member Function Documentation
__repr__()
__repr__ (self)
Definition at line 188 of file exceptions.py.
    def __repr__(self):
        return str(self)
__str__()
str __str__ (self)
Definition at line 172 of file exceptions.py.
    def __str__(self) -> str:
        if self.pstr:
            if self.loc >= len(self.pstr):
                foundstr = ", found end of text"
            else:
                # pull out next word at error location
                found_match = _exception_word_extractor.match(self.pstr, self.loc)
                if found_match is not None:
                    found = found_match.group(0)
                else:
                    found = self.pstr[self.loc : self.loc + 1]
                foundstr = (", found %r" % found).replace(r"\\", "\\")
        else:
            foundstr = ""
        return f"{self.msg}{foundstr}  (at char {self.loc}), (line:{self.lineno}, col:{self.column})"
References loc, and pstr.
_from_exception()
_from_exception (cls, pe) protected
internal factory method to simplify creating one type of ParseException
from another - avoids having __init__ signature conflicts among subclasses
Definition at line 128 of file exceptions.py.
    def _from_exception(cls, pe):
        """
        internal factory method to simplify creating one type of ParseException
        from another - avoids having __init__ signature conflicts among subclasses
        """
        return cls(pe.pstr, pe.loc, pe.msg, pe.parser_element)
col()
int col (self)
Return the 1-based column on the line of text where the exception occurred.
Definition at line 150 of file exceptions.py.
    def col(self) -> int:
        """
        Return the 1-based column on the line of text where the exception occurred.
        """
        return col(self.loc, self.pstr)
References col(), loc, and pstr.
Referenced by col(), and column().
column()
int column (self)
Return the 1-based column on the line of text where the exception occurred.
Definition at line 157 of file exceptions.py.
    def column(self) -> int:
        """
        Return the 1-based column on the line of text where the exception occurred.
        """
        return col(self.loc, self.pstr)
References col(), loc, and pstr.
Referenced by mark_input_line().
explain()
str explain (self, depth = 16)
Method to translate the Python internal traceback into a list
of the pyparsing expressions that caused the exception to be raised.
Parameters:
- depth (default=16) - number of levels back in the stack trace to list expression
  and function names; if None, the full stack trace names will be listed; if 0, only
  the failing input line, marker, and exception string will be shown
Returns a multi-line string listing the ParserElements and/or function names in the
exception's stack trace.
Example::
    expr = pp.Word(pp.nums) * 3
    try:
        expr.parse_string("123 456 A789")
    except pp.ParseException as pe:
        print(pe.explain(depth=0))
prints::
    123 456 A789
            ^
    ParseException: Expected W:(0-9), found 'A'  (at char 8), (line:1, col:9)
Note: the diagnostic output will include string representations of the expressions
that failed to parse. These representations will be more helpful if you use `set_name` to
give identifiable names to your expressions. Otherwise they will use the default string
forms, which may be cryptic to read.
Note: pyparsing's default truncation of exception tracebacks may also truncate the
stack of expressions that are displayed in the ``explain`` output. To get the full listing
of parser expressions, you may have to set ``ParserElement.verbose_stacktrace = True``
Definition at line 207 of file exceptions.py.
    def explain(self, depth=16) -> str:
        """
        Method to translate the Python internal traceback into a list
        of the pyparsing expressions that caused the exception to be raised.
        Parameters:
        - depth (default=16) - number of levels back in the stack trace to list expression
          and function names; if None, the full stack trace names will be listed; if 0, only
          the failing input line, marker, and exception string will be shown
        Returns a multi-line string listing the ParserElements and/or function names in the
        exception's stack trace.
        Example::
            expr = pp.Word(pp.nums) * 3
            try:
                expr.parse_string("123 456 A789")
            except pp.ParseException as pe:
                print(pe.explain(depth=0))
        prints::
            123 456 A789
                    ^
            ParseException: Expected W:(0-9), found 'A'  (at char 8), (line:1, col:9)
        Note: the diagnostic output will include string representations of the expressions
        that failed to parse. These representations will be more helpful if you use `set_name` to
        give identifiable names to your expressions. Otherwise they will use the default string
        forms, which may be cryptic to read.
        Note: pyparsing's default truncation of exception tracebacks may also truncate the
        stack of expressions that are displayed in the ``explain`` output. To get the full listing
        of parser expressions, you may have to set ``ParserElement.verbose_stacktrace = True``
        """
        return self.explain_exception(self, depth)
References explain_exception().
explain_exception()
explain_exception (exc, depth = 16) static
Method to take an exception and translate the Python internal traceback into a list
of the pyparsing expressions that caused the exception to be raised.
Parameters:
- exc - exception raised during parsing (need not be a ParseException, in support
  of Python exceptions that might be raised in a parse action)
- depth (default=16) - number of levels back in the stack trace to list expression
  and function names; if None, the full stack trace names will be listed; if 0, only
  the failing input line, marker, and exception string will be shown
Returns a multi-line string listing the ParserElements and/or function names in the
exception's stack trace.
Definition at line 62 of file exceptions.py.
    def explain_exception(exc, depth=16):
        """
        Method to take an exception and translate the Python internal traceback into a list
        of the pyparsing expressions that caused the exception to be raised.
        Parameters:
        - exc - exception raised during parsing (need not be a ParseException, in support
          of Python exceptions that might be raised in a parse action)
        - depth (default=16) - number of levels back in the stack trace to list expression
          and function names; if None, the full stack trace names will be listed; if 0, only
          the failing input line, marker, and exception string will be shown
        Returns a multi-line string listing the ParserElements and/or function names in the
        exception's stack trace.
        """
        import inspect
        from .core import ParserElement
        if depth is None:
            depth = sys.getrecursionlimit()
        ret = []
        if isinstance(exc, ParseBaseException):
            ret.append(exc.line)
            ret.append(" " * (exc.column - 1) + "^")
        ret.append(f"{type(exc).__name__}: {exc}")
        if depth > 0:
            callers = inspect.getinnerframes(exc.__traceback__, context=depth)
            seen = set()
            for i, ff in enumerate(callers[-depth:]):
                frm = ff[0]
                f_self = frm.f_locals.get("self", None)
                if isinstance(f_self, ParserElement):
                    if not frm.f_code.co_name.startswith(
                        ("parseImpl", "_parseNoCache")
                    ):
                        continue
                    if id(f_self) in seen:
                        continue
                    seen.add(id(f_self))
                    self_type = type(f_self)
                    ret.append(
                        f"{self_type.__module__}.{self_type.__name__} - {f_self}"
                    )
                elif f_self is not None:
                    self_type = type(f_self)
                    ret.append(f"{self_type.__module__}.{self_type.__name__}")
                else:
                    code = frm.f_code
                    if code.co_name in ("wrapper", "<module>"):
                        continue
                    ret.append(code.co_name)
                depth -= 1
                if not depth:
                    break
        return "\n".join(ret)
Referenced by explain().
line()
str line (self)
Return the line of text where the exception occurred.
Definition at line 136 of file exceptions.py.
    def line(self) -> str:
        """
        Return the line of text where the exception occurred.
        """
        return line(self.loc, self.pstr)
References line(), loc, and pstr.
Referenced by line(), and mark_input_line().
lineno()
int lineno (self)
Return the 1-based line number of text where the exception occurred.
Definition at line 143 of file exceptions.py.
    def lineno(self) -> int:
        """
        Return the 1-based line number of text where the exception occurred.
        """
        return lineno(self.loc, self.pstr)
References lineno(), loc, and pstr.
Referenced by lineno().
mark_input_line()
str mark_input_line (self, typing.Optional[str] marker_string = None, * , str markerString = ">!<")
Extracts the exception line from the input string, and marks
the location of the exception with a special symbol.
Definition at line 191 of file exceptions.py.
    ) -> str:
        """
        Extracts the exception line from the input string, and marks
        the location of the exception with a special symbol.
        """
        markerString = marker_string if marker_string is not None else markerString
        line_str = self.line
        line_column = self.column - 1
        if markerString:
            line_str = "".join(
                (line_str[:line_column], markerString, line_str[line_column:])
            )
        return line_str.strip()
References column(), line(), and Frame.line.
markInputline()
markInputline (self)
Definition at line 248 of file exceptions.py.
    def markInputline(self): ...
parserElement() [1/2]
parserElement (self)
Definition at line 165 of file exceptions.py.
    def parserElement(self):
        return self.parser_element
References parser_element.
parserElement() [2/2]
parserElement (self, elem)
Definition at line 169 of file exceptions.py.
    def parserElement(self, elem):
        self.parser_element = elem
References parser_element.
Field Documentation
args
typing args .Tuple[str, int, typing.Optional[str]] static
Definition at line 32 of file exceptions.py.
Referenced by InvalidSchemeCombination.__str__().
loc
loc = loc
Definition at line 51 of file exceptions.py.
Referenced by __str__(), col(), column(), line(), and lineno().
msg
msg = pstr
Definition at line 53 of file exceptions.py.
parser_element
typing parser_element .Any static
Definition at line 31 of file exceptions.py.
Referenced by parserElement(), and parserElement().
pstr
pstr = ""
Definition at line 54 of file exceptions.py.
Referenced by __str__(), col(), column(), line(), and lineno().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/exceptions.py