Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: StashedUninstallPathSet Class Reference
StashedUninstallPathSet Class Reference
Public Member Functions
None __init__ (self)
str stash (self, str path)
None commit (self)
None rollback (self)
bool can_rollback (self)
Protected Member Functions
str _get_directory_stash (self, str path)
str _get_file_stash (self, str path)
Protected Attributes
dict _save_dirs = {}
list _moves = []
Detailed Description
A set of file rename operations to stash files while
tentatively uninstalling them.
Definition at line 201 of file req_uninstall.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Definition at line 205 of file req_uninstall.py.
    def __init__(self) -> None:
        # Mapping from source file root to [Adjacent]TempDirectory
        # for files under that directory.
        self._save_dirs: Dict[str, TempDirectory] = {}
        # (old path, new path) tuples for each move that may need
        # to be undone.
        self._moves: List[Tuple[str, str]] = []
Member Function Documentation
_get_directory_stash()
str _get_directory_stash (self, str path) protected
Stashes a directory.
Directories are stashed adjacent to their original location if
possible, or else moved/copied into the user's temp dir.
Definition at line 213 of file req_uninstall.py.
    def _get_directory_stash(self, path: str) -> str:
        """Stashes a directory.
        Directories are stashed adjacent to their original location if
        possible, or else moved/copied into the user's temp dir."""
        try:
            save_dir: TempDirectory = AdjacentTempDirectory(path)
        except OSError:
            save_dir = TempDirectory(kind="uninstall")
        self._save_dirs[os.path.normcase(path)] = save_dir
        return save_dir.path
References _save_dirs.
Referenced by stash().
_get_file_stash()
str _get_file_stash (self, str path) protected
Stashes a file.
If no root has been provided, one will be created for the directory
in the user's temp directory.
Definition at line 227 of file req_uninstall.py.
    def _get_file_stash(self, path: str) -> str:
        """Stashes a file.
        If no root has been provided, one will be created for the directory
        in the user's temp directory."""
        path = os.path.normcase(path)
        head, old_head = os.path.dirname(path), None
        save_dir = None
        while head != old_head:
            try:
                save_dir = self._save_dirs[head]
                break
            except KeyError:
                pass
            head, old_head = os.path.dirname(head), head
        else:
            # Did not find any suitable root
            head = os.path.dirname(path)
            save_dir = TempDirectory(kind="uninstall")
            self._save_dirs[head] = save_dir
        relpath = os.path.relpath(path, head)
        if relpath and relpath != os.path.curdir:
            return os.path.join(save_dir.path, relpath)
        return save_dir.path
References _save_dirs.
Referenced by stash().
can_rollback()
bool can_rollback (self)
Definition at line 302 of file req_uninstall.py.
    def can_rollback(self) -> bool:
        return bool(self._moves)
References _moves.
commit()
None commit (self)
Commits the uninstall by removing stashed files.
Definition at line 275 of file req_uninstall.py.
    def commit(self) -> None:
        """Commits the uninstall by removing stashed files."""
        for _, save_dir in self._save_dirs.items():
            save_dir.cleanup()
        self._moves = []
        self._save_dirs = {}
References _moves, and _save_dirs.
Referenced by rollback().
rollback()
None rollback (self)
Undoes the uninstall by moving stashed files back.
Definition at line 282 of file req_uninstall.py.
    def rollback(self) -> None:
        """Undoes the uninstall by moving stashed files back."""
        for p in self._moves:
            logger.info("Moving to %s\n from %s", *p)
        for new_path, path in self._moves:
            try:
                logger.debug("Replacing %s from %s", new_path, path)
                if os.path.isfile(new_path) or os.path.islink(new_path):
                    os.unlink(new_path)
                elif os.path.isdir(new_path):
                    rmtree(new_path)
                renames(path, new_path)
            except OSError as ex:
                logger.error("Failed to restore %s", new_path)
                logger.debug("Exception: %s", ex)
        self.commit()
References _moves, and commit().
stash()
str stash (self, str path)
Stashes the directory or file and returns its new location.
Handle symlinks as files to avoid modifying the symlink targets.
Definition at line 254 of file req_uninstall.py.
    def stash(self, path: str) -> str:
        """Stashes the directory or file and returns its new location.
        Handle symlinks as files to avoid modifying the symlink targets.
        """
        path_is_dir = os.path.isdir(path) and not os.path.islink(path)
        if path_is_dir:
            new_path = self._get_directory_stash(path)
        else:
            new_path = self._get_file_stash(path)
        self._moves.append((path, new_path))
        if path_is_dir and os.path.isdir(new_path):
            # If we're moving a directory, we need to
            # remove the destination first or else it will be
            # moved to inside the existing directory.
            # We just created new_path ourselves, so it will
            # be removable.
            os.rmdir(new_path)
        renames(path, new_path)
        return new_path
References _get_directory_stash(), _get_file_stash(), and _moves.
Field Documentation
_moves
_moves = [] protected
Definition at line 211 of file req_uninstall.py.
Referenced by can_rollback(), commit(), rollback(), and stash().
_save_dirs
dict _save_dirs = {} protected
Definition at line 208 of file req_uninstall.py.
Referenced by _get_directory_stash(), _get_file_stash(), and commit().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/req/req_uninstall.py