Let us walk on the 3-isogeny graph: pip._vendor.colorama.initialise Namespace Reference
pip._vendor.colorama.initialise Namespace Reference
Functions
_wipe_internal_state_for_tests ()
reset_all ()
init (autoreset=False, convert=None, strip=None, wrap=True)
deinit ()
just_fix_windows_console ()
colorama_text (*args, **kwargs)
reinit ()
wrap_stream (stream, convert, strip, autoreset, wrap)
Function Documentation
_wipe_internal_state_for_tests()
_wipe_internal_state_for_tests () protected
Definition at line 9 of file initialise.py.
def _wipe_internal_state_for_tests():
    global orig_stdout, orig_stderr
    orig_stdout = None
    orig_stderr = None
    global wrapped_stdout, wrapped_stderr
    wrapped_stdout = None
    wrapped_stderr = None
    global atexit_done
    atexit_done = False
    global fixed_windows_console
    fixed_windows_console = False
    try:
        # no-op if it wasn't registered
        atexit.unregister(reset_all)
    except AttributeError:
        # python 2: no atexit.unregister. Oh well, we did our best.
        pass
References i.
Referenced by pip._vendor.colorama.initialise.wrap_stream().
colorama_text()
colorama_text (* args, ** kwargs)
Definition at line 96 of file initialise.py.
def colorama_text(*args, **kwargs):
    init(*args, **kwargs)
    try:
        yield
    finally:
        deinit()
References pip._vendor.colorama.initialise.deinit().
deinit()
deinit ()
Definition at line 65 of file initialise.py.
def deinit():
    if orig_stdout is not None:
        sys.stdout = orig_stdout
    if orig_stderr is not None:
        sys.stderr = orig_stderr
References i.
Referenced by pip._vendor.colorama.initialise.colorama_text().
init()
init (autoreset = False, convert = None, strip = None, wrap = True)
Definition at line 37 of file initialise.py.
def init(autoreset=False, convert=None, strip=None, wrap=True):
    if not wrap and any([autoreset, convert, strip]):
        raise ValueError('wrap=False conflicts with any other arg=True')
    global wrapped_stdout, wrapped_stderr
    global orig_stdout, orig_stderr
    orig_stdout = sys.stdout
    orig_stderr = sys.stderr
    if sys.stdout is None:
        wrapped_stdout = None
    else:
        sys.stdout = wrapped_stdout = \
            wrap_stream(orig_stdout, convert, strip, autoreset, wrap)
    if sys.stderr is None:
        wrapped_stderr = None
    else:
        sys.stderr = wrapped_stderr = \
            wrap_stream(orig_stderr, convert, strip, autoreset, wrap)
    global atexit_done
    if not atexit_done:
        atexit.register(reset_all)
        atexit_done = True
References i, and pip._vendor.colorama.initialise.wrap_stream().
just_fix_windows_console()
just_fix_windows_console ()
Definition at line 72 of file initialise.py.
def just_fix_windows_console():
    global fixed_windows_console
    if sys.platform != "win32":
        return
    if fixed_windows_console:
        return
    if wrapped_stdout is not None or wrapped_stderr is not None:
        # Someone already ran init() and it did stuff, so we won't second-guess them
        return
    # On newer versions of Windows, AnsiToWin32.__init__ will implicitly enable the
    # native ANSI support in the console as a side-effect. We only need to actually
    # replace sys.stdout/stderr if we're in the old-style conversion mode.
    new_stdout = AnsiToWin32(sys.stdout, convert=None, strip=None, autoreset=False)
    if new_stdout.convert:
        sys.stdout = new_stdout
    new_stderr = AnsiToWin32(sys.stderr, convert=None, strip=None, autoreset=False)
    if new_stderr.convert:
        sys.stderr = new_stderr
    fixed_windows_console = True
@contextlib.contextmanager
References i.
reinit()
reinit ()
Definition at line 104 of file initialise.py.
def reinit():
    if wrapped_stdout is not None:
        sys.stdout = wrapped_stdout
    if wrapped_stderr is not None:
        sys.stderr = wrapped_stderr
References i.
reset_all()
reset_all ()
Definition at line 32 of file initialise.py.
def reset_all():
    if AnsiToWin32 is not None:    # Issue #74: objects might become None at exit
        AnsiToWin32(orig_stdout).reset_all()
References pip._vendor.colorama.initialise.reset_all().
Referenced by pip._vendor.colorama.initialise.reset_all().
wrap_stream()
wrap_stream (stream, convert, strip, autoreset, wrap)
Definition at line 111 of file initialise.py.
def wrap_stream(stream, convert, strip, autoreset, wrap):
    if wrap:
        wrapper = AnsiToWin32(stream,
            convert=convert, strip=strip, autoreset=autoreset)
        if wrapper.should_wrap():
            stream = wrapper.stream
    return stream
# Use this for initial setup as well, to reduce code duplication
References pip._vendor.colorama.initialise._wipe_internal_state_for_tests(), and i.
Referenced by pip._vendor.colorama.initialise.init().