Let us walk on the 3-isogeny graph: MockResponse Class Reference
MockResponse Class Reference
Public Member Functions
__init__ (self, headers)
info (self)
getheaders (self, name)
Protected Attributes
_headers
Detailed Description
Wraps a `httplib.HTTPMessage` to mimic a `urllib.addinfourl`.
...what? Basically, expose the parsed HTTP headers from the server response
the way `cookielib` expects to see them.
Definition at line 103 of file cookies.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, headers)
Make a MockResponse for `cookielib` to read.
:param headers: a httplib.HTTPMessage or analogous carrying the headers
Definition at line 110 of file cookies.py.
    def __init__(self, headers):
        """Make a MockResponse for `cookielib` to read.
        :param headers: a httplib.HTTPMessage or analogous carrying the headers
        """
        self._headers = headers
Referenced by Protocol.__init_subclass__().
Member Function Documentation
getheaders()
getheaders (self, name)
Definition at line 120 of file cookies.py.
    def getheaders(self, name):
        self._headers.getheaders(name)
References MockResponse._headers, and MockResponse.getheaders().
Referenced by MockResponse.getheaders().
info()
info (self)
Definition at line 117 of file cookies.py.
    def info(self):
        return self._headers
References MockResponse._headers.
Referenced by DirectUrl._remove_auth_from_netloc(), Wheel.install(), DirectUrl.is_local_editable(), and DirectUrl.to_dict().
Field Documentation
_headers
_headers protected
Definition at line 115 of file cookies.py.
Referenced by MockResponse.getheaders(), and MockResponse.info().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/requests/cookies.py