Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Wheel Class Reference
Wheel Class Reference
Public Member Functions
None __init__ (self, str filename)
List[str] get_formatted_file_tags (self)
int support_index_min (self, List[Tag] tags)
int find_most_preferred_tag (self, List[Tag] tags, Dict[Tag, int] tag_to_priority)
bool supported (self, Iterable[Tag] tags)
Data Fields
filename = filename
name = wheel_info.group("name").replace("_", "-")
version = wheel_info.group("ver").replace("_", "-")
build_tag = wheel_info.group("build")
pyversions = wheel_info.group("pyver").split(".")
abis = wheel_info.group("abi").split(".")
plats = wheel_info.group("plat").split(".")
dict file_tags
Static Public Attributes
wheel_file_re
Detailed Description
A wheel file
Definition at line 12 of file wheel.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, str filename)
:raises InvalidWheelFilename: when the filename is invalid for a wheel
Definition at line 22 of file wheel.py.
    def __init__(self, filename: str) -> None:
        """
        :raises InvalidWheelFilename: when the filename is invalid for a wheel
        """
        wheel_info = self.wheel_file_re.match(filename)
        if not wheel_info:
            raise InvalidWheelFilename(f"{filename} is not a valid wheel filename.")
        self.filename = filename
        self.name = wheel_info.group("name").replace("_", "-")
        # we'll assume "_" means "-" due to wheel naming scheme
        # (https://github.com/pypa/pip/issues/1150)
        self.version = wheel_info.group("ver").replace("_", "-")
        self.build_tag = wheel_info.group("build")
        self.pyversions = wheel_info.group("pyver").split(".")
        self.abis = wheel_info.group("abi").split(".")
        self.plats = wheel_info.group("plat").split(".")
        # All the tag combinations from this file
        self.file_tags = {
            Tag(x, y, z) for x in self.pyversions for y in self.abis for z in self.plats
        }
References wheel_file_re.
Member Function Documentation
find_most_preferred_tag()
int find_most_preferred_tag (self, List[Tag] tags, Dict[Tag, int] tag_to_priority)
Return the priority of the most preferred tag that one of the wheel's file
tag combinations achieves in the given list of supported tags using the given
tag_to_priority mapping, where lower priorities are more-preferred.
This is used in place of support_index_min in some cases in order to avoid
an expensive linear scan of a large list of tags.
:param tags: the PEP 425 tags to check the wheel against.
:param tag_to_priority: a mapping from tag to priority of that tag, where
    lower is more preferred.
:raises ValueError: If none of the wheel's file tags match one of
    the supported tags.
Definition at line 66 of file wheel.py.
    ) -> int:
        """Return the priority of the most preferred tag that one of the wheel's file
        tag combinations achieves in the given list of supported tags using the given
        tag_to_priority mapping, where lower priorities are more-preferred.
        This is used in place of support_index_min in some cases in order to avoid
        an expensive linear scan of a large list of tags.
        :param tags: the PEP 425 tags to check the wheel against.
        :param tag_to_priority: a mapping from tag to priority of that tag, where
            lower is more preferred.
        :raises ValueError: If none of the wheel's file tags match one of
            the supported tags.
        """
        return min(
            tag_to_priority[tag] for tag in self.file_tags if tag in tag_to_priority
        )
References file_tags.
get_formatted_file_tags()
List[str] get_formatted_file_tags (self)
Return the wheel's tags as a sorted list of strings.
Definition at line 44 of file wheel.py.
    def get_formatted_file_tags(self) -> List[str]:
        """Return the wheel's tags as a sorted list of strings."""
        return sorted(str(tag) for tag in self.file_tags)
References file_tags.
support_index_min()
int support_index_min (self, List[Tag] tags)
Return the lowest index that one of the wheel's file_tag combinations
achieves in the given list of supported tags.
For example, if there are 8 supported tags and one of the file tags
is first in the list, then return 0.
:param tags: the PEP 425 tags to check the wheel against, in order
    with most preferred first.
:raises ValueError: If none of the wheel's file tags match one of
    the supported tags.
Definition at line 48 of file wheel.py.
    def support_index_min(self, tags: List[Tag]) -> int:
        """Return the lowest index that one of the wheel's file_tag combinations
        achieves in the given list of supported tags.
        For example, if there are 8 supported tags and one of the file tags
        is first in the list, then return 0.
        :param tags: the PEP 425 tags to check the wheel against, in order
            with most preferred first.
        :raises ValueError: If none of the wheel's file tags match one of
            the supported tags.
        """
        try:
            return next(i for i, t in enumerate(tags) if t in self.file_tags)
        except StopIteration:
            raise ValueError()
References file_tags.
supported()
bool supported (self, Iterable[Tag] tags)
Return whether the wheel is compatible with one of the given tags.
:param tags: the PEP 425 tags to check the wheel against.
Definition at line 87 of file wheel.py.
    def supported(self, tags: Iterable[Tag]) -> bool:
        """Return whether the wheel is compatible with one of the given tags.
        :param tags: the PEP 425 tags to check the wheel against.
        """
        return not self.file_tags.isdisjoint(tags)
References file_tags.
Field Documentation
abis
abis = wheel_info.group("abi").split(".")
Definition at line 36 of file wheel.py.
build_tag
build_tag = wheel_info.group("build")
Definition at line 34 of file wheel.py.
file_tags
file_tags
Initial value:
=  {
            Tag(x, y, z) for x in self.pyversions for y in self.abis for z in self.plats
        }
Definition at line 40 of file wheel.py.
Referenced by find_most_preferred_tag(), get_formatted_file_tags(), support_index_min(), and supported().
filename
filename = filename
Definition at line 29 of file wheel.py.
Referenced by _get_extensions(), HtmlFormatter._wrap_tablelinenos(), exists(), info(), install(), metadata(), mount(), PyPIRCFile.read(), unmount(), PyPIRCFile.update(), update(), and verify().
name
name = wheel_info.group("name").replace("_", "-")
Definition at line 30 of file wheel.py.
Referenced by AlreadyInstalledCandidate.__eq__(), Distribution.__eq__(), ExportEntry.__eq__(), _LazyDescr.__get__(), Distribution.__hash__(), Metadata.__repr__(), ExportEntry.__repr__(), Encoding.__repr__(), Color.__rich_repr__(), Layout.__rich_repr__(), EggInfoDistribution.__str__(), InstalledDistribution.__str__(), Requirement.__str__(), ParserElement.__str__(), Tag.__str__(), _SixMetaPathImporter._add_module(), Matcher._check_compatible(), InstallRequirement._get_archive_name(), _get_extensions(), _SixMetaPathImporter._get_module(), Distribution._get_requirements(), _Cache.add(), InstallRequirement.archive(), build(), _Cache.clear(), InstallRequirement.ensure_build_location(), filename(), Layout.get(), InstalledDistribution.get_distinfo_file(), get_wheel_metadata(), InstallRequirement.install(), install(), VersionControl.is_repository_directory(), SpecifierRequirement.is_satisfied_by(), LinuxDistribution.linux_distribution(), ElementState.mark_for_extraction(), metadata(), Distribution.name_and_version(), VersionControl.obtain(), InstallRequirement.prepare_metadata(), Distribution.provides(), Metadata.provides(), VcsSupport.register(), VersionControl.run_command(), InstallRequirement.uninstall(), update(), and verify().
plats
plats = wheel_info.group("plat").split(".")
Definition at line 37 of file wheel.py.
pyversions
pyversions = wheel_info.group("pyver").split(".")
Definition at line 35 of file wheel.py.
version
version = wheel_info.group("ver").replace("_", "-")
Definition at line 33 of file wheel.py.
Referenced by AlreadyInstalledCandidate.__eq__(), Distribution.__eq__(), Distribution.__hash__(), Metadata.__repr__(), EggInfoDistribution.__str__(), InstalledDistribution.__str__(), PlatformDirsABC._append_app_name_and_version(), WrappedSocket._custom_validate(), _get_extensions(), build(), filename(), InstalledDistribution.get_distinfo_file(), get_wheel_metadata(), LinuxDistribution.info(), install(), LinuxDistribution.linux_distribution(), metadata(), LinuxDistribution.name(), Distribution.name_and_version(), Distribution.provides(), Metadata.provides(), update(), verify(), and LinuxDistribution.version_parts().
wheel_file_re
wheel_file_re static
Initial value:
=  re.compile(
        ,
        re.VERBOSE,
    )
Definition at line 15 of file wheel.py.
Referenced by __init__().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/models/wheel.py