Let us walk on the 3-isogeny graph: DistPathLocator Class Reference
DistPathLocator Class Reference
Public Member Functions
__init__ (self, distpath, **kwargs)
Public Member Functions inherited from Locator
get_errors (self)
clear_errors (self)
clear_cache (self)
get_distribution_names (self)
get_project (self, name)
score_url (self, url)
prefer_url (self, url1, url2)
split_filename (self, filename, project_name)
convert_url_to_download_info (self, url, project_name)
locate (self, requirement, prereleases=False)
Data Fields
distpath
Data Fields inherited from Locator
opener
matcher
errors
downloadable_extensions
Protected Member Functions
_get_project (self, name)
Protected Member Functions inherited from Locator
_get_scheme (self)
_set_scheme (self, value)
_get_digest (self, info)
_update_version_data (self, result, info)
Additional Inherited Members
Static Public Attributes inherited from Locator
tuple source_extensions = ('.tar.gz', '.tar.bz2', '.tar', '.zip', '.tgz', '.tbz')
tuple binary_extensions = ('.egg', '.exe', '.whl')
tuple excluded_extensions = ('.pdf',)
wheel_tags = None
tuple downloadable_extensions = source_extensions + ('.whl',)
Protected Attributes inherited from Locator
_cache
_scheme
Properties inherited from Locator
scheme = property(_get_scheme, _set_scheme)
Detailed Description
This locator finds installed distributions in a path. It can be useful for
adding to an :class:`AggregatingLocator`.
Definition at line 938 of file locators.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, distpath, ** kwargs)
Initialise an instance.
:param distpath: A :class:`DistributionPath` instance to search.
Reimplemented from Locator.
Definition at line 943 of file locators.py.
    def __init__(self, distpath, **kwargs):
        """
        Initialise an instance.
        :param distpath: A :class:`DistributionPath` instance to search.
        """
        super(DistPathLocator, self).__init__(**kwargs)
        assert isinstance(distpath, DistributionPath)
        self.distpath = distpath
References DistPathLocator.__init__(), and i.
Referenced by DistPathLocator.__init__(), and Protocol.__init_subclass__().
Member Function Documentation
_get_project()
_get_project (self, name) protected
For a given project, get a dictionary mapping available versions to Distribution
instances.
This should be implemented in subclasses.
If called from a locate() request, self.matcher will be set to a
matcher for the requirement to satisfy, otherwise it will be None.
Reimplemented from Locator.
Definition at line 953 of file locators.py.
    def _get_project(self, name):
        dist = self.distpath.get_distribution(name)
        if dist is None:
            result = {'urls': {}, 'digests': {}}
        else:
            result = {
                dist.version: dist,
                'urls': {dist.version: set([dist.source_url])},
                'digests': {dist.version: set([None])}
            }
        return result
References DistPathLocator.distpath, and i.
Referenced by Locator.get_project().
Field Documentation
distpath
distpath
Definition at line 951 of file locators.py.
Referenced by DistPathLocator._get_project().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/locators.py