Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: SessionCommandMixin Class Reference
SessionCommandMixin Class Reference
Public Member Functions
None __init__ (self)
PipSession get_default_session (self, Values options)
Public Member Functions inherited from CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Protected Member Functions
Optional[List[str]] _get_index_urls (cls, Values options)
PipSession _build_session (self, Values options, Optional[int] retries=None, Optional[int] timeout=None, bool fallback_to_certifi=False)
Protected Attributes
Optional[PipSession] _session = None
Protected Attributes inherited from CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Detailed Description
A class mixin for command classes needing _build_session().
Definition at line 71 of file req_command.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Definition at line 77 of file req_command.py.
    def __init__(self) -> None:
        super().__init__()
        self._session: Optional[PipSession] = None
References __init__().
Referenced by __init__().
Member Function Documentation
_build_session()
PipSession _build_session (self, Values options, Optional[int] retries = None, Optional[int] timeout = None, bool fallback_to_certifi = False) protected
Definition at line 105 of file req_command.py.
    ) -> PipSession:
        cache_dir = options.cache_dir
        assert not cache_dir or os.path.isabs(cache_dir)
        if "truststore" in options.features_enabled:
            try:
                ssl_context = _create_truststore_ssl_context()
            except Exception:
                if not fallback_to_certifi:
                    raise
                ssl_context = None
        else:
            ssl_context = None
        session = PipSession(
            cache=os.path.join(cache_dir, "http") if cache_dir else None,
            retries=retries if retries is not None else options.retries,
            trusted_hosts=options.trusted_hosts,
            index_urls=self._get_index_urls(options),
            ssl_context=ssl_context,
        )
        # Handle custom ca-bundles from the user
        if options.cert:
            session.verify = options.cert
        # Handle SSL client certificate
        if options.client_cert:
            session.cert = options.client_cert
        # Handle timeouts
        if options.timeout or timeout:
            session.timeout = timeout if timeout is not None else options.timeout
        # Handle configured proxies
        if options.proxy:
            session.proxies = {
                "http": options.proxy,
                "https": options.proxy,
            }
        # Determine if we can prompt the user for authentication or not
        session.auth.prompting = not options.no_input
        session.auth.keyring_provider = options.keyring_provider
        return session
References pip._internal.cli.req_command._create_truststore_ssl_context(), and _get_index_urls().
Referenced by IndexCommand.get_available_package_versions(), get_default_session(), IndexGroupCommand.handle_pip_version_check(), and ListCommand.iter_packages_latest_infos().
_get_index_urls()
Optional[List[str]] _get_index_urls (cls, Values options) protected
Return a list of index urls from user-provided options.
Definition at line 82 of file req_command.py.
    def _get_index_urls(cls, options: Values) -> Optional[List[str]]:
        """Return a list of index urls from user-provided options."""
        index_urls = []
        if not getattr(options, "no_index", False):
            url = getattr(options, "index_url", None)
            if url:
                index_urls.append(url)
        urls = getattr(options, "extra_index_urls", None)
        if urls:
            index_urls.extend(urls)
        # Return None rather than an empty list
        return index_urls or None
Referenced by _build_session().
get_default_session()
PipSession get_default_session (self, Values options)
Get a default-managed session.
Definition at line 95 of file req_command.py.
    def get_default_session(self, options: Values) -> PipSession:
        """Get a default-managed session."""
        if self._session is None:
            self._session = self.enter_context(self._build_session(options))
            # there's no type annotation on requests.Session, so it's
            # automatically ContextManager[Any] and self._session becomes Any,
            # then https://github.com/python/mypy/issues/7696 kicks in
            assert self._session is not None
        return self._session
References _build_session(), _session, and CommandContextMixIn.enter_context().
Referenced by DownloadCommand.run(), InstallCommand.run(), UninstallCommand.run(), WheelCommand.run(), and SearchCommand.search().
Field Documentation
_session
Optional[PipSession] _session = None protected
Definition at line 79 of file req_command.py.
Referenced by BatchDownloader.__call__(), Downloader.__call__(), RequirementPreparer._fetch_metadata_using_lazy_wheel(), RequirementsFileParser._parse_file(), LazyZipOverHTTP._stream_response(), get_default_session(), and PipXmlrpcTransport.request().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/cli/req_command.py