Let us walk on the 3-isogeny graph: StreamWrapper Class Reference
StreamWrapper Class Reference
Public Member Functions
"StreamWrapper" from_stream (cls, TextIO orig_stream)
str encoding (self)
Static Public Attributes
TextIO orig_stream
Detailed Description
Definition at line 343 of file misc.py.
Member Function Documentation
encoding()
str encoding (self)
Definition at line 355 of file misc.py.
    def encoding(self) -> str:  # type: ignore
        return self.orig_stream.encoding
@contextlib.contextmanager
References StreamWrapper.orig_stream.
Referenced by TestcaseFormatter.__init__(), HtmlFormatter._decodeifneeded(), HtmlFormatter._wrap_full(), ConsoleOptions.ascii_only(), IncrementalDecoder.decode(), Formatter.format(), NullFormatter.format(), TestcaseFormatter.format(), LatexFormatter.format_unencoded(), SvgFormatter.format_unencoded(), Response.json(), Console.options(), and Response.text().
from_stream()
"StreamWrapper" from_stream (cls, TextIO orig_stream)
Definition at line 347 of file misc.py.
    def from_stream(cls, orig_stream: TextIO) -> "StreamWrapper":
        ret = cls()
        ret.orig_stream = orig_stream
        return ret
References i.
Field Documentation
orig_stream
TextIO orig_stream static
Definition at line 344 of file misc.py.
Referenced by StreamWrapper.encoding().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/utils/misc.py