Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: BasePath Class Reference
BasePath Class Reference
Public Member Functions
str name (self)
"BasePath" parent (self)
Detailed Description
A protocol that various path objects conform.
This exists because importlib.metadata uses both ``pathlib.Path`` and
``zipfile.Path``, and we need a common base for type hints (Union does not
work well since ``zipfile.Path`` is too new for our linter setup).
This does not mean to be exhaustive, but only contains things that present
in both classes *that we need*.
Definition at line 14 of file _compat.py.
Member Function Documentation
name()
str name (self)
Definition at line 26 of file _compat.py.
    def name(self) -> str:
        raise NotImplementedError()
Referenced by ParserElement.__str__(), Tag.__str__(), SpecifierRequirement.is_satisfied_by(), and LinuxDistribution.linux_distribution().
parent()
"BasePath" parent (self)
Definition at line 30 of file _compat.py.
    def parent(self) -> "BasePath":
        raise NotImplementedError()
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_compat.py