Let us walk on the 3-isogeny graph: Environment Class Reference
Environment Class Reference
Public Member Functions
None __init__ (self, pkg_resources.WorkingSet ws)
BaseEnvironment default (cls)
BaseEnvironment from_paths (cls, Optional[List[str]] paths)
Optional[BaseDistribution] get_distribution (self, str name)
Public Member Functions inherited from BaseEnvironment
Iterator[BaseDistribution] iter_all_distributions (self)
Iterator[BaseDistribution] iter_installed_distributions (self, bool local_only=True, Container[str] skip=stdlib_pkgs, bool include_editables=True, bool editables_only=False, bool user_only=False)
Protected Member Functions
Iterator[BaseDistribution] _iter_distributions (self)
Optional[BaseDistribution] _search_distribution (self, str name)
Protected Attributes
_ws
Detailed Description
Definition at line 222 of file pkg_resources.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, pkg_resources.WorkingSet ws)
Definition at line 223 of file pkg_resources.py.
    def __init__(self, ws: pkg_resources.WorkingSet) -> None:
        self._ws = ws
Referenced by Protocol.__init_subclass__().
Member Function Documentation
_iter_distributions()
Iterator[BaseDistribution] _iter_distributions (self) protected
Iterate through installed distributions.
This function should be implemented by subclass, but never called
directly. Use the public ``iter_distribution()`` instead, which
implements additional logic to make sure the distributions are valid.
Reimplemented from BaseEnvironment.
Definition at line 234 of file pkg_resources.py.
    def _iter_distributions(self) -> Iterator[BaseDistribution]:
        for dist in self._ws:
            yield Distribution(dist)
References Environment._ws.
Referenced by BaseEnvironment.iter_all_distributions().
_search_distribution()
Optional[BaseDistribution] _search_distribution (self, str name) protected
Find a distribution matching the ``name`` in the environment.
This searches from *all* distributions available in the environment, to
match the behavior of ``pkg_resources.get_distribution()``.
Definition at line 238 of file pkg_resources.py.
    def _search_distribution(self, name: str) -> Optional[BaseDistribution]:
        """Find a distribution matching the ``name`` in the environment.
        This searches from *all* distributions available in the environment, to
        match the behavior of ``pkg_resources.get_distribution()``.
        """
        canonical_name = canonicalize_name(name)
        for dist in self.iter_all_distributions():
            if dist.canonical_name == canonical_name:
                return dist
        return None
References i, and BaseEnvironment.iter_all_distributions().
Referenced by Environment.get_distribution().
default()
BaseEnvironment default (cls)
Reimplemented from BaseEnvironment.
Definition at line 227 of file pkg_resources.py.
    def default(cls) -> BaseEnvironment:
        return cls(pkg_resources.working_set)
References i.
from_paths()
BaseEnvironment from_paths (cls, Optional[List[str]] paths)
Reimplemented from BaseEnvironment.
Definition at line 231 of file pkg_resources.py.
    def from_paths(cls, paths: Optional[List[str]]) -> BaseEnvironment:
        return cls(pkg_resources.WorkingSet(paths))
References i.
get_distribution()
Optional[BaseDistribution] get_distribution (self, str name)
Given a requirement name, return the installed distributions.
The name may not be normalized. The implementation must canonicalize
it for lookup.
Reimplemented from BaseEnvironment.
Definition at line 250 of file pkg_resources.py.
    def get_distribution(self, name: str) -> Optional[BaseDistribution]:
        # Search the distribution by looking through the working set.
        dist = self._search_distribution(name)
        if dist:
            return dist
        # If distribution could not be found, call working_set.require to
        # update the working set, and try to find the distribution again.
        # This might happen for e.g. when you install a package twice, once
        # using setup.py develop and again using setup.py install. Now when
        # running pip uninstall twice, the package gets removed from the
        # working set in the first uninstall, so we have to populate the
        # working set again so that pip knows about it and the packages gets
        # picked up and is successfully uninstalled the second time too.
        try:
            # We didn't pass in any version specifiers, so this can never
            # raise pkg_resources.VersionConflict.
            self._ws.require(name)
        except pkg_resources.DistributionNotFound:
            return None
        return self._search_distribution(name)
References Environment._search_distribution(), Environment._ws, and i.
Referenced by DistributionPath.get_file_path().
Field Documentation
_ws
_ws protected
Definition at line 224 of file pkg_resources.py.
Referenced by Environment._iter_distributions(), and Environment.get_distribution().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/metadata/pkg_resources.py