Let us walk on the 3-isogeny graph: pip._vendor.urllib3.contrib._appengine_environ Namespace Reference
pip._vendor.urllib3.contrib._appengine_environ Namespace Reference
Functions
is_appengine ()
is_appengine_sandbox ()
is_local_appengine ()
is_prod_appengine ()
is_prod_appengine_mvms ()
Detailed Description
This module provides means to detect the App Engine environment.
Function Documentation
is_appengine()
is_appengine ()
Definition at line 8 of file _appengine_environ.py.
def is_appengine():
    return is_local_appengine() or is_prod_appengine()
References pip._vendor.urllib3.contrib._appengine_environ.is_local_appengine(), and pip._vendor.urllib3.contrib._appengine_environ.is_prod_appengine().
Referenced by pip._vendor.urllib3.contrib._appengine_environ.is_appengine_sandbox().
is_appengine_sandbox()
is_appengine_sandbox ()
Reports if the app is running in the first generation sandbox.
The second generation runtimes are technically still in a sandbox, but it
is much less restrictive, so generally you shouldn't need to check for it.
see https://cloud.google.com/appengine/docs/standard/runtimes
Definition at line 12 of file _appengine_environ.py.
def is_appengine_sandbox():
    """Reports if the app is running in the first generation sandbox.
    The second generation runtimes are technically still in a sandbox, but it
    is much less restrictive, so generally you shouldn't need to check for it.
    see https://cloud.google.com/appengine/docs/standard/runtimes
    """
    return is_appengine() and os.environ["APPENGINE_RUNTIME"] == "python27"
References i, and pip._vendor.urllib3.contrib._appengine_environ.is_appengine().
is_local_appengine()
is_local_appengine ()
Definition at line 22 of file _appengine_environ.py.
def is_local_appengine():
    return "APPENGINE_RUNTIME" in os.environ and os.environ.get(
        "SERVER_SOFTWARE", ""
    ).startswith("Development/")
References i.
Referenced by pip._vendor.urllib3.contrib._appengine_environ.is_appengine().
is_prod_appengine()
is_prod_appengine ()
Definition at line 28 of file _appengine_environ.py.
def is_prod_appengine():
    return "APPENGINE_RUNTIME" in os.environ and os.environ.get(
        "SERVER_SOFTWARE", ""
    ).startswith("Google App Engine/")
References i.
Referenced by pip._vendor.urllib3.contrib._appengine_environ.is_appengine().
is_prod_appengine_mvms()
is_prod_appengine_mvms ()
Deprecated.
Definition at line 34 of file _appengine_environ.py.
def is_prod_appengine_mvms():
    """Deprecated."""
    return False