Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: SJISDistributionAnalysis Class Reference
SJISDistributionAnalysis Class Reference
Public Member Functions
None __init__ (self)
int get_order (self, Union[bytes, bytearray] byte_str)
Public Member Functions inherited from CharDistributionAnalysis
None __init__ (self)
None reset (self)
None feed (self, Union[bytes, bytearray] char, int char_len)
float get_confidence (self)
bool got_enough_data (self)
Additional Inherited Members
Data Fields inherited from CharDistributionAnalysis
float typical_distribution_ratio = 0.0
Static Public Attributes inherited from CharDistributionAnalysis
int ENOUGH_DATA_THRESHOLD = 1024
float SURE_YES = 0.99
float SURE_NO = 0.01
int MINIMUM_DATA_THRESHOLD = 3
Protected Attributes inherited from CharDistributionAnalysis
Tuple[int,...] _char_to_freq_order = tuple()
int _table_size = 0
bool _done = False
int _total_chars = 0
int _freq_chars = 0
Detailed Description
Definition at line 221 of file chardistribution.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Definition at line 222 of file chardistribution.py.
    def __init__(self) -> None:
        super().__init__()
        self._char_to_freq_order = JIS_CHAR_TO_FREQ_ORDER
        self._table_size = JIS_TABLE_SIZE
        self.typical_distribution_ratio = JIS_TYPICAL_DISTRIBUTION_RATIO
References __init__().
Referenced by __init__().
Member Function Documentation
get_order()
int get_order (self, Union[bytes, bytearray] byte_str)
Reimplemented from CharDistributionAnalysis.
Definition at line 228 of file chardistribution.py.
    def get_order(self, byte_str: Union[bytes, bytearray]) -> int:
        # for sjis encoding, we are interested
        #   first  byte range: 0x81 -- 0x9f , 0xe0 -- 0xfe
        #   second byte range: 0x40 -- 0x7e,  0x81 -- oxfe
        # no validation needed here. State machine has done that
        first_char, second_char = byte_str[0], byte_str[1]
        if 0x81 <= first_char <= 0x9F:
            order = 188 * (first_char - 0x81)
        elif 0xE0 <= first_char <= 0xEF:
            order = 188 * (first_char - 0xE0 + 31)
        else:
            return -1
        order = order + second_char - 0x40
        if second_char > 0x7F:
            order = -1
        return order
Referenced by JapaneseContextAnalysis.feed().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/chardet/chardistribution.py