Let us walk on the 3-isogeny graph: DelegatingLexer Class Reference
DelegatingLexer Class Reference
Public Member Functions
__init__ (self, _root_lexer, _language_lexer, _needle=Other, **options)
get_tokens_unprocessed (self, text)
Public Member Functions inherited from Lexer
__repr__ (self)
add_filter (self, filter_, **options)
analyse_text (text)
get_tokens (self, text, unfiltered=False)
Public Member Functions inherited from LexerMeta
__new__ (mcs, name, bases, d)
Data Fields
root_lexer
language_lexer
needle
Data Fields inherited from Lexer
options
stripnl
stripall
ensurenl
tabsize
encoding
filters
Additional Inherited Members
Static Public Attributes inherited from Lexer
name = None
list aliases = []
list filenames = []
list alias_filenames = []
list mimetypes = []
int priority = 0
url = None
Detailed Description
This lexer takes two lexer as arguments. A root lexer and
a language lexer. First everything is scanned using the language
lexer, afterwards all ``Other`` tokens are lexed using the root
lexer.
The lexers from the ``template`` lexer package use this base lexer.
Definition at line 269 of file lexer.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, options, _language_lexer, _needle = Other, ** options)
This constructor takes arbitrary options as keyword arguments.
Every subclass must first process its own options and then call
the `Lexer` constructor, since it processes the basic
options like `stripnl`.
An example looks like this:
.. sourcecode:: python
   def __init__(self, **options):
       self.compress = options.get('compress', '')
       Lexer.__init__(self, **options)
As these options must all be specifiable as strings (due to the
command line usage), there are various utility functions
available to help with that, see `Utilities`_.
Reimplemented from Lexer.
Reimplemented in PythonConsoleLexer.
Definition at line 279 of file lexer.py.
    def __init__(self, _root_lexer, _language_lexer, _needle=Other, **options):
        self.root_lexer = _root_lexer(**options)
        self.language_lexer = _language_lexer(**options)
        self.needle = _needle
        Lexer.__init__(self, **options)
Referenced by Protocol.__init_subclass__().
Member Function Documentation
get_tokens_unprocessed()
get_tokens_unprocessed (self, text)
This method should process the text and return an iterable of
``(index, tokentype, value)`` tuples where ``index`` is the starting
position of the token within the input text.
It must be overridden by subclasses. It is recommended to
implement it as a generator to maximize effectiveness.
Reimplemented from Lexer.
Definition at line 285 of file lexer.py.
    def get_tokens_unprocessed(self, text):
        buffered = ''
        insertions = []
        lng_buffer = []
        for i, t, v in self.language_lexer.get_tokens_unprocessed(text):
            if t is self.needle:
                if lng_buffer:
                    insertions.append((len(buffered), lng_buffer))
                    lng_buffer = []
                buffered += v
            else:
                lng_buffer.append((i, t, v))
        if lng_buffer:
            insertions.append((len(buffered), lng_buffer))
        return do_insertions(insertions,
                             self.root_lexer.get_tokens_unprocessed(buffered))
# ------------------------------------------------------------------------------
# RegexLexer and ExtendedRegexLexer
#
References DelegatingLexer.get_tokens_unprocessed(), i, DelegatingLexer.language_lexer, DelegatingLexer.needle, and DelegatingLexer.root_lexer.
Referenced by DelegatingLexer.get_tokens_unprocessed().
Field Documentation
language_lexer
language_lexer
Definition at line 281 of file lexer.py.
Referenced by DelegatingLexer.get_tokens_unprocessed().
needle
needle
Definition at line 282 of file lexer.py.
Referenced by DelegatingLexer.get_tokens_unprocessed().
root_lexer
root_lexer
Definition at line 280 of file lexer.py.
Referenced by DelegatingLexer.get_tokens_unprocessed().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pygments/lexer.py