Let us walk on the 3-isogeny graph: Module_six_moves_urllib Class Reference
Module_six_moves_urllib Class Reference
Public Member Functions
__dir__ (self)
Static Public Attributes
parse = _importer._get_module("moves.urllib_parse")
error = _importer._get_module("moves.urllib_error")
request = _importer._get_module("moves.urllib_request")
response = _importer._get_module("moves.urllib_response")
robotparser = _importer._get_module("moves.urllib_robotparser")
Detailed Description
Create a six.moves.urllib namespace that resembles the Python 3 namespace
Definition at line 524 of file six.py.
Member Function Documentation
__dir__()
__dir__ (self)
Definition at line 535 of file six.py.
    def __dir__(self):
        return ["parse", "error", "request", "response", "robotparser"]
Field Documentation
error
error = _importer._get_module("moves.urllib_error") static
Definition at line 530 of file six.py.
parse
parse = _importer._get_module("moves.urllib_parse") static
Definition at line 529 of file six.py.
Referenced by Style.normalize().
request
request = _importer._get_module("moves.urllib_request") static
Definition at line 531 of file six.py.
Referenced by Session.delete(), Session.get(), Session.head(), Session.options(), Session.patch(), Session.post(), and Session.put().
response
response = _importer._get_module("moves.urllib_response") static
Definition at line 532 of file six.py.
robotparser
robotparser = _importer._get_module("moves.urllib_robotparser") static
Definition at line 533 of file six.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/urllib3/packages/six.py