Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: SearchCommand Class Reference
SearchCommand Class Reference
Public Member Functions
None add_options (self)
int run (self, Values options, List[str] args)
List[Dict[str, str]] search (self, List[str] query, Values options)
Public Member Functions inherited from Command
None __init__ (self, str name, str summary, bool isolated=False)
None handle_pip_version_check (self, Values options)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Public Member Functions inherited from SessionCommandMixin
None __init__ (self)
PipSession get_default_session (self, Values options)
Additional Inherited Members
Data Fields inherited from Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Static Public Attributes inherited from Command
str usage = ""
bool ignore_require_venv = False
Protected Member Functions inherited from Command
int _main (self, List[str] args)
Protected Member Functions inherited from SessionCommandMixin
Optional[List[str]] _get_index_urls (cls, Values options)
PipSession _build_session (self, Values options, Optional[int] retries=None, Optional[int] timeout=None, bool fallback_to_certifi=False)
Protected Attributes inherited from CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Protected Attributes inherited from SessionCommandMixin
Optional[PipSession] _session = None
Detailed Description
Search for PyPI packages whose name or summary contains <query>.
Definition at line 34 of file search.py.
Member Function Documentation
add_options()
None add_options (self)
Reimplemented from Command.
Definition at line 41 of file search.py.
    def add_options(self) -> None:
        self.cmd_opts.add_option(
            "-i",
            "--index",
            dest="index",
            metavar="URL",
            default=PyPI.pypi_url,
            help="Base URL of Python Package Index (default %default)",
        )
        self.parser.insert_option_group(0, self.cmd_opts)
References Command.cmd_opts.
run()
int run (self, Values options, List[str] args)
Reimplemented from Command.
Definition at line 53 of file search.py.
    def run(self, options: Values, args: List[str]) -> int:
        if not args:
            raise CommandError("Missing required argument (search query).")
        query = args
        pypi_hits = self.search(query, options)
        hits = transform_hits(pypi_hits)
        terminal_width = None
        if sys.stdout.isatty():
            terminal_width = shutil.get_terminal_size()[0]
        print_results(hits, terminal_width=terminal_width)
        if pypi_hits:
            return SUCCESS
        return NO_MATCHES_FOUND
References pip._internal.commands.search.print_results(), search(), and pip._internal.commands.search.transform_hits().
search()
List[Dict[str, str]] search (self, List[str] query, Values options)
Definition at line 69 of file search.py.
    def search(self, query: List[str], options: Values) -> List[Dict[str, str]]:
        index_url = options.index
        session = self.get_default_session(options)
        transport = PipXmlrpcTransport(index_url, session)
        pypi = xmlrpc.client.ServerProxy(index_url, transport)
        try:
            hits = pypi.search({"name": query, "summary": query}, "or")
        except xmlrpc.client.Fault as fault:
            message = "XMLRPC request failed [code: {code}]\n{string}".format(
                code=fault.faultCode,
                string=fault.faultString,
            )
            raise CommandError(message)
        assert isinstance(hits, list)
        return hits
References SessionCommandMixin.get_default_session().
Referenced by run().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/commands/search.py