Let us walk on the 3-isogeny graph: ConvertingDict Class Reference
ConvertingDict Class Reference
Public Member Functions
__getitem__ (self, key)
get (self, key, default=None)
Detailed Description
A converting dictionary wrapper.
Definition at line 913 of file compat.py.
Member Function Documentation
__getitem__()
__getitem__ (self, key)
Definition at line 916 of file compat.py.
        def __getitem__(self, key):
            value = dict.__getitem__(self, key)
            result = self.configurator.convert(value)
            #If the converted value is different, save for next time
            if value is not result:
                self[key] = result
                if type(result) in (ConvertingDict, ConvertingList,
                                    ConvertingTuple):
                    result.parent = self
                    result.key = key
            return result
References i.
get()
get (self, key, default = None)
Definition at line 928 of file compat.py.
        def get(self, key, default=None):
            value = dict.get(self, key, default)
            result = self.configurator.convert(value)
            #If the converted value is different, save for next time
            if value is not result:
                self[key] = result
                if type(result) in (ConvertingDict, ConvertingList,
                                    ConvertingTuple):
                    result.parent = self
                    result.key = key
            return result
    def pop(self, key, default=None):
References i.
Referenced by LegacyMetadata.__getitem__(), Layout.__getitem__(), LegacyMetadata.check(), ThemeStack.push_theme(), and LegacyMetadata.write_file().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/compat.py