Let us walk on the 3-isogeny graph: TimeElapsedColumn Class Reference
TimeElapsedColumn Class Reference
Public Member Functions
Text render (self, "Task" task)
Public Member Functions inherited from ProgressColumn
None __init__ (self, Optional[Column] table_column=None)
Column get_table_column (self)
RenderableType __call__ (self, "Task" task)
Additional Inherited Members
Static Public Attributes inherited from ProgressColumn
Optional max_refresh = None
Protected Attributes inherited from ProgressColumn
_table_column
Detailed Description
Renders time elapsed.
Definition at line 676 of file progress.py.
Member Function Documentation
render()
Text render (self, "Task" task)
Show time elapsed.
Reimplemented from ProgressColumn.
Definition at line 679 of file progress.py.
    def render(self, task: "Task") -> Text:
        """Show time elapsed."""
        elapsed = task.finished_time if task.finished else task.elapsed
        if elapsed is None:
            return Text("-:--:--", style="progress.elapsed")
        delta = timedelta(seconds=int(elapsed))
        return Text(str(delta), style="progress.elapsed")
References i.
Referenced by ProgressColumn.__call__(), Spinner.__rich_console__(), Layout.__rich_console__(), Spinner.__rich_measure__(), RichHandler.emit(), Console.log(), Console.print(), Console.render(), Console.render_lines(), and Console.update_screen_lines().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/rich/progress.py