Let us walk on the 3-isogeny graph: DirectedGraph Class Reference
DirectedGraph Class Reference
Public Member Functions
__init__ (self)
__iter__ (self)
__len__ (self)
__contains__ (self, key)
copy (self)
add (self, key)
remove (self, key)
connected (self, f, t)
connect (self, f, t)
iter_edges (self)
iter_children (self, key)
iter_parents (self, key)
Protected Attributes
_vertices
_forwards
_backwards
Detailed Description
A graph structure with directed edges.
Definition at line 6 of file structs.py.
Constructor & Destructor Documentation
__init__()
__init__ (self)
Definition at line 9 of file structs.py.
    def __init__(self):
        self._vertices = set()
        self._forwards = {}  # <key> -> Set[<key>]
        self._backwards = {}  # <key> -> Set[<key>]
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__contains__()
__contains__ (self, key)
Definition at line 20 of file structs.py.
    def __contains__(self, key):
        return key in self._vertices
References DirectedGraph._vertices.
__iter__()
__iter__ (self)
Definition at line 14 of file structs.py.
    def __iter__(self):
        return iter(self._vertices)
References DirectedGraph._vertices.
__len__()
__len__ (self)
Definition at line 17 of file structs.py.
    def __len__(self):
        return len(self._vertices)
References DirectedGraph._vertices, and i.
add()
add (self, key)
Add a new vertex to the graph.
Definition at line 31 of file structs.py.
    def add(self, key):
        """Add a new vertex to the graph."""
        if key in self._vertices:
            raise ValueError("vertex exists")
        self._vertices.add(key)
        self._forwards[key] = set()
        self._backwards[key] = set()
References DirectedGraph._backwards, DirectedGraph._forwards, DirectedGraph._vertices, and DirectedGraph.add().
Referenced by DirectedGraph.add(), UninstallPathSet.add(), Manifest.add_many(), DirectedGraph.connect(), HTTPHeaderDict.extend(), and BuildTracker.track().
connect()
connect (self, f, t)
Connect two existing vertices.
Nothing happens if the vertices are already connected.
Definition at line 50 of file structs.py.
    def connect(self, f, t):
        """Connect two existing vertices.
        Nothing happens if the vertices are already connected.
        """
        if t not in self._vertices:
            raise KeyError(t)
        self._forwards[f].add(t)
        self._backwards[t].add(f)
References DirectedGraph._backwards, DirectedGraph._forwards, DirectedGraph._vertices, DirectedGraph.add(), and i.
Referenced by Retry.increment(), Retry.is_exhausted(), and Retry.new().
connected()
connected (self, f, t)
Definition at line 47 of file structs.py.
    def connected(self, f, t):
        return f in self._backwards[t] and t in self._forwards[f]
References DirectedGraph._backwards, and DirectedGraph._forwards.
copy()
copy (self)
Return a shallow copy of this graph.
Definition at line 23 of file structs.py.
    def copy(self):
        """Return a shallow copy of this graph."""
        other = DirectedGraph()
        other._vertices = set(self._vertices)
        other._forwards = {k: set(v) for k, v in self._forwards.items()}
        other._backwards = {k: set(v) for k, v in self._backwards.items()}
        return other
References DirectedGraph._backwards, DirectedGraph._forwards, DirectedGraph._vertices, and i.
Referenced by ParseResults.__add__(), Text.__add__(), ParserElement.__call__(), ParseResults.__radd__(), ParserElement._setResultsName(), ParseResults.deepcopy(), Text.divide(), ConsoleOptions.reset_height(), Text.split(), ConsoleOptions.update(), ConsoleOptions.update_dimensions(), ConsoleOptions.update_height(), ConsoleOptions.update_width(), Text.with_indent_guides(), and BaseRetrying.wraps().
iter_children()
iter_children (self, key)
Definition at line 65 of file structs.py.
    def iter_children(self, key):
        return iter(self._forwards[key])
References DirectedGraph._forwards.
iter_edges()
iter_edges (self)
Definition at line 60 of file structs.py.
    def iter_edges(self):
        for f, children in self._forwards.items():
            for t in children:
                yield f, t
References DirectedGraph._forwards.
iter_parents()
iter_parents (self, key)
Definition at line 68 of file structs.py.
    def iter_parents(self, key):
        return iter(self._backwards[key])
References DirectedGraph._backwards.
remove()
remove (self, key)
Remove a vertex from the graph, disconnecting all edges from/to it.
Definition at line 39 of file structs.py.
    def remove(self, key):
        """Remove a vertex from the graph, disconnecting all edges from/to it."""
        self._vertices.remove(key)
        for f in self._forwards.pop(key):
            self._backwards[f].remove(key)
        for t in self._backwards.pop(key):
            self._forwards[t].remove(key)
References DirectedGraph._backwards, DirectedGraph._forwards, DirectedGraph._vertices, and DirectedGraph.remove().
Referenced by DirectedGraph.remove(), Sequencer.remove_node(), and BuildTracker.track().
Field Documentation
_backwards
_backwards protected
Definition at line 12 of file structs.py.
Referenced by DirectedGraph.add(), DirectedGraph.connect(), DirectedGraph.connected(), DirectedGraph.copy(), DirectedGraph.iter_parents(), and DirectedGraph.remove().
_forwards
_forwards protected
Definition at line 11 of file structs.py.
Referenced by DirectedGraph.add(), DirectedGraph.connect(), DirectedGraph.connected(), DirectedGraph.copy(), DirectedGraph.iter_children(), DirectedGraph.iter_edges(), and DirectedGraph.remove().
_vertices
_vertices protected
Definition at line 10 of file structs.py.
Referenced by DirectedGraph.__contains__(), DirectedGraph.__iter__(), DirectedGraph.__len__(), DirectedGraph.add(), DirectedGraph.connect(), DirectedGraph.copy(), and DirectedGraph.remove().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/structs.py