Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: ParseElementEnhance Class Reference
ParseElementEnhance Class Reference
Public Member Functions
__init__ (self, Union[ParserElement, str] expr, bool savelist=False)
List[ParserElement] recurse (self)
parseImpl (self, instring, loc, doActions=True)
ParserElement leave_whitespace (self, bool recursive=True)
ParserElement ignore_whitespace (self, bool recursive=True)
ParserElement ignore (self, other)
ParserElement streamline (self)
None validate (self, validateTrace=None)
leaveWhitespace (self)
ignoreWhitespace (self)
Public Member Functions inherited from ParserElement
using_each (cls, seq, **class_kwargs)
__init__ (self, bool savelist=False)
"ParserElement" suppress_warning (self, Diagnostics warning_type)
visit_all (self)
"ParserElement" copy (self)
"ParserElement" set_results_name (self, str name, bool list_all_matches=False, *, bool listAllMatches=False)
"ParserElement" set_break (self, bool break_flag=True)
"ParserElement" set_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_condition (self, *ParseCondition fns, **kwargs)
"ParserElement" set_fail_action (self, ParseFailAction fn)
int preParse (self, str instring, int loc)
postParse (self, instring, loc, tokenlist)
int try_parse (self, str instring, int loc, *, bool raise_fatal=False, bool do_actions=False)
bool can_parse_next (self, str instring, int loc, bool do_actions=False)
ParseResults parse_string (self, str instring, bool parse_all=False, *, bool parseAll=False)
Generator[Tuple[ParseResults, int, int], None, None] scan_string (self, str instring, int max_matches=_MAX_INT, bool overlap=False, *, bool debug=False, int maxMatches=_MAX_INT)
str transform_string (self, str instring, *, bool debug=False)
ParseResults search_string (self, str instring, int max_matches=_MAX_INT, *, bool debug=False, int maxMatches=_MAX_INT)
Generator[str, None, None] split (self, str instring, int maxsplit=_MAX_INT, bool include_separators=False, *, includeSeparators=False)
"ParserElement" __add__ (self, other)
"ParserElement" __radd__ (self, other)
"ParserElement" __sub__ (self, other)
"ParserElement" __rsub__ (self, other)
"ParserElement" __mul__ (self, other)
"ParserElement" __rmul__ (self, other)
"ParserElement" __or__ (self, other)
"ParserElement" __ror__ (self, other)
"ParserElement" __xor__ (self, other)
"ParserElement" __rxor__ (self, other)
"ParserElement" __and__ (self, other)
"ParserElement" __rand__ (self, other)
"ParserElement" __invert__ (self)
__getitem__ (self, key)
"ParserElement" __call__ (self, typing.Optional[str] name=None)
"ParserElement" suppress (self)
"ParserElement" set_whitespace_chars (self, Union[Set[str], str] chars, bool copy_defaults=False)
"ParserElement" parse_with_tabs (self)
"ParserElement" set_debug_actions (self, DebugStartAction start_action, DebugSuccessAction success_action, DebugExceptionAction exception_action)
"ParserElement" set_debug (self, bool flag=True, bool recurse=False)
str default_name (self)
"ParserElement" set_name (self, str name)
str name (self)
str __str__ (self)
str __repr__ (self)
ParseResults parse_file (self, Union[str, Path, TextIO] file_or_filename, str encoding="utf-8", bool parse_all=False, *, bool parseAll=False)
__eq__ (self, other)
__hash__ (self)
bool matches (self, str test_string, bool parse_all=True, *, bool parseAll=True)
Tuple[bool, List[Tuple[str, Union[ParseResults, Exception]]]] run_tests (self, Union[str, List[str]] tests, bool parse_all=True, typing.Optional[Union["ParserElement", str]] comment="#", bool full_dump=True, bool print_results=True, bool failure_tests=False, typing.Optional[Callable[[str, ParseResults], str]] post_parse=None, typing.Optional[TextIO] file=None, bool with_line_numbers=False, *, bool parseAll=True, bool fullDump=True, bool printResults=True, bool failureTests=False, typing.Optional[Callable[[str, ParseResults], str]] postParse=None)
None create_diagram (self, Union[TextIO, Path, str] output_html, int vertical=3, bool show_results_names=False, bool show_groups=False, bool embed=False, **kwargs)
setResultsName (self)
setBreak (self)
setParseAction (self)
addParseAction (self)
addCondition (self)
setFailAction (self)
tryParse (self)
parseString (self)
scanString (self)
transformString (self)
searchString (self)
setWhitespaceChars (self)
parseWithTabs (self)
setDebugActions (self)
setDebug (self)
setName (self)
parseFile (self)
runTests (self)
Data Fields
expr = expr
Data Fields inherited from ParserElement
List[ParseAction] parseAction = list()
typing.Optional[ParseFailAction] failAction = None
str customName = None
str resultsName = None
saveAsList = savelist
bool skipWhitespace = True
whiteChars = set(ParserElement.DEFAULT_WHITE_CHARS)
bool copyDefaultWhiteChars = True
bool mayReturnEmpty = False
bool keepTabs = False
List[] ignoreExprs = list()
bool debug = False
bool streamlined = False
bool mayIndexError = True
str errmsg = ""
bool modalResults = True
debugActions = self.DebugActions(None, None, None)
bool callPreparse = True
bool callDuringTry = False
list suppress_warnings_ = []
Protected Member Functions
_checkRecursion (self, parseElementList)
str _generateDefaultName (self)
Protected Member Functions inherited from ParserElement
_setResultsName (self, name, listAllMatches=False)
int _skipIgnorables (self, str instring, int loc)
Tuple[int, ParseResults] _parseNoCache (self, instring, loc, doActions=True, callPreParse=True)
Tuple[int, ParseResults] _parseCache (self, instring, loc, doActions=True, callPreParse=True)
Additional Inherited Members
Static Public Member Functions inherited from ParserElement
None set_default_whitespace_chars (str chars)
None inline_literals_using (type cls)
None reset_cache ()
None disable_memoization ()
None enable_left_recursion (typing.Optional[int] cache_size_limit=None, *, force=False)
None enable_packrat (int cache_size_limit=128, *, bool force=False)
inlineLiteralsUsing ()
setDefaultWhitespaceChars ()
enableLeftRecursion ()
enablePackrat ()
Static Public Attributes inherited from ParserElement
str DEFAULT_WHITE_CHARS = " \n\t\r"
bool verbose_stacktrace = False
recursion_lock = RLock()
dict recursion_memos = {}
tuple packrat_cache
packrat_cache_lock = RLock()
list packrat_cache_stats = [0, 0]
bool canParseNext = can_parse_next
None resetCache = reset_cache
str defaultName = default_name
Protected Attributes inherited from ParserElement
typing.Optional[str] _defaultName = None
Static Protected Attributes inherited from ParserElement
type _literalStringClass = None
Tuple[int, ParseResults] _parse = _parseNoCache
bool _packratEnabled = False
bool _left_recursion_enabled = False
Detailed Description
Abstract subclass of :class:`ParserElement`, for combining and
post-processing parsed tokens.
Definition at line 4514 of file core.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, Union[ParserElement, str] expr, bool savelist = False)
Definition at line 4519 of file core.py.
    def __init__(self, expr: Union[ParserElement, str], savelist: bool = False):
        super().__init__(savelist)
        if isinstance(expr, str_type):
            expr_str = typing.cast(str, expr)
            if issubclass(self._literalStringClass, Token):
                expr = self._literalStringClass(expr_str)  # type: ignore[call-arg]
            elif issubclass(type(self), self._literalStringClass):
                expr = Literal(expr_str)
            else:
                expr = self._literalStringClass(Literal(expr_str))  # type: ignore[assignment, call-arg]
        expr = typing.cast(ParserElement, expr)
        self.expr = expr
        if expr is not None:
            self.mayIndexError = expr.mayIndexError
            self.mayReturnEmpty = expr.mayReturnEmpty
            self.set_whitespace_chars(
                expr.whiteChars, copy_defaults=expr.copyDefaultWhiteChars
            )
            self.skipWhitespace = expr.skipWhitespace
            self.saveAsList = expr.saveAsList
            self.callPreparse = expr.callPreparse
            self.ignoreExprs.extend(expr.ignoreExprs)
References __init__().
Referenced by __init__().
Member Function Documentation
_checkRecursion()
_checkRecursion (self, parseElementList) protected
Reimplemented from ParserElement.
Definition at line 4591 of file core.py.
    def _checkRecursion(self, parseElementList):
        if self in parseElementList:
            raise RecursiveGrammarException(parseElementList + [self])
        subRecCheckList = parseElementList[:] + [self]
        if self.expr is not None:
            self.expr._checkRecursion(subRecCheckList)
References _checkRecursion(), and expr.
Referenced by _checkRecursion().
_generateDefaultName()
str _generateDefaultName (self) protected
Child classes must define this method, which defines how the ``default_name`` is set.
Reimplemented from ParserElement.
Reimplemented in DelimitedList, Forward, NotAny, OneOrMore, Opt, and ZeroOrMore.
Definition at line 4611 of file core.py.
    def _generateDefaultName(self) -> str:
        return f"{self.__class__.__name__}:({str(self.expr)})"
ignore()
ParserElement ignore (self, other)
Define expression to be ignored (e.g., comments) while doing pattern
matching; may be called repeatedly, to define multiple comment or other
ignorable patterns.
Example::
    patt = Word(alphas)[1, ...]
    patt.parse_string('ablaj /* comment */ lskjd')
    # -> ['ablaj']
    patt.ignore(c_style_comment)
    patt.parse_string('ablaj /* comment */ lskjd')
    # -> ['ablaj', 'lskjd']
Reimplemented from ParserElement.
Reimplemented in Combine.
Definition at line 4573 of file core.py.
    def ignore(self, other) -> ParserElement:
        if isinstance(other, Suppress):
            if other not in self.ignoreExprs:
                super().ignore(other)
                if self.expr is not None:
                    self.expr.ignore(self.ignoreExprs[-1])
        else:
            super().ignore(other)
            if self.expr is not None:
                self.expr.ignore(self.ignoreExprs[-1])
        return self
ignore_whitespace()
ParserElement ignore_whitespace (self, bool recursive = True)
Enables the skipping of whitespace before matching the characters in the
:class:`ParserElement`'s defined pattern.
:param recursive: If ``True`` (the default), also enable whitespace skipping in child elements (if any)
Reimplemented from ParserElement.
Reimplemented in Forward.
Definition at line 4564 of file core.py.
    def ignore_whitespace(self, recursive: bool = True) -> ParserElement:
        super().ignore_whitespace(recursive)
        if recursive:
            if self.expr is not None:
                self.expr = self.expr.copy()
                self.expr.ignore_whitespace(recursive)
        return self
References ParserElement.copy(), expr, and ignore_whitespace().
Referenced by ignore_whitespace().
ignoreWhitespace()
ignoreWhitespace (self)
Reimplemented from ParserElement.
Reimplemented in Forward.
Definition at line 4620 of file core.py.
    def ignoreWhitespace(self): ...
leave_whitespace()
ParserElement leave_whitespace (self, bool recursive = True)
Disables the skipping of whitespace before matching the characters in the
:class:`ParserElement`'s defined pattern.  This is normally only used internally by
the pyparsing module, but may be needed in some whitespace-sensitive grammars.
:param recursive: If true (the default), also disable whitespace skipping in child elements (if any)
Reimplemented from ParserElement.
Reimplemented in Forward.
Definition at line 4555 of file core.py.
    def leave_whitespace(self, recursive: bool = True) -> ParserElement:
        super().leave_whitespace(recursive)
        if recursive:
            if self.expr is not None:
                self.expr = self.expr.copy()
                self.expr.leave_whitespace(recursive)
        return self
References ParserElement.copy(), expr, and leave_whitespace().
Referenced by leave_whitespace().
leaveWhitespace()
leaveWhitespace (self)
Reimplemented from ParserElement.
Reimplemented in Forward.
Definition at line 4617 of file core.py.
    def leaveWhitespace(self): ...
parseImpl()
parseImpl (self, instring, loc, doActions = True)
Reimplemented from ParserElement.
Reimplemented in _MultipleMatch, AtLineStart, AtStringStart, FollowedBy, Forward, IndentedBlock, Located, NotAny, Opt, PrecededBy, SkipTo, and ZeroOrMore.
Definition at line 4545 of file core.py.
    def parseImpl(self, instring, loc, doActions=True):
        if self.expr is not None:
            try:
                return self.expr._parse(instring, loc, doActions, callPreParse=False)
            except ParseBaseException as pbe:
                pbe.msg = self.errmsg
                raise
        else:
            raise ParseException(instring, loc, "No expression defined", self)
References ParserElement._parse, ParserElement.errmsg, and expr.
recurse()
List[ParserElement] recurse (self)
Reimplemented from ParserElement.
Definition at line 4542 of file core.py.
    def recurse(self) -> List[ParserElement]:
        return [self.expr] if self.expr is not None else []
References expr.
Referenced by _MultipleMatch._setResultsName().
streamline()
ParserElement streamline (self)
Reimplemented from ParserElement.
Reimplemented in Forward.
Definition at line 4585 of file core.py.
    def streamline(self) -> ParserElement:
        super().streamline()
        if self.expr is not None:
            self.expr.streamline()
        return self
References expr, and streamline().
Referenced by DelimitedList._generateDefaultName(), and streamline().
validate()
None validate (self, validateTrace = None)
Check defined expressions for valid structure, check for infinite recursive definitions.
Reimplemented from ParserElement.
Reimplemented in Forward.
Definition at line 4598 of file core.py.
    def validate(self, validateTrace=None) -> None:
        warnings.warn(
            "ParserElement.validate() is deprecated, and should not be used to check for left recursion",
            DeprecationWarning,
            stacklevel=2,
        )
        if validateTrace is None:
            validateTrace = []
        tmp = validateTrace[:] + [self]
        if self.expr is not None:
            self.expr.validate(tmp)
        self._checkRecursion([])
References ParserElement._checkRecursion(), expr, and validate.
Field Documentation
expr
expr = expr
Definition at line 4530 of file core.py.
Referenced by Forward.__del__(), Suppress.__sub__(), _checkRecursion(), Opt._generateDefaultName(), _MultipleMatch._setResultsName(), Forward._setResultsName(), Forward.copy(), ignore_whitespace(), leave_whitespace(), _MultipleMatch.parseImpl(), FollowedBy.parseImpl(), Forward.parseImpl(), IndentedBlock.parseImpl(), Located.parseImpl(), NotAny.parseImpl(), Opt.parseImpl(), parseImpl(), PrecededBy.parseImpl(), SkipTo.parseImpl(), recurse(), Forward.streamline(), streamline(), Forward.validate(), and validate().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/core.py