Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Latin1Prober Class Reference
Latin1Prober Class Reference
Public Member Functions
None __init__ (self)
None reset (self)
str charset_name (self)
str language (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
float get_confidence (self)
Public Member Functions inherited from CharSetProber
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
ProbingState state (self)
Protected Attributes
_last_char_class = OTH
list _freq_counter = []
Protected Attributes inherited from CharSetProber
_state = ProbingState.DETECTING
Additional Inherited Members
Static Public Member Functions inherited from CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Data Fields inherited from CharSetProber
bool active = True
lang_filter = lang_filter
logger = logging.getLogger(__name__)
Static Public Attributes inherited from CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Detailed Description
Definition at line 100 of file latin1prober.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Definition at line 101 of file latin1prober.py.
    def __init__(self) -> None:
        super().__init__()
        self._last_char_class = OTH
        self._freq_counter: List[int] = []
        self.reset()
References __init__().
Referenced by __init__().
Member Function Documentation
charset_name()
str charset_name (self)
Reimplemented from CharSetProber.
Definition at line 113 of file latin1prober.py.
    def charset_name(self) -> str:
        return "ISO-8859-1"
feed()
ProbingState feed (self, Union[bytes, bytearray] byte_str)
Reimplemented from CharSetProber.
Definition at line 120 of file latin1prober.py.
    def feed(self, byte_str: Union[bytes, bytearray]) -> ProbingState:
        byte_str = self.remove_xml_tags(byte_str)
        for c in byte_str:
            char_class = Latin1_CharToClass[c]
            freq = Latin1ClassModel[(self._last_char_class * CLASS_NUM) + char_class]
            if freq == 0:
                self._state = ProbingState.NOT_ME
                break
            self._freq_counter[freq] += 1
            self._last_char_class = char_class
        return self.state
References _last_char_class, and CharSetProber.remove_xml_tags().
get_confidence()
float get_confidence (self)
Reimplemented from CharSetProber.
Definition at line 133 of file latin1prober.py.
    def get_confidence(self) -> float:
        if self.state == ProbingState.NOT_ME:
            return 0.01
        total = sum(self._freq_counter)
        confidence = (
            0.0
            if total < 0.01
            else (self._freq_counter[3] - self._freq_counter[1] * 20.0) / total
        )
        confidence = max(confidence, 0.0)
        # lower the confidence of latin1 so that other more accurate
        # detector can take priority.
        confidence *= 0.73
        return confidence
language()
str language (self)
Reimplemented from CharSetProber.
Definition at line 117 of file latin1prober.py.
    def language(self) -> str:
        return ""
reset()
None reset (self)
Reimplemented from CharSetProber.
Definition at line 107 of file latin1prober.py.
    def reset(self) -> None:
        self._last_char_class = OTH
        self._freq_counter = [0] * FREQ_CAT_NUM
        super().reset()
References _freq_counter, _last_char_class, and reset().
Referenced by reset().
Field Documentation
_freq_counter
list _freq_counter = [] protected
Definition at line 104 of file latin1prober.py.
Referenced by reset(), and MacRomanProber.reset().
_last_char_class
_last_char_class = OTH protected
Definition at line 103 of file latin1prober.py.
Referenced by feed(), MacRomanProber.feed(), reset(), and MacRomanProber.reset().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/chardet/latin1prober.py