Let us walk on the 3-isogeny graph: JSONHighlighter Class Reference
JSONHighlighter Class Reference
Public Member Functions
None highlight (self, Text text)
Public Member Functions inherited from Highlighter
Text __call__ (self, Union[str, Text] text)
Data Fields
JSON_STR
Static Public Attributes
str JSON_STR = r"(?<![\\\w])(?P<str>b?\".*?(?<!\\‍)\")"
dict JSON_WHITESPACE = {" ", "\n", "\r", "\t"}
str base_style = "json."
list highlights
Static Public Attributes inherited from RegexHighlighter
list highlights = []
str base_style = ""
Detailed Description
Highlights JSON
Definition at line 106 of file highlighter.py.
Member Function Documentation
highlight()
None highlight (self, Text text)
Highlight :class:`rich.text.Text` using regular expressions.
Args:
    text (~Text): Text to highlighted.
Reimplemented from RegexHighlighter.
Definition at line 123 of file highlighter.py.
    def highlight(self, text: Text) -> None:
        super().highlight(text)
        # Additional work to handle highlighting JSON keys
        plain = text.plain
        append = text.spans.append
        whitespace = self.JSON_WHITESPACE
        for match in re.finditer(self.JSON_STR, plain):
            start, end = match.span()
            cursor = end
            while cursor < len(plain):
                char = plain[cursor]
                cursor += 1
                if char == ":":
                    append(Span(start, end, "json.key"))
                elif char in whitespace:
                    continue
                break
References i, and JSONHighlighter.JSON_WHITESPACE.
Referenced by Highlighter.__call__(), Panel.__rich_console__(), Table.__rich_console__(), Tree.__rich_console__(), Syntax._get_syntax(), and Tree.add().
Field Documentation
base_style
str base_style = "json." static
Definition at line 113 of file highlighter.py.
Referenced by RegexHighlighter.highlight().
highlights
list highlights static
Initial value:
=  [
        _combine_regex(
            r"(?P<brace>[\{\[\‍(\‍)\]\}])",
            r"\b(?P<bool_true>true)\b|\b(?P<bool_false>false)\b|\b(?P<null>null)\b",
            r"(?P<number>(?<!\w)\-?[0-9]+\.?[0-9]*(e[\-\+]?\d+?)?\b|0x[0-9a-fA-F]*)",
            JSON_STR,
        ),
    ]
Definition at line 114 of file highlighter.py.
Referenced by RegexHighlighter.highlight().
JSON_STR [1/2]
str JSON_STR = r"(?<![\\\w])(?P<str>b?\".*?(?<!\\‍)\")" static
Definition at line 110 of file highlighter.py.
JSON_STR [2/2]
JSON_STR
Definition at line 130 of file highlighter.py.
JSON_WHITESPACE
dict JSON_WHITESPACE = {" ", "\n", "\r", "\t"} static
Definition at line 111 of file highlighter.py.
Referenced by JSONHighlighter.highlight().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/rich/highlighter.py