Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: pip._vendor.rich.scope Namespace Reference
pip._vendor.rich.scope Namespace Reference
Functions
"ConsoleRenderable" render_scope ("Mapping[str, Any]" scope, *, Optional[TextType] title=None, bool sort_keys=True, bool indent_guides=False, Optional[int] max_length=None, Optional[int] max_string=None)
None test (float foo, float bar)
Function Documentation
render_scope()
"ConsoleRenderable" render_scope ("Mapping[str, Any]" scope, * , Optional[TextType] title = None, bool sort_keys = True, bool indent_guides = False, Optional[int] max_length = None, Optional[int] max_string = None)
Render python variables in a given scope.
Args:
    scope (Mapping): A mapping containing variable names and values.
    title (str, optional): Optional title. Defaults to None.
    sort_keys (bool, optional): Enable sorting of items. Defaults to True.
    indent_guides (bool, optional): Enable indentation guides. Defaults to False.
    max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
        Defaults to None.
    max_string (int, optional): Maximum length of string before truncating, or None to disable. Defaults to None.
Returns:
    ConsoleRenderable: A renderable object.
Definition at line 14 of file scope.py.
) -> "ConsoleRenderable":
    """Render python variables in a given scope.
    Args:
        scope (Mapping): A mapping containing variable names and values.
        title (str, optional): Optional title. Defaults to None.
        sort_keys (bool, optional): Enable sorting of items. Defaults to True.
        indent_guides (bool, optional): Enable indentation guides. Defaults to False.
        max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
            Defaults to None.
        max_string (int, optional): Maximum length of string before truncating, or None to disable. Defaults to None.
    Returns:
        ConsoleRenderable: A renderable object.
    """
    highlighter = ReprHighlighter()
    items_table = Table.grid(padding=(0, 1), expand=False)
    items_table.add_column(justify="right")
    def sort_items(item: Tuple[str, Any]) -> Tuple[bool, str]:
        """Sort special variables first, then alphabetically."""
        key, _ = item
        return (not key.startswith("__"), key.lower())
    items = sorted(scope.items(), key=sort_items) if sort_keys else scope.items()
    for key, value in items:
        key_text = Text.assemble(
            (key, "scope.key.special" if key.startswith("__") else "scope.key"),
            (" =", "scope.equals"),
        )
        items_table.add_row(
            key_text,
            Pretty(
                value,
                highlighter=highlighter,
                indent_guides=indent_guides,
                max_length=max_length,
                max_string=max_string,
            ),
        )
    return Panel.fit(
        items_table,
        title=title,
        border_style="scope.border",
        padding=(0, 1),
    )
References pip._vendor.rich.print().
Referenced by test().
test()
None test (float foo, float bar)
Definition at line 75 of file scope.py.
    def test(foo: float, bar: float) -> None:
        list_of_things = [1, 2, 3, None, 4, True, False, "Hello World"]
        dict_of_things = {
            "version": "1.1",
            "method": "confirmFruitPurchase",
            "params": [["apple", "orange", "mangoes", "pomelo"], 1.123],
            "id": "194521489",
        }
        print(render_scope(locals(), title="[i]locals", sort_keys=False))
References pip._vendor.rich.print(), render_scope(), and test().
Referenced by test().