Let us walk on the 3-isogeny graph: RedisCache Class Reference
RedisCache Class Reference
Public Member Functions
__init__ (self, conn)
get (self, key)
set (self, key, value, expires=None)
delete (self, key)
clear (self)
close (self)
Data Fields
conn
Detailed Description
Definition at line 11 of file redis_cache.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, conn)
Definition at line 13 of file redis_cache.py.
    def __init__(self, conn):
        self.conn = conn
Referenced by Protocol.__init_subclass__().
Member Function Documentation
clear()
clear (self)
Helper for clearing all the keys in a database. Use with
caution!
Definition at line 31 of file redis_cache.py.
    def clear(self):
        """Helper for clearing all the keys in a database. Use with
        caution!"""
        for key in self.conn.keys():
            self.conn.delete(key)
References RedisCache.conn.
Referenced by PoolManager.__exit__().
close()
close (self)
Redis uses connection pooling, no need to close the connection.
Reimplemented from BaseCache.
Definition at line 37 of file redis_cache.py.
    def close(self):
        """Redis uses connection pooling, no need to close the connection."""
        pass
Referenced by SSLTransport.__exit__(), Response.__exit__(), Session.__exit__(), ZipExtFile.__exit__(), ZipFile.__exit__(), ConnectionPool.__exit__(), _Reader.__exit__(), WrappedSocket._custom_validate(), WrappedSocket._decref_socketios(), WrappedSocket._drop(), WrappedSocket._raise_on_error(), HTTPResponse._update_chunk_length(), and WrappedSocket.recv_into().
delete()
delete (self, key)
Reimplemented from BaseCache.
Definition at line 28 of file redis_cache.py.
    def delete(self, key):
        self.conn.delete(key)
References RedisCache.conn.
get()
get (self, key)
Reimplemented from BaseCache.
Definition at line 16 of file redis_cache.py.
    def get(self, key):
        return self.conn.get(key)
References RedisCache.conn.
Referenced by LegacyMetadata.__getitem__(), Layout.__getitem__(), LegacyMetadata.check(), ThemeStack.push_theme(), and LegacyMetadata.write_file().
set()
set (self, key, value, expires = None)
Reimplemented from BaseCache.
Definition at line 19 of file redis_cache.py.
    def set(self, key, value, expires=None):
        if not expires:
            self.conn.set(key, value)
        elif isinstance(expires, datetime):
            expires = expires - datetime.utcnow()
            self.conn.setex(key, int(expires.total_seconds()), value)
        else:
            self.conn.setex(key, expires, value)
References RedisCache.conn, i, and RedisCache.set().
Referenced by LegacyMetadata.__setitem__(), RequestsCookieJar.__setitem__(), Flags.finalize_pending(), LegacyMetadata.read_file(), RedisCache.set(), and LegacyMetadata.update().
Field Documentation
conn
conn
Definition at line 14 of file redis_cache.py.
Referenced by RedisCache.clear(), RedisCache.delete(), RedisCache.get(), and RedisCache.set().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/cachecontrol/caches/redis_cache.py