Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: DownloadCommand Class Reference
DownloadCommand Class Reference
Public Member Functions
None add_options (self)
int run (self, Values options, List[str] args)
Public Member Functions inherited from RequirementCommand
None __init__ (self, *Any args, **Any kw)
RequirementPreparer make_requirement_preparer (cls, TempDirectory temp_build_dir, Values options, BuildTracker build_tracker, PipSession session, PackageFinder finder, bool use_user_site, Optional[str] download_dir=None, int verbosity=0)
BaseResolver make_resolver (cls, RequirementPreparer preparer, PackageFinder finder, Values options, Optional[WheelCache] wheel_cache=None, bool use_user_site=False, bool ignore_installed=True, bool ignore_requires_python=False, bool force_reinstall=False, str upgrade_strategy="to-satisfy-only", Optional[bool] use_pep517=None, Optional[Tuple[int,...]] py_version_info=None)
List[InstallRequirement] get_requirements (self, List[str] args, Values options, PackageFinder finder, PipSession session)
Public Member Functions inherited from IndexGroupCommand
None handle_pip_version_check (self, Values options)
Public Member Functions inherited from Command
None __init__ (self, str name, str summary, bool isolated=False)
Tuple[Values, List[str]] parse_args (self, List[str] args)
int main (self, List[str] args)
Public Member Functions inherited from CommandContextMixIn
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Public Member Functions inherited from SessionCommandMixin
None __init__ (self)
PipSession get_default_session (self, Values options)
Additional Inherited Members
Static Public Member Functions inherited from RequirementCommand
str determine_resolver_variant (Values options)
None trace_basic_info (PackageFinder finder)
Data Fields inherited from Command
name = name
summary = summary
parser
Optional[TempDirRegistry] tempdir_registry = None
cmd_opts = optparse.OptionGroup(self.parser, optgroup_name)
verbosity = options.verbose - options.quiet
Static Public Attributes inherited from Command
str usage = ""
bool ignore_require_venv = False
Protected Member Functions inherited from RequirementCommand
PackageFinder _build_package_finder (self, Values options, PipSession session, Optional[TargetPython] target_python=None, Optional[bool] ignore_requires_python=None)
Protected Member Functions inherited from Command
int _main (self, List[str] args)
Protected Member Functions inherited from SessionCommandMixin
Optional[List[str]] _get_index_urls (cls, Values options)
PipSession _build_session (self, Values options, Optional[int] retries=None, Optional[int] timeout=None, bool fallback_to_certifi=False)
Protected Attributes inherited from CommandContextMixIn
bool _in_main_context = False
_main_context = ExitStack()
Protected Attributes inherited from SessionCommandMixin
Optional[PipSession] _session = None
Detailed Description
Download packages from:
- PyPI (and other indexes) using requirement specifiers.
- VCS project urls.
- Local project directories.
- Local or remote source archives.
pip also supports downloading from "requirements files", which provide
an easy way to specify a whole environment to be downloaded.
Definition at line 18 of file download.py.
Member Function Documentation
add_options()
None add_options (self)
Reimplemented from Command.
Definition at line 38 of file download.py.
    def add_options(self) -> None:
        self.cmd_opts.add_option(cmdoptions.constraints())
        self.cmd_opts.add_option(cmdoptions.requirements())
        self.cmd_opts.add_option(cmdoptions.no_deps())
        self.cmd_opts.add_option(cmdoptions.global_options())
        self.cmd_opts.add_option(cmdoptions.no_binary())
        self.cmd_opts.add_option(cmdoptions.only_binary())
        self.cmd_opts.add_option(cmdoptions.prefer_binary())
        self.cmd_opts.add_option(cmdoptions.src())
        self.cmd_opts.add_option(cmdoptions.pre())
        self.cmd_opts.add_option(cmdoptions.require_hashes())
        self.cmd_opts.add_option(cmdoptions.progress_bar())
        self.cmd_opts.add_option(cmdoptions.no_build_isolation())
        self.cmd_opts.add_option(cmdoptions.use_pep517())
        self.cmd_opts.add_option(cmdoptions.no_use_pep517())
        self.cmd_opts.add_option(cmdoptions.check_build_deps())
        self.cmd_opts.add_option(cmdoptions.ignore_requires_python())
        self.cmd_opts.add_option(
            "-d",
            "--dest",
            "--destination-dir",
            "--destination-directory",
            dest="download_dir",
            metavar="dir",
            default=os.curdir,
            help="Download packages into <dir>.",
        )
        cmdoptions.add_target_python_options(self.cmd_opts)
        index_opts = cmdoptions.make_option_group(
            cmdoptions.index_group,
            self.parser,
        )
        self.parser.insert_option_group(0, index_opts)
        self.parser.insert_option_group(0, self.cmd_opts)
References Command.cmd_opts.
run()
int run (self, Values options, List[str] args)
Reimplemented from Command.
Definition at line 78 of file download.py.
    def run(self, options: Values, args: List[str]) -> int:
        options.ignore_installed = True
        # editable doesn't really make sense for `pip download`, but the bowels
        # of the RequirementSet code require that property.
        options.editables = []
        cmdoptions.check_dist_restriction(options)
        options.download_dir = normalize_path(options.download_dir)
        ensure_dir(options.download_dir)
        session = self.get_default_session(options)
        target_python = make_target_python(options)
        finder = self._build_package_finder(
            options=options,
            session=session,
            target_python=target_python,
            ignore_requires_python=options.ignore_requires_python,
        )
        build_tracker = self.enter_context(get_build_tracker())
        directory = TempDirectory(
            delete=not options.no_clean,
            kind="download",
            globally_managed=True,
        )
        reqs = self.get_requirements(args, options, finder, session)
        check_legacy_setup_py_options(options, reqs)
        preparer = self.make_requirement_preparer(
            temp_build_dir=directory,
            options=options,
            build_tracker=build_tracker,
            session=session,
            finder=finder,
            download_dir=options.download_dir,
            use_user_site=False,
            verbosity=self.verbosity,
        )
        resolver = self.make_resolver(
            preparer=preparer,
            finder=finder,
            options=options,
            ignore_requires_python=options.ignore_requires_python,
            use_pep517=options.use_pep517,
            py_version_info=options.python_version,
        )
        self.trace_basic_info(finder)
        requirement_set = resolver.resolve(reqs, check_supported_wheels=True)
        downloaded: List[str] = []
        for req in requirement_set.requirements.values():
            if req.satisfied_by is None:
                assert req.name is not None
                preparer.save_linked_requirement(req)
                downloaded.append(req.name)
        preparer.prepare_linked_requirements_more(requirement_set.requirements.values())
        requirement_set.warn_legacy_versions_and_specifiers()
        if downloaded:
            write_output("Successfully downloaded %s", " ".join(downloaded))
        return SUCCESS
References RequirementCommand._build_package_finder(), CommandContextMixIn.enter_context(), SessionCommandMixin.get_default_session(), RequirementCommand.get_requirements(), RequirementCommand.make_requirement_preparer(), RequirementCommand.make_resolver(), RequirementCommand.trace_basic_info(), and Command.verbosity.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/commands/download.py