Let us walk on the 3-isogeny graph: ParserElement._CacheType Class Reference
ParserElement._CacheType Class Reference
Public Member Functions
get (self, *args)
set (self, *args)
Static Public Attributes
bool not_in_cache
Detailed Description
class to help type checking
Definition at line 935 of file core.py.
Member Function Documentation
get()
get (self, * args)
Definition at line 942 of file core.py.
        def get(self, *args):
            ...
Referenced by LegacyMetadata.__getitem__(), Layout.__getitem__(), LegacyMetadata.check(), ThemeStack.push_theme(), and LegacyMetadata.write_file().
set()
set (self, * args)
Definition at line 945 of file core.py.
        def set(self, *args):
            ...
    # argument cache for optimizing repeated calls when backtracking through recursive expressions
Referenced by LegacyMetadata.__setitem__(), RequestsCookieJar.__setitem__(), Flags.finalize_pending(), LegacyMetadata.read_file(), and LegacyMetadata.update().
Field Documentation
not_in_cache
bool not_in_cache static
Definition at line 940 of file core.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/core.py