Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: BaseEntryPoint Class Reference
BaseEntryPoint Class Reference
Public Member Functions
str name (self)
str value (self)
str group (self)
Detailed Description
Definition at line 57 of file base.py.
Member Function Documentation
group()
str group (self)
Definition at line 67 of file base.py.
    def group(self) -> str:
        raise NotImplementedError()
name()
str name (self)
Definition at line 59 of file base.py.
    def name(self) -> str:
        raise NotImplementedError()
Referenced by ParserElement.__str__(), Tag.__str__(), SpecifierRequirement.is_satisfied_by(), and LinuxDistribution.linux_distribution().
value()
str value (self)
Definition at line 63 of file base.py.
    def value(self) -> str:
        raise NotImplementedError()
Referenced by LinkHash.as_hashes(), and LinkHash.is_hash_allowed().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/metadata/base.py