Let us walk on the 3-isogeny graph: Future Class Reference
Future Class Reference
Public Member Functions
get (self)
Detailed Description
Generic class to defer some work.
Handled specially in RegexLexerMeta, to support regex string construction at
first use.
Definition at line 271 of file util.py.
Member Function Documentation
get()
get (self)
Reimplemented in words.
Definition at line 277 of file util.py.
    def get(self):
        raise NotImplementedError
Referenced by LegacyMetadata.__getitem__(), Layout.__getitem__(), LegacyMetadata.check(), ThemeStack.push_theme(), and LegacyMetadata.write_file().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pygments/util.py