Let us walk on the 3-isogeny graph: AbstractResolver Class Reference
AbstractResolver Class Reference
Public Member Functions
__init__ (self, provider, reporter)
resolve (self, requirements, **kwargs)
Data Fields
provider
reporter
Static Public Attributes
base_exception = Exception
Detailed Description
The thing that performs the actual resolution work.
Definition at line 112 of file providers.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, provider, reporter)
Definition at line 117 of file providers.py.
    def __init__(self, provider, reporter):
        self.provider = provider
        self.reporter = reporter
Referenced by Protocol.__init_subclass__().
Member Function Documentation
resolve()
resolve (self, requirements, ** kwargs)
Take a collection of constraints, spit out the resolution result.
This returns a representation of the final resolution state, with one
guarenteed attribute ``mapping`` that contains resolved candidates as
values. The keys are their respective identifiers.
:param requirements: A collection of constraints.
:param kwargs: Additional keyword arguments that subclasses may accept.
:raises: ``self.base_exception`` or its subclass.
Reimplemented in Resolver.
Definition at line 121 of file providers.py.
    def resolve(self, requirements, **kwargs):
        """Take a collection of constraints, spit out the resolution result.
        This returns a representation of the final resolution state, with one
        guarenteed attribute ``mapping`` that contains resolved candidates as
        values. The keys are their respective identifiers.
        :param requirements: A collection of constraints.
        :param kwargs: Additional keyword arguments that subclasses may accept.
        :raises: ``self.base_exception`` or its subclass.
        """
        raise NotImplementedError
Referenced by BaseConfigurator.configure_custom(), Configurator.configure_custom(), and BaseConfigurator.ext_convert().
Field Documentation
base_exception
base_exception = Exception static
Definition at line 115 of file providers.py.
provider
provider
Definition at line 118 of file providers.py.
Referenced by Resolver.resolve().
reporter
reporter
Definition at line 119 of file providers.py.
Referenced by Resolver.resolve().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/providers.py