Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: _FlatDirectorySource Class Reference
_FlatDirectorySource Class Reference
Public Member Functions
None __init__ (self, CandidatesFromPage candidates_from_page, str path)
Optional[Link] link (self)
FoundCandidates page_candidates (self)
FoundLinks file_links (self)
Protected Attributes
_candidates_from_page = candidates_from_page
_path = pathlib.Path(os.path.realpath(path))
Detailed Description
Link source specified by ``--find-links=<path-to-dir>``.
This looks the content of the directory, and returns:
* ``page_candidates``: Links listed on each HTML file in the directory.
* ``file_candidates``: Archives in the directory.
Definition at line 39 of file sources.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, CandidatesFromPage candidates_from_page, str path)
Definition at line 48 of file sources.py.
    ) -> None:
        self._candidates_from_page = candidates_from_page
        self._path = pathlib.Path(os.path.realpath(path))
Member Function Documentation
file_links()
FoundLinks file_links (self)
Links found by specifying archives directly.
Reimplemented from LinkSource.
Definition at line 67 of file sources.py.
    def file_links(self) -> FoundLinks:
        for path in self._path.iterdir():
            url = path_to_url(str(path))
            if _is_html_file(url):
                continue
            yield Link(url)
References pip._internal.index.sources._is_html_file(), and _path.
link()
Optional[Link] link (self)
Returns the underlying link, if there's one.
Reimplemented from LinkSource.
Definition at line 57 of file sources.py.
    def link(self) -> Optional[Link]:
        return None
page_candidates()
FoundCandidates page_candidates (self)
Candidates found by parsing an archive listing HTML file.
Reimplemented from LinkSource.
Definition at line 60 of file sources.py.
    def page_candidates(self) -> FoundCandidates:
        for path in self._path.iterdir():
            url = path_to_url(str(path))
            if not _is_html_file(url):
                continue
            yield from self._candidates_from_page(Link(url))
References _candidates_from_page, pip._internal.index.sources._is_html_file(), and _path.
Field Documentation
_candidates_from_page
_candidates_from_page = candidates_from_page protected
Definition at line 53 of file sources.py.
Referenced by page_candidates(), _IndexDirectorySource.page_candidates(), _LocalFileSource.page_candidates(), and _RemoteFileSource.page_candidates().
_path
_path = pathlib.Path(os.path.realpath(path)) protected
Definition at line 54 of file sources.py.
Referenced by file_links(), and page_candidates().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/index/sources.py