Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: CSVReader Class Reference
CSVReader Class Reference
Public Member Functions
__init__ (self, **kwargs)
__iter__ (self)
next (self)
Data Fields
stream = stream
reader = csv.reader(self.stream, **self.defaults)
Detailed Description
Definition at line 1583 of file util.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, ** kwargs)
Definition at line 1584 of file util.py.
    def __init__(self, **kwargs):
        if 'stream' in kwargs:
            stream = kwargs['stream']
            if sys.version_info[0] >= 3:
                # needs to be a text stream
                stream = codecs.getreader('utf-8')(stream)
            self.stream = stream
        else:
            self.stream = _csv_open(kwargs['path'], 'r')
        self.reader = csv.reader(self.stream, **self.defaults)
Member Function Documentation
__iter__()
__iter__ (self)
Definition at line 1595 of file util.py.
    def __iter__(self):
        return self
next()
next (self)
Definition at line 1598 of file util.py.
    def next(self):
        result = next(self.reader)
        if sys.version_info[0] < 3:
            for i, item in enumerate(result):
                if not isinstance(item, text_type):
                    result[i] = item.decode('utf-8')
        return result
References next(), and reader.
Referenced by next().
Field Documentation
reader
reader = csv.reader(self.stream, **self.defaults)
Definition at line 1593 of file util.py.
Referenced by _ReadContext.__enter__(), _ReadContext.__exit__(), next(), and SubprocessMixin.run_command().
stream
stream = stream
Definition at line 1590 of file util.py.
Referenced by HTTPResponse.__iter__(), Session.merge_environment_settings(), and Session.send().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/util.py