Let us walk on the 3-isogeny graph: HiddenText Class Reference
HiddenText Class Reference
Public Member Functions
None __init__ (self, str secret, str redacted)
str __repr__ (self)
str __str__ (self)
bool __eq__ (self, Any other)
Data Fields
secret
redacted
Detailed Description
Definition at line 535 of file misc.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, str secret, str redacted)
Definition at line 536 of file misc.py.
    def __init__(self, secret: str, redacted: str) -> None:
        self.secret = secret
        self.redacted = redacted
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__eq__()
bool __eq__ (self, Any other)
Definition at line 547 of file misc.py.
    def __eq__(self, other: Any) -> bool:
        if type(self) != type(other):
            return False
        # The string being used for redaction doesn't also have to match,
        # just the raw, original string.
        return self.secret == other.secret
References i, and HiddenText.secret.
Referenced by Version.__ge__(), Version.__gt__(), Version.__le__(), Version.__ne__(), Matcher.__ne__(), Timestamp.__ne__(), and HTTPHeaderDict.__ne__().
__repr__()
str __repr__ (self)
Definition at line 540 of file misc.py.
    def __repr__(self) -> str:
        return "<HiddenText {!r}>".format(str(self))
__str__()
str __str__ (self)
Definition at line 543 of file misc.py.
    def __str__(self) -> str:
        return self.redacted
References HiddenText.redacted.
Field Documentation
redacted
redacted
Definition at line 538 of file misc.py.
Referenced by HiddenText.__str__().
secret
secret
Definition at line 537 of file misc.py.
Referenced by HiddenText.__eq__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/utils/misc.py