Let us walk on the 3-isogeny graph: pip._vendor.pyparsing.core Namespace Reference
pip._vendor.pyparsing.core Namespace Reference
Data Structures
class _MultipleMatch
class _NullToken
class _PendingSkip
class _SingleCharLiteral
class And
class AtLineStart
class AtStringStart
class cached_property
class CaselessKeyword
class CaselessLiteral
class Char
class CharsNotIn
class CloseMatch
class Combine
class DelimitedList
class Diagnostics
class Dict
class Each
class Empty
class FollowedBy
class Forward
class GoToColumn
class Group
class IndentedBlock
class Keyword
class LineEnd
class LineStart
class Literal
class Located
class MatchFirst
class NoMatch
class NotAny
class OneOrMore
class Opt
class Or
class ParseElementEnhance
class ParseExpression
class ParserElement
class PositionToken
class PrecededBy
class QuotedString
class Regex
class SkipTo
class StringEnd
class StringStart
class Suppress
class Token
class TokenConverter
class White
class Word
class WordEnd
class WordStart
class ZeroOrMore
Functions
None enable_diag (Diagnostics diag_enum)
None disable_diag (Diagnostics diag_enum)
None enable_all_warnings ()
bool _should_enable_warnings (typing.Iterable[str] cmd_line_warn_options, typing.Optional[str] warn_env_var)
_trim_arity (func, max_limit=3)
ParseAction condition_as_parse_action (ParseCondition fn, typing.Optional[str] message=None, bool fatal=False)
_default_start_debug_action (str instring, int loc, "ParserElement" expr, bool cache_hit=False)
_default_success_debug_action (str instring, int startloc, int endloc, "ParserElement" expr, ParseResults toks, bool cache_hit=False)
_default_exception_debug_action (str instring, int loc, "ParserElement" expr, Exception exc, bool cache_hit=False)
null_debug_action (*args)
ParseAction trace_parse_action (ParseAction f)
str srange (str s)
ParseAction token_map (func, *args)
None autoname_elements ()
nullDebugAction ()
traceParseAction ()
conditionAsParseAction ()
tokenMap ()
Variables
_MAX_INT = sys.maxsize
tuple str_type = (str, bytes)
dict _single_arg_builtins
_generatorType = types.GeneratorType
ParseImplReturnType = Tuple[int, Any]
PostParseReturnType = Union[ParseResults, Sequence[ParseResults]]
ParseAction
ParseCondition
ParseFailAction = Callable[[str, int, "ParserElement", Exception], None]
DebugStartAction = Callable[[str, int, "ParserElement", bool], None]
DebugSuccessAction
DebugExceptionAction = Callable[[str, int, "ParserElement", Exception, bool], None]
alphas = string.ascii_uppercase + string.ascii_lowercase
identchars = pyparsing_unicode.Latin1.identchars
identbodychars = pyparsing_unicode.Latin1.identbodychars
str nums = "0123456789"
str hexnums = nums + "ABCDEFabcdef"
str alphanums = alphas + nums
str printables = "".join([c for c in string.printable if c not in string.whitespace])
traceback _trim_arity_call_line = None
Optional = Opt
empty = Empty().set_name("empty")
line_start = LineStart().set_name("line_start")
line_end = LineEnd().set_name("line_end")
string_start = StringStart().set_name("string_start")
string_end = StringEnd().set_name("string_end")
_escapedPunc
_escapedHexChar
_escapedOctChar
tuple _singleChar
_charRange = Group(_singleChar + Suppress("-") + _singleChar)
tuple _reBracketExpr
dbl_quoted_string
sgl_quoted_string
quoted_string
python_quoted_string
unicode_string = Combine("u" + quoted_string.copy()).set_name("unicode string literal")
str alphas8bit = srange(r"[\0xc0-\0xd6\0xd8-\0xf6\0xf8-\0xff]")
str punc8bit = srange(r"[\0xa1-\0xbf\0xd7\0xf7]")
list _builtin_exprs
sglQuotedString = sgl_quoted_string
dblQuotedString = dbl_quoted_string
quotedString = quoted_string
unicodeString = unicode_string
lineStart = line_start
lineEnd = line_end
stringStart = string_start
stringEnd = string_end
Function Documentation
_default_exception_debug_action()
_default_exception_debug_action (str instring, int loc, "ParserElement" expr, Exception exc, bool cache_hit = False) protected
Definition at line 379 of file core.py.
):
    cache_hit_str = "*" if cache_hit else ""
    print(f"{cache_hit_str}Match {expr} failed, {type(exc).__name__} raised: {exc}")
_default_start_debug_action()
_default_start_debug_action (str instring, int loc, "ParserElement" expr, bool cache_hit = False) protected
Definition at line 354 of file core.py.
):
    cache_hit_str = "*" if cache_hit else ""
    print(
        (
            f"{cache_hit_str}Match {expr} at loc {loc}({lineno(loc, instring)},{col(loc, instring)})\n"
            f"  {line(loc, instring)}\n"
            f"  {' ' * (col(loc, instring) - 1)}^"
        )
    )
_default_success_debug_action()
_default_success_debug_action (str instring, int startloc, int endloc, "ParserElement" expr, ParseResults toks, bool cache_hit = False) protected
Definition at line 367 of file core.py.
):
    cache_hit_str = "*" if cache_hit else ""
    print(f"{cache_hit_str}Matched {expr} -> {toks.as_list()}")
_should_enable_warnings()
bool _should_enable_warnings (typing.Iterable[str] cmd_line_warn_options, typing.Optional[str] warn_env_var) protected
Definition at line 197 of file core.py.
) -> bool:
    enable = bool(warn_env_var)
    for warn_opt in cmd_line_warn_options:
        w_action, w_message, w_category, w_module, w_line = (warn_opt + "::::").split(
            ":"
        )[:5]
        if not w_action.lower().startswith("i") and (
            not (w_message or w_category or w_module) or w_module == "pyparsing"
        ):
            enable = True
        elif w_action.lower().startswith("i") and w_module in ("pyparsing", ""):
            enable = False
    return enable
References pip._vendor.pyparsing.core._should_enable_warnings(), pip._vendor.pyparsing.core.enable_all_warnings(), and i.
Referenced by pip._vendor.pyparsing.core._should_enable_warnings().
_trim_arity()
_trim_arity (func, max_limit = 3) protected
decorator to trim function calls to match the arity of the target
Definition at line 269 of file core.py.
def _trim_arity(func, max_limit=3):
    """decorator to trim function calls to match the arity of the target"""
    global _trim_arity_call_line
    if func in _single_arg_builtins:
        return lambda s, l, t: func(t)
    limit = 0
    found_arity = False
    # synthesize what would be returned by traceback.extract_stack at the call to
    # user's parse action 'func', so that we don't incur call penalty at parse time
    # fmt: off
    LINE_DIFF = 7
    # IF ANY CODE CHANGES, EVEN JUST COMMENTS OR BLANK LINES, BETWEEN THE NEXT LINE AND
    # THE CALL TO FUNC INSIDE WRAPPER, LINE_DIFF MUST BE MODIFIED!!!!
    _trim_arity_call_line = (_trim_arity_call_line or traceback.extract_stack(limit=2)[-1])
    pa_call_line_synth = (_trim_arity_call_line[0], _trim_arity_call_line[1] + LINE_DIFF)
    def wrapper(*args):
        nonlocal found_arity, limit
        while 1:
            try:
                ret = func(*args[limit:])
                found_arity = True
                return ret
            except TypeError as te:
                # re-raise TypeErrors if they did not come from our arity testing
                if found_arity:
                    raise
                else:
                    tb = te.__traceback__
                    frames = traceback.extract_tb(tb, limit=2)
                    frame_summary = frames[-1]
                    trim_arity_type_error = (
                        [frame_summary[:2]][-1][:2] == pa_call_line_synth
                    )
                    del tb
                    if trim_arity_type_error:
                        if limit < max_limit:
                            limit += 1
                            continue
                    raise
    # fmt: on
    # copy func name to wrapper for sensible debug output
    # (can't use functools.wraps, since that messes with function signature)
    func_name = getattr(func, "__name__", getattr(func, "__class__").__name__)
    wrapper.__name__ = func_name
    wrapper.__doc__ = func.__doc__
    return wrapper
References i.
Referenced by ParserElement.add_parse_action(), pip._vendor.pyparsing.core.condition_as_parse_action(), and pip._vendor.pyparsing.core.trace_parse_action().
autoname_elements()
None autoname_elements ()
Utility to simplify mass-naming of parser elements, for
generating railroad diagram with named subdiagrams.
Definition at line 6035 of file core.py.
def autoname_elements() -> None:
    """
    Utility to simplify mass-naming of parser elements, for
    generating railroad diagram with named subdiagrams.
    """
    calling_frame = sys._getframe().f_back
    if calling_frame is None:
        return
    calling_frame = typing.cast(types.FrameType, calling_frame)
    for name, var in calling_frame.f_locals.items():
        if isinstance(var, ParserElement) and not var.customName:
            var.set_name(name)
References i.
condition_as_parse_action()
ParseAction condition_as_parse_action (ParseCondition fn, typing.Optional[str] message = None, bool fatal = False)
Function to convert a simple predicate function that returns ``True`` or ``False``
into a parse action. Can be used in places when a parse action is required
and :class:`ParserElement.add_condition` cannot be used (such as when adding a condition
to an operator level in :class:`infix_notation`).
Optional keyword arguments:
- ``message`` - define a custom message to be used in the raised exception
- ``fatal`` - if True, will raise :class:`ParseFatalException` to stop parsing immediately;
  otherwise will raise :class:`ParseException`
Definition at line 326 of file core.py.
) -> ParseAction:
    """
    Function to convert a simple predicate function that returns ``True`` or ``False``
    into a parse action. Can be used in places when a parse action is required
    and :class:`ParserElement.add_condition` cannot be used (such as when adding a condition
    to an operator level in :class:`infix_notation`).
    Optional keyword arguments:
    - ``message`` - define a custom message to be used in the raised exception
    - ``fatal`` - if True, will raise :class:`ParseFatalException` to stop parsing immediately;
      otherwise will raise :class:`ParseException`
    """
    msg = message if message is not None else "failed user-defined condition"
    exc_type = ParseFatalException if fatal else ParseException
    fn = _trim_arity(fn)
    @wraps(fn)
    def pa(s, l, t):
        if not bool(fn(s, l, t)):
            raise exc_type(s, l, msg)
    return pa
References pip._vendor.pyparsing.core._trim_arity(), and i.
Referenced by ParserElement.add_condition().
conditionAsParseAction()
conditionAsParseAction ()
Definition at line 6111 of file core.py.
def conditionAsParseAction(): ...
@replaced_by_pep8(token_map)
disable_diag()
None disable_diag (Diagnostics diag_enum)
Disable a global pyparsing diagnostic flag (see :class:`Diagnostics`).
Definition at line 179 of file core.py.
def disable_diag(diag_enum: Diagnostics) -> None:
    """
    Disable a global pyparsing diagnostic flag (see :class:`Diagnostics`).
    """
    __diag__.disable(diag_enum.name)
References i.
enable_all_warnings()
None enable_all_warnings ()
Enable all global pyparsing diagnostic warnings (see :class:`Diagnostics`).
Definition at line 186 of file core.py.
def enable_all_warnings() -> None:
    """
    Enable all global pyparsing diagnostic warnings (see :class:`Diagnostics`).
    """
    __diag__.enable_all_warnings()
# hide abstract class
References i.
Referenced by pip._vendor.pyparsing.core._should_enable_warnings().
enable_diag()
None enable_diag (Diagnostics diag_enum)
Enable a global pyparsing diagnostic flag (see :class:`Diagnostics`).
Definition at line 172 of file core.py.
def enable_diag(diag_enum: Diagnostics) -> None:
    """
    Enable a global pyparsing diagnostic flag (see :class:`Diagnostics`).
    """
    __diag__.enable(diag_enum.name)
References i.
null_debug_action()
null_debug_action (* args)
'Do-nothing' debug action, to suppress debugging output during parsing.
Definition at line 390 of file core.py.
def null_debug_action(*args):
    """'Do-nothing' debug action, to suppress debugging output during parsing."""
nullDebugAction()
nullDebugAction ()
Definition at line 6105 of file core.py.
def nullDebugAction(): ...
@replaced_by_pep8(trace_parse_action)
srange()
str srange (str s)
Helper to easily define string ranges for use in :class:`Word`
construction. Borrows syntax from regexp ``'[]'`` string range
definitions::
    srange("[0-9]")   -> "0123456789"
    srange("[a-z]")   -> "abcdefghijklmnopqrstuvwxyz"
    srange("[a-z$_]") -> "abcdefghijklmnopqrstuvwxyz$_"
The input string must be enclosed in []'s, and the returned string
is the expanded character set joined into a single string. The
values enclosed in the []'s may be:
- a single character
- an escaped character with a leading backslash (such as ``\-``
  or ``\]``)
- an escaped hex character with a leading ``'\x'``
  (``\x21``, which is a ``'!'`` character) (``\0x##``
  is also supported for backwards compatibility)
- an escaped octal character with a leading ``'\0'``
  (``\041``, which is a ``'!'`` character)
- a range of any of the above, separated by a dash (``'a-z'``,
  etc.)
- any combination of the above (``'aeiouy'``,
  ``'a-zA-Z0-9_$'``, etc.)
Definition at line 5952 of file core.py.
def srange(s: str) -> str:
    r"""Helper to easily define string ranges for use in :class:`Word`
    construction. Borrows syntax from regexp ``'[]'`` string range
    definitions::
        srange("[0-9]")   -> "0123456789"
        srange("[a-z]")   -> "abcdefghijklmnopqrstuvwxyz"
        srange("[a-z$_]") -> "abcdefghijklmnopqrstuvwxyz$_"
    The input string must be enclosed in []'s, and the returned string
    is the expanded character set joined into a single string. The
    values enclosed in the []'s may be:
    - a single character
    - an escaped character with a leading backslash (such as ``\-``
      or ``\]``)
    - an escaped hex character with a leading ``'\x'``
      (``\x21``, which is a ``'!'`` character) (``\0x##``
      is also supported for backwards compatibility)
    - an escaped octal character with a leading ``'\0'``
      (``\041``, which is a ``'!'`` character)
    - a range of any of the above, separated by a dash (``'a-z'``,
      etc.)
    - any combination of the above (``'aeiouy'``,
      ``'a-zA-Z0-9_$'``, etc.)
    """
    _expanded = (
        lambda p: p
        if not isinstance(p, ParseResults)
        else "".join(chr(c) for c in range(ord(p[0]), ord(p[1]) + 1))
    )
    try:
        return "".join(_expanded(part) for part in _reBracketExpr.parse_string(s).body)
    except Exception as e:
        return ""
References i.
token_map()
ParseAction token_map (func, * args)
Helper to define a parse action by mapping a function to all
elements of a :class:`ParseResults` list. If any additional args are passed,
they are forwarded to the given function as additional arguments
after the token, as in
``hex_integer = Word(hexnums).set_parse_action(token_map(int, 16))``,
which will convert the parsed data to an integer using base 16.
Example (compare the last to example in :class:`ParserElement.transform_string`::
    hex_ints = Word(hexnums)[1, ...].set_parse_action(token_map(int, 16))
    hex_ints.run_tests('''
        00 11 22 aa FF 0a 0d 1a
        ''')
    upperword = Word(alphas).set_parse_action(token_map(str.upper))
    upperword[1, ...].run_tests('''
        my kingdom for a horse
        ''')
    wd = Word(alphas).set_parse_action(token_map(str.title))
    wd[1, ...].set_parse_action(' '.join).run_tests('''
        now is the winter of our discontent made glorious summer by this sun of york
        ''')
prints::
    00 11 22 aa FF 0a 0d 1a
    [0, 17, 34, 170, 255, 10, 13, 26]
    my kingdom for a horse
    ['MY', 'KINGDOM', 'FOR', 'A', 'HORSE']
    now is the winter of our discontent made glorious summer by this sun of york
    ['Now Is The Winter Of Our Discontent Made Glorious Summer By This Sun Of York']
Definition at line 5989 of file core.py.
def token_map(func, *args) -> ParseAction:
    """Helper to define a parse action by mapping a function to all
    elements of a :class:`ParseResults` list. If any additional args are passed,
    they are forwarded to the given function as additional arguments
    after the token, as in
    ``hex_integer = Word(hexnums).set_parse_action(token_map(int, 16))``,
    which will convert the parsed data to an integer using base 16.
    Example (compare the last to example in :class:`ParserElement.transform_string`::
        hex_ints = Word(hexnums)[1, ...].set_parse_action(token_map(int, 16))
        hex_ints.run_tests('''
            00 11 22 aa FF 0a 0d 1a
            ''')
        upperword = Word(alphas).set_parse_action(token_map(str.upper))
        upperword[1, ...].run_tests('''
            my kingdom for a horse
            ''')
        wd = Word(alphas).set_parse_action(token_map(str.title))
        wd[1, ...].set_parse_action(' '.join).run_tests('''
            now is the winter of our discontent made glorious summer by this sun of york
            ''')
    prints::
        00 11 22 aa FF 0a 0d 1a
        [0, 17, 34, 170, 255, 10, 13, 26]
        my kingdom for a horse
        ['MY', 'KINGDOM', 'FOR', 'A', 'HORSE']
        now is the winter of our discontent made glorious summer by this sun of york
        ['Now Is The Winter Of Our Discontent Made Glorious Summer By This Sun Of York']
    """
    def pa(s, l, t):
        return [func(tokn, *args) for tokn in t]
    func_name = getattr(func, "__name__", getattr(func, "__class__").__name__)
    pa.__name__ = func_name
    return pa
References i.
tokenMap()
tokenMap ()
Definition at line 6114 of file core.py.
def tokenMap(): ...
# fmt: on
trace_parse_action()
ParseAction trace_parse_action (ParseAction f)
Decorator for debugging parse actions.
When the parse action is called, this decorator will print
``">> entering method-name(line:<current_source_line>, <parse_location>, <matched_tokens>)"``.
When the parse action completes, the decorator will print
``"<<"`` followed by the returned value, or any exception that the parse action raised.
Example::
    wd = Word(alphas)
    @trace_parse_action
    def remove_duplicate_chars(tokens):
        return ''.join(sorted(set(''.join(tokens))))
    wds = wd[1, ...].set_parse_action(remove_duplicate_chars)
    print(wds.parse_string("slkdjs sld sldd sdlf sdljf"))
prints::
    >>entering remove_duplicate_chars(line: 'slkdjs sld sldd sdlf sdljf', 0, (['slkdjs', 'sld', 'sldd', 'sdlf', 'sdljf'], {}))
    <<leaving remove_duplicate_chars (ret: 'dfjkls')
    ['dfjkls']
Definition at line 5879 of file core.py.
def trace_parse_action(f: ParseAction) -> ParseAction:
    """Decorator for debugging parse actions.
    When the parse action is called, this decorator will print
    ``">> entering method-name(line:<current_source_line>, <parse_location>, <matched_tokens>)"``.
    When the parse action completes, the decorator will print
    ``"<<"`` followed by the returned value, or any exception that the parse action raised.
    Example::
        wd = Word(alphas)
        @trace_parse_action
        def remove_duplicate_chars(tokens):
            return ''.join(sorted(set(''.join(tokens))))
        wds = wd[1, ...].set_parse_action(remove_duplicate_chars)
        print(wds.parse_string("slkdjs sld sldd sdlf sdljf"))
    prints::
        >>entering remove_duplicate_chars(line: 'slkdjs sld sldd sdlf sdljf', 0, (['slkdjs', 'sld', 'sldd', 'sdlf', 'sdljf'], {}))
        <<leaving remove_duplicate_chars (ret: 'dfjkls')
        ['dfjkls']
    """
    f = _trim_arity(f)
    def z(*paArgs):
        thisFunc = f.__name__
        s, l, t = paArgs[-3:]
        if len(paArgs) > 3:
            thisFunc = paArgs[0].__class__.__name__ + "." + thisFunc
        sys.stderr.write(f">>entering {thisFunc}(line: {line(l, s)!r}, {l}, {t!r})\n")
        try:
            ret = f(*paArgs)
        except Exception as exc:
            sys.stderr.write(f"<<leaving {thisFunc} (exception: {exc})\n")
            raise
        sys.stderr.write(f"<<leaving {thisFunc} (ret: {ret!r})\n")
        return ret
    z.__name__ = f.__name__
    return z
# convenience constants for positional expressions
References pip._vendor.pyparsing.core._trim_arity(), and i.
traceParseAction()
traceParseAction ()
Definition at line 6108 of file core.py.
def traceParseAction(): ...
@replaced_by_pep8(condition_as_parse_action)
Variable Documentation
_builtin_exprs
list _builtin_exprs protected
Initial value:
=  [
    v for v in vars().values() if isinstance(v, ParserElement)
]
Definition at line 6089 of file core.py.
_charRange
_charRange = Group(_singleChar + Suppress("-") + _singleChar) protected
Definition at line 5943 of file core.py.
_escapedHexChar
_escapedHexChar protected
Initial value:
=  Regex(r"\\0?[xX][0-9a-fA-F]+").set_parse_action(
    lambda s, l, t: chr(int(t[0].lstrip(r"\0x"), 16))
)
Definition at line 5934 of file core.py.
_escapedOctChar
_escapedOctChar protected
Initial value:
=  Regex(r"\\0[0-7]+").set_parse_action(
    lambda s, l, t: chr(int(t[0][1:], 8))
)
Definition at line 5937 of file core.py.
_escapedPunc
_escapedPunc protected
Initial value:
=  Regex(r"\\[\\[\]\/\-\*\.\$\+\^\?()~ ]").set_parse_action(
    lambda s, l, t: t[0][1]
)
Definition at line 5931 of file core.py.
_generatorType
_generatorType = types.GeneratorType protected
Definition at line 235 of file core.py.
_MAX_INT
_MAX_INT = sys.maxsize protected
Definition at line 53 of file core.py.
_reBracketExpr
tuple _reBracketExpr protected
Initial value:
=  (
    Literal("[")
    + Opt("^").set_results_name("negate")
    + Group(OneOrMore(_charRange | _singleChar)).set_results_name("body")
    + Literal("]")
)
Definition at line 5944 of file core.py.
_single_arg_builtins
dict _single_arg_builtins protected
Initial value:
=  {
    sum,
    len,
    sorted,
    reversed,
    list,
    tuple,
    set,
    any,
    all,
    min,
    max,
}
Definition at line 221 of file core.py.
_singleChar
tuple _singleChar protected
Initial value:
=  (
    _escapedPunc | _escapedHexChar | _escapedOctChar | CharsNotIn(r"\]", exact=1)
)
Definition at line 5940 of file core.py.
_trim_arity_call_line
traceback _trim_arity_call_line = None protected
Definition at line 266 of file core.py.
alphanums
str alphanums = alphas + nums
Definition at line 263 of file core.py.
alphas
alphas = string.ascii_uppercase + string.ascii_lowercase
Definition at line 258 of file core.py.
alphas8bit
str alphas8bit = srange(r"[\0xc0-\0xd6\0xd8-\0xf6\0xf8-\0xff]")
Definition at line 6084 of file core.py.
dbl_quoted_string
dbl_quoted_string
Initial value:
=  Combine(
    Regex(r'"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"'
).set_name("string enclosed in double quotes")
Definition at line 6049 of file core.py.
dblQuotedString
dblQuotedString = dbl_quoted_string
Definition at line 6096 of file core.py.
DebugExceptionAction
DebugExceptionAction = Callable[[str, int, "ParserElement", Exception, bool], None]
Definition at line 255 of file core.py.
DebugStartAction
DebugStartAction = Callable[[str, int, "ParserElement", bool], None]
Definition at line 251 of file core.py.
DebugSuccessAction
DebugSuccessAction
Initial value:
=  Callable[
    [str, int, int, "ParserElement", ParseResults, bool], None
]
Definition at line 252 of file core.py.
empty
empty = Empty().set_name("empty")
Definition at line 5925 of file core.py.
hexnums
str hexnums = nums + "ABCDEFabcdef"
Definition at line 262 of file core.py.
identbodychars
identbodychars = pyparsing_unicode.Latin1.identbodychars
Definition at line 260 of file core.py.
identchars
identchars = pyparsing_unicode.Latin1.identchars
Definition at line 259 of file core.py.
line_end
line_end = LineEnd().set_name("line_end")
Definition at line 5927 of file core.py.
line_start
line_start = LineStart().set_name("line_start")
Definition at line 5926 of file core.py.
lineEnd
lineEnd = line_end
Definition at line 6100 of file core.py.
lineStart
lineStart = line_start
Definition at line 6099 of file core.py.
nums
str nums = "0123456789"
Definition at line 261 of file core.py.
Optional
Optional = Opt
Definition at line 5235 of file core.py.
ParseAction
ParseAction
Initial value:
=  Union[
    Callable[[], Any],
    Callable[[ParseResults], Any],
    Callable[[int, ParseResults], Any],
    Callable[[str, int, ParseResults], Any],
]
Definition at line 238 of file core.py.
ParseCondition
ParseCondition
Initial value:
=  Union[
    Callable[[], bool],
    Callable[[ParseResults], bool],
    Callable[[int, ParseResults], bool],
    Callable[[str, int, ParseResults], bool],
]
Definition at line 244 of file core.py.
ParseFailAction
ParseFailAction = Callable[[str, int, "ParserElement", Exception], None]
Definition at line 250 of file core.py.
ParseImplReturnType
ParseImplReturnType = Tuple[int, Any]
Definition at line 236 of file core.py.
PostParseReturnType
PostParseReturnType = Union[ParseResults, Sequence[ParseResults]]
Definition at line 237 of file core.py.
printables
str printables = "".join([c for c in string.printable if c not in string.whitespace])
Definition at line 264 of file core.py.
punc8bit
str punc8bit = srange(r"[\0xa1-\0xbf\0xd7\0xf7]")
Definition at line 6085 of file core.py.
python_quoted_string
python_quoted_string
Initial value:
=  Combine(
    (Regex(r'"""(?:[^"\\]|""(?!")|"(?!"")|\\.)*', flags=re.MULTILINE) + '"""').set_name(
        "multiline double quoted string"
    )
    ^ (
        Regex(r"'''(?:[^'\\]|''(?!')|'(?!'')|\\.)*", flags=re.MULTILINE) + "'''"
    ).set_name("multiline single quoted string")
    ^ (Regex(r'"(?:[^"\n\r\\]|(?:\\")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"').set_name(
        "double quoted string"
    )
    ^ (Regex(r"'(?:[^'\n\r\\]|(?:\\')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'").set_name(
        "single quoted string"
    )
).set_name("Python quoted string")
Definition at line 6066 of file core.py.
quoted_string
quoted_string
Initial value:
=  Combine(
    (Regex(r'"(?:[^"\n\r\\]|(?:"")|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*') + '"').set_name(
        "double quoted string"
    )
    | (Regex(r"'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'").set_name(
        "single quoted string"
    )
).set_name("quoted string using single or double quotes")
Definition at line 6057 of file core.py.
Referenced by pip._vendor.pyparsing.helpers.nested_expr().
quotedString
quotedString = quoted_string
Definition at line 6097 of file core.py.
sgl_quoted_string
sgl_quoted_string
Initial value:
=  Combine(
    Regex(r"'(?:[^'\n\r\\]|(?:'')|(?:\\(?:[^x]|x[0-9a-fA-F]+)))*") + "'"
).set_name("string enclosed in single quotes")
Definition at line 6053 of file core.py.
sglQuotedString
sglQuotedString = sgl_quoted_string
Definition at line 6095 of file core.py.
str_type
tuple str_type = (str, bytes)
Definition at line 54 of file core.py.
string_end
string_end = StringEnd().set_name("string_end")
Definition at line 5929 of file core.py.
string_start
string_start = StringStart().set_name("string_start")
Definition at line 5928 of file core.py.
stringEnd
stringEnd = string_end
Definition at line 6102 of file core.py.
stringStart
stringStart = string_start
Definition at line 6101 of file core.py.
unicode_string
unicode_string = Combine("u" + quoted_string.copy()).set_name("unicode string literal")
Definition at line 6081 of file core.py.
unicodeString
unicodeString = unicode_string
Definition at line 6098 of file core.py.