My Project: C:/Users/liwuen/Desktop/Doxygen local test/pqc-engineering-ssec-23/dCTIDH/main/checkct.c File Reference
checkct.c File Reference
#include <time.h>
#include <secsidh/secsidh.h>
#include <assert.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "cycle.h"
#include "fp-counters.h"
#include "primes.h"
#include "ctidh.h"
#include "ctidh_api.h"
Macros
#define cprintf(...)
#define CPASTER(x, y)
#define CEVALUATOR(x, y)
#define CONSTNAMESPACE(name)
#define SK_SIZE CONSTNAMESPACE(SK_SIZE)
#define PK_SIZE CONSTNAMESPACE(PK_SIZE)
#define SS_SIZE CONSTNAMESPACE(SS_SIZE)
#define pk_size FNAMESPACE(pk_size)
#define sk_size FNAMESPACE(sk_size)
#define ss_size FNAMESPACE(ss_size)
#define FPASTER(x, y)
#define FEVALUATOR(x, y)
#define FNAMESPACE(name)
#define keygen FNAMESPACE(keygen)
#define derive FNAMESPACE(derive)
Functions
int main (void)
Macro Definition Documentation
CEVALUATOR
#define CEVALUATOR (x, y)
Value:
CPASTER(x, y)
Definition at line 22 of file checkct.c.
CONSTNAMESPACE
#define CONSTNAMESPACE (name)
Value:
CEVALUATOR(BITS, name)
Definition at line 23 of file checkct.c.
CPASTER
#define CPASTER (x, y)
Value:
SECSIDH_CTIDH##x##_##y
Definition at line 21 of file checkct.c.
cprintf
#define cprintf (...)
Definition at line 18 of file checkct.c.
derive
#define derive FNAMESPACE(derive)
Definition at line 37 of file checkct.c.
Referenced by main().
FEVALUATOR
#define FEVALUATOR (x, y)
Value:
FPASTER(x, y)
Definition at line 33 of file checkct.c.
FNAMESPACE
#define FNAMESPACE (name)
Value:
FEVALUATOR(BITS, name)
Definition at line 34 of file checkct.c.
FPASTER
#define FPASTER (x, y)
Value:
secsidh_CTIDH##x##_##y
Definition at line 32 of file checkct.c.
keygen
#define keygen FNAMESPACE(keygen)
Definition at line 36 of file checkct.c.
Referenced by main().
PK_SIZE
#define PK_SIZE CONSTNAMESPACE(PK_SIZE)
Definition at line 25 of file checkct.c.
Referenced by main(), and main().
pk_size
#define pk_size FNAMESPACE(pk_size)
Definition at line 28 of file checkct.c.
Referenced by main(), and NSAPI().
SK_SIZE
#define SK_SIZE CONSTNAMESPACE(SK_SIZE)
Definition at line 24 of file checkct.c.
Referenced by main(), and main().
sk_size
#define sk_size FNAMESPACE(sk_size)
Definition at line 29 of file checkct.c.
Referenced by main(), and NSAPI().
SS_SIZE
#define SS_SIZE CONSTNAMESPACE(SS_SIZE)
Definition at line 26 of file checkct.c.
Referenced by main(), and main().
ss_size
#define ss_size FNAMESPACE(ss_size)
Definition at line 30 of file checkct.c.
Referenced by main(), and NSAPI().
Function Documentation
main()
int main (void)
Definition at line 52 of file checkct.c.
{
    printf("\033[0;33m// Key generation\033[0m\n");
    printf("sizeof private key = %lu \n", sizeof(private_key));
    printf("sizeof public key = %lu \n", sizeof(public_key));
    // ----------
    // Alice
    printf("\n\033[0;35m// Alice\033[0m\n");
    uint8_t a[SK_SIZE] = {0}, A[PK_SIZE] = {0}, ss_a[SS_SIZE] = {0};
    keygen(A, a);
    // ----------
    // Bob
    printf("\n\033[0;34m// Bob\033[0m\n");
    uint8_t b[SK_SIZE], B[PK_SIZE], ss_b[SS_SIZE];
    keygen(B, b);
    //------------------------------------------------------
    // Secret sharing derivation
    printf("\033[0;33m// Secret sharing generation\033[0m\n");
    // ----------------
    // Alice
    printf("\n\033[0;35m// Alice\033[0m\n");
    assert(derive(ss_a, B, a) == 0);
    printf("\n\033[0;34m// Bob\033[0m\n");
    assert(derive(ss_b, A, b) == 0);
    // =============================
    // Verifying same secret sharing
    assert(dumb_fp_isequal(ss_a, ss_b, SS_SIZE));
    //------------------------------------------------------
    printf("\n\033[0;32m// Successfully secret sharing computation!\033[0m\n");
    return 0;
}
References a, assert(), derive, keygen, PK_SIZE, SK_SIZE, and SS_SIZE.
Referenced by AsmAVX2Codegenerator::main(), AsmKaratsubaCodegenerator::main(), AsmKaratsubaRedc::main(), AsmMontRedc::main(), AsmMontRedc32::main(), AsmMontRedcAVX2::main(), AsmMultCodegenerator_noPIC::main(), and AsmMultCodegenerator_PIC::main().