Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: _UnboundedCache Class Reference
_UnboundedCache Class Reference
Public Member Functions
__init__ (self)
Data Fields
not_in_cache = object()
size = None
get = types.MethodType(get, self)
set = types.MethodType(set_, self)
clear = types.MethodType(clear, self)
Detailed Description
Definition at line 80 of file util.py.
Constructor & Destructor Documentation
__init__()
__init__ (self)
Definition at line 81 of file util.py.
    def __init__(self):
        cache = {}
        cache_get = cache.get
        self.not_in_cache = not_in_cache = object()
        def get(_, key):
            return cache_get(key, not_in_cache)
        def set_(_, key, value):
            cache[key] = value
        def clear(_):
            cache.clear()
        self.size = None
        self.get = types.MethodType(get, self)
        self.set = types.MethodType(set_, self)
        self.clear = types.MethodType(clear, self)
Field Documentation
clear
clear = types.MethodType(clear, self)
Definition at line 98 of file util.py.
Referenced by PoolManager.__exit__().
get
get = types.MethodType(get, self)
Definition at line 96 of file util.py.
Referenced by LegacyMetadata.__getitem__(), Layout.__getitem__(), LegacyMetadata.check(), ThemeStack.pop_theme(), ThemeStack.push_theme(), and LegacyMetadata.write_file().
not_in_cache
not_in_cache = object()
Definition at line 84 of file util.py.
set
set = types.MethodType(set_, self)
Definition at line 97 of file util.py.
Referenced by LegacyMetadata.__setitem__(), RequestsCookieJar.__setitem__(), Flags.finalize_pending(), LegacyMetadata.read_file(), and LegacyMetadata.update().
size
size = None
Definition at line 95 of file util.py.
Referenced by Bar.__rich_console__(), Layout.__rich_repr__(), Console.height(), Console.options(), and Console.width().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/util.py