Let us walk on the 3-isogeny graph: pip._vendor.pyproject_hooks._in_process._in_process Namespace Reference
pip._vendor.pyproject_hooks._in_process._in_process Namespace Reference
Data Structures
class _DummyException
class BackendInvalid
class BackendUnavailable
class GotUnsupportedOperation
class HookMissing
Functions
write_json (obj, path, **kwargs)
read_json (path)
contained_in (filename, directory)
_build_backend ()
_supported_features ()
get_requires_for_build_wheel (config_settings)
get_requires_for_build_editable (config_settings)
prepare_metadata_for_build_wheel (metadata_directory, config_settings, _allow_fallback)
prepare_metadata_for_build_editable (metadata_directory, config_settings, _allow_fallback)
_dist_info_files (whl_zip)
_get_wheel_metadata_from_wheel (whl_basename, metadata_directory, config_settings)
_find_already_built_wheel (metadata_directory)
build_wheel (wheel_directory, config_settings, metadata_directory=None)
build_editable (wheel_directory, config_settings, metadata_directory=None)
get_requires_for_build_sdist (config_settings)
build_sdist (sdist_directory, config_settings)
main ()
Variables
str WHEEL_BUILT_MARKER = 'PEP517_ALREADY_BUILT_WHEEL'
dict HOOK_NAMES
Detailed Description
This is invoked in a subprocess to call the build backend hooks.
It expects:
- Command line args: hook_name, control_dir
- Environment variables:
      PEP517_BUILD_BACKEND=entry.point:spec
      PEP517_BACKEND_PATH=paths (separated with os.pathsep)
- control_dir/input.json:
  - {"kwargs": {...}}
Results:
- control_dir/output.json
  - {"return_val": ...}
Function Documentation
_build_backend()
_build_backend () protected
Find and load the build backend
Definition at line 66 of file _in_process.py.
def _build_backend():
    """Find and load the build backend"""
    # Add in-tree backend directories to the front of sys.path.
    backend_path = os.environ.get('PEP517_BACKEND_PATH')
    if backend_path:
        extra_pathitems = backend_path.split(os.pathsep)
        sys.path[:0] = extra_pathitems
    ep = os.environ['PEP517_BUILD_BACKEND']
    mod_path, _, obj_path = ep.partition(':')
    try:
        obj = import_module(mod_path)
    except ImportError:
        raise BackendUnavailable(traceback.format_exc())
    if backend_path:
        if not any(
            contained_in(obj.__file__, path)
            for path in extra_pathitems
        ):
            raise BackendInvalid("Backend was not loaded from backend-path")
    if obj_path:
        for path_part in obj_path.split('.'):
            obj = getattr(obj, path_part)
    return obj
References pip._vendor.pyproject_hooks._in_process._in_process.contained_in(), and i.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process._supported_features(), pip._vendor.pyproject_hooks._in_process._in_process.build_editable(), pip._vendor.pyproject_hooks._in_process._in_process.build_sdist(), pip._vendor.pyproject_hooks._in_process._in_process.build_wheel(), pip._vendor.pyproject_hooks._in_process._in_process.get_requires_for_build_editable(), pip._vendor.pyproject_hooks._in_process._in_process.get_requires_for_build_sdist(), pip._vendor.pyproject_hooks._in_process._in_process.get_requires_for_build_wheel(), pip._vendor.pyproject_hooks._in_process._in_process.prepare_metadata_for_build_editable(), and pip._vendor.pyproject_hooks._in_process._in_process.prepare_metadata_for_build_wheel().
_dist_info_files()
_dist_info_files (whl_zip) protected
Identify the .dist-info folder inside a wheel ZipFile.
Definition at line 187 of file _in_process.py.
def _dist_info_files(whl_zip):
    """Identify the .dist-info folder inside a wheel ZipFile."""
    res = []
    for path in whl_zip.namelist():
        m = re.match(r'[^/\\]+-[^/\\]+\.dist-info/', path)
        if m:
            res.append(path)
    if res:
        return res
    raise Exception("No .dist-info folder found in wheel")
References i.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process._get_wheel_metadata_from_wheel().
_find_already_built_wheel()
_find_already_built_wheel (metadata_directory) protected
Check for a wheel already built during the get_wheel_metadata hook.
Definition at line 217 of file _in_process.py.
def _find_already_built_wheel(metadata_directory):
    """Check for a wheel already built during the get_wheel_metadata hook.
    """
    if not metadata_directory:
        return None
    metadata_parent = os.path.dirname(metadata_directory)
    if not os.path.isfile(pjoin(metadata_parent, WHEEL_BUILT_MARKER)):
        return None
    whl_files = glob(os.path.join(metadata_parent, '*.whl'))
    if not whl_files:
        print('Found wheel built marker, but no .whl files')
        return None
    if len(whl_files) > 1:
        print('Found multiple .whl files; unspecified behaviour. '
              'Will call build_wheel.')
        return None
    # Exactly one .whl file
    return whl_files[0]
References i.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.build_editable(), and pip._vendor.pyproject_hooks._in_process._in_process.build_wheel().
_get_wheel_metadata_from_wheel()
_get_wheel_metadata_from_wheel (whl_basename, metadata_directory, config_settings) protected
Extract the metadata from a wheel.
Fallback for when the build backend does not
define the 'get_wheel_metadata' hook.
Definition at line 199 of file _in_process.py.
        whl_basename, metadata_directory, config_settings):
    """Extract the metadata from a wheel.
    Fallback for when the build backend does not
    define the 'get_wheel_metadata' hook.
    """
    from zipfile import ZipFile
    with open(os.path.join(metadata_directory, WHEEL_BUILT_MARKER), 'wb'):
        pass  # Touch marker file
    whl_file = os.path.join(metadata_directory, whl_basename)
    with ZipFile(whl_file) as zipf:
        dist_info = _dist_info_files(zipf)
        zipf.extractall(path=metadata_directory, members=dist_info)
    return dist_info[0].split('/')[0]
References pip._vendor.pyproject_hooks._in_process._in_process._dist_info_files(), and i.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.prepare_metadata_for_build_editable(), and pip._vendor.pyproject_hooks._in_process._in_process.prepare_metadata_for_build_wheel().
_supported_features()
_supported_features () protected
Return the list of options features supported by the backend.
Returns a list of strings.
The only possible value is 'build_editable'.
Definition at line 94 of file _in_process.py.
def _supported_features():
    """Return the list of options features supported by the backend.
    Returns a list of strings.
    The only possible value is 'build_editable'.
    """
    backend = _build_backend()
    features = []
    if hasattr(backend, "build_editable"):
        features.append("build_editable")
    return features
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), and i.
build_editable()
build_editable (wheel_directory, config_settings, metadata_directory = None)
Invoke the optional build_editable hook.
If a wheel was already built in the
prepare_metadata_for_build_editable fallback, this
will copy it rather than rebuilding the wheel.
Definition at line 255 of file _in_process.py.
def build_editable(wheel_directory, config_settings, metadata_directory=None):
    """Invoke the optional build_editable hook.
    If a wheel was already built in the
    prepare_metadata_for_build_editable fallback, this
    will copy it rather than rebuilding the wheel.
    """
    backend = _build_backend()
    try:
        hook = backend.build_editable
    except AttributeError:
        raise HookMissing()
    else:
        prebuilt_whl = _find_already_built_wheel(metadata_directory)
        if prebuilt_whl:
            shutil.copy2(prebuilt_whl, wheel_directory)
            return os.path.basename(prebuilt_whl)
        return hook(wheel_directory, config_settings, metadata_directory)
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), pip._vendor.pyproject_hooks._in_process._in_process._find_already_built_wheel(), and i.
build_sdist()
build_sdist (sdist_directory, config_settings)
Invoke the mandatory build_sdist hook.
Definition at line 300 of file _in_process.py.
def build_sdist(sdist_directory, config_settings):
    """Invoke the mandatory build_sdist hook."""
    backend = _build_backend()
    try:
        return backend.build_sdist(sdist_directory, config_settings)
    except getattr(backend, 'UnsupportedOperation', _DummyException):
        raise GotUnsupportedOperation(traceback.format_exc())
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), and i.
build_wheel()
build_wheel (wheel_directory, config_settings, metadata_directory = None)
Invoke the mandatory build_wheel hook.
If a wheel was already built in the
prepare_metadata_for_build_wheel fallback, this
will copy it rather than rebuilding the wheel.
Definition at line 239 of file _in_process.py.
def build_wheel(wheel_directory, config_settings, metadata_directory=None):
    """Invoke the mandatory build_wheel hook.
    If a wheel was already built in the
    prepare_metadata_for_build_wheel fallback, this
    will copy it rather than rebuilding the wheel.
    """
    prebuilt_whl = _find_already_built_wheel(metadata_directory)
    if prebuilt_whl:
        shutil.copy2(prebuilt_whl, wheel_directory)
        return os.path.basename(prebuilt_whl)
    return _build_backend().build_wheel(wheel_directory, config_settings,
                                        metadata_directory)
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), pip._vendor.pyproject_hooks._in_process._in_process._find_already_built_wheel(), pip._vendor.pyproject_hooks._in_process._in_process.build_wheel(), and i.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.build_wheel().
contained_in()
contained_in (filename, directory)
Test if a file is located within the given directory.
Definition at line 59 of file _in_process.py.
def contained_in(filename, directory):
    """Test if a file is located within the given directory."""
    filename = os.path.normcase(os.path.abspath(filename))
    directory = os.path.normcase(os.path.abspath(directory))
    return os.path.commonprefix([filename, directory]) == directory
References i.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process._build_backend().
get_requires_for_build_editable()
get_requires_for_build_editable (config_settings)
Invoke the optional get_requires_for_build_editable hook
Returns [] if the hook is not defined.
Definition at line 121 of file _in_process.py.
def get_requires_for_build_editable(config_settings):
    """Invoke the optional get_requires_for_build_editable hook
    Returns [] if the hook is not defined.
    """
    backend = _build_backend()
    try:
        hook = backend.get_requires_for_build_editable
    except AttributeError:
        return []
    else:
        return hook(config_settings)
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), and i.
get_requires_for_build_sdist()
get_requires_for_build_sdist (config_settings)
Invoke the optional get_requires_for_build_wheel hook
Returns [] if the hook is not defined.
Definition at line 276 of file _in_process.py.
def get_requires_for_build_sdist(config_settings):
    """Invoke the optional get_requires_for_build_wheel hook
    Returns [] if the hook is not defined.
    """
    backend = _build_backend()
    try:
        hook = backend.get_requires_for_build_sdist
    except AttributeError:
        return []
    else:
        return hook(config_settings)
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), and i.
get_requires_for_build_wheel()
get_requires_for_build_wheel (config_settings)
Invoke the optional get_requires_for_build_wheel hook
Returns [] if the hook is not defined.
Definition at line 107 of file _in_process.py.
def get_requires_for_build_wheel(config_settings):
    """Invoke the optional get_requires_for_build_wheel hook
    Returns [] if the hook is not defined.
    """
    backend = _build_backend()
    try:
        hook = backend.get_requires_for_build_wheel
    except AttributeError:
        return []
    else:
        return hook(config_settings)
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), and i.
main()
main ()
Definition at line 322 of file _in_process.py.
def main():
    if len(sys.argv) < 3:
        sys.exit("Needs args: hook_name, control_dir")
    hook_name = sys.argv[1]
    control_dir = sys.argv[2]
    if hook_name not in HOOK_NAMES:
        sys.exit("Unknown hook: %s" % hook_name)
    hook = globals()[hook_name]
    hook_input = read_json(pjoin(control_dir, 'input.json'))
    json_out = {'unsupported': False, 'return_val': None}
    try:
        json_out['return_val'] = hook(**hook_input['kwargs'])
    except BackendUnavailable as e:
        json_out['no_backend'] = True
        json_out['traceback'] = e.traceback
    except BackendInvalid as e:
        json_out['backend_invalid'] = True
        json_out['backend_error'] = e.message
    except GotUnsupportedOperation as e:
        json_out['unsupported'] = True
        json_out['traceback'] = e.traceback
    except HookMissing as e:
        json_out['hook_missing'] = True
        json_out['missing_hook_name'] = e.hook_name or hook_name
    write_json(json_out, pjoin(control_dir, 'output.json'), indent=2)
References i, pip._vendor.pyproject_hooks._in_process._in_process.main(), pip._vendor.pyproject_hooks._in_process._in_process.read_json(), and pip._vendor.pyproject_hooks._in_process._in_process.write_json().
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.main().
prepare_metadata_for_build_editable()
prepare_metadata_for_build_editable (metadata_directory, config_settings, _allow_fallback)
Invoke optional prepare_metadata_for_build_editable
Implements a fallback by building an editable wheel if the hook isn't
defined, unless _allow_fallback is False in which case HookMissing is
raised.
Definition at line 157 of file _in_process.py.
        metadata_directory, config_settings, _allow_fallback):
    """Invoke optional prepare_metadata_for_build_editable
    Implements a fallback by building an editable wheel if the hook isn't
    defined, unless _allow_fallback is False in which case HookMissing is
    raised.
    """
    backend = _build_backend()
    try:
        hook = backend.prepare_metadata_for_build_editable
    except AttributeError:
        if not _allow_fallback:
            raise HookMissing()
        try:
            build_hook = backend.build_editable
        except AttributeError:
            raise HookMissing(hook_name='build_editable')
        else:
            whl_basename = build_hook(metadata_directory, config_settings)
            return _get_wheel_metadata_from_wheel(whl_basename,
                                                  metadata_directory,
                                                  config_settings)
    else:
        return hook(metadata_directory, config_settings)
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), pip._vendor.pyproject_hooks._in_process._in_process._get_wheel_metadata_from_wheel(), and i.
prepare_metadata_for_build_wheel()
prepare_metadata_for_build_wheel (metadata_directory, config_settings, _allow_fallback)
Invoke optional prepare_metadata_for_build_wheel
Implements a fallback by building a wheel if the hook isn't defined,
unless _allow_fallback is False in which case HookMissing is raised.
Definition at line 135 of file _in_process.py.
        metadata_directory, config_settings, _allow_fallback):
    """Invoke optional prepare_metadata_for_build_wheel
    Implements a fallback by building a wheel if the hook isn't defined,
    unless _allow_fallback is False in which case HookMissing is raised.
    """
    backend = _build_backend()
    try:
        hook = backend.prepare_metadata_for_build_wheel
    except AttributeError:
        if not _allow_fallback:
            raise HookMissing()
    else:
        return hook(metadata_directory, config_settings)
    # fallback to build_wheel outside the try block to avoid exception chaining
    # which can be confusing to users and is not relevant
    whl_basename = backend.build_wheel(metadata_directory, config_settings)
    return _get_wheel_metadata_from_wheel(whl_basename, metadata_directory,
                                          config_settings)
References pip._vendor.pyproject_hooks._in_process._in_process._build_backend(), pip._vendor.pyproject_hooks._in_process._in_process._get_wheel_metadata_from_wheel(), and i.
read_json()
read_json (path)
Definition at line 35 of file _in_process.py.
def read_json(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)
References i.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.main().
write_json()
write_json (obj, path, ** kwargs)
Definition at line 30 of file _in_process.py.
def write_json(obj, path, **kwargs):
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(obj, f, **kwargs)
References i.
Referenced by pip._vendor.pyproject_hooks._in_process._in_process.main().
Variable Documentation
HOOK_NAMES
dict HOOK_NAMES
Initial value:
=  {
    'get_requires_for_build_wheel',
    'prepare_metadata_for_build_wheel',
    'build_wheel',
    'get_requires_for_build_editable',
    'prepare_metadata_for_build_editable',
    'build_editable',
    'get_requires_for_build_sdist',
    'build_sdist',
    '_supported_features',
}
Definition at line 309 of file _in_process.py.
WHEEL_BUILT_MARKER
str WHEEL_BUILT_MARKER = 'PEP517_ALREADY_BUILT_WHEEL'
Definition at line 184 of file _in_process.py.