Let us walk on the 3-isogeny graph: NestedDict Class Reference
NestedDict Class Reference
Public Member Functions
None __init__ (self)
dict get_or_create_nest (self, Key key, *bool access_lists=True)
None append_nest_to_list (self, Key key)
Detailed Description
Definition at line 193 of file _parser.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Definition at line 194 of file _parser.py.
    def __init__(self) -> None:
        # The parsed content of the TOML document
        self.dict: dict[str, Any] = {}
Referenced by Protocol.__init_subclass__().
Member Function Documentation
append_nest_to_list()
None append_nest_to_list (self, Key key)
Definition at line 215 of file _parser.py.
    def append_nest_to_list(self, key: Key) -> None:
        cont = self.get_or_create_nest(key[:-1])
        last_key = key[-1]
        if last_key in cont:
            list_ = cont[last_key]
            if not isinstance(list_, list):
                raise KeyError("An object other than list found behind this key")
            list_.append({})
        else:
            cont[last_key] = [{}]
References NestedDict.get_or_create_nest(), and i.
get_or_create_nest()
dict get_or_create_nest (self, Key key, *bool access_lists = True)
Definition at line 198 of file _parser.py.
    ) -> dict:
        cont: Any = self.dict
        for k in key:
            if k not in cont:
                cont[k] = {}
            cont = cont[k]
            if access_lists and isinstance(cont, list):
                cont = cont[-1]
            if not isinstance(cont, dict):
                raise KeyError("There is no nest behind this key")
        return cont
References i.
Referenced by NestedDict.append_nest_to_list().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/tomli/_parser.py