Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: LRUMemo Class Reference
LRUMemo Class Reference
Public Member Functions
__init__ (self, capacity)
__getitem__ (self, key)
__setitem__ (self, key, value)
__delitem__ (self, key)
clear (self)
Protected Attributes
_capacity = capacity
dict _active = {}
_memory = collections.OrderedDict()
Detailed Description
A memoizing mapping that retains `capacity` deleted items
The memo tracks retained items by their access order; once `capacity` items
are retained, the least recently used item is discarded.
Definition at line 129 of file util.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, capacity)
Definition at line 137 of file util.py.
    def __init__(self, capacity):
        self._capacity = capacity
        self._active = {}
        self._memory = collections.OrderedDict()
Member Function Documentation
__delitem__()
__delitem__ (self, key)
Definition at line 153 of file util.py.
    def __delitem__(self, key):
        try:
            value = self._active.pop(key)
        except KeyError:
            pass
        else:
            while len(self._memory) >= self._capacity:
                self._memory.popitem(last=False)
            self._memory[key] = value
References _active, _capacity, and _memory.
__getitem__()
__getitem__ (self, key)
Definition at line 142 of file util.py.
    def __getitem__(self, key):
        try:
            return self._active[key]
        except KeyError:
            self._memory.move_to_end(key)
            return self._memory[key]
References _active, and _memory.
__setitem__()
__setitem__ (self, key, value)
Definition at line 149 of file util.py.
    def __setitem__(self, key, value):
        self._memory.pop(key, None)
        self._active[key] = value
References _active, and _memory.
clear()
clear (self)
Definition at line 163 of file util.py.
    def clear(self):
        self._active.clear()
        self._memory.clear()
References _active, _memory, and clear.
Referenced by PoolManager.__exit__().
Field Documentation
_active
dict _active = {} protected
Definition at line 139 of file util.py.
Referenced by __delitem__(), __getitem__(), __setitem__(), and clear().
_capacity
_capacity = capacity protected
Definition at line 138 of file util.py.
Referenced by __delitem__().
_memory
_memory = collections.OrderedDict() protected
Definition at line 140 of file util.py.
Referenced by __delitem__(), __getitem__(), __setitem__(), and clear().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/util.py