Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: ExtType Class Reference
ExtType Class Reference
Public Member Functions
__new__ (cls, code, data)
Detailed Description
ExtType represents ext type in msgpack.
Definition at line 21 of file ext.py.
Member Function Documentation
__new__()
__new__ (cls, code, data)
Definition at line 24 of file ext.py.
    def __new__(cls, code, data):
        if not isinstance(code, int):
            raise TypeError("code must be int")
        if not isinstance(data, bytes):
            raise TypeError("data must be bytes")
        if not 0 <= code <= 127:
            raise ValueError("code must be 0~127")
        return super(ExtType, cls).__new__(cls, code, data)
References __new__().
Referenced by __new__(), Style._add(), Style.clear_meta_and_links(), Style.copy(), Style.from_color(), JSON.from_data(), Style.from_meta(), Style.update_link(), and Style.without_color().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/msgpack/ext.py