Let us walk on the 3-isogeny graph: MBCSGroupProber Class Reference
MBCSGroupProber Class Reference
Public Member Functions
None __init__ (self, LanguageFilter lang_filter=LanguageFilter.NONE)
Public Member Functions inherited from CharSetGroupProber
None reset (self)
Optional[str] charset_name (self)
Optional[str] language (self)
ProbingState feed (self, Union[bytes, bytearray] byte_str)
float get_confidence (self)
Public Member Functions inherited from CharSetProber
ProbingState state (self)
Data Fields
probers
Data Fields inherited from CharSetProber
active
lang_filter
logger
Additional Inherited Members
Static Public Member Functions inherited from CharSetProber
bytes filter_high_byte_only (Union[bytes, bytearray] buf)
bytearray filter_international_words (Union[bytes, bytearray] buf)
bytes remove_xml_tags (Union[bytes, bytearray] buf)
Static Public Attributes inherited from CharSetProber
float SHORTCUT_THRESHOLD = 0.95
Protected Attributes inherited from CharSetGroupProber
_active_num
_best_guess_prober
_state
Protected Attributes inherited from CharSetProber
_state
Detailed Description
Definition at line 43 of file mbcsgroupprober.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, LanguageFilter lang_filter = LanguageFilter.NONE)
Reimplemented from CharSetGroupProber.
Definition at line 44 of file mbcsgroupprober.py.
    def __init__(self, lang_filter: LanguageFilter = LanguageFilter.NONE) -> None:
        super().__init__(lang_filter=lang_filter)
        self.probers = [
            UTF8Prober(),
            SJISProber(),
            EUCJPProber(),
            GB2312Prober(),
            EUCKRProber(),
            CP949Prober(),
            Big5Prober(),
            EUCTWProber(),
            JOHABProber(),
        ]
        self.reset()
References MBCSGroupProber.__init__(), and i.
Referenced by MBCSGroupProber.__init__(), and Protocol.__init_subclass__().
Field Documentation
probers
probers
Definition at line 46 of file mbcsgroupprober.py.
Referenced by CharSetGroupProber.feed(), CharSetGroupProber.get_confidence(), and CharSetGroupProber.reset().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/chardet/mbcsgroupprober.py