Let us walk on the 3-isogeny graph: pip._internal.commands.freeze Namespace Reference
pip._internal.commands.freeze Namespace Reference
Data Structures
class FreezeCommand
Functions
bool _should_suppress_build_backends ()
AbstractSet[str] _dev_pkgs ()
Function Documentation
_dev_pkgs()
AbstractSet[str] _dev_pkgs () protected
Definition at line 16 of file freeze.py.
def _dev_pkgs() -> AbstractSet[str]:
    pkgs = {"pip"}
    if _should_suppress_build_backends():
        pkgs |= {"setuptools", "distribute", "wheel"}
    return pkgs
References pip._internal.commands.freeze._should_suppress_build_backends().
Referenced by FreezeCommand.add_options(), and FreezeCommand.run().
_should_suppress_build_backends()
bool _should_suppress_build_backends () protected
Definition at line 12 of file freeze.py.
def _should_suppress_build_backends() -> bool:
    return sys.version_info < (3, 12)
References i.
Referenced by pip._internal.commands.freeze._dev_pkgs().