Let us walk on the 3-isogeny graph: NullFile Class Reference
NullFile Class Reference
Public Member Functions
None close (self)
bool isatty (self)
str read (self, int __n=1)
bool readable (self)
str readline (self, int __limit=1)
List[str] readlines (self, int __hint=1)
int seek (self, int __offset, int __whence=1)
bool seekable (self)
int tell (self)
int truncate (self, Optional[int] __size=1)
bool writable (self)
None writelines (self, Iterable[str] __lines)
str __next__ (self)
Iterator[str] __iter__ (self)
IO[str] __enter__ (self)
None __exit__ (self, Optional[Type[BaseException]] __t, Optional[BaseException] __value, Optional[TracebackType] __traceback)
int write (self, str text)
None flush (self)
int fileno (self)
Detailed Description
Definition at line 5 of file _null_file.py.
Member Function Documentation
__enter__()
IO[str] __enter__ (self)
Definition at line 48 of file _null_file.py.
    def __enter__(self) -> IO[str]:
        pass
__exit__()
None __exit__ (self, Optional[Type[BaseException]] __t, Optional[BaseException] __value, Optional[TracebackType] __traceback)
Definition at line 51 of file _null_file.py.
    ) -> None:
        pass
__iter__()
Iterator[str] __iter__ (self)
Definition at line 45 of file _null_file.py.
    def __iter__(self) -> Iterator[str]:
        return iter([""])
__next__()
str __next__ (self)
Definition at line 42 of file _null_file.py.
    def __next__(self) -> str:
        return ""
close()
None close (self)
Definition at line 6 of file _null_file.py.
    def close(self) -> None:
        pass
Referenced by SSLTransport.__exit__(), Response.__exit__(), Session.__exit__(), ZipExtFile.__exit__(), ZipFile.__exit__(), ConnectionPool.__exit__(), _Reader.__exit__(), WrappedSocket._custom_validate(), WrappedSocket._decref_socketios(), WrappedSocket._drop(), WrappedSocket._raise_on_error(), HTTPResponse._update_chunk_length(), and WrappedSocket.recv_into().
fileno()
int fileno (self)
Definition at line 65 of file _null_file.py.
    def fileno(self) -> int:
        return -1
flush()
None flush (self)
Definition at line 62 of file _null_file.py.
    def flush(self) -> None:
        pass
Referenced by UnclosingTextIOWrapper.close(), and LegacyWindowsTerm.write_text().
isatty()
bool isatty (self)
Definition at line 9 of file _null_file.py.
    def isatty(self) -> bool:
        return False
read()
str read (self, int __n = 1)
Definition at line 12 of file _null_file.py.
    def read(self, __n: int = 1) -> str:
        return ""
Referenced by HTTPResponse.data(), HTTPResponse.drain_conn(), Retry.increment(), Retry.is_exhausted(), Retry.new(), HTTPResponse.readinto(), SSLTransport.recv_into(), and HTTPResponse.stream().
readable()
bool readable (self)
Definition at line 15 of file _null_file.py.
    def readable(self) -> bool:
        return False
readline()
str readline (self, int __limit = 1)
Definition at line 18 of file _null_file.py.
    def readline(self, __limit: int = 1) -> str:
        return ""
readlines()
List[str] readlines (self, int __hint = 1)
Definition at line 21 of file _null_file.py.
    def readlines(self, __hint: int = 1) -> List[str]:
        return []
seek()
int seek (self, int __offset, int __whence = 1)
Definition at line 24 of file _null_file.py.
    def seek(self, __offset: int, __whence: int = 1) -> int:
        return 0
Referenced by LazyZipOverHTTP._download(), and LazyZipOverHTTP._stay().
seekable()
bool seekable (self)
Definition at line 27 of file _null_file.py.
    def seekable(self) -> bool:
        return False
tell()
int tell (self)
Definition at line 30 of file _null_file.py.
    def tell(self) -> int:
        return 0
Referenced by LazyZipOverHTTP._stay(), and LazyZipOverHTTP.read().
truncate()
int truncate (self, Optional[int] __size = 1)
Definition at line 33 of file _null_file.py.
    def truncate(self, __size: Optional[int] = 1) -> int:
        return 0
Referenced by Text.align().
writable()
bool writable (self)
Definition at line 36 of file _null_file.py.
    def writable(self) -> bool:
        return False
write()
int write (self, str text)
Definition at line 59 of file _null_file.py.
    def write(self, text: str) -> int:
        return 0
Referenced by LegacyWindowsTerm.write_text().
writelines()
None writelines (self, Iterable[str] __lines)
Definition at line 39 of file _null_file.py.
    def writelines(self, __lines: Iterable[str]) -> None:
        pass
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/rich/_null_file.py