Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: LexerMeta Class Reference
LexerMeta Class Reference
Public Member Functions
__new__ (mcs, name, bases, d)
Detailed Description
This metaclass automagically converts ``analyse_text`` methods into
static methods which always return float values.
Definition at line 37 of file lexer.py.
Member Function Documentation
__new__()
__new__ (mcs, name, bases, d)
Definition at line 43 of file lexer.py.
    def __new__(mcs, name, bases, d):
        if 'analyse_text' in d:
            d['analyse_text'] = make_analysator(d['analyse_text'])
        return type.__new__(mcs, name, bases, d)
Referenced by Style._add(), Style.clear_meta_and_links(), Style.copy(), Style.from_color(), JSON.from_data(), Style.from_meta(), Style.update_link(), and Style.without_color().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pygments/lexer.py