Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: _Finder Class Reference
_Finder Class Reference
Public Member Functions
find_spec (self, fullname, path, target=None)
Static Public Member Functions
exec_module (old, module)
load_module (old, name)
Static Public Attributes
fullname = None
list lock = []
Detailed Description
A meta path finder that allows patching the imported distutils modules.
Definition at line 43 of file _virtualenv.py.
Member Function Documentation
exec_module()
exec_module (old, module) static
Definition at line 89 of file _virtualenv.py.
    def exec_module(old, module):
        old(module)
        if module.__name__ in _DISTUTILS_PATCH:
            patch_dist(module)
References _virtualenv.patch_dist().
Referenced by find_spec().
find_spec()
find_spec (self, fullname, path, target = None)
Definition at line 53 of file _virtualenv.py.
    def find_spec(self, fullname, path, target=None):  # noqa: ARG002
        if fullname in _DISTUTILS_PATCH and self.fullname is None:
            # initialize lock[0] lazily
            if len(self.lock) == 0:
                import threading
                lock = threading.Lock()
                # there is possibility that two threads T1 and T2 are simultaneously running into find_spec,
                # observing .lock as empty, and further going into hereby initialization. However due to the GIL,
                # list.append() operation is atomic and this way only one of the threads will "win" to put the lock
                # - that every thread will use - into .lock[0].
                # https://docs.python.org/3/faq/library.html#what-kinds-of-global-value-mutation-are-thread-safe
                self.lock.append(lock)
            from functools import partial
            from importlib.util import find_spec
            with self.lock[0]:
                self.fullname = fullname
                try:
                    spec = find_spec(fullname, path)
                    if spec is not None:
                        # https://www.python.org/dev/peps/pep-0451/#how-loading-will-work
                        is_new_api = hasattr(spec.loader, "exec_module")
                        func_name = "exec_module" if is_new_api else "load_module"
                        old = getattr(spec.loader, func_name)
                        func = self.exec_module if is_new_api else self.load_module
                        if old is not func:
                            with suppress(AttributeError):  # C-Extension loaders are r/o such as zipimporter with <3.7
                                setattr(spec.loader, func_name, partial(func, old))
                        return spec
                finally:
                    self.fullname = None
        return None
References exec_module(), find_spec(), fullname, load_module(), and lock.
Referenced by find_spec().
load_module()
load_module (old, name) static
Definition at line 95 of file _virtualenv.py.
    def load_module(old, name):
        module = old(name)
        if module.__name__ in _DISTUTILS_PATCH:
            patch_dist(module)
        return module
References _virtualenv.patch_dist().
Referenced by _SixMetaPathImporter.create_module(), and find_spec().
Field Documentation
fullname
fullname = None static
Definition at line 46 of file _virtualenv.py.
Referenced by find_spec().
lock
lock = [] static
Definition at line 51 of file _virtualenv.py.
Referenced by RecentlyUsedContainer.__delitem__(), RecentlyUsedContainer.__getitem__(), RecentlyUsedContainer.__len__(), RecentlyUsedContainer.__setitem__(), RecentlyUsedContainer.clear(), DictCache.delete(), find_spec(), RecentlyUsedContainer.keys(), and DictCache.set().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/_virtualenv.py