Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: pip._vendor.cachecontrol.heuristics Namespace Reference
pip._vendor.cachecontrol.heuristics Namespace Reference
Data Structures
class BaseHeuristic
class ExpiresAfter
class LastModified
class OneDayCache
Functions
expire_after (delta, date=None)
datetime_to_header (dt)
Variables
str TIME_FMT = "%a, %d %b %Y %H:%M:%S GMT"
Function Documentation
datetime_to_header()
datetime_to_header (dt)
Definition at line 20 of file heuristics.py.
def datetime_to_header(dt):
    return formatdate(calendar.timegm(dt.timetuple()))
Referenced by ExpiresAfter.update_headers(), and OneDayCache.update_headers().
expire_after()
expire_after (delta, date = None)
Definition at line 15 of file heuristics.py.
def expire_after(delta, date=None):
    date = date or datetime.utcnow()
    return date + delta
Referenced by ExpiresAfter.update_headers(), and OneDayCache.update_headers().
Variable Documentation
TIME_FMT
str TIME_FMT = "%a, %d %b %Y %H:%M:%S GMT"
Definition at line 12 of file heuristics.py.