Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Node Class Reference
Node Class Reference
Public Member Functions
Iterable[str] iter_tokens (self)
bool check_length (self, int start_length, int max_length)
str __str__ (self)
str render (self, int max_width=80, int indent_size=4, bool expand_all=False)
Static Public Attributes
str key_repr = ""
str value_repr = ""
str open_brace = ""
str close_brace = ""
str empty = ""
bool last = False
bool is_tuple = False
bool is_namedtuple = False
Optional children = None
str key_separator = ": "
str separator = ", "
Detailed Description
A node in a repr tree. May be atomic or a container.
Definition at line 389 of file pretty.py.
Member Function Documentation
__str__()
str __str__ (self)
Definition at line 443 of file pretty.py.
    def __str__(self) -> str:
        repr_text = "".join(self.iter_tokens())
        return repr_text
References iter_tokens().
check_length()
bool check_length (self, int start_length, int max_length)
Check the length fits within a limit.
Args:
    start_length (int): Starting length of the line (indent, prefix, suffix).
    max_length (int): Maximum length.
Returns:
    bool: True if the node can be rendered within max length, otherwise False.
Definition at line 426 of file pretty.py.
    def check_length(self, start_length: int, max_length: int) -> bool:
        """Check the length fits within a limit.
        Args:
            start_length (int): Starting length of the line (indent, prefix, suffix).
            max_length (int): Maximum length.
        Returns:
            bool: True if the node can be rendered within max length, otherwise False.
        """
        total_length = start_length
        for token in self.iter_tokens():
            total_length += cell_len(token)
            if total_length > max_length:
                return False
        return True
References iter_tokens().
iter_tokens()
Iterable[str] iter_tokens (self)
Generate tokens for this node.
Definition at line 404 of file pretty.py.
    def iter_tokens(self) -> Iterable[str]:
        """Generate tokens for this node."""
        if self.key_repr:
            yield self.key_repr
            yield self.key_separator
        if self.value_repr:
            yield self.value_repr
        elif self.children is not None:
            if self.children:
                yield self.open_brace
                if self.is_tuple and not self.is_namedtuple and len(self.children) == 1:
                    yield from self.children[0].iter_tokens()
                    yield ","
                else:
                    for child in self.children:
                        yield from child.iter_tokens()
                        if not child.last:
                            yield self.separator
                yield self.close_brace
            else:
                yield self.empty
References children, close_brace, empty, is_namedtuple, is_tuple, iter_tokens(), key_repr, key_separator, open_brace, separator, and value_repr.
Referenced by __str__(), check_length(), and iter_tokens().
render()
str render (self, int max_width = 80, int indent_size = 4, bool expand_all = False)
Render the node to a pretty repr.
Args:
    max_width (int, optional): Maximum width of the repr. Defaults to 80.
    indent_size (int, optional): Size of indents. Defaults to 4.
    expand_all (bool, optional): Expand all levels. Defaults to False.
Returns:
    str: A repr string of the original object.
Definition at line 447 of file pretty.py.
    ) -> str:
        """Render the node to a pretty repr.
        Args:
            max_width (int, optional): Maximum width of the repr. Defaults to 80.
            indent_size (int, optional): Size of indents. Defaults to 4.
            expand_all (bool, optional): Expand all levels. Defaults to False.
        Returns:
            str: A repr string of the original object.
        """
        lines = [_Line(node=self, is_root=True)]
        line_no = 0
        while line_no < len(lines):
            line = lines[line_no]
            if line.expandable and not line.expanded:
                if expand_all or not line.check_length(max_width):
                    lines[line_no : line_no + 1] = line.expand(indent_size)
            line_no += 1
        repr_str = "\n".join(str(line) for line in lines)
        return repr_str
@dataclass
Referenced by ProgressColumn.__call__(), Spinner.__rich_console__(), and Spinner.__rich_measure__().
Field Documentation
children
children = None static
Definition at line 400 of file pretty.py.
Referenced by Tree.add(), and iter_tokens().
close_brace
str close_brace = "" static
Definition at line 395 of file pretty.py.
Referenced by iter_tokens().
empty
str empty = "" static
Definition at line 396 of file pretty.py.
Referenced by iter_tokens().
is_namedtuple
bool is_namedtuple = False static
Definition at line 399 of file pretty.py.
Referenced by iter_tokens().
is_tuple
bool is_tuple = False static
Definition at line 398 of file pretty.py.
Referenced by iter_tokens().
key_repr
str key_repr = "" static
Definition at line 392 of file pretty.py.
Referenced by iter_tokens().
key_separator
str key_separator = ": " static
Definition at line 401 of file pretty.py.
Referenced by iter_tokens().
last
bool last = False static
Definition at line 397 of file pretty.py.
Referenced by _Line.__str__(), and _Line.expand().
open_brace
str open_brace = "" static
Definition at line 394 of file pretty.py.
Referenced by iter_tokens().
separator
str separator = ", " static
Definition at line 402 of file pretty.py.
Referenced by iter_tokens().
value_repr
str value_repr = "" static
Definition at line 393 of file pretty.py.
Referenced by iter_tokens().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/rich/pretty.py