Let us walk on the 3-isogeny graph: Token Class Reference
Token Class Reference
Public Member Functions
__init__ (self)
Public Member Functions inherited from ParserElement
using_each (cls, seq, **class_kwargs)
"ParserElement" suppress_warning (self, Diagnostics warning_type)
visit_all (self)
"ParserElement" copy (self)
"ParserElement" set_results_name (self, str name, bool list_all_matches=False, *bool listAllMatches=False)
"ParserElement" set_break (self, bool break_flag=True)
"ParserElement" set_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_condition (self, *ParseCondition fns, **kwargs)
"ParserElement" set_fail_action (self, ParseFailAction fn)
int preParse (self, str instring, int loc)
parseImpl (self, instring, loc, doActions=True)
postParse (self, instring, loc, tokenlist)
int try_parse (self, str instring, int loc, *bool raise_fatal=False, bool do_actions=False)
bool can_parse_next (self, str instring, int loc, bool do_actions=False)
ParseResults parse_string (self, str instring, bool parse_all=False, *bool parseAll=False)
Generator[Tuple[ParseResults, int, int], None, None] scan_string (self, str instring, int max_matches=_MAX_INT, bool overlap=False, *bool debug=False, int maxMatches=_MAX_INT)
str transform_string (self, str instring, *bool debug=False)
ParseResults search_string (self, str instring, int max_matches=_MAX_INT, *bool debug=False, int maxMatches=_MAX_INT)
Generator[str, None, None] split (self, str instring, int maxsplit=_MAX_INT, bool include_separators=False, *includeSeparators=False)
"ParserElement" __add__ (self, other)
"ParserElement" __radd__ (self, other)
"ParserElement" __sub__ (self, other)
"ParserElement" __rsub__ (self, other)
"ParserElement" __mul__ (self, other)
"ParserElement" __rmul__ (self, other)
"ParserElement" __or__ (self, other)
"ParserElement" __ror__ (self, other)
"ParserElement" __xor__ (self, other)
"ParserElement" __rxor__ (self, other)
"ParserElement" __and__ (self, other)
"ParserElement" __rand__ (self, other)
"ParserElement" __invert__ (self)
__getitem__ (self, key)
"ParserElement" __call__ (self, typing.Optional[str] name=None)
"ParserElement" suppress (self)
"ParserElement" ignore_whitespace (self, bool recursive=True)
"ParserElement" leave_whitespace (self, bool recursive=True)
"ParserElement" set_whitespace_chars (self, Union[Set[str], str] chars, bool copy_defaults=False)
"ParserElement" parse_with_tabs (self)
"ParserElement" ignore (self, "ParserElement" other)
"ParserElement" set_debug_actions (self, DebugStartAction start_action, DebugSuccessAction success_action, DebugExceptionAction exception_action)
"ParserElement" set_debug (self, bool flag=True, bool recurse=False)
str default_name (self)
"ParserElement" set_name (self, str name)
str name (self)
str __str__ (self)
str __repr__ (self)
"ParserElement" streamline (self)
List["ParserElement"] recurse (self)
None validate (self, validateTrace=None)
ParseResults parse_file (self, Union[str, Path, TextIO] file_or_filename, str encoding="utf-8", bool parse_all=False, *bool parseAll=False)
__eq__ (self, other)
__hash__ (self)
bool matches (self, str test_string, bool parse_all=True, *bool parseAll=True)
Tuple[bool, List[Tuple[str, Union[ParseResults, Exception]]]] run_tests (self, Union[str, List[str]] tests, bool parse_all=True, typing.Optional[Union["ParserElement", str]] comment="#", bool full_dump=True, bool print_results=True, bool failure_tests=False, typing.Optional[Callable[[str, ParseResults], str]] post_parse=None, typing.Optional[TextIO] file=None, bool with_line_numbers=False, *bool parseAll=True, bool fullDump=True, bool printResults=True, bool failureTests=False, typing.Optional[Callable[[str, ParseResults], str]] postParse=None)
None create_diagram (self, Union[TextIO, Path, str] output_html, int vertical=3, bool show_results_names=False, bool show_groups=False, bool embed=False, **kwargs)
setResultsName (self)
setBreak (self)
setParseAction (self)
addParseAction (self)
addCondition (self)
setFailAction (self)
tryParse (self)
parseString (self)
scanString (self)
transformString (self)
searchString (self)
ignoreWhitespace (self)
leaveWhitespace (self)
setWhitespaceChars (self)
parseWithTabs (self)
setDebugActions (self)
setDebug (self)
setName (self)
parseFile (self)
runTests (self)
Protected Member Functions
str _generateDefaultName (self)
Protected Member Functions inherited from ParserElement
_setResultsName (self, name, listAllMatches=False)
int _skipIgnorables (self, str instring, int loc)
Tuple[int, ParseResults] _parseNoCache (self, instring, loc, doActions=True, callPreParse=True)
Tuple[int, ParseResults] _parseCache (self, instring, loc, doActions=True, callPreParse=True)
_checkRecursion (self, parseElementList)
Additional Inherited Members
Static Public Member Functions inherited from ParserElement
None set_default_whitespace_chars (str chars)
None inline_literals_using (type cls)
None reset_cache ()
None disable_memoization ()
None enable_left_recursion (typing.Optional[int] cache_size_limit=None, *force=False)
None enable_packrat (int cache_size_limit=128, *bool force=False)
inlineLiteralsUsing ()
setDefaultWhitespaceChars ()
enableLeftRecursion ()
enablePackrat ()
Data Fields inherited from ParserElement
saveAsList
skipWhitespace
whiteChars
copyDefaultWhiteChars
mayReturnEmpty
keepTabs
debug
streamlined
mayIndexError
errmsg
modalResults
debugActions
callPreparse
callDuringTry
parseAction
failAction
resultsName
customName
Static Public Attributes inherited from ParserElement
str DEFAULT_WHITE_CHARS = " \n\t\r"
bool verbose_stacktrace = False
recursion_lock = RLock()
dict recursion_memos = {}
tuple packrat_cache
packrat_cache_lock = RLock()
list packrat_cache_stats = [0, 0]
bool canParseNext = can_parse_next
None resetCache = reset_cache
str defaultName = default_name
Protected Attributes inherited from ParserElement
_parse
_defaultName
Static Protected Attributes inherited from ParserElement
type _literalStringClass = None
Tuple[int, ParseResults] _parse = _parseNoCache
bool _packratEnabled = False
bool _left_recursion_enabled = False
Detailed Description
Abstract :class:`ParserElement` subclass, for defining atomic
matching patterns.
Definition at line 2372 of file core.py.
Constructor & Destructor Documentation
__init__()
__init__ (self)
Reimplemented from ParserElement.
Reimplemented in NoMatch, PositionToken, LineStart, LineEnd, StringStart, StringEnd, And._ErrorStop, Regex, GoToColumn, IndentedBlock._Indent, IndentedBlock._IndentGreater, Empty, Char, Word, CloseMatch, Literal, CaselessLiteral, CaselessKeyword, Keyword, CharsNotIn, QuotedString, WordStart, WordEnd, and White.
Definition at line 2377 of file core.py.
    def __init__(self):
        super().__init__(savelist=False)
References Token.__init__(), and i.
Referenced by Token.__init__(), and Protocol.__init_subclass__().
Member Function Documentation
_generateDefaultName()
str _generateDefaultName (self) protected
Child classes must define this method, which defines how the ``default_name`` is set.
Reimplemented from ParserElement.
Reimplemented in Literal, Empty, Keyword, CloseMatch, Word, Regex, QuotedString, CharsNotIn, White, and And._ErrorStop.
Definition at line 2380 of file core.py.
    def _generateDefaultName(self) -> str:
        return type(self).__name__
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/core.py