Let us walk on the 3-isogeny graph: wait_none Class Reference
wait_none Class Reference
Public Member Functions
None __init__ (self)
Public Member Functions inherited from wait_fixed
float __call__ (self, "RetryCallState" retry_state)
Public Member Functions inherited from wait_base
"wait_combine" __add__ (self, "wait_base" other)
typing.Union["wait_combine", "wait_base"] __radd__ (self, "wait_base" other)
Additional Inherited Members
Data Fields inherited from wait_fixed
wait_fixed
Detailed Description
Wait strategy that doesn't wait at all before retrying.
Definition at line 57 of file wait.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Reimplemented from wait_fixed.
Definition at line 60 of file wait.py.
    def __init__(self) -> None:
        super().__init__(0)
References wait_none.__init__(), and i.
Referenced by wait_none.__init__(), and Protocol.__init_subclass__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/tenacity/wait.py