Let us walk on the 3-isogeny graph: pip._vendor.rich.cells Namespace Reference
pip._vendor.rich.cells Namespace Reference
Functions
int cached_cell_len (str text)
int cell_len (str text, Callable[[str], int] _cell_len=cached_cell_len)
int get_character_cell_size (str character)
int _get_codepoint_cell_size (int codepoint)
str set_cell_size (str text, int total)
List[str] chop_cells (str text, int max_size, int position=0)
Variables
_is_single_cell_widths = re.compile("^[\u0020-\u006f\u00a0\u02ff\u0370-\u0482]*$").match
Function Documentation
_get_codepoint_cell_size()
int _get_codepoint_cell_size (int codepoint) protected
Get the cell size of a character.
Args:
    codepoint (int): Codepoint of a character.
Returns:
    int: Number of cells (0, 1 or 2) occupied by that character.
Definition at line 59 of file cells.py.
def _get_codepoint_cell_size(codepoint: int) -> int:
    """Get the cell size of a character.
    Args:
        codepoint (int): Codepoint of a character.
    Returns:
        int: Number of cells (0, 1 or 2) occupied by that character.
    """
    _table = CELL_WIDTHS
    lower_bound = 0
    upper_bound = len(_table) - 1
    index = (lower_bound + upper_bound) // 2
    while True:
        start, end, width = _table[index]
        if codepoint < start:
            upper_bound = index - 1
        elif codepoint > end:
            lower_bound = index + 1
        else:
            return 0 if width == -1 else width
        if upper_bound < lower_bound:
            break
        index = (lower_bound + upper_bound) // 2
    return 1
References i.
Referenced by pip._vendor.rich.cells.get_character_cell_size().
cached_cell_len()
int cached_cell_len (str text)
Get the number of cells required to display text.
This method always caches, which may use up a lot of memory. It is recommended to use
`cell_len` over this method.
Args:
    text (str): Text to display.
Returns:
    int: Get the number of cells required to display text.
Definition at line 12 of file cells.py.
def cached_cell_len(text: str) -> int:
    """Get the number of cells required to display text.
    This method always caches, which may use up a lot of memory. It is recommended to use
    `cell_len` over this method.
    Args:
        text (str): Text to display.
    Returns:
        int: Get the number of cells required to display text.
    """
    _get_size = get_character_cell_size
    total_size = sum(_get_size(character) for character in text)
    return total_size
References i.
cell_len()
int cell_len (str text, Callable[[str], int] _cell_len = cached_cell_len)
Get the number of cells required to display text.
Args:
    text (str): Text to display.
Returns:
    int: Get the number of cells required to display text.
Definition at line 29 of file cells.py.
def cell_len(text: str, _cell_len: Callable[[str], int] = cached_cell_len) -> int:
    """Get the number of cells required to display text.
    Args:
        text (str): Text to display.
    Returns:
        int: Get the number of cells required to display text.
    """
    if len(text) < 512:
        return _cell_len(text)
    _get_size = get_character_cell_size
    total_size = sum(_get_size(character) for character in text)
    return total_size
@lru_cache(maxsize=4096)
References i.
chop_cells()
List[str] chop_cells (str text, int max_size, int position = 0)
Break text in to equal (cell) length strings, returning the characters in reverse
order
Definition at line 124 of file cells.py.
def chop_cells(text: str, max_size: int, position: int = 0) -> List[str]:
    """Break text in to equal (cell) length strings, returning the characters in reverse
    order"""
    _get_character_cell_size = get_character_cell_size
    characters = [
        (character, _get_character_cell_size(character)) for character in text
    ]
    total_size = position
    lines: List[List[str]] = [[]]
    append = lines[-1].append
    for character, size in reversed(characters):
        if total_size + size > max_size:
            lines.append([character])
            append = lines[-1].append
            total_size = size
        else:
            total_size += size
            append(character)
    return ["".join(line) for line in lines]
get_character_cell_size()
int get_character_cell_size (str character)
Get the cell size of a character.
Args:
    character (str): A single character.
Returns:
    int: Number of cells (0, 1 or 2) occupied by that character.
Definition at line 46 of file cells.py.
def get_character_cell_size(character: str) -> int:
    """Get the cell size of a character.
    Args:
        character (str): A single character.
    Returns:
        int: Number of cells (0, 1 or 2) occupied by that character.
    """
    return _get_codepoint_cell_size(ord(character))
@lru_cache(maxsize=4096)
References pip._vendor.rich.cells._get_codepoint_cell_size(), and i.
set_cell_size()
str set_cell_size (str text, int total)
Set the length of a string to fit within given number of cells.
Definition at line 87 of file cells.py.
def set_cell_size(text: str, total: int) -> str:
    """Set the length of a string to fit within given number of cells."""
    if _is_single_cell_widths(text):
        size = len(text)
        if size < total:
            return text + " " * (total - size)
        return text[:total]
    if total <= 0:
        return ""
    cell_size = cell_len(text)
    if cell_size == total:
        return text
    if cell_size < total:
        return text + " " * (total - cell_size)
    start = 0
    end = len(text)
    # Binary search until we find the right size
    while True:
        pos = (start + end) // 2
        before = text[: pos + 1]
        before_len = cell_len(before)
        if before_len == total + 1 and cell_len(before[-1]) == 2:
            return before[:-1] + " "
        if before_len == total:
            return before
        if before_len > total:
            end = pos
        else:
            start = pos
# TODO: This is inefficient
# TODO: This might not work with CWJ type characters
References pip._vendor.rich.cells._is_single_cell_widths, and i.
Variable Documentation
_is_single_cell_widths
_is_single_cell_widths = re.compile("^[\u0020-\u006f\u00a0\u02ff\u0370-\u0482]*$").match protected
Definition at line 8 of file cells.py.
Referenced by pip._vendor.rich.cells.set_cell_size().