Let us walk on the 3-isogeny graph: ConfiguredBuildBackendHookCaller Class Reference
ConfiguredBuildBackendHookCaller Class Reference
Public Member Functions
__init__ (self, Any config_holder, str source_dir, str build_backend, Optional[str] backend_path=None, Optional[Callable[..., None]] runner=None, Optional[str] python_executable=None)
str build_wheel (self, str wheel_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None, Optional[str] metadata_directory=None)
str build_sdist (self, str sdist_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
str build_editable (self, str wheel_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None, Optional[str] metadata_directory=None)
List[str] get_requires_for_build_wheel (self, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
List[str] get_requires_for_build_sdist (self, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
List[str] get_requires_for_build_editable (self, Optional[Dict[str, Union[str, List[str]]]] config_settings=None)
str prepare_metadata_for_build_wheel (self, str metadata_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None, bool _allow_fallback=True)
str prepare_metadata_for_build_editable (self, str metadata_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings=None, bool _allow_fallback=True)
Public Member Functions inherited from BuildBackendHookCaller
subprocess_runner (self, runner)
Data Fields
config_holder
Data Fields inherited from BuildBackendHookCaller
source_dir
build_backend
backend_path
python_executable
Additional Inherited Members
Protected Member Functions inherited from BuildBackendHookCaller
_supported_features (self)
_call_hook (self, hook_name, kwargs)
Protected Attributes inherited from BuildBackendHookCaller
_subprocess_runner
Detailed Description
Definition at line 648 of file misc.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, Any source_dir, str build_backend, str backend_path, Optional[str] runner = None, Optional[Callable[..., None]] python_executable = None, Optional[str] python_executable = None)
:param source_dir: The source directory to invoke the build backend for
:param build_backend: The build backend spec
:param backend_path: Additional path entries for the build backend spec
:param runner: The :ref:`subprocess runner <Subprocess Runners>` to use
:param python_executable:
    The Python executable used to invoke the build backend
Reimplemented from BuildBackendHookCaller.
Definition at line 649 of file misc.py.
    ):
        super().__init__(
            source_dir, build_backend, backend_path, runner, python_executable
        )
        self.config_holder = config_holder
References ConfiguredBuildBackendHookCaller.__init__(), and i.
Referenced by ConfiguredBuildBackendHookCaller.__init__(), and Protocol.__init_subclass__().
Member Function Documentation
build_editable()
str build_editable (self, str wheel_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None, Optional[str] metadata_directory = None)
Build an editable wheel from this project.
:returns:
    The name of the newly created wheel within ``wheel_directory``.
.. admonition:: Interaction with fallback
    If the ``build_editable`` hook was called in the fallback for
    :meth:`prepare_metadata_for_build_editable`, the build backend
    would not be invoked. Instead, the previously built wheel will be
    copied to ``wheel_directory`` and the name of that file will be
    returned.
Reimplemented from BuildBackendHookCaller.
Definition at line 682 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().build_editable(
            wheel_directory, config_settings=cs, metadata_directory=metadata_directory
        )
References ConfiguredBuildBackendHookCaller.build_editable(), ConfiguredBuildBackendHookCaller.config_holder, and i.
Referenced by ConfiguredBuildBackendHookCaller.build_editable().
build_sdist()
str build_sdist (self, str sdist_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None)
Build an sdist from this project.
:returns:
    The name of the newly created sdist within ``wheel_directory``.
Reimplemented from BuildBackendHookCaller.
Definition at line 674 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().build_sdist(sdist_directory, config_settings=cs)
References ConfiguredBuildBackendHookCaller.build_sdist(), ConfiguredBuildBackendHookCaller.config_holder, and i.
Referenced by ConfiguredBuildBackendHookCaller.build_sdist().
build_wheel()
str build_wheel (self, str wheel_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None, Optional[str] metadata_directory = None)
Build a wheel from this project.
:returns:
    The name of the newly created wheel within ``wheel_directory``.
.. admonition:: Interaction with fallback
    If the ``build_wheel`` hook was called in the fallback for
    :meth:`prepare_metadata_for_build_wheel`, the build backend would
    not be invoked. Instead, the previously built wheel will be copied
    to ``wheel_directory`` and the name of that file will be returned.
Reimplemented from BuildBackendHookCaller.
Definition at line 663 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().build_wheel(
            wheel_directory, config_settings=cs, metadata_directory=metadata_directory
        )
References ConfiguredBuildBackendHookCaller.build_wheel(), ConfiguredBuildBackendHookCaller.config_holder, and i.
Referenced by ConfiguredBuildBackendHookCaller.build_wheel().
get_requires_for_build_editable()
List[str] get_requires_for_build_editable (self, Optional[Dict[str, Union[str, List[str]]]] config_settings = None)
Get additional dependencies required for building an editable wheel.
:returns: A list of :pep:`dependency specifiers <508>`.
:rtype: list[str]
.. admonition:: Fallback
    If the build backend does not defined a hook with this name, an
    empty list will be returned.
Reimplemented from BuildBackendHookCaller.
Definition at line 705 of file misc.py.
    ) -> List[str]:
        cs = self.config_holder.config_settings
        return super().get_requires_for_build_editable(config_settings=cs)
References ConfiguredBuildBackendHookCaller.config_holder, ConfiguredBuildBackendHookCaller.get_requires_for_build_editable(), and i.
Referenced by ConfiguredBuildBackendHookCaller.get_requires_for_build_editable().
get_requires_for_build_sdist()
List[str] get_requires_for_build_sdist (self, Optional[Dict[str, Union[str, List[str]]]] config_settings = None)
Get additional dependencies required for building an sdist.
:returns: A list of :pep:`dependency specifiers <508>`.
:rtype: list[str]
Reimplemented from BuildBackendHookCaller.
Definition at line 699 of file misc.py.
    ) -> List[str]:
        cs = self.config_holder.config_settings
        return super().get_requires_for_build_sdist(config_settings=cs)
References ConfiguredBuildBackendHookCaller.config_holder, ConfiguredBuildBackendHookCaller.get_requires_for_build_sdist(), and i.
Referenced by ConfiguredBuildBackendHookCaller.get_requires_for_build_sdist().
get_requires_for_build_wheel()
List[str] get_requires_for_build_wheel (self, Optional[Dict[str, Union[str, List[str]]]] config_settings = None)
Get additional dependencies required for building a wheel.
:returns: A list of :pep:`dependency specifiers <508>`.
:rtype: list[str]
.. admonition:: Fallback
    If the build backend does not defined a hook with this name, an
    empty list will be returned.
Reimplemented from BuildBackendHookCaller.
Definition at line 693 of file misc.py.
    ) -> List[str]:
        cs = self.config_holder.config_settings
        return super().get_requires_for_build_wheel(config_settings=cs)
References ConfiguredBuildBackendHookCaller.config_holder, ConfiguredBuildBackendHookCaller.get_requires_for_build_wheel(), and i.
Referenced by ConfiguredBuildBackendHookCaller.get_requires_for_build_wheel().
prepare_metadata_for_build_editable()
str prepare_metadata_for_build_editable (self, str metadata_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None, bool _allow_fallback = True)
Prepare a ``*.dist-info`` folder with metadata for this project.
:returns: Name of the newly created subfolder within
          ``metadata_directory``, containing the metadata.
:rtype: str
.. admonition:: Fallback
    If the build backend does not define a hook with this name and
    ``_allow_fallback`` is truthy, the backend will be asked to build a
    wheel via the ``build_editable`` hook and the dist-info
    extracted from that will be returned.
Reimplemented from BuildBackendHookCaller.
Definition at line 724 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().prepare_metadata_for_build_editable(
            metadata_directory=metadata_directory,
            config_settings=cs,
            _allow_fallback=_allow_fallback,
        )
References ConfiguredBuildBackendHookCaller.config_holder, i, and ConfiguredBuildBackendHookCaller.prepare_metadata_for_build_editable().
Referenced by ConfiguredBuildBackendHookCaller.prepare_metadata_for_build_editable().
prepare_metadata_for_build_wheel()
str prepare_metadata_for_build_wheel (self, str metadata_directory, Optional[Dict[str, Union[str, List[str]]]] config_settings = None, bool _allow_fallback = True)
Prepare a ``*.dist-info`` folder with metadata for this project.
:returns: Name of the newly created subfolder within
          ``metadata_directory``, containing the metadata.
:rtype: str
.. admonition:: Fallback
    If the build backend does not define a hook with this name and
    ``_allow_fallback`` is truthy, the backend will be asked to build a
    wheel via the ``build_wheel`` hook and the dist-info extracted from
    that will be returned.
Reimplemented from BuildBackendHookCaller.
Definition at line 711 of file misc.py.
    ) -> str:
        cs = self.config_holder.config_settings
        return super().prepare_metadata_for_build_wheel(
            metadata_directory=metadata_directory,
            config_settings=cs,
            _allow_fallback=_allow_fallback,
        )
References ConfiguredBuildBackendHookCaller.config_holder, i, and ConfiguredBuildBackendHookCaller.prepare_metadata_for_build_wheel().
Referenced by ConfiguredBuildBackendHookCaller.prepare_metadata_for_build_wheel().
Field Documentation
config_holder
config_holder
Definition at line 661 of file misc.py.
Referenced by ConfiguredBuildBackendHookCaller.build_editable(), ConfiguredBuildBackendHookCaller.build_sdist(), ConfiguredBuildBackendHookCaller.build_wheel(), ConfiguredBuildBackendHookCaller.get_requires_for_build_editable(), ConfiguredBuildBackendHookCaller.get_requires_for_build_sdist(), ConfiguredBuildBackendHookCaller.get_requires_for_build_wheel(), ConfiguredBuildBackendHookCaller.prepare_metadata_for_build_editable(), and ConfiguredBuildBackendHookCaller.prepare_metadata_for_build_wheel().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/utils/misc.py