Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: LifoQueue Class Reference
LifoQueue Class Reference
Data Fields
queue = collections.deque()
Protected Member Functions
_init (self, _)
_qsize (self, len=len)
_put (self, item)
_get (self)
Detailed Description
Definition at line 11 of file queue.py.
Member Function Documentation
_get()
_get (self) protected
Definition at line 21 of file queue.py.
    def _get(self):
        return self.queue.pop()
References queue.
_init()
_init (self, _) protected
Definition at line 12 of file queue.py.
    def _init(self, _):
        self.queue = collections.deque()
_put()
_put (self, item) protected
Definition at line 18 of file queue.py.
    def _put(self, item):
        self.queue.append(item)
References pip._vendor.urllib3.append, and queue.
_qsize()
_qsize (self, len = len) protected
Definition at line 15 of file queue.py.
    def _qsize(self, len=len):
        return len(self.queue)
References queue.
Field Documentation
queue
queue = collections.deque()
Definition at line 13 of file queue.py.
Referenced by _get(), _put(), and _qsize().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/urllib3/util/queue.py