Let us walk on the 3-isogeny graph: _ProtocolMeta Class Reference
_ProtocolMeta Class Reference
Public Member Functions
__new__ (mcls, name, bases, namespace, **kwargs)
__init__ (cls, *args, **kwargs)
__subclasscheck__ (cls, other)
__instancecheck__ (cls, instance)
__eq__ (cls, other)
int __hash__ (cls)
Detailed Description
Definition at line 611 of file typing_extensions.py.
Constructor & Destructor Documentation
__init__()
__init__ (cls, * args, ** kwargs)
Definition at line 634 of file typing_extensions.py.
        def __init__(cls, *args, **kwargs):
            abc.ABCMeta.__init__(cls, *args, **kwargs)
            if getattr(cls, "_is_protocol", False):
                cls.__protocol_attrs__ = _get_protocol_attrs(cls)
                # PEP 544 prohibits using issubclass()
                # with protocols that have non-method members.
                cls.__callable_proto_members_only__ = all(
                    callable(getattr(cls, attr, None)) for attr in cls.__protocol_attrs__
                )
References _ProtocolMeta.__callable_proto_members_only__, _ProtocolMeta.__protocol_attrs__, pip._vendor.typing_extensions._get_protocol_attrs(), and i.
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__eq__()
__eq__ (cls, other)
Definition at line 699 of file typing_extensions.py.
        def __eq__(cls, other):
            # Hack so that typing.Generic.__class_getitem__
            # treats typing_extensions.Protocol
            # as equivalent to typing.Protocol on Python 3.8+
            if abc.ABCMeta.__eq__(cls, other) is True:
                return True
            return (
                cls is Protocol and other is getattr(typing, "Protocol", object())
            )
References i.
Referenced by Version.__ge__(), Version.__gt__(), Version.__le__(), Version.__ne__(), Matcher.__ne__(), Timestamp.__ne__(), and HTTPHeaderDict.__ne__().
__hash__()
int __hash__ (cls)
Definition at line 712 of file typing_extensions.py.
        def __hash__(cls) -> int:
            return type.__hash__(cls)
    @classmethod
References i.
Referenced by Style.__eq__(), and Style.__ne__().
__instancecheck__()
__instancecheck__ (cls, instance)
Definition at line 668 of file typing_extensions.py.
        def __instancecheck__(cls, instance):
            # We need this method for situations where attributes are
            # assigned in __init__.
            if cls is Protocol:
                return type.__instancecheck__(cls, instance)
            if not getattr(cls, "_is_protocol", False):
                # i.e., it's a concrete subclass of a protocol
                return abc.ABCMeta.__instancecheck__(cls, instance)
            if (
                not getattr(cls, '_is_runtime_protocol', False) and
                not _allow_reckless_class_checks()
            ):
                raise TypeError("Instance and class checks can only be used with"
                                " @runtime_checkable protocols")
            if abc.ABCMeta.__instancecheck__(cls, instance):
                return True
            for attr in cls.__protocol_attrs__:
                try:
                    val = inspect.getattr_static(instance, attr)
                except AttributeError:
                    break
                if val is None and callable(getattr(cls, attr, None)):
                    break
            else:
                return True
            return False
References _ProtocolMeta.__protocol_attrs__, pip._vendor.typing_extensions._allow_reckless_class_checks(), and i.
__new__()
__new__ (mcls, name, bases, namespace, ** kwargs)
Reimplemented in Protocol.
Definition at line 618 of file typing_extensions.py.
        def __new__(mcls, name, bases, namespace, **kwargs):
            if name == "Protocol" and len(bases) < 2:
                pass
            elif {Protocol, _typing_Protocol} & set(bases):
                for base in bases:
                    if not (
                        base in {object, typing.Generic, Protocol, _typing_Protocol}
                        or base.__name__ in _PROTO_ALLOWLIST.get(base.__module__, [])
                        or is_protocol(base)
                    ):
                        raise TypeError(
                            f"Protocols can only inherit from other protocols, "
                            f"got {base!r}"
                        )
            return abc.ABCMeta.__new__(mcls, name, bases, namespace, **kwargs)
References i, and pip._vendor.typing_extensions.is_protocol.
Referenced by Style._add(), Style.clear_meta_and_links(), Style.copy(), Style.from_color(), JSON.from_data(), Style.from_meta(), Style.update_link(), and Style.without_color().
__subclasscheck__()
__subclasscheck__ (cls, other)
Definition at line 644 of file typing_extensions.py.
        def __subclasscheck__(cls, other):
            if cls is Protocol:
                return type.__subclasscheck__(cls, other)
            if (
                getattr(cls, '_is_protocol', False)
                and not _allow_reckless_class_checks()
            ):
                if not isinstance(other, type):
                    # Same error message as for issubclass(1, int).
                    raise TypeError('issubclass() arg 1 must be a class')
                if (
                    not cls.__callable_proto_members_only__
                    and cls.__dict__.get("__subclasshook__") is _proto_hook
                ):
                    raise TypeError(
                        "Protocols with non-method members don't support issubclass()"
                    )
                if not getattr(cls, '_is_runtime_protocol', False):
                    raise TypeError(
                        "Instance and class checks can only be used with "
                        "@runtime_checkable protocols"
                    )
            return abc.ABCMeta.__subclasscheck__(cls, other)
References _ProtocolMeta.__callable_proto_members_only__, StreamWrapper.__dict__, pip._vendor.typing_extensions._allow_reckless_class_checks(), and i.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/typing_extensions.py