Let us walk on the 3-isogeny graph: AsmMultCodegenerator_PIC Namespace Reference
AsmMultCodegenerator_PIC Namespace Reference
Functions
WordExtractor (p, pwords, Var)
PrintHeader (pbits, pbytes, plimbs)
PrintUintHeader (plimbs)
PrintFooter ()
PrintRedOnce (pbytes)
PrintSub ()
PrintMul (pbytes, pwords)
PrintPow (pwords)
PrintOthers ()
Print_Parameters (p, pbits, pbytes, pwords)
Print_Assembly (p)
main (argv)
Variables
int p_2047d221 = 0x5160D4543A2596D320C080B284C0FA5D3600AE4E29B85374858B238036139EA0B8B0C8B2850475382865FD4C9F7C3B5E531ED7D0FC022A13270300584EC78190FD09755A56CFEB1FC6961581CDFC56E824D0F31C4D4ECF04C5243CA0651820AF413023A7310203F74858FBECACA26B375BEBA9DE78CC420A069477B7FE595F83B148223C6841B3592C74AF79F39AE8F3D64F8B9FC946BB1C84A4541CBC2F363029B2C1E296158774A9646D2E186AD699B304FC7311F0DEC85E651756DDB4E3888D02333D591583AE5DB2F656E63A6179CDB059ED9BF90BAD614DCA5628C940C5004D99FB1CB03CE478F65726B12E42FA1C7C8FFFFFFFFFFFFFFFFFFFFFFFFFFF
int p_2047n221 = 0x459AEF6A877E5ADAA0902C6A81793F136D3E606CECECC229616377E3B9C4A5630F19ADD54D8C5523E1A3AED0A5CB129A69220DB334EFF4A66BFA495ACCBFA7A31B1097D145C0FB10A0427AD5EE55DA93D7B04D72732719ACF7C00FC0BCDC2ADD1DCC5DD91163C9547109B0A8A65EC1BDEB34774FB24FE7A88EEC915BE40A0402A3D8A48E8371EC94456DE1CB00A2F8C07FAF5AACAB12ED8E6C81F4CD3BFE4FB5C3A08FCD2434148F82FEEC069F4509398AEDB078EAD657ED2D3BB68D87A80459D590CF47C1CD12CFE0A33DE40AB61EC18AD9791E0024F0E7EF3E782F87E2823D2B205845C6ED21AEB7E8298551D41019334FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
int p_2047k221 = 0x4f49aaf26e4aefb626bb94dc36fd0732eff9ff84c9b3b1b49c85afe27f67725f25d9e24a0748378bdebd472aa103a02b9c3c0fc3740c26d882af03859d69962d0ce8ad54d154c156241fe343116b31776c0e7aab1bf721dfac0073a2b919b0a4b543b329bed97c9490c340c95add5f8c457afa1ae8c5352a05816da706eb3cab844d51d759b0c53089a678df7aae625ba90481e7927800a6ac53715e3b7b996293f4fab37d61640dffc6c6b2579b25d1d51310e46e8c2b097835f78ebc56ce0c478af769ae62b6e0f6d3630a6ebae5ed1a549b7f4b8f58f1f61fe1a2e6d6cac6c5a05e7d325440ecfc70c3714d157138c90a04ffffffffffffffffffffffffff
int p_4095d221 = 
int p_4095n221 = 
int p_4095k256 = 
int p_5119d256 = 
int p_5119n234 = 
int p_5119k234 = 
int p_6143d306 = 
int p_6143n234 = 
int p_6143k256 = 
int p_8191d306 = 
int p_8191n332 = 
int p_8191k332 = 
int p_9215d384 = 
int p_9215n332 = 
int p_9215k384 = 
int p_512k256 = 0x65b48e8f740f89bffc8ab0d15e3e4c4ab42d083aedc88c425afbfcc69322c9cda7aac6c567f35507516730cc1f0b4f25c2721bf457aca8351b81b90533c6c87b
int p_2048 = p_2047k221
int p_4096 = p_4095k256
int p_5120 = p_5119k234
int p_6144 = p_6143k256
int p_8192 = p_8191k332
int p_9216 = p_9215k384
int p_512 = p_512k256
Function Documentation
main()
main (argv)
Definition at line 452 of file AsmMultCodegenerator_PIC.py.
def main(argv):
    global printOut
    if(len(argv) < 2):
        print(
            "\nplease specify the prime and desired output [0 = assembly | 1 = UintHeader]\n")
        sys.exit()
    else:
        prime = argv[0]
        length = 0
        if(prime=="512k256"):
            p = p_512k256
            length = 512
            if(p.bit_length() > length):
                print("\nError : prime p too long\n")
                sys.exit()
        elif(prime=="2047n221"):
            p = p_2048
            length = 2048
            if(p.bit_length() > length):
                print("\nError : prime p too long\n")
                sys.exit()
        elif(prime=="4095n221"):
            p = p_4096
            length = 4096
            if(p.bit_length() > length):
                print("\nError : prime p too long\n")
                sys.exit()
        elif(prime=="5119n234"):
            p = p_5120
            length = 5120
            if(p.bit_length() > length):
                print("\nError : prime p too long\n")
                sys.exit()
        elif(prime=="6143n234"):
            p = p_6144
            length = 6144
            if(p.bit_length() > length):
                print("\nError : prime p too long\n")
                sys.exit()
        elif(prime=="8191n332"):
            p = p_8192
            length = 8192
            if(p.bit_length() > length):
                print("\nError : prime p too long\n")
                sys.exit()
        elif(prime=="9215n332"):
            p = p_9216
            length = 9216
            if(p.bit_length() > length):
                print("\nError : prime p too long\n")
                sys.exit()
        else:
            print("\nError : no prime available for this length\n")
            sys.exit()
        if int(argv[1]) == 0 :
            Print_Assembly(p)
        else:
            PrintUintHeader(length//64)
References if, main(), Print_Assembly(), and PrintUintHeader().
Print_Assembly()
Print_Assembly (p)
Definition at line 354 of file AsmMultCodegenerator_PIC.py.
def Print_Assembly(p):
#// size of p in bits, bytes ,words
    pbits = math.ceil(math.log(p, 2.0))
    pbytes = math.ceil(pbits/8)
    if((pbytes%4) != 0):
        pbytes = pbytes + 4 - (pbytes%4)
    pwords = math.ceil(pbits/64)
#// Writing header;
    S = PrintHeader(pbits, pbytes, pwords)
#// Writing parameters;
    S = Print_Parameters(p, pbits, pbytes, pwords)
#// Printing Reduce Once
    S = PrintRedOnce(pbytes)
#// Printing Add_Sub
    S = PrintSub()
#// Printing Mult
    S = PrintMul(pbytes, pwords)
#// Printing Pow
    # S = PrintPow(pwords)
#// Printing Others
    S = PrintOthers()
    return 0;
#//+++++++++++++++ Main ++++++++++++++++++//
# Primes of the form p := 2^e * prod(ell_i's) - 1
References if, Print_Parameters(), PrintHeader(), PrintMul(), PrintOthers(), PrintRedOnce(), and PrintSub().
Referenced by main().
Print_Parameters()
Print_Parameters (p, pbits, pbytes, pwords)
Definition at line 291 of file AsmMultCodegenerator_PIC.py.
def Print_Parameters(p, pbits, pbytes, pwords):
#// Montgomery parameter R
    R = 2**(64*pwords)
    RR = IntegerModRing(R)
#//Extracting p words and saving in file
    P = WordExtractor(p, pwords, "p");
# // Computing -(1/p) mod R;
    #pinv = IntegerRing()!(RR!(-1/p))
    pinv = int(RR(-p).inverse_of_unit())
    #pinv = -(1//p)%R
# //Extracting pinv words and saving in file
    Pinv = WordExtractor(pinv, pwords, "inv_min_p_mod_r")
    S = "uintbig_1_fp:\n"
    S = S + "    .quad 1, 0, 0, 0\n"
    N = (pwords//4) -1;
    for i in range(1, N+1):
        S = S + "    .quad 0, 0, 0, 0\n"
    S = S + "\n"
# // Printing zero
    S = ".global fp_0\nfp_0:\n.zero pbytes\n\n"
    print(S)
# PrintFile(Name, S);
# // 1 at Montgomery domain
    one = R%p
# //Extracting one words and saving in file
    ONE = WordExtractor(one, pwords, "fp_1")
# // 1 at Montgomery domain
    two = (R+one)%p
# //Extracting one words and saving in file
    TWO = WordExtractor(two, pwords, "fp_2")
# // R^2 at Montgomery domain
    Rsqr = R**2%p
# //Extracting Rsqr words and saving in file
    RsqrWords = WordExtractor(Rsqr, pwords, "r_squared_mod_p ")
# //Extracting p-2 words and saving in file
    pminus2Words = WordExtractor(p-2, pwords, "p_minus_2")
# //Extracting phalves words and saving in file
    phalvesWords = WordExtractor((p-1)//2, pwords, "p_minus_1_halves")
# //Extracting pquarters words and saving in file
    pquartersWords = WordExtractor((p-3)//4, pwords, "p_minus_3_quarters")
# //Printing footer
    S = PrintFooter()
    return 0
#////////////////////////////////////////
References PrintFooter(), and WordExtractor().
Referenced by Print_Assembly().
PrintFooter()
PrintFooter ()
Definition at line 87 of file AsmMultCodegenerator_PIC.py.
def PrintFooter():
    # S = ".section .data\n\n"
    # S = S + ".global fpadd\nfpadd:\n     .quad 0\n\n"
    # S = S + ".global fpsqr\nfpsqr:\n     .quad 0\n\n"
    # S = S + ".global fpmul\nfpmul:\n     .quad 0\n\n"
    S = ".section .text\n\n.p2align 4,,15\n\n"
    #S = S + ".global init_counters\ninit_counters:\n      ret\n\n"
    #S = S + ".global init_counters\ninit_counters:\n      movq [rip + fpadd], 0\n      movq [rip + fpsqr], 0\n      movq [rip + fpmul], 0\n      ret\n\n"
    S = S + ".global fp_copy\nfp_copy:\n    cld\n    mov rcx, plimbs\n    rep movsq\n    ret\n\n"
    S = S + ".global fp_cswap\nfp_cswap:\n    movzx rax, dl\n    neg rax\n    .set k, 0\n    .rept plimbs\n        mov rcx, [rdi + 8*k]\n"
    S = S + "        mov rdx, [rsi + 8*k]\n        mov r8, rcx\n        xor r8, rdx\n        and r8, rax\n\n        xor rcx, r8\n        xor rdx, r8\n\n"
    S = S + "        mov [rdi + 8*k], rcx\n        mov [rsi + 8*k], rdx\n\n        .set k, k+1\n    .endr\n    ret\n\n"
    S = S + ".global fp_cmov\n"
    S = S + "fp_cmov:\n"
    S = S + "    movzx rax, dl\n"
    S = S + "    neg rax\n"
    S = S + "    .set k, 0\n"
    S = S + "    .rept plimbs\n"
    S = S + "        mov rcx, [rdi + 8*k]\n"
    S = S + "        mov rdx, [rsi + 8*k]\n"
    S = S + "        xor rdx, rcx\n"
    S = S + "        and rdx, rax\n"
    S = S + "        xor rcx, rdx\n"
    S = S + "        mov [rdi + 8*k], rcx\n"
    S = S + "        .set k, k+1\n"
    S = S + "    .endr\n"
    S = S + "    ret\n"
    print(S)
    return S
#////////////////////////////////////////
Referenced by Print_Parameters().
PrintHeader()
PrintHeader (pbits, pbytes, plimbs)
Definition at line 40 of file AsmMultCodegenerator_PIC.py.
def PrintHeader(pbits, pbytes, plimbs):
    S = ".intel_syntax noprefix\n\n"
    S = S + ".section .rodata\n\n"
    S = S + ".set pbits," + str(pbits) + "\n"
    S = S + ".set pbytes," + str(pbytes) + "\n"
    S = S + ".set plimbs," + str(plimbs) + "\n\n"
    print(S)
    return S
#//////////////////////////////////////////////////////////////////
Referenced by Print_Assembly().
PrintMul()
PrintMul (pbytes, pwords)
Definition at line 184 of file AsmMultCodegenerator_PIC.py.
def PrintMul(pbytes, pwords):
    Reg_Ar = ["rbx", "rcx"]
    S = ".global fp_mul2\nfp_mul2:\n  mov rdx, rdi\n.global fp_mul\nfp_mul:\n  push rbp\n  push rbx\n  push r14\n\n"
    #S = S +"  incq [rip + fpmul]  /* increasing number of multiplications performed */\n\n"
    S = S + "  sub rsp, " + str(pbytes + 16) + "\n  mov [rsp+ " + str(pbytes+8) + "],rdi\n  mov rdi,rsi\n  mov rsi,rdx\n\n\n"
    S = S + "  xor rax,rax\n"
    N = pbytes
    for i in range(0,N+1,8):
        S = S + "  mov [rsp+" + str(i) + "],rax\n"
    S = S + "\n\n.macro MULSTEP, k, "
    R = ""
    for i in range(0, pwords):
        R = ""
        R = R + "I" + str(i) + ","
        S = S + R
    S = S + "I" + str(pwords) + "\n\n"
    # S = S + "    mov r11,[rsp+\\I0]\n    mov rdx, [rsi +  0]\n    mulx rcx, rdx, [rdi + 8*\\k]\n    add rdx, r11\n    mulx rcx, rdx, [rip + inv_min_p_mod_r]"
    S = S + "    mov r11,[rsp+\\I0]\n    mov rdx, [rsi +  0]\n    mulx rcx, rdx, [rdi + 8*\\k]\n    add rdx, r11\n    mov rax, inv_min_p_mod_r@GOTPCREL[rip]\n    mulx rcx, rdx, [rax]"
    S = S + "\n\n    xor rax, rax /* clear flags */\n\n\n"
    S = S + "    mov r14, p@GOTPCREL[rip]\n    mulx rbx, rax, [r14]\n    adox r11, rax\n    mov [rsp+\\I0], r11\n\n"
    N = pbytes-8
    for i in range(8,N+1,8):
        S = S + "    mov r11,[rsp+\\I" + str(int(i/8)) + "]\n    mulx " + Reg_Ar[(int(i/8) % 2)] + ", rax, [r14 + " + str(i) + "]\n "
        # S = S + "    mov r11,[rsp+\\I" + str(int(i/8)) + "]\n    mulx " + Reg_Ar[(int(i/8) % 2)] + ", rax, [rip + p + " + str(i) + "]\n "
        S = S + "   adcx r11, " + Reg_Ar[-(int(i/8) % 2) +1] + "\n   adox r11, rax\n    mov [rsp+\\I" + str(int(i/8)) + "],r11\n\n"
    S = S + "\n    mov r11,[rsp+\\I" + str(pwords) + "]\n    mov rax, 0\n    adcx r11, rcx\n    adox r11, rax\n    mov [rsp+\\I" + str(pwords) + "],r11\n\n"
    S = S + "    mov rdx, [rdi + 8*\\k]\n\n    xor rax, rax /* clear flags */\n\n"
    S = S + "    mov r11,[rsp+\\I0]\n    mulx rbx, rax, [rsi +  0]\n    adox r11, rax\n    mov [rsp+\\I0],r11\n\n"
    for i in range(8,N+1,8):
        S = S + "    mov r11,[rsp+\\I" + str(int(i/8)) + "]\n    mulx " + Reg_Ar[int(i/8) % 2] + ", rax, [rsi +  " + str(i) + "]\n"
        S = S + "    adcx r11, " + Reg_Ar[-(int(i/8) % 2) +1] + "\n    adox r11, rax\n    mov [rsp+\\I" + str(int(i/8)) + "],r11\n\n"
    S = S + "    mov r11,[rsp+\\I" + str(pwords) + "]\n    mov rax, 0\n    adcx r11, rcx\n    adox r11, rax\n    mov [rsp+\\I" + str(pwords) + "],r11\n\n.endm\n\n"
    T = ""
    for i in range(0, pwords):
        T = T + "MULSTEP " + str(i) + ","
        for j in range(8,pbytes+1,8):
            T = T + str((j + i*8) % (pbytes + 8)) + ","
        S = S + T
        T = ""
        S = S + str((pbytes +8 + i*8) % (pbytes + 8)) + "\n"
    S = S + "\n\n    mov rdi,[rsp+" + str(pbytes+8) + "]\n\n"
    for i in range(0,N+1,8):
        S = S + "    mov r11,[rsp+" + str(i) + "]\n    mov [rdi+" + str(i) + "],r11\n"
    S = S + "    add rsp," + str(pbytes+16) + "\n\n    pop r14\n    pop rbx\n    pop rbp\n\n    jmp .reduce_once\n\n\n"
    # S = S + ".global fp_sq1\nfp_sq1:\n    mov rsi, rdi\n.global fp_sqr\nfp_sqr:\n    mov rdx, rsi\n\n    decq [rip + fpmul]\n    incq [rip + fpsqr]\n\n    jmp fp_mul\n"
    S = S + ".global fp_sq1\nfp_sq1:\n    mov rsi, rdi\n.global fp_sqr\nfp_sqr:\n    mov rdx, rsi\n\n    jmp fp_mul\n"
    print(S)
    return S
#////////////////////////////////////////
Referenced by Print_Assembly().
PrintOthers()
PrintOthers ()
Definition at line 275 of file AsmMultCodegenerator_PIC.py.
def PrintOthers():
    # S = ".global fp_inv\nfp_inv:\n    mov r14, p_minus_2@GOTPCREL[rip]\n    lea rsi, [r14]\n    jmp fp_pow\n\n\n"
    # S = S + ".global fp_issquare\nfp_issquare:\n    push rdi\n    mov rax, p_minus_1_halves@GOTPCREL[rip]\n    lea rsi, [rax]\n    call fp_pow\n    pop rdi\n\n"
    # S = S + "    xor rax, rax\n    mov r12, fp_1@GOTPCREL[rip]\n    .set k, 0\n    .rept plimbs\n        mov rsi, [rdi + 8*k]\n        xor rsi, [r12 + 8*k]\n        or rax, rsi\n"
    # # S = S + "    xor rax, rax\n    mov r12, fp_1@GOTPCREL[rip]\n    .set k, 0\n    .rept plimbs\n        mov rsi, [rdi + 8*k]\n        mov r13, [r12 + 8*k]\n        xor rsi, r13\n        or rax, rsi\n"
    # #S = S + "    xor rax, rax\n    .set k, 0\n    .rept plimbs\n        mov rsi, [rdi + 8*k]\n        xor rsi, [rip + fp_1 + 8*k]\n        or rax, rsi\n"
    # S = S + "         .set k, k+1\n    .endr\n    test rax, rax\n    setz al\n    movzx rax, al\n    ret\n\n\n"
    S = ".global fp_random\nfp_random:\n\n    push rdi\n    mov rsi, pbytes\n    call randombytes\n    pop rdi\n"
    S = S + "    mov rax, 1\n    shl rax, (pbits % 64)\n    dec rax\n    and [rdi + pbytes-8], rax\n    mov r8, p@GOTPCREL[rip]\n    .set k, plimbs-1\n    .rept plimbs\n"
    S = S + "        mov rax, [r8 + 8*k]\n        cmp [rdi + 8*k], rax\n        jge fp_random\n        jl 0f\n        .set k, k-1\n    .endr\n    0:\n    ret"
    print(S)
    return S
#////////////////////////////////////////
Referenced by Print_Assembly().
PrintPow()
PrintPow (pwords)
Definition at line 258 of file AsmMultCodegenerator_PIC.py.
def PrintPow(pwords):
    S = ".global fp_pow\nfp_pow:\n    push rbx\n    mov rbx, rsi\n    push r12\n    push r13\n    push rdi\n    sub rsp, pbytes\n\n"
    S = S + "    mov rsi, rdi\n    mov rdi, rsp\n    call fp_copy\n\n    mov rdi, [rsp + pbytes]\n    mov r14, fp_1@GOTPCREL[rip]\n    lea rsi, [r14]\n    call fp_copy\n\n"
    S = S + ".macro POWSTEP, k\n        mov r13, [rbx + 8*\\k]\n        xor r12, r12\n\n"
    S = S + "        0:\n        test r13, 1\n        jz 1f\n\n        mov rdi, [rsp + pbytes]\n        mov rsi, rsp\n        call fp_mul2\n\n"
    S = S + "        1:\n        mov rdi, rsp\n        call fp_sq1\n\n        shr r13\n\n                inc r12\n                test r12, 64\n        jz 0b\n.endm\n\n"
    for i in range(0, pwords):
        S = S + "    POWSTEP " + str(i) + "\n"
    S = S + "    add rsp, pbytes+8\n    pop r13\n    pop r12\n    pop rbx\n    ret\n\n\n"
    print(S)
    return S
#////////////////////////////////////////
PrintRedOnce()
PrintRedOnce (pbytes)
Definition at line 119 of file AsmMultCodegenerator_PIC.py.
def PrintRedOnce(pbytes):
    # Reg_Ar = ["rdi", "rsi", "rdx", "rcx", "r8", "r9", "r10", "r11"]
    Reg_Ar = ["rdi", "rsi", "rdx", "rcx", "r8", "r9", "r10", "r11"]
    S = ".reduce_once:\n    push rbp\n    push r12\n    push r13\n    mov rbp, rdi\n    mov r12, p@GOTPCREL[rip]\n\n    mov rdi, [rbp +  0]\n    sub rdi, [r12]\n"
    N = pbytes-8
    for i in range(8,N+1,8):
        # S = S + "    mov " + Reg_Ar[(int(i/8) % 8)] + ", [rbp +  " + str(i) + "]\n    mov r13, [r12 + " + str(i) + "]\n    sbb " +  Reg_Ar[(int(i/8) % 8)] + ", r13\n"
        S = S + "    mov " + Reg_Ar[(int(i/8) % 8)] + ", [rbp +  " + str(i) + "]\n    sbb " +  Reg_Ar[(int(i/8) % 8)] + ", [r12 + " + str(i) + "]\n"
        if ((int((i+8)/8)%8) == 0) and (i != 0):
            S = S + "\n"
    S = S + "\n    setnc al\n    movzx rax, al\n    neg rax\n\n"
    S = S + ".macro cswap2, r, m\n    xor \\r, \\m\n    and \\r, rax\n    xor \\m, \\r\n.endm\n\n\n"
    n = -(int(pbytes/8) % 8) +8
    for i in range(1, n+1):
        S = S + "    cswap2 " + Reg_Ar[i-1] + ", [rbp +  " + str((pbytes-n*8)+(i-1)*8) + "]\n"
    N = N - (n*8)
    M = math.ceil(N/64)
    for j in range(1, M+1):
        S = S + "\n    mov rdi, [rbp +  0]\n    sub rdi, [r12]\n"
        for i in range(8,N+1,8):
            # S = S + "    mov " + Reg_Ar[int(i/8) % 8] + ", [rbp +  " + str(i) + "]\n    sbb " + Reg_Ar[int(i/8) % 8] + ",  [rip + p + " + str(i) + "]\n"
            S = S + "    mov " + Reg_Ar[int(i/8) % 8] + ", [rbp +  " + str(i) + "]\n    sbb " + Reg_Ar[int(i/8) % 8] + ", [r12 + " + str(i) + "]\n"
            if ((int((i+8)/8)%8) == 0) and (i != 0):
                S = S + "\n"
        for i in range(1,9):
            S = S + "    cswap2 " + Reg_Ar[i-1] + ", [rbp +  " + str((N-64)+i*8) + "]\n"
        N = N - 64
    S = S + "    pop r13\n    pop r12\n    pop rbp\n    ret\n\n"
    print(S)
    return S
#////////////////////////////////////////
Referenced by Print_Assembly().
PrintSub()
PrintSub ()
Definition at line 164 of file AsmMultCodegenerator_PIC.py.
def PrintSub():
    S= ".global fp_add2\nfp_add2:\n  mov rdx, rdi\n\n"
    # S = S + ".global fp_add\nfp_add:\n  push rdi\n  call uintbig_add\n  pop rdi\n\n  incq [rip + fpadd]\n\n  jmp .reduce_once\n\n"
    S = S + ".global fp_add\nfp_add:\n  push rdi\n  call uintbig_add\n  pop rdi\n\n  jmp .reduce_once\n\n"
    S = S + ".global fp_sub2\nfp_sub2:\n  mov rdx, rdi\n  xchg rsi, rdx\n\n.global fp_sub\nfp_sub:\n  push rdi\n  call uintbig_sub\n  pop rdi\n\n\n"
    # S = S + "  incq [rip + fpadd]  /* increasing number of additions performed */\n\n  neg rax\n\n  sub rsp, pbytes\n\n"
    S = S + "  neg rax\n\n  sub rsp, pbytes\n\n"
    S = S + "  mov r8, p@GOTPCREL[rip]\n  mov rcx, [r8]\n  and rcx, rax\n  mov [rsp + 0],rcx\n  .set k, 1\n  .rept plimbs-1\n      mov rcx, [r8 + 8*k]\n      and rcx, rax\n"
    # S = S + "  mov r8, p@GOTPCREL[rip]\n  mov rcx, [r8]\n  and rcx, rax\n  mov [rsp + 0],rcx\n  .set k, 1\n  .rept plimbs-1\n      mov r13, [r8 + 8*k]\n      mov rcx, r13\n      and rcx, rax\n"
    S = S + "      mov [rsp + 8*k], rcx\n      .set k, k+1\n  .endr\n\n"
    S = S + "  mov rcx, [rsp +  0]\n  add rcx, [rdi +  0]\n  mov [rdi +  0], rcx\n  .set k, 1\n  .rept plimbs-1\n      mov rcx, [rsp + 8*k]\n"
    S = S + "      adc rcx, [rdi + 8*k]\n      mov [rdi + 8*k], rcx\n      .set k, k+1\n  .endr\n\n  add rsp, pbytes\n  ret\n\n\n"
    S = S + "/* Montgomery arithmetic */\n\n.global fp_enc\nfp_enc:\n    mov r8, r_squared_mod_p@GOTPCREL[rip]\n    lea rdx, [r8]\n    jmp fp_mul\n\n"
    S = S + ".global fp_dec\nfp_dec:\n    mov r8, uintbig_1@GOTPCREL[rip]\n    lea rdx, [r8]\n    jmp fp_mul\n\n\n"
    print(S)
    return S
#////////////////////////////////////////
Referenced by Print_Assembly().
PrintUintHeader()
PrintUintHeader (plimbs)
Definition at line 51 of file AsmMultCodegenerator_PIC.py.
def PrintUintHeader(plimbs):
    S = ".intel_syntax noprefix\n\n"
    S = S + ".section .rodata\n\n"
    S = S + ".global uintbig_1\nuintbig_1:\n"
    S = S + "    .quad 1, 0, 0, 0\n"
    N = (plimbs//4) -1;
    for i in range(1, N+1):
        S = S + "    .quad 0, 0, 0, 0\n"
    N = plimbs%4;
    if (N != 0):
        S = S + "    .quad"
        for i in range(1,N):
                S = S + " 0,"
        S = S + "0\n"
    S = S + ".section .text\n\n"
    S = S + ".global uintbig_add\nuintbig_add:\n    mov rax, [rsi +  0]\n    add rax, [rdx +  0]\n    mov [rdi +  0], rax\n    .set k, 1\n"
    S = S + "    .rept " + str(plimbs-1) + "\n"
    S = S + "mov rax, [rsi + 8*k]\n        adc rax, [rdx + 8*k]\n        mov [rdi + 8*k], rax\n        .set k, k+1\n    .endr\n    setc al\n    movzx rax, al\n    ret\n\n"
    S = S + ".global uintbig_sub\nuintbig_sub:\n    mov rax, [rsi +  0]\n    sub rax, [rdx +  0]\n    mov [rdi +  0], rax\n    .set k, 1\n"
    S = S + "    .rept " + str(plimbs-1) + "\n"
    S = S + "      mov rax, [rsi + 8*k]\n        sbb rax, [rdx + 8*k]\n        mov [rdi + 8*k], rax\n        .set k, k+1\n    .endr\n    setc al\n    movzx rax, al\n    ret"
    print(S)
    return 0
#////////////////////////////////////////
Referenced by main().
WordExtractor()
WordExtractor (p, pwords, Var)
Definition at line 12 of file AsmMultCodegenerator_PIC.py.
def WordExtractor(p, pwords, Var):
    k = 64
    PWord = []
    S =  ".global " + Var + "\n" + Var + ":\n"
    pp = p
    for i in range(1,pwords+1):
        if (((i - 1)%4) == 0):
            S = S + ".quad "
        #PWord[i] = pp%2**k
        PWord.append(pp%2**k)
        if((i%4) != 0):
            #S = S + str(hex(PWord[i-1])).upper() + ","
            S = S + "0x{:X}".format(PWord[i-1]) +  ","
        else:
            #S = S + str(hex(PWord[i-1])).upper() + " \n"
            S = S + "0x{:X}".format(PWord[i-1]) +  " \n"
        pp = pp // (2**k)
    S =  S + "\n\n"
    print(S)
    return S
#//////////////////////////////////////////////////////////////////
References if.
Referenced by Print_Parameters().
Variable Documentation
p_2047d221
int p_2047d221 = 0x5160D4543A2596D320C080B284C0FA5D3600AE4E29B85374858B238036139EA0B8B0C8B2850475382865FD4C9F7C3B5E531ED7D0FC022A13270300584EC78190FD09755A56CFEB1FC6961581CDFC56E824D0F31C4D4ECF04C5243CA0651820AF413023A7310203F74858FBECACA26B375BEBA9DE78CC420A069477B7FE595F83B148223C6841B3592C74AF79F39AE8F3D64F8B9FC946BB1C84A4541CBC2F363029B2C1E296158774A9646D2E186AD699B304FC7311F0DEC85E651756DDB4E3888D02333D591583AE5DB2F656E63A6179CDB059ED9BF90BAD614DCA5628C940C5004D99FB1CB03CE478F65726B12E42FA1C7C8FFFFFFFFFFFFFFFFFFFFFFFFFFF
Definition at line 390 of file AsmMultCodegenerator_PIC.py.
p_2047k221
int p_2047k221 = 0x4f49aaf26e4aefb626bb94dc36fd0732eff9ff84c9b3b1b49c85afe27f67725f25d9e24a0748378bdebd472aa103a02b9c3c0fc3740c26d882af03859d69962d0ce8ad54d154c156241fe343116b31776c0e7aab1bf721dfac0073a2b919b0a4b543b329bed97c9490c340c95add5f8c457afa1ae8c5352a05816da706eb3cab844d51d759b0c53089a678df7aae625ba90481e7927800a6ac53715e3b7b996293f4fab37d61640dffc6c6b2579b25d1d51310e46e8c2b097835f78ebc56ce0c478af769ae62b6e0f6d3630a6ebae5ed1a549b7f4b8f58f1f61fe1a2e6d6cac6c5a05e7d325440ecfc70c3714d157138c90a04ffffffffffffffffffffffffff
Definition at line 392 of file AsmMultCodegenerator_PIC.py.
p_2047n221
int p_2047n221 = 0x459AEF6A877E5ADAA0902C6A81793F136D3E606CECECC229616377E3B9C4A5630F19ADD54D8C5523E1A3AED0A5CB129A69220DB334EFF4A66BFA495ACCBFA7A31B1097D145C0FB10A0427AD5EE55DA93D7B04D72732719ACF7C00FC0BCDC2ADD1DCC5DD91163C9547109B0A8A65EC1BDEB34774FB24FE7A88EEC915BE40A0402A3D8A48E8371EC94456DE1CB00A2F8C07FAF5AACAB12ED8E6C81F4CD3BFE4FB5C3A08FCD2434148F82FEEC069F4509398AEDB078EAD657ED2D3BB68D87A80459D590CF47C1CD12CFE0A33DE40AB61EC18AD9791E0024F0E7EF3E782F87E2823D2B205845C6ED21AEB7E8298551D41019334FFFFFFFFFFFFFFFFFFFFFFFFFFFFF
Definition at line 391 of file AsmMultCodegenerator_PIC.py.
p_2048
int p_2048 = p_2047k221
Definition at line 436 of file AsmMultCodegenerator_PIC.py.
p_4095d221
int p_4095d221 = 
Definition at line 396 of file AsmMultCodegenerator_PIC.py.
p_4095k256
int p_4095k256 = 
Definition at line 400 of file AsmMultCodegenerator_PIC.py.
p_4095n221
int p_4095n221 = 
Definition at line 398 of file AsmMultCodegenerator_PIC.py.
p_4096
int p_4096 = p_4095k256
Definition at line 437 of file AsmMultCodegenerator_PIC.py.
p_5119d256
int p_5119d256 = 
Definition at line 402 of file AsmMultCodegenerator_PIC.py.
p_5119k234
int p_5119k234 = 
Definition at line 407 of file AsmMultCodegenerator_PIC.py.
p_5119n234
int p_5119n234 = 
Definition at line 404 of file AsmMultCodegenerator_PIC.py.
p_512
int p_512 = p_512k256
Definition at line 450 of file AsmMultCodegenerator_PIC.py.
p_5120
int p_5120 = p_5119k234
Definition at line 438 of file AsmMultCodegenerator_PIC.py.
p_512k256
int p_512k256 = 0x65b48e8f740f89bffc8ab0d15e3e4c4ab42d083aedc88c425afbfcc69322c9cda7aac6c567f35507516730cc1f0b4f25c2721bf457aca8351b81b90533c6c87b
Definition at line 428 of file AsmMultCodegenerator_PIC.py.
p_6143d306
int p_6143d306 = 
Definition at line 409 of file AsmMultCodegenerator_PIC.py.
p_6143k256
int p_6143k256 = 
Definition at line 413 of file AsmMultCodegenerator_PIC.py.
p_6143n234
int p_6143n234 = 
Definition at line 411 of file AsmMultCodegenerator_PIC.py.
p_6144
int p_6144 = p_6143k256
Definition at line 446 of file AsmMultCodegenerator_PIC.py.
p_8191d306
int p_8191d306 = 
Definition at line 415 of file AsmMultCodegenerator_PIC.py.
p_8191k332
int p_8191k332 = 
Definition at line 420 of file AsmMultCodegenerator_PIC.py.
p_8191n332
int p_8191n332 = 
Definition at line 417 of file AsmMultCodegenerator_PIC.py.
p_8192
int p_8192 = p_8191k332
Definition at line 447 of file AsmMultCodegenerator_PIC.py.
p_9215d384
int p_9215d384 = 
Definition at line 422 of file AsmMultCodegenerator_PIC.py.
p_9215k384
int p_9215k384 = 
Definition at line 426 of file AsmMultCodegenerator_PIC.py.
p_9215n332
int p_9215n332 = 
Definition at line 424 of file AsmMultCodegenerator_PIC.py.
p_9216
int p_9216 = p_9215k384
Definition at line 448 of file AsmMultCodegenerator_PIC.py.