Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: LegacySpecifier Class Reference
LegacySpecifier Class Reference
Public Member Functions
None __init__ (self, str spec="", Optional[bool] prereleases=None)
Public Member Functions inherited from _IndividualSpecifier
None __init__ (self, str spec="", Optional[bool] prereleases=None)
str __repr__ (self)
str __str__ (self)
int __hash__ (self)
bool __eq__ (self, object other)
str operator (self)
str version (self)
Optional[bool] prereleases (self)
None prereleases (self, bool value)
bool __contains__ (self, str item)
bool contains (self, UnparsedVersion item, Optional[bool] prereleases=None)
Iterable[VersionTypeVar] filter (self, Iterable[VersionTypeVar] iterable, Optional[bool] prereleases=None)
Public Member Functions inherited from BaseSpecifier
str __str__ (self)
int __hash__ (self)
bool __eq__ (self, object other)
Protected Member Functions
LegacyVersion _coerce_version (self, UnparsedVersion version)
bool _compare_equal (self, LegacyVersion prospective, str spec)
bool _compare_not_equal (self, LegacyVersion prospective, str spec)
bool _compare_less_than_equal (self, LegacyVersion prospective, str spec)
bool _compare_greater_than_equal (self, LegacyVersion prospective, str spec)
bool _compare_less_than (self, LegacyVersion prospective, str spec)
bool _compare_greater_than (self, LegacyVersion prospective, str spec)
Protected Member Functions inherited from _IndividualSpecifier
Tuple[str, str] _canonical_spec (self)
CallableOperator _get_operator (self, str op)
Static Protected Attributes
str _regex_str
Static Protected Attributes inherited from _IndividualSpecifier
dict _operators = {}
Pattern _regex [str]
Additional Inherited Members
Data Fields inherited from _IndividualSpecifier
version
Protected Attributes inherited from _IndividualSpecifier
tuple _spec
Optional[bool] _prereleases = prereleases
Tuple[str, str] _canonical_spec
Detailed Description
Definition at line 227 of file specifiers.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, str spec = "", Optional[bool] prereleases = None)
Definition at line 252 of file specifiers.py.
    def __init__(self, spec: str = "", prereleases: Optional[bool] = None) -> None:
        super().__init__(spec, prereleases)
        warnings.warn(
            "Creating a LegacyVersion has been deprecated and will be "
            "removed in the next major release",
            DeprecationWarning,
        )
References __init__().
Referenced by __init__().
Member Function Documentation
_coerce_version()
LegacyVersion _coerce_version (self, UnparsedVersion version) protected
Reimplemented from _IndividualSpecifier.
Definition at line 261 of file specifiers.py.
    def _coerce_version(self, version: UnparsedVersion) -> LegacyVersion:
        if not isinstance(version, LegacyVersion):
            version = LegacyVersion(str(version))
        return version
_compare_equal()
bool _compare_equal (self, LegacyVersion prospective, str spec) protected
Definition at line 266 of file specifiers.py.
    def _compare_equal(self, prospective: LegacyVersion, spec: str) -> bool:
        return prospective == self._coerce_version(spec)
References _IndividualSpecifier._coerce_version().
Referenced by Specifier._compare_not_equal().
_compare_greater_than()
bool _compare_greater_than (self, LegacyVersion prospective, str spec) protected
Definition at line 283 of file specifiers.py.
    def _compare_greater_than(self, prospective: LegacyVersion, spec: str) -> bool:
        return prospective > self._coerce_version(spec)
References _IndividualSpecifier._coerce_version().
_compare_greater_than_equal()
bool _compare_greater_than_equal (self, LegacyVersion prospective, str spec) protected
Definition at line 275 of file specifiers.py.
    ) -> bool:
        return prospective >= self._coerce_version(spec)
References _IndividualSpecifier._coerce_version().
_compare_less_than()
bool _compare_less_than (self, LegacyVersion prospective, str spec) protected
Definition at line 280 of file specifiers.py.
    def _compare_less_than(self, prospective: LegacyVersion, spec: str) -> bool:
        return prospective < self._coerce_version(spec)
References _IndividualSpecifier._coerce_version().
_compare_less_than_equal()
bool _compare_less_than_equal (self, LegacyVersion prospective, str spec) protected
Definition at line 272 of file specifiers.py.
    def _compare_less_than_equal(self, prospective: LegacyVersion, spec: str) -> bool:
        return prospective <= self._coerce_version(spec)
References _IndividualSpecifier._coerce_version().
_compare_not_equal()
bool _compare_not_equal (self, LegacyVersion prospective, str spec) protected
Definition at line 269 of file specifiers.py.
    def _compare_not_equal(self, prospective: LegacyVersion, spec: str) -> bool:
        return prospective != self._coerce_version(spec)
References _IndividualSpecifier._coerce_version().
Field Documentation
_regex_str
str _regex_str static protected
Initial value:
=  r"""
        (?P<operator>(==|!=|<=|>=|<|>))
        \s*
        (?P<version>
            [^,;\s)]* # Since this is a "legacy" specifier, and the version
                      # string can be just about anything, we match everything
                      # except for whitespace, a semi-colon for marker support,
                      # a closing paren since versions can be enclosed in
                      # them, and a comma since it's a version separator.
        )
        """
Definition at line 229 of file specifiers.py.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/packaging/specifiers.py