Let us walk on the 3-isogeny graph: pip._vendor.urllib3.filepost Namespace Reference
pip._vendor.urllib3.filepost Namespace Reference
Functions
choose_boundary ()
iter_field_objects (fields)
iter_fields (fields)
encode_multipart_formdata (fields, boundary=None)
Variables
writer = codecs.lookup("utf-8")[3]
Function Documentation
choose_boundary()
choose_boundary ()
Our embarrassingly-simple replacement for mimetools.choose_boundary.
Definition at line 15 of file filepost.py.
def choose_boundary():
    """
    Our embarrassingly-simple replacement for mimetools.choose_boundary.
    """
    boundary = binascii.hexlify(os.urandom(16))
    if not six.PY2:
        boundary = boundary.decode("ascii")
    return boundary
References i.
Referenced by pip._vendor.urllib3.filepost.encode_multipart_formdata().
encode_multipart_formdata()
encode_multipart_formdata (fields, boundary = None)
Encode a dictionary of ``fields`` using the multipart/form-data MIME format.
:param fields:
    Dictionary of fields or list of (key, :class:`~urllib3.fields.RequestField`).
:param boundary:
    If not specified, then a random boundary will be generated using
    :func:`urllib3.filepost.choose_boundary`.
Definition at line 63 of file filepost.py.
def encode_multipart_formdata(fields, boundary=None):
    """
    Encode a dictionary of ``fields`` using the multipart/form-data MIME format.
    :param fields:
        Dictionary of fields or list of (key, :class:`~urllib3.fields.RequestField`).
    :param boundary:
        If not specified, then a random boundary will be generated using
        :func:`urllib3.filepost.choose_boundary`.
    """
    body = BytesIO()
    if boundary is None:
        boundary = choose_boundary()
    for field in iter_field_objects(fields):
        body.write(b("--%s\r\n" % (boundary)))
        writer(body).write(field.render_headers())
        data = field.data
        if isinstance(data, int):
            data = str(data)  # Backwards compatibility
        if isinstance(data, six.text_type):
            writer(body).write(data)
        else:
            body.write(data)
        body.write(b"\r\n")
    body.write(b("--%s--\r\n" % (boundary)))
    content_type = str("multipart/form-data; boundary=%s" % boundary)
    return body.getvalue(), content_type
References pip._vendor.urllib3.filepost.choose_boundary(), i, pip._vendor.urllib3.filepost.iter_field_objects(), and pip._vendor.urllib3.filepost.writer.
iter_field_objects()
iter_field_objects (fields)
Iterate over fields.
Supports list of (k, v) tuples and dicts, and lists of
:class:`~urllib3.fields.RequestField`.
Definition at line 25 of file filepost.py.
def iter_field_objects(fields):
    """
    Iterate over fields.
    Supports list of (k, v) tuples and dicts, and lists of
    :class:`~urllib3.fields.RequestField`.
    """
    if isinstance(fields, dict):
        i = six.iteritems(fields)
    else:
        i = iter(fields)
    for field in i:
        if isinstance(field, RequestField):
            yield field
        else:
            yield RequestField.from_tuples(*field)
References i.
Referenced by pip._vendor.urllib3.filepost.encode_multipart_formdata().
iter_fields()
iter_fields (fields)
.. deprecated:: 1.6
Iterate over fields.
The addition of :class:`~urllib3.fields.RequestField` makes this function
obsolete. Instead, use :func:`iter_field_objects`, which returns
:class:`~urllib3.fields.RequestField` objects.
Supports list of (k, v) tuples and dicts.
Definition at line 45 of file filepost.py.
def iter_fields(fields):
    """
    .. deprecated:: 1.6
    Iterate over fields.
    The addition of :class:`~urllib3.fields.RequestField` makes this function
    obsolete. Instead, use :func:`iter_field_objects`, which returns
    :class:`~urllib3.fields.RequestField` objects.
    Supports list of (k, v) tuples and dicts.
    """
    if isinstance(fields, dict):
        return ((k, v) for k, v in six.iteritems(fields))
    return ((k, v) for k, v in fields)
References i.
Variable Documentation
writer
writer = codecs.lookup("utf-8")[3]
Definition at line 12 of file filepost.py.
Referenced by pip._vendor.urllib3.filepost.encode_multipart_formdata().