Let us walk on the 3-isogeny graph: pip._vendor.cachecontrol._cmd Namespace Reference
pip._vendor.cachecontrol._cmd Namespace Reference
Functions
setup_logging ()
get_session ()
get_args ()
main (args=None)
Function Documentation
get_args()
get_args ()
Definition at line 34 of file _cmd.py.
def get_args():
    parser = ArgumentParser()
    parser.add_argument("url", help="The URL to try and cache")
    return parser.parse_args()
References i.
Referenced by pip._vendor.cachecontrol._cmd.main().
get_session()
get_session ()
Definition at line 22 of file _cmd.py.
def get_session():
    adapter = CacheControlAdapter(
        DictCache(), cache_etags=True, serializer=None, heuristic=None
    )
    sess = requests.Session()
    sess.mount("http://", adapter)
    sess.mount("https://", adapter)
    sess.cache_controller = adapter.controller
    return sess
References i.
Referenced by pip._vendor.cachecontrol._cmd.main().
main()
main (args = None)
Definition at line 40 of file _cmd.py.
def main(args=None):
    args = get_args()
    sess = get_session()
    # Make a request to get a response
    resp = sess.get(args.url)
    # Turn on logging
    setup_logging()
    # try setting the cache
    sess.cache_controller.cache_response(resp.request, resp.raw)
    # Now try to get it
    if sess.cache_controller.cached_request(resp.request):
        print("Cached!")
    else:
        print("Not cached :(")
References pip._vendor.cachecontrol._cmd.get_args(), pip._vendor.cachecontrol._cmd.get_session(), i, and pip._vendor.cachecontrol._cmd.setup_logging().
setup_logging()
setup_logging ()
Definition at line 16 of file _cmd.py.
def setup_logging():
    logger.setLevel(logging.DEBUG)
    handler = logging.StreamHandler()
    logger.addHandler(handler)
References i.
Referenced by pip._vendor.cachecontrol._cmd.main().