Let us walk on the 3-isogeny graph: /home/liwuen/projects_dev/pqc-engineering-ssec-23/high-level-scripts/j-invariants.m File Reference
j-invariants.m File Reference
Functions
assert (var1 eq var2)
id c6 ()
Variables
clear
function j_invariant(a1, a3, a2, a4, a6) b2 b4
b6 __pad0__
b8 __pad1__
Disc __pad2__
c4 __pad3__
c6 __pad4__
var1 __pad5__
var2 __pad6__
return c4
end function
Pt< t > __pad7__
Ru< u > __pad8__
Px< x > __pad9__
Ri< i > __pad10__
Ra< a1, a3, alpha > __pad11__
Ra< a1, a3, alpha > zeta3
alpha_ __pad12__
_alpha __pad13__
num
den __pad14__
den a3
den fac_num
assert num div &* fk [2]
fac_den __pad15__
Function Documentation
assert()
assert (var1 eq var2)
Referenced by random_walks3::cgl_hash3(), cofactor_multiples(), hdr_code::cube_root(), fp2_test(), basefield_chain3::get_order3_points_fp(), main(), main(), poly_mul_high(), poly_mul_low(), poly_mul_mid(), poly_mul_selfreciprocal(), hdr_code::print_parameters(), psnip_clock_get_time(), basefield_chain3::radical_walk3(), random_boundedl1(), setup::setup_fp(), setup::setup_fq(), setup::sqrt_fp(), setup::sqrt_fp2(), tests::test_3div_poly(), random_walks2::to_mont(), xISOG_matryoshka(), and xISOG_old().
c6()
id c6 () virtual
Referenced by int32_sort().
Variable Documentation
__pad0__
b6 __pad0__
Definition at line 5 of file j-invariants.m.
__pad10__
Ri<i> __pad10__
Definition at line 17 of file j-invariants.m.
__pad11__
Ra<a1, a3, alpha> __pad11__
Definition at line 17 of file j-invariants.m.
__pad12__
alpha_ __pad12__
Definition at line 26 of file j-invariants.m.
__pad13__
_alpha __pad13__
Definition at line 27 of file j-invariants.m.
__pad14__
den __pad14__
Definition at line 29 of file j-invariants.m.
__pad15__
fac_den __pad15__
Definition at line 32 of file j-invariants.m.
__pad1__
b8 __pad1__
Definition at line 6 of file j-invariants.m.
__pad2__
Disc __pad2__
Definition at line 7 of file j-invariants.m.
__pad3__
c4 __pad3__
Definition at line 9 of file j-invariants.m.
__pad4__
c6 __pad4__
Definition at line 10 of file j-invariants.m.
__pad5__
var1 __pad5__
Definition at line 12 of file j-invariants.m.
__pad6__
var2 __pad6__
Definition at line 13 of file j-invariants.m.
__pad7__
Pt<t> __pad7__
Definition at line 17 of file j-invariants.m.
__pad8__
Ru<u> __pad8__
Definition at line 17 of file j-invariants.m.
__pad9__
Px<x> __pad9__
Definition at line 17 of file j-invariants.m.
a3
_den a3
Definition at line 29 of file j-invariants.m.
Referenced by cgl_hash_digest_3(), int32_sort(), and isogeny_walks_3().
b4
function j_invariant (a1, a3, a2, a4, a6) b2 b4
Definition at line 4 of file j-invariants.m.
Referenced by int32_sort().
c4
return c4
Definition at line 16 of file j-invariants.m.
Referenced by int32_sort().
clear
clear
Definition at line 1 of file j-invariants.m.
fac_num
den fac_num
Definition at line 30 of file j-invariants.m.
fk
assert num div&* fk[2]
Definition at line 31 of file j-invariants.m.
function
end function
Definition at line 17 of file j-invariants.m.
Referenced by pip._vendor.webencodings.tests::assert_raises().
num
num
Definition at line 29 of file j-invariants.m.
Referenced by isogeny_to_montgomery(), isogeny_to_montgomery(), isogeny_walks_switch_from_model_3(), and random_coin().
zeta3
Ra<a1, a3, alpha> zeta3
Definition at line 25 of file j-invariants.m.