Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Forward Class Reference
Forward Class Reference
Public Member Functions
__init__ (self, typing.Optional[Union[ParserElement, str]] other=None)
"Forward" __lshift__ (self, other)
"Forward" __ilshift__ (self, other)
"ParserElement" __or__ (self, other)
__del__ (self)
parseImpl (self, instring, loc, doActions=True)
ParserElement leave_whitespace (self, bool recursive=True)
ParserElement ignore_whitespace (self, bool recursive=True)
ParserElement streamline (self)
None validate (self, validateTrace=None)
ParserElement copy (self)
leaveWhitespace (self)
ignoreWhitespace (self)
Public Member Functions inherited from ParseElementEnhance
__init__ (self, Union[ParserElement, str] expr, bool savelist=False)
List[ParserElement] recurse (self)
ParserElement ignore (self, other)
Public Member Functions inherited from ParserElement
using_each (cls, seq, **class_kwargs)
__init__ (self, bool savelist=False)
"ParserElement" suppress_warning (self, Diagnostics warning_type)
visit_all (self)
"ParserElement" set_results_name (self, str name, bool list_all_matches=False, *, bool listAllMatches=False)
"ParserElement" set_break (self, bool break_flag=True)
"ParserElement" set_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_condition (self, *ParseCondition fns, **kwargs)
"ParserElement" set_fail_action (self, ParseFailAction fn)
int preParse (self, str instring, int loc)
postParse (self, instring, loc, tokenlist)
int try_parse (self, str instring, int loc, *, bool raise_fatal=False, bool do_actions=False)
bool can_parse_next (self, str instring, int loc, bool do_actions=False)
ParseResults parse_string (self, str instring, bool parse_all=False, *, bool parseAll=False)
Generator[Tuple[ParseResults, int, int], None, None] scan_string (self, str instring, int max_matches=_MAX_INT, bool overlap=False, *, bool debug=False, int maxMatches=_MAX_INT)
str transform_string (self, str instring, *, bool debug=False)
ParseResults search_string (self, str instring, int max_matches=_MAX_INT, *, bool debug=False, int maxMatches=_MAX_INT)
Generator[str, None, None] split (self, str instring, int maxsplit=_MAX_INT, bool include_separators=False, *, includeSeparators=False)
"ParserElement" __add__ (self, other)
"ParserElement" __radd__ (self, other)
"ParserElement" __sub__ (self, other)
"ParserElement" __rsub__ (self, other)
"ParserElement" __mul__ (self, other)
"ParserElement" __rmul__ (self, other)
"ParserElement" __or__ (self, other)
"ParserElement" __ror__ (self, other)
"ParserElement" __xor__ (self, other)
"ParserElement" __rxor__ (self, other)
"ParserElement" __and__ (self, other)
"ParserElement" __rand__ (self, other)
"ParserElement" __invert__ (self)
__getitem__ (self, key)
"ParserElement" __call__ (self, typing.Optional[str] name=None)
"ParserElement" suppress (self)
"ParserElement" set_whitespace_chars (self, Union[Set[str], str] chars, bool copy_defaults=False)
"ParserElement" parse_with_tabs (self)
"ParserElement" set_debug_actions (self, DebugStartAction start_action, DebugSuccessAction success_action, DebugExceptionAction exception_action)
"ParserElement" set_debug (self, bool flag=True, bool recurse=False)
str default_name (self)
"ParserElement" set_name (self, str name)
str name (self)
str __str__ (self)
str __repr__ (self)
ParseResults parse_file (self, Union[str, Path, TextIO] file_or_filename, str encoding="utf-8", bool parse_all=False, *, bool parseAll=False)
__eq__ (self, other)
__hash__ (self)
bool matches (self, str test_string, bool parse_all=True, *, bool parseAll=True)
Tuple[bool, List[Tuple[str, Union[ParseResults, Exception]]]] run_tests (self, Union[str, List[str]] tests, bool parse_all=True, typing.Optional[Union["ParserElement", str]] comment="#", bool full_dump=True, bool print_results=True, bool failure_tests=False, typing.Optional[Callable[[str, ParseResults], str]] post_parse=None, typing.Optional[TextIO] file=None, bool with_line_numbers=False, *, bool parseAll=True, bool fullDump=True, bool printResults=True, bool failureTests=False, typing.Optional[Callable[[str, ParseResults], str]] postParse=None)
None create_diagram (self, Union[TextIO, Path, str] output_html, int vertical=3, bool show_results_names=False, bool show_groups=False, bool embed=False, **kwargs)
setResultsName (self)
setBreak (self)
setParseAction (self)
addParseAction (self)
addCondition (self)
setFailAction (self)
tryParse (self)
parseString (self)
scanString (self)
transformString (self)
searchString (self)
setWhitespaceChars (self)
parseWithTabs (self)
setDebugActions (self)
setDebug (self)
setName (self)
parseFile (self)
runTests (self)
Data Fields
caller_frame = traceback.extract_stack(limit=2)[0]
lshift_line = None
Data Fields inherited from ParseElementEnhance
expr = expr
Data Fields inherited from ParserElement
List[ParseAction] parseAction = list()
typing.Optional[ParseFailAction] failAction = None
str customName = None
str resultsName = None
saveAsList = savelist
bool skipWhitespace = True
whiteChars = set(ParserElement.DEFAULT_WHITE_CHARS)
bool copyDefaultWhiteChars = True
bool mayReturnEmpty = False
bool keepTabs = False
List[] ignoreExprs = list()
bool debug = False
bool streamlined = False
bool mayIndexError = True
str errmsg = ""
bool modalResults = True
debugActions = self.DebugActions(None, None, None)
bool callPreparse = True
bool callDuringTry = False
list suppress_warnings_ = []
Protected Member Functions
str _generateDefaultName (self)
_setResultsName (self, name, list_all_matches=False)
Protected Member Functions inherited from ParseElementEnhance
_checkRecursion (self, parseElementList)
Protected Member Functions inherited from ParserElement
int _skipIgnorables (self, str instring, int loc)
Tuple[int, ParseResults] _parseNoCache (self, instring, loc, doActions=True, callPreParse=True)
Tuple[int, ParseResults] _parseCache (self, instring, loc, doActions=True, callPreParse=True)
Additional Inherited Members
Static Public Member Functions inherited from ParserElement
None set_default_whitespace_chars (str chars)
None inline_literals_using (type cls)
None reset_cache ()
None disable_memoization ()
None enable_left_recursion (typing.Optional[int] cache_size_limit=None, *, force=False)
None enable_packrat (int cache_size_limit=128, *, bool force=False)
inlineLiteralsUsing ()
setDefaultWhitespaceChars ()
enableLeftRecursion ()
enablePackrat ()
Static Public Attributes inherited from ParserElement
str DEFAULT_WHITE_CHARS = " \n\t\r"
bool verbose_stacktrace = False
recursion_lock = RLock()
dict recursion_memos = {}
tuple packrat_cache
packrat_cache_lock = RLock()
list packrat_cache_stats = [0, 0]
bool canParseNext = can_parse_next
None resetCache = reset_cache
str defaultName = default_name
Protected Attributes inherited from ParserElement
typing.Optional[str] _defaultName = None
Static Protected Attributes inherited from ParserElement
type _literalStringClass = None
Tuple[int, ParseResults] _parse = _parseNoCache
bool _packratEnabled = False
bool _left_recursion_enabled = False
Detailed Description
Forward declaration of an expression to be defined later -
used for recursive grammars, such as algebraic infix notation.
When the expression is known, it is assigned to the ``Forward``
variable using the ``'<<'`` operator.
Note: take care when assigning to ``Forward`` not to overlook
precedence of operators.
Specifically, ``'|'`` has a lower precedence than ``'<<'``, so that::
    fwd_expr << a | b | c
will actually be evaluated as::
    (fwd_expr << a) | b | c
thereby leaving b and c out as parseable alternatives.  It is recommended that you
explicitly group the values inserted into the ``Forward``::
    fwd_expr << (a | b | c)
Converting to use the ``'<<='`` operator instead will avoid this problem.
See :class:`ParseResults.pprint` for an example of a recursive
parser created using ``Forward``.
Definition at line 5368 of file core.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, typing.Optional[Union[ParserElement, str]] other = None)
Definition at line 5397 of file core.py.
    def __init__(self, other: typing.Optional[Union[ParserElement, str]] = None):
        self.caller_frame = traceback.extract_stack(limit=2)[0]
        super().__init__(other, savelist=False)  # type: ignore[arg-type]
        self.lshift_line = None
__del__()
__del__ (self)
Definition at line 5445 of file core.py.
    def __del__(self):
        # see if we are getting dropped because of '=' reassignment of var instead of '<<=' or '<<'
        if (
            self.expr is None
            and __diag__.warn_on_assignment_to_Forward
            and Diagnostics.warn_on_assignment_to_Forward not in self.suppress_warnings_
        ):
            warnings.warn_explicit(
                "Forward defined here but no expression attached later using '<<=' or '<<'",
                UserWarning,
                filename=self.caller_frame.filename,
                lineno=self.caller_frame.lineno,
            )
References caller_frame, ParseElementEnhance.expr, and ParserElement.suppress_warnings_.
Member Function Documentation
__ilshift__()
"Forward" __ilshift__ (self, other)
Definition at line 5424 of file core.py.
    def __ilshift__(self, other) -> "Forward":
        if not isinstance(other, ParserElement):
            return NotImplemented
        return self << other
__lshift__()
"Forward" __lshift__ (self, other)
Definition at line 5402 of file core.py.
    def __lshift__(self, other) -> "Forward":
        if hasattr(self, "caller_frame"):
            del self.caller_frame
        if isinstance(other, str_type):
            other = self._literalStringClass(other)
        if not isinstance(other, ParserElement):
            return NotImplemented
        self.expr = other
        self.streamlined = other.streamlined
        self.mayIndexError = self.expr.mayIndexError
        self.mayReturnEmpty = self.expr.mayReturnEmpty
        self.set_whitespace_chars(
            self.expr.whiteChars, copy_defaults=self.expr.copyDefaultWhiteChars
        )
        self.skipWhitespace = self.expr.skipWhitespace
        self.saveAsList = self.expr.saveAsList
        self.ignoreExprs.extend(self.expr.ignoreExprs)
        self.lshift_line = traceback.extract_stack(limit=2)[-2]  # type: ignore[assignment]
        return self
References ParserElement._literalStringClass, and caller_frame.
__or__()
"ParserElement" __or__ (self, other)
Definition at line 5430 of file core.py.
    def __or__(self, other) -> "ParserElement":
        caller_line = traceback.extract_stack(limit=2)[-2]
        if (
            __diag__.warn_on_match_first_with_lshift_operator
            and caller_line == self.lshift_line
            and Diagnostics.warn_on_match_first_with_lshift_operator
            not in self.suppress_warnings_
        ):
            warnings.warn(
                "using '<<' operator with '|' is probably an error, use '<<='",
                stacklevel=2,
            )
        ret = super().__or__(other)
        return ret
References __or__(), lshift_line, and ParserElement.suppress_warnings_.
Referenced by __or__().
_generateDefaultName()
str _generateDefaultName (self) protected
Child classes must define this method, which defines how the ``default_name`` is set.
Reimplemented from ParseElementEnhance.
Definition at line 5584 of file core.py.
    def _generateDefaultName(self) -> str:
        # Avoid infinite recursion by setting a temporary _defaultName
        self._defaultName = ": ..."
        # Use the string representation of main expression.
        retString = "..."
        try:
            if self.expr is not None:
                retString = str(self.expr)[:1000]
            else:
                retString = "None"
        finally:
            return self.__class__.__name__ + ": " + retString
_setResultsName()
_setResultsName (self, name, list_all_matches = False) protected
Reimplemented from ParserElement.
Definition at line 5606 of file core.py.
    def _setResultsName(self, name, list_all_matches=False):
        if (
            __diag__.warn_name_set_on_empty_Forward
            and Diagnostics.warn_name_set_on_empty_Forward
            not in self.suppress_warnings_
        ):
            if self.expr is None:
                warnings.warn(
                    "{}: setting results name {!r} on {} expression "
                    "that has no contained expression".format(
                        "warn_name_set_on_empty_Forward", name, type(self).__name__
                    ),
                    stacklevel=3,
                )
        return super()._setResultsName(name, list_all_matches)
References _setResultsName(), ParseElementEnhance.expr, and ParserElement.suppress_warnings_.
Referenced by _setResultsName().
copy()
ParserElement copy (self)
Make a copy of this :class:`ParserElement`.  Useful for defining
different parse actions for the same parsing pattern, using copies of
the original parse element.
Example::
    integer = Word(nums).set_parse_action(lambda toks: int(toks[0]))
    integerK = integer.copy().add_parse_action(lambda toks: toks[0] * 1024) + Suppress("K")
    integerM = integer.copy().add_parse_action(lambda toks: toks[0] * 1024 * 1024) + Suppress("M")
    print((integerK | integerM | integer)[1, ...].parse_string("5K 100 640K 256M"))
prints::
    [5120, 100, 655360, 268435456]
Equivalent form of ``expr.copy()`` is just ``expr()``::
    integerM = integer().add_parse_action(lambda toks: toks[0] * 1024 * 1024) + Suppress("M")
Reimplemented from ParserElement.
Definition at line 5598 of file core.py.
    def copy(self) -> ParserElement:
        if self.expr is not None:
            return super().copy()
        else:
            ret = Forward()
            ret <<= self
            return ret
References copy(), and ParseElementEnhance.expr.
Referenced by ParseResults.__add__(), Text.__add__(), ParseResults.__radd__(), copy(), ParseResults.deepcopy(), Text.divide(), ConsoleOptions.reset_height(), Text.split(), ConsoleOptions.update(), ConsoleOptions.update_dimensions(), ConsoleOptions.update_height(), ConsoleOptions.update_width(), Text.with_indent_guides(), and BaseRetrying.wraps().
ignore_whitespace()
ParserElement ignore_whitespace (self, bool recursive = True)
Enables the skipping of whitespace before matching the characters in the
:class:`ParserElement`'s defined pattern.
:param recursive: If ``True`` (the default), also enable whitespace skipping in child elements (if any)
Reimplemented from ParseElementEnhance.
Definition at line 5558 of file core.py.
    def ignore_whitespace(self, recursive: bool = True) -> ParserElement:
        self.skipWhitespace = True
        return self
References ParserElement.skipWhitespace.
ignoreWhitespace()
ignoreWhitespace (self)
Reimplemented from ParseElementEnhance.
Definition at line 5629 of file core.py.
    def ignoreWhitespace(self): ...
leave_whitespace()
ParserElement leave_whitespace (self, bool recursive = True)
Disables the skipping of whitespace before matching the characters in the
:class:`ParserElement`'s defined pattern.  This is normally only used internally by
the pyparsing module, but may be needed in some whitespace-sensitive grammars.
:param recursive: If true (the default), also disable whitespace skipping in child elements (if any)
Reimplemented from ParseElementEnhance.
Definition at line 5554 of file core.py.
    def leave_whitespace(self, recursive: bool = True) -> ParserElement:
        self.skipWhitespace = False
        return self
References ParserElement.skipWhitespace.
leaveWhitespace()
leaveWhitespace (self)
Reimplemented from ParseElementEnhance.
Definition at line 5626 of file core.py.
    def leaveWhitespace(self): ...
parseImpl()
parseImpl (self, instring, loc, doActions = True)
Reimplemented from ParseElementEnhance.
Definition at line 5459 of file core.py.
    def parseImpl(self, instring, loc, doActions=True):
        if (
            self.expr is None
            and __diag__.warn_on_parse_using_empty_Forward
            and Diagnostics.warn_on_parse_using_empty_Forward
            not in self.suppress_warnings_
        ):
            # walk stack until parse_string, scan_string, search_string, or transform_string is found
            parse_fns = (
                "parse_string",
                "scan_string",
                "search_string",
                "transform_string",
            )
            tb = traceback.extract_stack(limit=200)
            for i, frm in enumerate(reversed(tb), start=1):
                if frm.name in parse_fns:
                    stacklevel = i + 1
                    break
            else:
                stacklevel = 2
            warnings.warn(
                "Forward expression was never assigned a value, will not parse any input",
                stacklevel=stacklevel,
            )
        if not ParserElement._left_recursion_enabled:
            return super().parseImpl(instring, loc, doActions)
        # ## Bounded Recursion algorithm ##
        # Recursion only needs to be processed at ``Forward`` elements, since they are
        # the only ones that can actually refer to themselves. The general idea is
        # to handle recursion stepwise: We start at no recursion, then recurse once,
        # recurse twice, ..., until more recursion offers no benefit (we hit the bound).
        #
        # The "trick" here is that each ``Forward`` gets evaluated in two contexts
        # - to *match* a specific recursion level, and
        # - to *search* the bounded recursion level
        # and the two run concurrently. The *search* must *match* each recursion level
        # to find the best possible match. This is handled by a memo table, which
        # provides the previous match to the next level match attempt.
        #
        # See also "Left Recursion in Parsing Expression Grammars", Medeiros et al.
        #
        # There is a complication since we not only *parse* but also *transform* via
        # actions: We do not want to run the actions too often while expanding. Thus,
        # we expand using `doActions=False` and only run `doActions=True` if the next
        # recursion level is acceptable.
        with ParserElement.recursion_lock:
            memo = ParserElement.recursion_memos
            try:
                # we are parsing at a specific recursion expansion - use it as-is
                prev_loc, prev_result = memo[loc, self, doActions]
                if isinstance(prev_result, Exception):
                    raise prev_result
                return prev_loc, prev_result.copy()
            except KeyError:
                act_key = (loc, self, True)
                peek_key = (loc, self, False)
                # we are searching for the best recursion expansion - keep on improving
                # both `doActions` cases must be tracked separately here!
                prev_loc, prev_peek = memo[peek_key] = (
                    loc - 1,
                    ParseException(
                        instring, loc, "Forward recursion without base case", self
                    ),
                )
                if doActions:
                    memo[act_key] = memo[peek_key]
                while True:
                    try:
                        new_loc, new_peek = super().parseImpl(instring, loc, False)
                    except ParseException:
                        # we failed before getting any match  do not hide the error
                        if isinstance(prev_peek, Exception):
                            raise
                        new_loc, new_peek = prev_loc, prev_peek
                    # the match did not get better: we are done
                    if new_loc <= prev_loc:
                        if doActions:
                            # replace the match for doActions=False as well,
                            # in case the action did backtrack
                            prev_loc, prev_result = memo[peek_key] = memo[act_key]
                            del memo[peek_key], memo[act_key]
                            return prev_loc, prev_result.copy()
                        del memo[peek_key]
                        return prev_loc, prev_peek.copy()
                    # the match did get better: see if we can improve further
                    else:
                        if doActions:
                            try:
                                memo[act_key] = super().parseImpl(instring, loc, True)
                            except ParseException as e:
                                memo[peek_key] = memo[act_key] = (new_loc, e)
                                raise
                        prev_loc, prev_peek = memo[peek_key] = new_loc, new_peek
References ParseElementEnhance.expr, parseImpl(), and ParserElement.suppress_warnings_.
Referenced by parseImpl().
streamline()
ParserElement streamline (self)
Reimplemented from ParseElementEnhance.
Definition at line 5562 of file core.py.
    def streamline(self) -> ParserElement:
        if not self.streamlined:
            self.streamlined = True
            if self.expr is not None:
                self.expr.streamline()
        return self
References ParseElementEnhance.expr, streamline(), and ParserElement.streamlined.
Referenced by streamline().
validate()
None validate (self, validateTrace = None)
Check defined expressions for valid structure, check for infinite recursive definitions.
Reimplemented from ParseElementEnhance.
Definition at line 5569 of file core.py.
    def validate(self, validateTrace=None) -> None:
        warnings.warn(
            "ParserElement.validate() is deprecated, and should not be used to check for left recursion",
            DeprecationWarning,
            stacklevel=2,
        )
        if validateTrace is None:
            validateTrace = []
        if self not in validateTrace:
            tmp = validateTrace[:] + [self]
            if self.expr is not None:
                self.expr.validate(tmp)
        self._checkRecursion([])
References ParserElement._checkRecursion(), ParseElementEnhance.expr, and validate.
Field Documentation
caller_frame
caller_frame = traceback.extract_stack(limit=2)[0]
Definition at line 5398 of file core.py.
Referenced by __del__(), and __lshift__().
lshift_line
lshift_line = None
Definition at line 5400 of file core.py.
Referenced by __or__().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/core.py