Let us walk on the 3-isogeny graph: AnnotatedItem Class Reference
AnnotatedItem Class Reference
Public Member Functions
__init__ (self, str label, item)
Detailed Description
Simple subclass of Group that creates an annotation label
Definition at line 86 of file __init__.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, str label, item)
Definition at line 91 of file __init__.py.
    def __init__(self, label: str, item):
        super().__init__(item=item, label="[{}]".format(label) if label else label)
References AnnotatedItem.__init__(), and i.
Referenced by AnnotatedItem.__init__(), and Protocol.__init_subclass__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/diagram/__init__.py