Let us walk on the 3-isogeny graph: pip._vendor.pygments.formatters.latex Namespace Reference
pip._vendor.pygments.formatters.latex Namespace Reference
Data Structures
class LatexEmbeddedLexer
class LatexFormatter
Functions
escape_tex (text, commandprefix)
_get_ttype_name (ttype)
Variables
str DOC_TEMPLATE
str STYLE_TEMPLATE
Small explanation of the mess below :)
Detailed Description
    pygments.formatters.latex
    ~~~~~~~~~~~~~~~~~~~~~~~~~
    Formatter for LaTeX fancyvrb output.
    :copyright: Copyright 2006-2023 by the Pygments team, see AUTHORS.
    :license: BSD, see LICENSE for details.
Function Documentation
_get_ttype_name()
_get_ttype_name (ttype) protected
Definition at line 135 of file latex.py.
def _get_ttype_name(ttype):
    fname = STANDARD_TYPES.get(ttype)
    if fname:
        return fname
    aname = ''
    while fname is None:
        aname = ttype[-1] + aname
        ttype = ttype.parent
        fname = STANDARD_TYPES.get(ttype)
    return fname + aname
References i.
Referenced by LatexFormatter._create_stylesheet(), and LatexFormatter.format_unencoded().
escape_tex()
escape_tex (text, commandprefix)
Definition at line 22 of file latex.py.
def escape_tex(text, commandprefix):
    return text.replace('\\', '\x00'). \
                replace('{', '\x01'). \
                replace('}', '\x02'). \
                replace('\x00', r'\%sZbs{}' % commandprefix). \
                replace('\x01', r'\%sZob{}' % commandprefix). \
                replace('\x02', r'\%sZcb{}' % commandprefix). \
                replace('^', r'\%sZca{}' % commandprefix). \
                replace('_', r'\%sZus{}' % commandprefix). \
                replace('&', r'\%sZam{}' % commandprefix). \
                replace('<', r'\%sZlt{}' % commandprefix). \
                replace('>', r'\%sZgt{}' % commandprefix). \
                replace('#', r'\%sZsh{}' % commandprefix). \
                replace('%', r'\%sZpc{}' % commandprefix). \
                replace('$', r'\%sZdl{}' % commandprefix). \
                replace('-', r'\%sZhy{}' % commandprefix). \
                replace("'", r'\%sZsq{}' % commandprefix). \
                replace('"', r'\%sZdq{}' % commandprefix). \
                replace('~', r'\%sZti{}' % commandprefix)
References i.
Referenced by LatexFormatter.format_unencoded().
Variable Documentation
DOC_TEMPLATE
str DOC_TEMPLATE
Initial value:
=  r'''
\documentclass{%(docclass)s}
\usepackage{fancyvrb}
\usepackage{color}
\usepackage[%(encoding)s]{inputenc}
%(preamble)s
%(styledefs)s
\begin{document}
\section*{%(title)s}
%(code)s
\end{document}
'''
Definition at line 43 of file latex.py.
STYLE_TEMPLATE
str STYLE_TEMPLATE
Small explanation of the mess below :)
The previous version of the LaTeX formatter just assigned a command to each token type defined in the current style. That obviously is problematic if the highlighted code is produced for a different style than the style commands themselves.
This version works much like the HTML formatter which assigns multiple CSS classes to each tag, from the most specific to the least specific token type, thus falling back to the parent token type if one is not defined. Here, the classes are there too and use the same short forms given in token.STANDARD_TYPES.
Highlighted code now only uses one custom command, which by default is \PY and selectable by the commandprefix option (and in addition the escapes \PYZat, \PYZlb and \PYZrb which haven't been renamed for backwards compatibility purposes).
\PY has two arguments: the classes, separated by +, and the text to render in that style. The classes are resolved into the respective style commands by magic, which serves to ignore unknown classes.
The magic macros are:
\PY@it, \PY@bf, etc. are unconditionally wrapped around the text to render in \PY@do. Their definition determines the style.
\PY@reset resets \PY@it etc. to do nothing.
\PY@toks parses the list of classes, using magic inspired by the keyval package (but modified to use plusses instead of commas because fancyvrb redefines commas inside its environments).
\PY@tok processes one class, calling the \PY@tok@classname command if it exists.
\PY@tok@classname sets the \PY@it etc. to reflect the chosen style for its class.
\PY resets the style, parses the classnames and then calls \PY@do.
Tip: to read this code, print it out in substituted form using e.g.
‍print STYLE_TEMPLATE % {'cp': 'PY'}
Definition at line 98 of file latex.py.