Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: PyOpenSSLContext Class Reference
PyOpenSSLContext Class Reference
Public Member Functions
__init__ (self, protocol)
options (self)
options (self, value)
verify_mode (self)
verify_mode (self, value)
set_default_verify_paths (self)
set_ciphers (self, ciphers)
load_verify_locations (self, cafile=None, capath=None, cadata=None)
load_cert_chain (self, certfile, keyfile=None, password=None)
set_alpn_protocols (self, protocols)
wrap_socket (self, sock, server_side=False, do_handshake_on_connect=True, suppress_ragged_eofs=True, server_hostname=None)
Data Fields
protocol = _openssl_versions[protocol]
bool check_hostname = False
Protected Attributes
_ctx = OpenSSL.SSL.Context(self.protocol)
int _options = 0
Detailed Description
I am a wrapper class for the PyOpenSSL ``Context`` object. I am responsible
for translating the interface of the standard library ``SSLContext`` object
to calls into PyOpenSSL.
Definition at line 423 of file pyopenssl.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, protocol)
Definition at line 430 of file pyopenssl.py.
    def __init__(self, protocol):
        self.protocol = _openssl_versions[protocol]
        self._ctx = OpenSSL.SSL.Context(self.protocol)
        self._options = 0
        self.check_hostname = False
Member Function Documentation
load_cert_chain()
load_cert_chain (self, certfile, keyfile = None, password = None)
Definition at line 473 of file pyopenssl.py.
    def load_cert_chain(self, certfile, keyfile=None, password=None):
        self._ctx.use_certificate_chain_file(certfile)
        if password is not None:
            if not isinstance(password, six.binary_type):
                password = password.encode("utf-8")
            self._ctx.set_passwd_cb(lambda *_: password)
        self._ctx.use_privatekey_file(keyfile or certfile)
References _ctx.
load_verify_locations()
load_verify_locations (self, cafile = None, capath = None, cadata = None)
Definition at line 461 of file pyopenssl.py.
    def load_verify_locations(self, cafile=None, capath=None, cadata=None):
        if cafile is not None:
            cafile = cafile.encode("utf-8")
        if capath is not None:
            capath = capath.encode("utf-8")
        try:
            self._ctx.load_verify_locations(cafile, capath)
            if cadata is not None:
                self._ctx.load_verify_locations(BytesIO(cadata))
        except OpenSSL.SSL.Error as e:
            raise ssl.SSLError("unable to load trusted certificates: %r" % e)
References _ctx, and load_verify_locations().
Referenced by load_verify_locations().
options() [1/2]
options (self)
Definition at line 437 of file pyopenssl.py.
    def options(self):
        return self._options
References _options.
options() [2/2]
options (self, value)
Definition at line 441 of file pyopenssl.py.
    def options(self, value):
        self._options = value
        self._ctx.set_options(value)
References _ctx, and _options.
set_alpn_protocols()
set_alpn_protocols (self, protocols)
Definition at line 481 of file pyopenssl.py.
    def set_alpn_protocols(self, protocols):
        protocols = [six.ensure_binary(p) for p in protocols]
        return self._ctx.set_alpn_protos(protocols)
References _ctx.
set_ciphers()
set_ciphers (self, ciphers)
Definition at line 456 of file pyopenssl.py.
    def set_ciphers(self, ciphers):
        if isinstance(ciphers, six.text_type):
            ciphers = ciphers.encode("utf-8")
        self._ctx.set_cipher_list(ciphers)
References _ctx.
set_default_verify_paths()
set_default_verify_paths (self)
Definition at line 453 of file pyopenssl.py.
    def set_default_verify_paths(self):
        self._ctx.set_default_verify_paths()
References _ctx, and set_default_verify_paths().
Referenced by set_default_verify_paths().
verify_mode() [1/2]
verify_mode (self)
Definition at line 446 of file pyopenssl.py.
    def verify_mode(self):
        return _openssl_to_stdlib_verify[self._ctx.get_verify_mode()]
References _ctx.
verify_mode() [2/2]
verify_mode (self, value)
Definition at line 450 of file pyopenssl.py.
    def verify_mode(self, value):
        self._ctx.set_verify(_stdlib_to_openssl_verify[value], _verify_callback)
References _ctx.
wrap_socket()
wrap_socket (self, sock, server_side = False, do_handshake_on_connect = True, suppress_ragged_eofs = True, server_hostname = None)
Definition at line 485 of file pyopenssl.py.
    ):
        cnx = OpenSSL.SSL.Connection(self._ctx, sock)
        if isinstance(server_hostname, six.text_type):  # Platform-specific: Python 3
            server_hostname = server_hostname.encode("utf-8")
        if server_hostname is not None:
            cnx.set_tlsext_host_name(server_hostname)
        cnx.set_connect_state()
        while True:
            try:
                cnx.do_handshake()
            except OpenSSL.SSL.WantReadError:
                if not util.wait_for_read(sock, sock.gettimeout()):
                    raise timeout("select timed out")
                continue
            except OpenSSL.SSL.Error as e:
                raise ssl.SSLError("bad handshake: %r" % e)
            break
        return WrappedSocket(cnx, sock)
References _ctx.
Field Documentation
_ctx
_ctx = OpenSSL.SSL.Context(self.protocol) protected
Definition at line 432 of file pyopenssl.py.
Referenced by load_cert_chain(), load_verify_locations(), options(), set_alpn_protocols(), set_ciphers(), set_default_verify_paths(), verify_mode(), verify_mode(), and wrap_socket().
_options
int _options = 0 protected
Definition at line 433 of file pyopenssl.py.
Referenced by options(), options(), SecureTransportContext.options(), and SecureTransportContext.options().
check_hostname
bool check_hostname = False
Definition at line 434 of file pyopenssl.py.
protocol
protocol = _openssl_versions[protocol]
Definition at line 431 of file pyopenssl.py.
Referenced by SSLContext.wrap_socket().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/urllib3/contrib/pyopenssl.py