Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Transport Class Reference
Transport Class Reference
Public Member Functions
__init__ (self, timeout, use_datetime=0)
make_connection (self, host)
Data Fields
timeout = timeout
Protected Attributes
_extra_headers = eh
_connection = host, httplib.HTTPConnection(h)
Detailed Description
Definition at line 1506 of file util.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, timeout, use_datetime = 0)
Definition at line 1507 of file util.py.
    def __init__(self, timeout, use_datetime=0):
        self.timeout = timeout
        xmlrpclib.Transport.__init__(self, use_datetime)
Member Function Documentation
make_connection()
make_connection (self, host)
Definition at line 1511 of file util.py.
    def make_connection(self, host):
        h, eh, x509 = self.get_host_info(host)
        if not self._connection or host != self._connection[0]:
            self._extra_headers = eh
            self._connection = host, httplib.HTTPConnection(h)
        return self._connection[1]
References _connection.
Field Documentation
_connection
_connection = host, httplib.HTTPConnection(h) protected
Definition at line 1515 of file util.py.
Referenced by HTTPResponse._error_catcher(), HTTPResponse.connection(), SafeTransport.make_connection(), make_connection(), and HTTPResponse.release_conn().
_extra_headers
_extra_headers = eh protected
Definition at line 1514 of file util.py.
timeout
timeout = timeout
Definition at line 1508 of file util.py.
Referenced by HTTPConnection._new_conn(), HTTPSConnection.connect(), SafeTransport.make_connection(), and HTTPConnection.request().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/util.py