Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: pip Namespace Reference
pip Namespace Reference
Namespaces
namespace __main__
namespace __pip
-runner__
namespace __pip-runner__
namespace _internal
namespace _vendor
Functions
int main (Optional[List[str]] args=None)
Function Documentation
main()
int main (Optional[List[str]] args = None)
This is an internal API only meant for use by pip's own console scripts.
For additional details, see https://github.com/pypa/pip/issues/7498.
Definition at line 6 of file __init__.py.
def main(args: Optional[List[str]] = None) -> int:
    """This is an internal API only meant for use by pip's own console scripts.
    For additional details, see https://github.com/pypa/pip/issues/7498.
    """
    from pip._internal.utils.entrypoints import _wrapper
    return _wrapper(args)
Referenced by AnsiToWin32Test.test_native_windows_ansi(), IsattyTest.test_withPycharmStreamWrapped(), JustFixWindowsConsoleTest.testJustFixWindowsConsole(), WinTermTest.testSetConsoleOnStderr(), and AnsiTest.testStyleAttributes().