Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: SafeFileCache Class Reference
SafeFileCache Class Reference
Public Member Functions
None __init__ (self, str directory)
Optional[bytes] get (self, str key)
None set (self, str key, bytes value, Optional[int] expires=None)
None delete (self, str key)
Public Member Functions inherited from BaseCache
close (self)
Data Fields
directory = directory
Protected Member Functions
str _get_cache_path (self, str name)
Detailed Description
A file based cache which is safe to use even when the target directory may
not be accessible or writable.
Definition at line 31 of file cache.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, str directory)
Definition at line 37 of file cache.py.
    def __init__(self, directory: str) -> None:
        assert directory is not None, "Cache directory must not be None."
        super().__init__()
        self.directory = directory
References __init__().
Referenced by __init__().
Member Function Documentation
_get_cache_path()
str _get_cache_path (self, str name) protected
Definition at line 42 of file cache.py.
    def _get_cache_path(self, name: str) -> str:
        # From cachecontrol.caches.file_cache.FileCache._fn, brought into our
        # class for backwards-compatibility and to avoid using a non-public
        # method.
        hashed = FileCache.encode(name)
        parts = list(hashed[:5]) + [hashed]
        return os.path.join(self.directory, *parts)
References directory.
Referenced by delete(), get(), and set().
delete()
None delete (self, str key)
Reimplemented from BaseCache.
Definition at line 66 of file cache.py.
    def delete(self, key: str) -> None:
        path = self._get_cache_path(key)
        with suppressed_cache_errors():
            os.remove(path)
References _get_cache_path(), and pip._internal.network.cache.suppressed_cache_errors().
get()
Optional[bytes] get (self, str key)
Reimplemented from BaseCache.
Definition at line 50 of file cache.py.
    def get(self, key: str) -> Optional[bytes]:
        path = self._get_cache_path(key)
        with suppressed_cache_errors():
            with open(path, "rb") as f:
                return f.read()
References _get_cache_path(), and pip._internal.network.cache.suppressed_cache_errors().
Referenced by LegacyMetadata.__getitem__(), Layout.__getitem__(), LegacyMetadata.check(), and LegacyMetadata.write_file().
set()
None set (self, str key, bytes value, Optional[int] expires = None)
Reimplemented from BaseCache.
Definition at line 56 of file cache.py.
    def set(self, key: str, value: bytes, expires: Optional[int] = None) -> None:
        path = self._get_cache_path(key)
        with suppressed_cache_errors():
            ensure_dir(os.path.dirname(path))
            with adjacent_tmp_file(path) as f:
                f.write(value)
            replace(f.name, path)
References _get_cache_path(), and pip._internal.network.cache.suppressed_cache_errors().
Referenced by LegacyMetadata.__setitem__(), RequestsCookieJar.__setitem__(), Flags.finalize_pending(), LegacyMetadata.read_file(), and LegacyMetadata.update().
Field Documentation
directory
directory = directory
Definition at line 40 of file cache.py.
Referenced by _FileCacheMixin._fn(), and _get_cache_path().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/network/cache.py