Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: RequestException Class Reference
RequestException Class Reference
Public Member Functions
__init__ (self, *args, **kwargs)
Data Fields
response = response
request = kwargs.pop("request", None)
Detailed Description
There was an ambiguous exception that occurred while handling your
request.
Definition at line 12 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, * args, ** kwargs)
Initialize RequestException with `request` and `response` objects.
Definition at line 17 of file exceptions.py.
    def __init__(self, *args, **kwargs):
        """Initialize RequestException with `request` and `response` objects."""
        response = kwargs.pop("response", None)
        self.response = response
        self.request = kwargs.pop("request", None)
        if response is not None and not self.request and hasattr(response, "request"):
            self.request = self.response.request
        super().__init__(*args, **kwargs)
Field Documentation
request
request = kwargs.pop("request", None)
Definition at line 21 of file exceptions.py.
Referenced by Session.delete(), Session.get(), Session.head(), Session.options(), Session.patch(), Session.post(), and Session.put().
response
response = response
Definition at line 20 of file exceptions.py.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/requests/exceptions.py