Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Distribution Class Reference
Distribution Class Reference
Public Member Functions
None __init__ (self, importlib.metadata.Distribution dist, Optional[BasePath] info_location, Optional[BasePath] installed_location)
BaseDistribution from_directory (cls, str directory)
BaseDistribution from_metadata_file_contents (cls, bytes metadata_contents, str filename, str project_name)
BaseDistribution from_wheel (cls, Wheel wheel, str name)
Optional[str] location (self)
Optional[str] info_location (self)
Optional[str] installed_location (self)
NormalizedName canonical_name (self)
DistributionVersion version (self)
bool is_file (self, InfoPath path)
Iterator[str] iter_distutils_script_names (self)
str read_text (self, InfoPath path)
Iterable[BaseEntryPoint] iter_entry_points (self)
Iterable[str] iter_provided_extras (self)
Iterable[Requirement] iter_dependencies (self, Collection[str] extras=())
Public Member Functions inherited from BaseDistribution
str __repr__ (self)
str __str__ (self)
Optional[str] editable_project_location (self)
bool installed_by_distutils (self)
bool installed_as_egg (self)
bool installed_with_setuptools_egg_info (self)
bool installed_with_dist_info (self)
str setuptools_filename (self)
Optional[DirectUrl] direct_url (self)
str installer (self)
bool requested (self)
bool editable (self)
bool local (self)
bool in_usersite (self)
bool in_site_packages (self)
email.message.Message metadata (self)
Dict[str, Any] metadata_dict (self)
Optional[str] metadata_version (self)
str raw_name (self)
SpecifierSet requires_python (self)
Optional[Iterator[str]] iter_declared_entries (self)
Protected Member Functions
Optional[str] _get_dist_name_from_location (self)
email.message.Message _metadata_impl (self)
Protected Member Functions inherited from BaseDistribution
email.message.Message _metadata_cached (self)
Optional[Iterator[str]] _iter_declared_entries_from_record (self)
Optional[Iterator[str]] _iter_declared_entries_from_legacy (self)
Iterator[RequiresEntry] _iter_requires_txt_entries (self)
Iterable[str] _iter_egg_info_extras (self)
Iterable[str] _iter_egg_info_dependencies (self)
None _add_egg_info_requires (self, email.message.Message metadata)
Protected Attributes
_dist = dist
Optional[str] _info_location = info_location
Optional[str] _installed_location = installed_location
Additional Inherited Members
Data Fields inherited from BaseDistribution
editable_project_location
metadata
raw_name
Detailed Description
Definition at line 96 of file _dists.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, importlib.metadata.Distribution dist, Optional[BasePath] info_location, Optional[BasePath] installed_location)
Definition at line 97 of file _dists.py.
    ) -> None:
        self._dist = dist
        self._info_location = info_location
        self._installed_location = installed_location
Member Function Documentation
_get_dist_name_from_location()
Optional[str] _get_dist_name_from_location (self) protected
Try to get the name from the metadata directory name.
This is much faster than reading metadata.
Definition at line 159 of file _dists.py.
    def _get_dist_name_from_location(self) -> Optional[str]:
        """Try to get the name from the metadata directory name.
        This is much faster than reading metadata.
        """
        if self._info_location is None:
            return None
        stem, suffix = os.path.splitext(self._info_location.name)
        if suffix not in (".dist-info", ".egg-info"):
            return None
        return stem.split("-", 1)[0]
References _info_location.
Referenced by canonical_name().
_metadata_impl()
email.message.Message _metadata_impl (self) protected
Reimplemented from BaseDistribution.
Definition at line 202 of file _dists.py.
    def _metadata_impl(self) -> email.message.Message:
        # From Python 3.10+, importlib.metadata declares PackageMetadata as the
        # return type. This protocol is unfortunately a disaster now and misses
        # a ton of fields that we need, including get() and get_payload(). We
        # rely on the implementation that the object is actually a Message now,
        # until upstream can improve the protocol. (python/cpython#94952)
        return cast(email.message.Message, self._dist.metadata)
References _dist.
canonical_name()
NormalizedName canonical_name (self)
Reimplemented from BaseDistribution.
Definition at line 172 of file _dists.py.
    def canonical_name(self) -> NormalizedName:
        name = self._get_dist_name_from_location() or get_dist_name(self._dist)
        return canonicalize_name(name)
References _dist, and _get_dist_name_from_location().
from_directory()
BaseDistribution from_directory (cls, str directory)
Load the distribution from a metadata directory.
:param directory: Path to a metadata directory, e.g. ``.dist-info``.
Reimplemented from BaseDistribution.
Definition at line 108 of file _dists.py.
    def from_directory(cls, directory: str) -> BaseDistribution:
        info_location = pathlib.Path(directory)
        dist = importlib.metadata.Distribution.at(info_location)
        return cls(dist, info_location, info_location.parent)
from_metadata_file_contents()
BaseDistribution from_metadata_file_contents (cls, bytes metadata_contents, str filename, str project_name)
Load the distribution from the contents of a METADATA file.
This is used to implement PEP 658 by generating a "shallow" dist object that can
be used for resolution without downloading or building the actual dist yet.
:param metadata_contents: The contents of a METADATA file.
:param filename: File name for the dist with this metadata.
:param project_name: Name of the project this dist represents.
Reimplemented from BaseDistribution.
Definition at line 114 of file _dists.py.
    ) -> BaseDistribution:
        # Generate temp dir to contain the metadata file, and write the file contents.
        temp_dir = pathlib.Path(
            TempDirectory(kind="metadata", globally_managed=True).path
        )
        metadata_path = temp_dir / "METADATA"
        metadata_path.write_bytes(metadata_contents)
        # Construct dist pointing to the newly created directory.
        dist = importlib.metadata.Distribution.at(metadata_path.parent)
        return cls(dist, metadata_path.parent, None)
from_wheel()
BaseDistribution from_wheel (cls, Wheel wheel, str name)
Load the distribution from a given wheel.
:param wheel: A concrete wheel definition.
:param name: File name of the wheel.
:raises InvalidWheel: Whenever loading of the wheel causes a
    :py:exc:`zipfile.BadZipFile` exception to be thrown.
:raises UnsupportedWheel: If the wheel is a valid zip, but malformed
    internally.
Reimplemented from BaseDistribution.
Definition at line 131 of file _dists.py.
    def from_wheel(cls, wheel: Wheel, name: str) -> BaseDistribution:
        try:
            with wheel.as_zipfile() as zf:
                dist = WheelDistribution.from_zipfile(zf, name, wheel.location)
        except zipfile.BadZipFile as e:
            raise InvalidWheel(wheel.location, name) from e
        except UnsupportedWheel as e:
            raise UnsupportedWheel(f"{name} has an invalid wheel, {e}")
        return cls(dist, dist.info_location, pathlib.PurePosixPath(wheel.location))
info_location()
Optional[str] info_location (self)
Location of the .[egg|dist]-info directory or file.
Similarly to ``location``, a string value is not necessarily a
filesystem path. ``None`` means the distribution is created in-memory.
For a modern .dist-info installation on disk, this should be something
like ``{location}/{raw_name}-{version}.dist-info``.
Do not canonicalize this value with e.g. ``pathlib.Path.resolve()``. If
this is a symbolic link, we want to preserve the relative path between
it and other files in the distribution.
Reimplemented from BaseDistribution.
Definition at line 148 of file _dists.py.
    def info_location(self) -> Optional[str]:
        if self._info_location is None:
            return None
        return str(self._info_location)
References _info_location.
installed_location()
Optional[str] installed_location (self)
Reimplemented from BaseDistribution.
Definition at line 154 of file _dists.py.
    def installed_location(self) -> Optional[str]:
        if self._installed_location is None:
            return None
        return normalize_path(str(self._installed_location))
References _installed_location.
is_file()
bool is_file (self, InfoPath path)
Check whether an entry in the info directory is a file.
Reimplemented from BaseDistribution.
Definition at line 180 of file _dists.py.
    def is_file(self, path: InfoPath) -> bool:
        return self._dist.read_text(str(path)) is not None
References _dist, and read_text().
iter_dependencies()
Iterable[Requirement] iter_dependencies (self, Collection[str] extras = ())
Dependencies of this distribution.
For modern .dist-info distributions, this is the collection of
"Requires-Dist:" entries in distribution metadata.
Reimplemented from BaseDistribution.
Definition at line 215 of file _dists.py.
    def iter_dependencies(self, extras: Collection[str] = ()) -> Iterable[Requirement]:
        contexts: Sequence[Dict[str, str]] = [{"extra": safe_extra(e)} for e in extras]
        for req_string in self.metadata.get_all("Requires-Dist", []):
            req = Requirement(req_string)
            if not req.marker:
                yield req
            elif not extras and req.marker.evaluate({"extra": ""}):
                yield req
            elif any(req.marker.evaluate(context) for context in contexts):
                yield req
References BaseDistribution.metadata.
iter_distutils_script_names()
Iterator[str] iter_distutils_script_names (self)
Find distutils 'scripts' entries metadata.
If 'scripts' is supplied in ``setup.py``, distutils records those in the
installed distribution's ``scripts`` directory, a file for each script.
Reimplemented from BaseDistribution.
Definition at line 183 of file _dists.py.
    def iter_distutils_script_names(self) -> Iterator[str]:
        # A distutils installation is always "flat" (not in e.g. egg form), so
        # if this distribution's info location is NOT a pathlib.Path (but e.g.
        # zipfile.Path), it can never contain any distutils scripts.
        if not isinstance(self._info_location, pathlib.Path):
            return
        for child in self._info_location.joinpath("scripts").iterdir():
            yield child.name
References _info_location.
iter_entry_points()
Iterable[BaseEntryPoint] iter_entry_points (self)
Reimplemented from BaseDistribution.
Definition at line 198 of file _dists.py.
    def iter_entry_points(self) -> Iterable[BaseEntryPoint]:
        # importlib.metadata's EntryPoint structure sasitfies BaseEntryPoint.
        return self._dist.entry_points
References _dist.
iter_provided_extras()
Iterable[str] iter_provided_extras (self)
Extras provided by this distribution.
For modern .dist-info distributions, this is the collection of
"Provides-Extra:" entries in distribution metadata.
Reimplemented from BaseDistribution.
Definition at line 210 of file _dists.py.
    def iter_provided_extras(self) -> Iterable[str]:
        return (
            safe_extra(extra) for extra in self.metadata.get_all("Provides-Extra", [])
        )
References BaseDistribution.metadata.
location()
Optional[str] location (self)
Where the distribution is loaded from.
A string value is not necessarily a filesystem path, since distributions
can be loaded from other sources, e.g. arbitrary zip archives. ``None``
means the distribution is created in-memory.
Do not canonicalize this value with e.g. ``pathlib.Path.resolve()``. If
this is a symbolic link, we want to preserve the relative path between
it and files in the distribution.
Reimplemented from BaseDistribution.
Definition at line 142 of file _dists.py.
    def location(self) -> Optional[str]:
        if self._info_location is None:
            return None
        return str(self._info_location.parent)
References _info_location.
read_text()
str read_text (self, InfoPath path)
Read a file in the info directory.
:raise FileNotFoundError: If ``path`` does not exist in the directory.
:raise NoneMetadataError: If ``path`` exists in the info directory, but
    cannot be read.
Reimplemented from BaseDistribution.
Definition at line 192 of file _dists.py.
    def read_text(self, path: InfoPath) -> str:
        content = self._dist.read_text(str(path))
        if content is None:
            raise FileNotFoundError(path)
        return content
References _dist, and read_text().
Referenced by is_file(), and read_text().
version()
DistributionVersion version (self)
Reimplemented from BaseDistribution.
Definition at line 177 of file _dists.py.
    def version(self) -> DistributionVersion:
        return parse_version(self._dist.version)
References _dist.
Referenced by WrappedSocket._custom_validate(), LinuxDistribution.info(), LinuxDistribution.linux_distribution(), LinuxDistribution.name(), and LinuxDistribution.version_parts().
Field Documentation
_dist
_dist = dist protected
Definition at line 103 of file _dists.py.
Referenced by _metadata_impl(), canonical_name(), info_location(), installed_by_distutils(), is_file(), iter_dependencies(), iter_distutils_script_names(), iter_entry_points(), iter_provided_extras(), location(), read_text(), UninstallPathSet.remove(), UninstallPathSet.rollback(), and version().
_info_location
_info_location = info_location protected
Definition at line 104 of file _dists.py.
Referenced by _get_dist_name_from_location(), info_location(), iter_distutils_script_names(), and location().
_installed_location
_installed_location = installed_location protected
Definition at line 105 of file _dists.py.
Referenced by installed_location().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/metadata/importlib/_dists.py