Let us walk on the 3-isogeny graph: retry_if_exception_message Class Reference
retry_if_exception_message Class Reference
Public Member Functions
None __init__ (self, typing.Optional[str] message=None, typing.Optional[str] match=None)
Public Member Functions inherited from retry_if_exception
bool __call__ (self, "RetryCallState" retry_state)
Public Member Functions inherited from retry_base
"retry_all" __and__ (self, "retry_base" other)
"retry_any" __or__ (self, "retry_base" other)
Additional Inherited Members
Data Fields inherited from retry_if_exception
predicate
Detailed Description
Retries if an exception message equals or matches.
Definition at line 198 of file retry.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, typing.Optional[str] message = None, typing.Optional[str] match = None)
Reimplemented from retry_if_exception.
Reimplemented in retry_if_not_exception_message.
Definition at line 201 of file retry.py.
    ) -> None:
        if message and match:
            raise TypeError(f"{self.__class__.__name__}() takes either 'message' or 'match', not both")
        # set predicate
        if message:
            def message_fnc(exception: BaseException) -> bool:
                return message == str(exception)
            predicate = message_fnc
        elif match:
            prog = re.compile(match)
            def match_fnc(exception: BaseException) -> bool:
                return bool(prog.match(str(exception)))
            predicate = match_fnc
        else:
            raise TypeError(f"{self.__class__.__name__}() missing 1 required argument 'message' or 'match'")
        super().__init__(predicate)
References retry_if_exception_message.__init__(), and i.
Referenced by retry_if_exception_message.__init__(), and Protocol.__init_subclass__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/tenacity/retry.py