Let us walk on the 3-isogeny graph: pip._vendor.rich._inspect Namespace Reference
pip._vendor.rich._inspect Namespace Reference
Data Structures
class Inspect
Functions
str _first_paragraph (str doc)
Tuple[type,...] get_object_types_mro (Union[object, Type[Any]] obj)
Collection[str] get_object_types_mro_as_strings (object obj)
bool is_object_one_of_types (object obj, Collection[str] fully_qualified_types_names)
Function Documentation
_first_paragraph()
str _first_paragraph (str doc) protected
Get the first paragraph from a docstring.
Definition at line 17 of file _inspect.py.
def _first_paragraph(doc: str) -> str:
    """Get the first paragraph from a docstring."""
    paragraph, _, _ = doc.partition("\n\n")
    return paragraph
References i.
Referenced by Inspect._get_formatted_doc().
get_object_types_mro()
Tuple[type, ...] get_object_types_mro (Union[object, Type[Any]] obj)
Returns the MRO of an object's class, or of the object itself if it's a class.
Definition at line 238 of file _inspect.py.
def get_object_types_mro(obj: Union[object, Type[Any]]) -> Tuple[type, ...]:
    """Returns the MRO of an object's class, or of the object itself if it's a class."""
    if not hasattr(obj, "__mro__"):
        # N.B. we cannot use `if type(obj) is type` here because it doesn't work with
        # some types of classes, such as the ones that use abc.ABCMeta.
        obj = type(obj)
    return getattr(obj, "__mro__", ())
References i.
Referenced by pip._vendor.rich._inspect.get_object_types_mro_as_strings().
get_object_types_mro_as_strings()
Collection[str] get_object_types_mro_as_strings (object obj)
Returns the MRO of an object's class as full qualified names, or of the object itself if it's a class.
Examples:
    `object_types_mro_as_strings(JSONDecoder)` will return `['json.decoder.JSONDecoder', 'builtins.object']`
Definition at line 247 of file _inspect.py.
def get_object_types_mro_as_strings(obj: object) -> Collection[str]:
    """
    Returns the MRO of an object's class as full qualified names, or of the object itself if it's a class.
    Examples:
        `object_types_mro_as_strings(JSONDecoder)` will return `['json.decoder.JSONDecoder', 'builtins.object']`
    """
    return [
        f'{getattr(type_, "__module__", "")}.{getattr(type_, "__qualname__", "")}'
        for type_ in get_object_types_mro(obj)
    ]
References pip._vendor.rich._inspect.get_object_types_mro().
Referenced by pip._vendor.rich._inspect.is_object_one_of_types().
is_object_one_of_types()
bool is_object_one_of_types (object obj, Collection[str] fully_qualified_types_names)
Returns `True` if the given object's class (or the object itself, if it's a class) has one of the
fully qualified names in its MRO.
Definition at line 260 of file _inspect.py.
) -> bool:
    """
    Returns `True` if the given object's class (or the object itself, if it's a class) has one of the
    fully qualified names in its MRO.
    """
    for type_name in get_object_types_mro_as_strings(obj):
        if type_name in fully_qualified_types_names:
            return True
    return False
References pip._vendor.rich._inspect.get_object_types_mro_as_strings().