Let us walk on the 3-isogeny graph: DirectoryLocator Class Reference
DirectoryLocator Class Reference
Public Member Functions
__init__ (self, path, **kwargs)
should_include (self, filename, parent)
get_distribution_names (self)
Public Member Functions inherited from Locator
get_errors (self)
clear_errors (self)
clear_cache (self)
get_project (self, name)
score_url (self, url)
prefer_url (self, url1, url2)
split_filename (self, filename, project_name)
convert_url_to_download_info (self, url, project_name)
locate (self, requirement, prereleases=False)
Data Fields
recursive
base_dir
downloadable_extensions
Data Fields inherited from Locator
opener
matcher
errors
downloadable_extensions
Protected Member Functions
_get_project (self, name)
Protected Member Functions inherited from Locator
_get_scheme (self)
_set_scheme (self, value)
_get_digest (self, info)
_update_version_data (self, result, info)
Additional Inherited Members
Static Public Attributes inherited from Locator
tuple source_extensions = ('.tar.gz', '.tar.bz2', '.tar', '.zip', '.tgz', '.tbz')
tuple binary_extensions = ('.egg', '.exe', '.whl')
tuple excluded_extensions = ('.pdf',)
wheel_tags = None
tuple downloadable_extensions = source_extensions + ('.whl',)
Protected Attributes inherited from Locator
_cache
_scheme
Properties inherited from Locator
scheme = property(_get_scheme, _set_scheme)
Detailed Description
This class locates distributions in a directory tree.
Definition at line 835 of file locators.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, path, ** kwargs)
Initialise an instance.
:param path: The root of the directory tree to search.
:param kwargs: Passed to the superclass constructor,
               except for:
               * recursive - if True (the default), subdirectories are
                 recursed into. If False, only the top-level directory
                 is searched,
Reimplemented from Locator.
Definition at line 840 of file locators.py.
    def __init__(self, path, **kwargs):
        """
        Initialise an instance.
        :param path: The root of the directory tree to search.
        :param kwargs: Passed to the superclass constructor,
                       except for:
                       * recursive - if True (the default), subdirectories are
                         recursed into. If False, only the top-level directory
                         is searched,
        """
        self.recursive = kwargs.pop('recursive', True)
        super(DirectoryLocator, self).__init__(**kwargs)
        path = os.path.abspath(path)
        if not os.path.isdir(path):  # pragma: no cover
            raise DistlibException('Not a directory: %r' % path)
        self.base_dir = path
Referenced by Protocol.__init_subclass__().
Member Function Documentation
_get_project()
_get_project (self, name) protected
For a given project, get a dictionary mapping available versions to Distribution
instances.
This should be implemented in subclasses.
If called from a locate() request, self.matcher will be set to a
matcher for the requirement to satisfy, otherwise it will be None.
Reimplemented from Locator.
Definition at line 865 of file locators.py.
    def _get_project(self, name):
        result = {'urls': {}, 'digests': {}}
        for root, dirs, files in os.walk(self.base_dir):
            for fn in files:
                if self.should_include(fn, root):
                    fn = os.path.join(root, fn)
                    url = urlunparse(('file', '',
                                      pathname2url(os.path.abspath(fn)),
                                      '', '', ''))
                    info = self.convert_url_to_download_info(url, name)
                    if info:
                        self._update_version_data(result, info)
            if not self.recursive:
                break
        return result
References Locator._update_version_data(), DirectoryLocator.base_dir, Locator.convert_url_to_download_info(), i, DirectoryLocator.recursive, and DirectoryLocator.should_include().
Referenced by Locator.get_project().
get_distribution_names()
get_distribution_names (self)
Return all the distribution names known to this locator.
Reimplemented from Locator.
Definition at line 881 of file locators.py.
    def get_distribution_names(self):
        """
        Return all the distribution names known to this locator.
        """
        result = set()
        for root, dirs, files in os.walk(self.base_dir):
            for fn in files:
                if self.should_include(fn, root):
                    fn = os.path.join(root, fn)
                    url = urlunparse(('file', '',
                                      pathname2url(os.path.abspath(fn)),
                                      '', '', ''))
                    info = self.convert_url_to_download_info(url, None)
                    if info:
                        result.add(info['name'])
            if not self.recursive:
                break
        return result
References DirectoryLocator.base_dir, Locator.convert_url_to_download_info(), i, DirectoryLocator.recursive, and DirectoryLocator.should_include().
should_include()
should_include (self, filename, parent)
Should a filename be considered as a candidate for a distribution
archive? As well as the filename, the directory which contains it
is provided, though not used by the current implementation.
Definition at line 857 of file locators.py.
    def should_include(self, filename, parent):
        """
        Should a filename be considered as a candidate for a distribution
        archive? As well as the filename, the directory which contains it
        is provided, though not used by the current implementation.
        """
        return filename.endswith(self.downloadable_extensions)
Referenced by DirectoryLocator._get_project(), and DirectoryLocator.get_distribution_names().
Field Documentation
base_dir
base_dir
Definition at line 855 of file locators.py.
Referenced by DirectoryLocator._get_project(), and DirectoryLocator.get_distribution_names().
downloadable_extensions
downloadable_extensions
Definition at line 863 of file locators.py.
Referenced by Locator.score_url().
recursive
recursive
Definition at line 850 of file locators.py.
Referenced by DirectoryLocator._get_project(), and DirectoryLocator.get_distribution_names().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/locators.py