Let us walk on the 3-isogeny graph: KeyBasedCompareMixin Class Reference
KeyBasedCompareMixin Class Reference
Public Member Functions
None __init__ (self, Any key, Type["KeyBasedCompareMixin"] defining_class)
int __hash__ (self)
bool __lt__ (self, Any other)
bool __le__ (self, Any other)
bool __gt__ (self, Any other)
bool __ge__ (self, Any other)
bool __eq__ (self, Any other)
Protected Member Functions
bool _compare (self, Any other, Callable[[Any, Any], bool] method)
Protected Attributes
_compare_key
_defining_class
Detailed Description
Provides comparison capabilities that is based on a key
Definition at line 8 of file models.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, Any key, Type["KeyBasedCompareMixin"] defining_class)
Reimplemented in InstallationCandidate, and Link.
Definition at line 13 of file models.py.
    def __init__(self, key: Any, defining_class: Type["KeyBasedCompareMixin"]) -> None:
        self._compare_key = key
        self._defining_class = defining_class
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__eq__()
bool __eq__ (self, Any other)
Definition at line 32 of file models.py.
    def __eq__(self, other: Any) -> bool:
        return self._compare(other, operator.__eq__)
References KeyBasedCompareMixin._compare(), and i.
Referenced by Version.__ge__(), Version.__gt__(), Version.__le__(), Version.__ne__(), Matcher.__ne__(), Timestamp.__ne__(), and HTTPHeaderDict.__ne__().
__ge__()
bool __ge__ (self, Any other)
Definition at line 29 of file models.py.
    def __ge__(self, other: Any) -> bool:
        return self._compare(other, operator.__ge__)
References KeyBasedCompareMixin._compare(), and i.
__gt__()
bool __gt__ (self, Any other)
Definition at line 26 of file models.py.
    def __gt__(self, other: Any) -> bool:
        return self._compare(other, operator.__gt__)
References KeyBasedCompareMixin._compare(), and i.
Referenced by Version.__ge__().
__hash__()
int __hash__ (self)
Definition at line 17 of file models.py.
    def __hash__(self) -> int:
        return hash(self._compare_key)
References KeyBasedCompareMixin._compare_key.
Referenced by Style.__eq__(), and Style.__ne__().
__le__()
bool __le__ (self, Any other)
Definition at line 23 of file models.py.
    def __le__(self, other: Any) -> bool:
        return self._compare(other, operator.__le__)
References KeyBasedCompareMixin._compare(), and i.
__lt__()
bool __lt__ (self, Any other)
Definition at line 20 of file models.py.
    def __lt__(self, other: Any) -> bool:
        return self._compare(other, operator.__lt__)
References KeyBasedCompareMixin._compare(), and i.
Referenced by Version.__gt__(), and Version.__le__().
_compare()
bool _compare (self, Any other, Callable[[Any, Any], bool] method) protected
Definition at line 35 of file models.py.
    def _compare(self, other: Any, method: Callable[[Any, Any], bool]) -> bool:
        if not isinstance(other, self._defining_class):
            return NotImplemented
        return method(self._compare_key, other._compare_key)
References KeyBasedCompareMixin._compare_key, KeyBasedCompareMixin._defining_class, and i.
Referenced by KeyBasedCompareMixin.__eq__(), KeyBasedCompareMixin.__ge__(), KeyBasedCompareMixin.__gt__(), KeyBasedCompareMixin.__le__(), and KeyBasedCompareMixin.__lt__().
Field Documentation
_compare_key
_compare_key protected
Definition at line 14 of file models.py.
Referenced by KeyBasedCompareMixin.__hash__(), and KeyBasedCompareMixin._compare().
_defining_class
_defining_class protected
Definition at line 15 of file models.py.
Referenced by KeyBasedCompareMixin._compare().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/utils/models.py