Let us walk on the 3-isogeny graph: pip._vendor.urllib3.util.wait Namespace Reference
pip._vendor.urllib3.util.wait Namespace Reference
Data Structures
class NoWayToWaitForSocketError
Functions
_retry_on_intr (fn, timeout)
select_wait_for_socket (sock, read=False, write=False, timeout=None)
poll_wait_for_socket (sock, read=False, write=False, timeout=None)
null_wait_for_socket (*args, **kwargs)
_have_working_poll ()
wait_for_socket (*args, **kwargs)
wait_for_read (sock, timeout=None)
wait_for_write (sock, timeout=None)
Function Documentation
_have_working_poll()
_have_working_poll () protected
Definition at line 113 of file wait.py.
def _have_working_poll():
    # Apparently some systems have a select.poll that fails as soon as you try
    # to use it, either due to strange configuration or broken monkeypatching
    # from libraries like eventlet/greenlet.
    try:
        poll_obj = select.poll()
        _retry_on_intr(poll_obj.poll, 0)
    except (AttributeError, OSError):
        return False
    else:
        return True
References pip._vendor.urllib3.util.wait._retry_on_intr(), and i.
Referenced by pip._vendor.urllib3.util.wait.wait_for_socket().
_retry_on_intr()
_retry_on_intr (fn, timeout) protected
Definition at line 42 of file wait.py.
    def _retry_on_intr(fn, timeout):
        return fn(timeout)
References i.
Referenced by pip._vendor.urllib3.util.wait._have_working_poll(), pip._vendor.urllib3.util.wait.poll_wait_for_socket(), and pip._vendor.urllib3.util.wait.select_wait_for_socket().
null_wait_for_socket()
null_wait_for_socket (* args, ** kwargs)
Definition at line 109 of file wait.py.
def null_wait_for_socket(*args, **kwargs):
    raise NoWayToWaitForSocketError("no select-equivalent available")
poll_wait_for_socket()
poll_wait_for_socket (sock, read = False, write = False, timeout = None)
Definition at line 89 of file wait.py.
def poll_wait_for_socket(sock, read=False, write=False, timeout=None):
    if not read and not write:
        raise RuntimeError("must specify at least one of read=True, write=True")
    mask = 0
    if read:
        mask |= select.POLLIN
    if write:
        mask |= select.POLLOUT
    poll_obj = select.poll()
    poll_obj.register(sock, mask)
    # For some reason, poll() takes timeout in milliseconds
    def do_poll(t):
        if t is not None:
            t *= 1000
        return poll_obj.poll(t)
    return bool(_retry_on_intr(do_poll, timeout))
References pip._vendor.urllib3.util.wait._retry_on_intr(), and i.
select_wait_for_socket()
select_wait_for_socket (sock, read = False, write = False, timeout = None)
Definition at line 70 of file wait.py.
def select_wait_for_socket(sock, read=False, write=False, timeout=None):
    if not read and not write:
        raise RuntimeError("must specify at least one of read=True, write=True")
    rcheck = []
    wcheck = []
    if read:
        rcheck.append(sock)
    if write:
        wcheck.append(sock)
    # When doing a non-blocking connect, most systems signal success by
    # marking the socket writable. Windows, though, signals success by marked
    # it as "exceptional". We paper over the difference by checking the write
    # sockets for both conditions. (The stdlib selectors module does the same
    # thing.)
    fn = partial(select.select, rcheck, wcheck, wcheck)
    rready, wready, xready = _retry_on_intr(fn, timeout)
    return bool(rready or wready or xready)
References pip._vendor.urllib3.util.wait._retry_on_intr(), and i.
wait_for_read()
wait_for_read (sock, timeout = None)
Waits for reading to be available on a given socket.
Returns True if the socket is readable, or False if the timeout expired.
Definition at line 141 of file wait.py.
def wait_for_read(sock, timeout=None):
    """Waits for reading to be available on a given socket.
    Returns True if the socket is readable, or False if the timeout expired.
    """
    return wait_for_socket(sock, read=True, timeout=timeout)
References pip._vendor.urllib3.util.wait.wait_for_socket().
wait_for_socket()
wait_for_socket (* args, ** kwargs)
Definition at line 126 of file wait.py.
def wait_for_socket(*args, **kwargs):
    # We delay choosing which implementation to use until the first time we're
    # called. We could do it at import time, but then we might make the wrong
    # decision if someone goes wild with monkeypatching select.poll after
    # we're imported.
    global wait_for_socket
    if _have_working_poll():
        wait_for_socket = poll_wait_for_socket
    elif hasattr(select, "select"):
        wait_for_socket = select_wait_for_socket
    else:  # Platform-specific: Appengine.
        wait_for_socket = null_wait_for_socket
    return wait_for_socket(*args, **kwargs)
References pip._vendor.urllib3.util.wait._have_working_poll(), i, and pip._vendor.urllib3.util.wait.wait_for_socket().
Referenced by pip._vendor.urllib3.util.wait.wait_for_read(), pip._vendor.urllib3.util.wait.wait_for_socket(), and pip._vendor.urllib3.util.wait.wait_for_write().
wait_for_write()
wait_for_write (sock, timeout = None)
Waits for writing to be available on a given socket.
Returns True if the socket is readable, or False if the timeout expired.
Definition at line 148 of file wait.py.
def wait_for_write(sock, timeout=None):
    """Waits for writing to be available on a given socket.
    Returns True if the socket is readable, or False if the timeout expired.
    """
    return wait_for_socket(sock, write=True, timeout=timeout)
References pip._vendor.urllib3.util.wait.wait_for_socket().