Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: RtfFormatter Class Reference
RtfFormatter Class Reference
Public Member Functions
__init__ (self, **options)
format_unencoded (self, tokensource, outfile)
Public Member Functions inherited from Formatter
__init__ (self, **options)
get_style_defs (self, arg='')
format (self, tokensource, outfile)
Data Fields
str fontface = options.get('fontface') or ''
fontsize = get_int_opt(options, 'fontsize', 0)
Data Fields inherited from Formatter
style = _lookup_style(options.get('style', 'default'))
full = get_bool_opt(options, 'full', False)
title = options.get('title', '')
str encoding = options.get('encoding', None) or None
options = options
Protected Member Functions
_escape (self, text)
_escape_text (self, text)
Additional Inherited Members
Static Public Attributes inherited from Formatter
name = None
list aliases = []
list filenames = []
bool unicodeoutput = True
Detailed Description
Format tokens as RTF markup. This formatter automatically outputs full RTF
documents with color information and other useful stuff. Perfect for Copy and
Paste into Microsoft(R) Word(R) documents.
Please note that ``encoding`` and ``outencoding`` options are ignored.
The RTF format is ASCII natively, but handles unicode characters correctly
thanks to escape sequences.
.. versionadded:: 0.6
Additional options accepted:
`style`
    The style to use, can be a string or a Style subclass (default:
    ``'default'``).
`fontface`
    The used font family, for example ``Bitstream Vera Sans``. Defaults to
    some generic font which is supposed to have fixed width.
`fontsize`
    Size of the font used. Size is specified in half points. The
    default is 24 half-points, giving a size 12 font.
    .. versionadded:: 2.0
Definition at line 18 of file rtf.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, ** options)
Additional options accepted:
``fontface``
    Name of the font used. Could for example be ``'Courier New'``
    to further specify the default which is ``'\fmodern'``. The RTF
    specification claims that ``\fmodern`` are "Fixed-pitch serif
    and sans serif fonts". Hope every RTF implementation thinks
    the same about modern...
Definition at line 50 of file rtf.py.
    def __init__(self, **options):
        r"""
        Additional options accepted:
        ``fontface``
            Name of the font used. Could for example be ``'Courier New'``
            to further specify the default which is ``'\fmodern'``. The RTF
            specification claims that ``\fmodern`` are "Fixed-pitch serif
            and sans serif fonts". Hope every RTF implementation thinks
            the same about modern...
        """
        Formatter.__init__(self, **options)
        self.fontface = options.get('fontface') or ''
        self.fontsize = get_int_opt(options, 'fontsize', 0)
Member Function Documentation
_escape()
_escape (self, text) protected
Definition at line 66 of file rtf.py.
    def _escape(self, text):
        return text.replace('\\', '\\\\') \
                   .replace('{', '\\{') \
                   .replace('}', '\\}')
Referenced by _escape_text(), and format_unencoded().
_escape_text()
_escape_text (self, text) protected
Definition at line 71 of file rtf.py.
    def _escape_text(self, text):
        # empty strings, should give a small performance improvement
        if not text:
            return ''
        # escape text
        text = self._escape(text)
        buf = []
        for c in text:
            cn = ord(c)
            if cn < (2**7):
                # ASCII character
                buf.append(str(c))
            elif (2**7) <= cn < (2**16):
                # single unicode escape sequence
                buf.append('{\\u%d}' % cn)
            elif (2**16) <= cn:
                # RTF limits unicode to 16 bits.
                # Force surrogate pairs
                buf.append('{\\u%d}{\\u%d}' % surrogatepair(cn))
        return ''.join(buf).replace('\n', '\\par\n')
References _escape().
format_unencoded()
format_unencoded (self, tokensource, outfile)
Definition at line 95 of file rtf.py.
    def format_unencoded(self, tokensource, outfile):
        # rtf 1.8 header
        outfile.write('{\\rtf1\\ansi\\uc0\\deff0'
                      '{\\fonttbl{\\f0\\fmodern\\fprq1\\fcharset0%s;}}'
                      '{\\colortbl;' % (self.fontface and
                                        ' ' + self._escape(self.fontface) or
                                        ''))
        # convert colors and save them in a mapping to access them later.
        color_mapping = {}
        offset = 1
        for _, style in self.style:
            for color in style['color'], style['bgcolor'], style['border']:
                if color and color not in color_mapping:
                    color_mapping[color] = offset
                    outfile.write('\\red%d\\green%d\\blue%d;' % (
                        int(color[0:2], 16),
                        int(color[2:4], 16),
                        int(color[4:6], 16)
                    ))
                    offset += 1
        outfile.write('}\\f0 ')
        if self.fontsize:
            outfile.write('\\fs%d' % self.fontsize)
        # highlight stream
        for ttype, value in tokensource:
            while not self.style.styles_token(ttype) and ttype.parent:
                ttype = ttype.parent
            style = self.style.style_for_token(ttype)
            buf = []
            if style['bgcolor']:
                buf.append('\\cb%d' % color_mapping[style['bgcolor']])
            if style['color']:
                buf.append('\\cf%d' % color_mapping[style['color']])
            if style['bold']:
                buf.append('\\b')
            if style['italic']:
                buf.append('\\i')
            if style['underline']:
                buf.append('\\ul')
            if style['border']:
                buf.append('\\chbrdr\\chcfpat%d' %
                           color_mapping[style['border']])
            start = ''.join(buf)
            if start:
                outfile.write('{%s ' % start)
            outfile.write(self._escape_text(value))
            if start:
                outfile.write('}')
        outfile.write('}')
References _escape(), and fontface.
Referenced by Formatter.format().
Field Documentation
fontface
fontface = options.get('fontface') or ''
Definition at line 63 of file rtf.py.
Referenced by format_unencoded().
fontsize
fontsize = get_int_opt(options, 'fontsize', 0)
Definition at line 64 of file rtf.py.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pygments/formatters/rtf.py