Let us walk on the 3-isogeny graph: CommandContextMixIn Class Reference
CommandContextMixIn Class Reference
Public Member Functions
None __init__ (self)
Generator[None, None, None] main_context (self)
_T enter_context (self, ContextManager[_T] context_provider)
Protected Attributes
_in_main_context
_main_context
Detailed Description
Definition at line 7 of file command_context.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Reimplemented in SessionCommandMixin, RequirementCommand, and Command.
Definition at line 8 of file command_context.py.
    def __init__(self) -> None:
        super().__init__()
        self._in_main_context = False
        self._main_context = ExitStack()
References CommandContextMixIn.__init__(), and i.
Referenced by CommandContextMixIn.__init__(), and Protocol.__init_subclass__().
Member Function Documentation
enter_context()
_T enter_context (self, ContextManager[_T] context_provider)
Definition at line 24 of file command_context.py.
    def enter_context(self, context_provider: ContextManager[_T]) -> _T:
        assert self._in_main_context
        return self._main_context.enter_context(context_provider)
References CommandContextMixIn._in_main_context, CommandContextMixIn._main_context, and CommandContextMixIn.enter_context().
Referenced by CommandContextMixIn.enter_context(), DownloadCommand.run(), InstallCommand.run(), and WheelCommand.run().
main_context()
Generator[None, None, None] main_context (self)
Definition at line 14 of file command_context.py.
    def main_context(self) -> Generator[None, None, None]:
        assert not self._in_main_context
        self._in_main_context = True
        try:
            with self._main_context:
                yield
        finally:
            self._in_main_context = False
References CommandContextMixIn._in_main_context, and CommandContextMixIn._main_context.
Referenced by Command.main().
Field Documentation
_in_main_context
_in_main_context protected
Definition at line 10 of file command_context.py.
Referenced by CommandContextMixIn.enter_context(), and CommandContextMixIn.main_context().
_main_context
_main_context protected
Definition at line 11 of file command_context.py.
Referenced by CommandContextMixIn.enter_context(), and CommandContextMixIn.main_context().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/cli/command_context.py