Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: pip._vendor.packaging.utils Namespace Reference
pip._vendor.packaging.utils Namespace Reference
Data Structures
class InvalidSdistFilename
class InvalidWheelFilename
Functions
NormalizedName canonicalize_name (str name)
str canonicalize_version (Union[Version, str] version)
Tuple[NormalizedName, Version, BuildTag, FrozenSet[Tag]] parse_wheel_filename (str filename)
Tuple[NormalizedName, Version] parse_sdist_filename (str filename)
Variables
BuildTag = Union[Tuple[()], Tuple[int, str]]
NormalizedName = NewType("NormalizedName", str)
_canonicalize_regex = re.compile(r"[-_.]+")
_build_tag_regex = re.compile(r"(\d+)(.*)")
Function Documentation
canonicalize_name()
NormalizedName canonicalize_name (str name)
Definition at line 32 of file utils.py.
def canonicalize_name(name: str) -> NormalizedName:
    # This is taken from PEP 503.
    value = _canonicalize_regex.sub("-", name).lower()
    return cast(NormalizedName, value)
Referenced by parse_sdist_filename(), and parse_wheel_filename().
canonicalize_version()
str canonicalize_version (Union[Version, str] version)
This is very similar to Version.__str__, but has one subtle difference
with the way it handles the release segment.
Definition at line 38 of file utils.py.
def canonicalize_version(version: Union[Version, str]) -> str:
    """
    This is very similar to Version.__str__, but has one subtle difference
    with the way it handles the release segment.
    """
    if isinstance(version, str):
        try:
            parsed = Version(version)
        except InvalidVersion:
            # Legacy versions cannot be normalized
            return version
    else:
        parsed = version
    parts = []
    # Epoch
    if parsed.epoch != 0:
        parts.append(f"{parsed.epoch}!")
    # Release segment
    # NB: This strips trailing '.0's to normalize
    parts.append(re.sub(r"(\.0)+$", "", ".".join(str(x) for x in parsed.release)))
    # Pre-release
    if parsed.pre is not None:
        parts.append("".join(str(x) for x in parsed.pre))
    # Post-release
    if parsed.post is not None:
        parts.append(f".post{parsed.post}")
    # Development release
    if parsed.dev is not None:
        parts.append(f".dev{parsed.dev}")
    # Local version segment
    if parsed.local is not None:
        parts.append(f"+{parsed.local}")
    return "".join(parts)
parse_sdist_filename()
Tuple[NormalizedName, Version] parse_sdist_filename (str filename)
Definition at line 117 of file utils.py.
def parse_sdist_filename(filename: str) -> Tuple[NormalizedName, Version]:
    if filename.endswith(".tar.gz"):
        file_stem = filename[: -len(".tar.gz")]
    elif filename.endswith(".zip"):
        file_stem = filename[: -len(".zip")]
    else:
        raise InvalidSdistFilename(
            f"Invalid sdist filename (extension must be '.tar.gz' or '.zip'):"
            f" {filename}"
        )
    # We are requiring a PEP 440 version, which cannot contain dashes,
    # so we split on the last dash.
    name_part, sep, version_part = file_stem.rpartition("-")
    if not sep:
        raise InvalidSdistFilename(f"Invalid sdist filename: {filename}")
    name = canonicalize_name(name_part)
    version = Version(version_part)
    return (name, version)
References canonicalize_name().
parse_wheel_filename()
Tuple[NormalizedName, Version, BuildTag, FrozenSet[Tag]] parse_wheel_filename (str filename)
Definition at line 81 of file utils.py.
) -> Tuple[NormalizedName, Version, BuildTag, FrozenSet[Tag]]:
    if not filename.endswith(".whl"):
        raise InvalidWheelFilename(
            f"Invalid wheel filename (extension must be '.whl'): {filename}"
        )
    filename = filename[:-4]
    dashes = filename.count("-")
    if dashes not in (4, 5):
        raise InvalidWheelFilename(
            f"Invalid wheel filename (wrong number of parts): {filename}"
        )
    parts = filename.split("-", dashes - 2)
    name_part = parts[0]
    # See PEP 427 for the rules on escaping the project name
    if "__" in name_part or re.match(r"^[\w\d._]*$", name_part, re.UNICODE) is None:
        raise InvalidWheelFilename(f"Invalid project name: {filename}")
    name = canonicalize_name(name_part)
    version = Version(parts[1])
    if dashes == 5:
        build_part = parts[2]
        build_match = _build_tag_regex.match(build_part)
        if build_match is None:
            raise InvalidWheelFilename(
                f"Invalid build number: {build_part} in '{filename}'"
            )
        build = cast(BuildTag, (int(build_match.group(1)), build_match.group(2)))
    else:
        build = ()
    tags = parse_tag(parts[-1])
    return (name, version, build, tags)
References canonicalize_name().
Variable Documentation
_build_tag_regex
_build_tag_regex = re.compile(r"(\d+)(.*)") protected
Definition at line 29 of file utils.py.
_canonicalize_regex
_canonicalize_regex = re.compile(r"[-_.]+") protected
Definition at line 27 of file utils.py.
BuildTag
BuildTag = Union[Tuple[()], Tuple[int, str]]
Definition at line 11 of file utils.py.
NormalizedName
NormalizedName = NewType("NormalizedName", str)
Definition at line 12 of file utils.py.