Let us walk on the 3-isogeny graph: ExpiresAfter Class Reference
ExpiresAfter Class Reference
Public Member Functions
__init__ (self, **kw)
update_headers (self, response)
warning (self, response)
Public Member Functions inherited from BaseHeuristic
apply (self, response)
Data Fields
delta
Detailed Description
Cache **all** requests for a defined time period.
Definition at line 75 of file heuristics.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, ** kw)
Definition at line 80 of file heuristics.py.
    def __init__(self, **kw):
        self.delta = timedelta(**kw)
Referenced by Protocol.__init_subclass__().
Member Function Documentation
update_headers()
update_headers (self, response)
Update the response headers with any new headers.
NOTE: This SHOULD always include some Warning header to
      signify that the response was cached by the client, not
      by way of the provided headers.
Reimplemented from BaseHeuristic.
Definition at line 83 of file heuristics.py.
    def update_headers(self, response):
        expires = expire_after(self.delta)
        return {"expires": datetime_to_header(expires), "cache-control": "public"}
References pip._vendor.cachecontrol.heuristics.datetime_to_header(), ExpiresAfter.delta, and pip._vendor.cachecontrol.heuristics.expire_after().
Referenced by BaseHeuristic.apply().
warning()
warning (self, response)
Return a valid 1xx warning header value describing the cache
adjustments.
The response is provided too allow warnings like 113
http://tools.ietf.org/html/rfc7234#section-5.5.4 where we need
to explicitly say response is over 24 hours old.
Reimplemented from BaseHeuristic.
Definition at line 87 of file heuristics.py.
    def warning(self, response):
        tmpl = "110 - Automatically cached for %s. Response might be stale"
        return tmpl % self.delta
References ExpiresAfter.delta.
Referenced by BaseHeuristic.apply().
Field Documentation
delta
delta
Definition at line 81 of file heuristics.py.
Referenced by ExpiresAfter.update_headers(), and ExpiresAfter.warning().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/cachecontrol/heuristics.py