Let us walk on the 3-isogeny graph: EditableCandidate Class Reference
EditableCandidate Class Reference
Public Member Functions
None __init__ (self, Link link, InstallRequirement template, "Factory" factory, Optional[NormalizedName] name=None, Optional[CandidateVersion] version=None)
Public Member Functions inherited from _InstallRequirementBackedCandidate
str __str__ (self)
str __repr__ (self)
int __hash__ (self)
bool __eq__ (self, Any other)
Optional[Link] source_link (self)
NormalizedName project_name (self)
str name (self)
CandidateVersion version (self)
str format_for_error (self)
Iterable[Optional[Requirement]] iter_dependencies (self, bool with_requires)
Optional[InstallRequirement] get_install_requirement (self)
Public Member Functions inherited from Candidate
bool is_installed (self)
bool is_editable (self)
Static Public Attributes
bool is_editable = True
Static Public Attributes inherited from _InstallRequirementBackedCandidate
BaseDistribution dist
bool is_installed = False
Protected Member Functions
BaseDistribution _prepare_distribution (self)
Protected Member Functions inherited from _InstallRequirementBackedCandidate
None _check_metadata_consistency (self, BaseDistribution dist)
BaseDistribution _prepare (self)
Protected Attributes
_ireq
Protected Attributes inherited from _InstallRequirementBackedCandidate
_link
_source_link
_factory
_ireq
_name
_version
Additional Inherited Members
Data Fields inherited from _InstallRequirementBackedCandidate
dist
name
version
Detailed Description
Definition at line 307 of file candidates.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, Link link, InstallRequirement template, "Factory" factory, Optional[NormalizedName] name = None, Optional[CandidateVersion] version = None)
Reimplemented from _InstallRequirementBackedCandidate.
Definition at line 310 of file candidates.py.
    ) -> None:
        super().__init__(
            link=link,
            source_link=link,
            ireq=make_install_req_from_editable(link, template),
            factory=factory,
            name=name,
            version=version,
        )
References EditableCandidate.__init__(), i, and pip._internal.resolution.resolvelib.candidates.make_install_req_from_editable().
Referenced by EditableCandidate.__init__(), and Protocol.__init_subclass__().
Member Function Documentation
_prepare_distribution()
BaseDistribution _prepare_distribution (self) protected
Reimplemented from _InstallRequirementBackedCandidate.
Definition at line 327 of file candidates.py.
    def _prepare_distribution(self) -> BaseDistribution:
        return self._factory.preparer.prepare_editable_requirement(self._ireq)
Referenced by _InstallRequirementBackedCandidate._prepare().
Field Documentation
_ireq
_ireq protected
Definition at line 328 of file candidates.py.
Referenced by SpecifierRequirement.__repr__(), SpecifierRequirement.__str__(), _InstallRequirementBackedCandidate._check_metadata_consistency(), _InstallRequirementBackedCandidate._prepare(), SpecifierRequirement.get_candidate_lookup(), _InstallRequirementBackedCandidate.get_install_requirement(), SpecifierRequirement.is_satisfied_by(), _InstallRequirementBackedCandidate.iter_dependencies(), AlreadyInstalledCandidate.iter_dependencies(), and SpecifierRequirement.project_name().
is_editable
bool is_editable = True static
Definition at line 308 of file candidates.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/candidates.py