Let us walk on the 3-isogeny graph: ResolutionTooDeep Class Reference
ResolutionTooDeep Class Reference
Public Member Functions
__init__ (self, round_count)
Data Fields
round_count
Detailed Description
Definition at line 95 of file resolvers.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, round_count)
Definition at line 96 of file resolvers.py.
    def __init__(self, round_count):
        super(ResolutionTooDeep, self).__init__(round_count)
        self.round_count = round_count
# Resolution state in a round.
References ResolutionTooDeep.__init__(), and i.
Referenced by ResolutionTooDeep.__init__(), and Protocol.__init_subclass__().
Field Documentation
round_count
round_count
Definition at line 98 of file resolvers.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py