Let us walk on the 3-isogeny graph: ResolutionImpossible Class Reference
ResolutionImpossible Class Reference
Public Member Functions
__init__ (self, causes)
Data Fields
causes
Detailed Description
Definition at line 88 of file resolvers.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, causes)
Definition at line 89 of file resolvers.py.
    def __init__(self, causes):
        super(ResolutionImpossible, self).__init__(causes)
        # causes is a list of RequirementInformation objects
        self.causes = causes
References ResolutionImpossible.__init__(), and i.
Referenced by ResolutionImpossible.__init__(), and Protocol.__init_subclass__().
Field Documentation
causes
causes
Definition at line 92 of file resolvers.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/resolvelib/resolvers.py