Let us walk on the 3-isogeny graph: StyleStack Class Reference
StyleStack Class Reference
Public Member Functions
None __init__ (self, "Style" default_style)
str __repr__ (self)
Style current (self)
None push (self, Style style)
Style pop (self)
Detailed Description
A stack of styles.
Definition at line 765 of file style.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, "Style" default_style)
Definition at line 770 of file style.py.
    def __init__(self, default_style: "Style") -> None:
        self._stack: List[Style] = [default_style]
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__repr__()
str __repr__ (self)
Definition at line 773 of file style.py.
    def __repr__(self) -> str:
        return f"<stylestack {self._stack!r}>"
current()
Style current (self)
Get the Style at the top of the stack.
Definition at line 777 of file style.py.
    def current(self) -> Style:
        """Get the Style at the top of the stack."""
        return self._stack[-1]
pop()
Style pop (self)
Pop last style and discard.
Returns:
    Style: New current style (also available as stack.current)
Definition at line 789 of file style.py.
    def pop(self) -> Style:
        """Pop last style and discard.
        Returns:
            Style: New current style (also available as stack.current)
        """
        self._stack.pop()
        return self._stack[-1]
References StyleStack.pop().
Referenced by StyleStack.pop().
push()
None push (self, Style style)
Push a new style on to the stack.
Args:
    style (Style): New style to combine with current style.
Definition at line 781 of file style.py.
    def push(self, style: Style) -> None:
        """Push a new style on to the stack.
        Args:
            style (Style): New style to combine with current style.
        """
        self._stack.append(self._stack[-1] + style)
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/rich/style.py