Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: BaseHeuristic Class Reference
BaseHeuristic Class Reference
Public Member Functions
warning (self, response)
update_headers (self, response)
apply (self, response)
Detailed Description
Definition at line 24 of file heuristics.py.
Member Function Documentation
apply()
apply (self, response)
Definition at line 46 of file heuristics.py.
    def apply(self, response):
        updated_headers = self.update_headers(response)
        if updated_headers:
            response.headers.update(updated_headers)
            warning_header_value = self.warning(response)
            if warning_header_value is not None:
                response.headers.update({"Warning": warning_header_value})
        return response
References update_headers(), and warning().
update_headers()
update_headers (self, response)
Update the response headers with any new headers.
NOTE: This SHOULD always include some Warning header to
      signify that the response was cached by the client, not
      by way of the provided headers.
Reimplemented in ExpiresAfter, LastModified, and OneDayCache.
Definition at line 37 of file heuristics.py.
    def update_headers(self, response):
        """Update the response headers with any new headers.
        NOTE: This SHOULD always include some Warning header to
              signify that the response was cached by the client, not
              by way of the provided headers.
        """
        return {}
Referenced by apply().
warning()
warning (self, response)
Return a valid 1xx warning header value describing the cache
adjustments.
The response is provided too allow warnings like 113
http://tools.ietf.org/html/rfc7234#section-5.5.4 where we need
to explicitly say response is over 24 hours old.
Reimplemented in ExpiresAfter, and LastModified.
Definition at line 26 of file heuristics.py.
    def warning(self, response):
        """
        Return a valid 1xx warning header value describing the cache
        adjustments.
        The response is provided too allow warnings like 113
        http://tools.ietf.org/html/rfc7234#section-5.5.4 where we need
        to explicitly say response is over 24 hours old.
        """
        return '110 - "Response is Stale"'
Referenced by apply().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/cachecontrol/heuristics.py