Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: UninstallPthEntries Class Reference
UninstallPthEntries Class Reference
Public Member Functions
None __init__ (self, str pth_file)
None add (self, str entry)
None remove (self)
bool rollback (self)
Data Fields
file = pth_file
Set[str] entries = set()
Protected Attributes
Optional[List[bytes]] _saved_lines = None
Detailed Description
Definition at line 595 of file req_uninstall.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, str pth_file)
Definition at line 596 of file req_uninstall.py.
    def __init__(self, pth_file: str) -> None:
        self.file = pth_file
        self.entries: Set[str] = set()
        self._saved_lines: Optional[List[bytes]] = None
Member Function Documentation
add()
None add (self, str entry)
Definition at line 601 of file req_uninstall.py.
    def add(self, entry: str) -> None:
        entry = os.path.normcase(entry)
        # On Windows, os.path.normcase converts the entry to use
        # backslashes.  This is correct for entries that describe absolute
        # paths outside of site-packages, but all the others use forward
        # slashes.
        # os.path.splitdrive is used instead of os.path.isabs because isabs
        # treats non-absolute paths with drive letter markings like c:foo\bar
        # as absolute paths. It also does not recognize UNC paths if they don't
        # have more than "\\sever\share". Valid examples: "\\server\share\" or
        # "\\server\share\folder".
        if WINDOWS and not os.path.splitdrive(entry)[0]:
            entry = entry.replace("\\", "/")
        self.entries.add(entry)
References add(), and entries.
Referenced by add(), Manifest.add_many(), and HTTPHeaderDict.extend().
remove()
None remove (self)
Definition at line 616 of file req_uninstall.py.
    def remove(self) -> None:
        logger.verbose("Removing pth entries from %s:", self.file)
        # If the file doesn't exist, log a warning and return
        if not os.path.isfile(self.file):
            logger.warning("Cannot remove entries from nonexistent file %s", self.file)
            return
        with open(self.file, "rb") as fh:
            # windows uses '\r\n' with py3k, but uses '\n' with py2.x
            lines = fh.readlines()
            self._saved_lines = lines
        if any(b"\r\n" in line for line in lines):
            endline = "\r\n"
        else:
            endline = "\n"
        # handle missing trailing newline
        if lines and not lines[-1].endswith(endline.encode("utf-8")):
            lines[-1] = lines[-1] + endline.encode("utf-8")
        for entry in self.entries:
            try:
                logger.verbose("Removing entry: %s", entry)
                lines.remove((entry + endline).encode("utf-8"))
            except ValueError:
                pass
        with open(self.file, "wb") as fh:
            fh.writelines(lines)
References _saved_lines, entries, and file.
Referenced by Sequencer.remove_node().
rollback()
bool rollback (self)
Definition at line 643 of file req_uninstall.py.
    def rollback(self) -> bool:
        if self._saved_lines is None:
            logger.error("Cannot roll back changes to %s, none were made", self.file)
            return False
        logger.debug("Rolling %s back to previous state", self.file)
        with open(self.file, "wb") as fh:
            fh.writelines(self._saved_lines)
        return True
References _saved_lines, and file.
Field Documentation
_saved_lines
_saved_lines = None protected
Definition at line 599 of file req_uninstall.py.
Referenced by remove(), and rollback().
entries
Set[str] entries = set()
Definition at line 598 of file req_uninstall.py.
Referenced by add(), and remove().
file
file = pth_file
Definition at line 597 of file req_uninstall.py.
Referenced by Console.is_terminal(), remove(), and rollback().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/req/req_uninstall.py