Let us walk on the 3-isogeny graph: pip._vendor.cachecontrol.serialize Namespace Reference
pip._vendor.cachecontrol.serialize Namespace Reference
Data Structures
class Serializer
Functions
_b64_decode_bytes (b)
_b64_decode_str (s)
Variables
_default_body_read = object()
Function Documentation
_b64_decode_bytes()
_b64_decode_bytes (b) protected
Definition at line 16 of file serialize.py.
def _b64_decode_bytes(b):
    return base64.b64decode(b.encode("ascii"))
References i.
Referenced by pip._vendor.cachecontrol.serialize._b64_decode_str(), and Serializer._loads_v2().
_b64_decode_str()
_b64_decode_str (s) protected
Definition at line 20 of file serialize.py.
def _b64_decode_str(s):
    return _b64_decode_bytes(s).decode("utf8")
References pip._vendor.cachecontrol.serialize._b64_decode_bytes().
Referenced by Serializer._loads_v2().
Variable Documentation
_default_body_read
_default_body_read = object() protected
Definition at line 24 of file serialize.py.