Let us walk on the 3-isogeny graph: NullProvider Class Reference
NullProvider Class Reference
Public Member Functions
__init__ (self, module)
get_resource_filename (self, manager, resource_name)
get_resource_stream (self, manager, resource_name)
get_resource_string (self, manager, resource_name)
has_resource (self, resource_name)
has_metadata (self, name)
get_metadata (self, name)
get_metadata_lines (self, name)
resource_isdir (self, resource_name)
metadata_isdir (self, name)
resource_listdir (self, resource_name)
metadata_listdir (self, name)
run_script (self, script_name, namespace)
Data Fields
module_path
Static Public Attributes
egg_name = None
egg_info = None
loader = None
Protected Member Functions
_get_metadata_path (self, name)
_has (self, path)
_isdir (self, path)
_listdir (self, path)
_fn (self, base, resource_name)
_get (self, path)
Static Protected Member Functions
_validate_resource_path (path)
Detailed Description
Try to implement resources and metadata for arbitrary PEP 302 loaders
Definition at line 1482 of file __init__.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, module)
Reimplemented in EmptyProvider, EggMetadata, EggProvider, ZipProvider, FileMetadata, and PathMetadata.
Definition at line 1489 of file __init__.py.
    def __init__(self, module):
        self.loader = getattr(module, '__loader__', None)
        self.module_path = os.path.dirname(getattr(module, '__file__', ''))
Referenced by Protocol.__init_subclass__().
Member Function Documentation
_fn()
_fn (self, base, resource_name) protected
Definition at line 1589 of file __init__.py.
    def _fn(self, base, resource_name):
        self._validate_resource_path(resource_name)
        if resource_name:
            return os.path.join(base, *resource_name.split('/'))
        return base
Referenced by _FileCacheMixin._delete(), _FileCacheMixin.get(), SeparateBodyFileCache.get_body(), _FileCacheMixin.set(), and SeparateBodyFileCache.set_body().
_get()
_get (self, path) protected
Reimplemented in DefaultProvider, and EmptyProvider.
Definition at line 1669 of file __init__.py.
    def _get(self, path):
        if hasattr(self.loader, 'get_data'):
            return self.loader.get_data(path)
        raise NotImplementedError(
            "Can't perform this operation for loaders without 'get_data()'"
        )
_get_metadata_path()
_get_metadata_path (self, name) protected
Reimplemented in FileMetadata.
Definition at line 1505 of file __init__.py.
    def _get_metadata_path(self, name):
        return self._fn(self.egg_info, name)
_has()
_has (self, path) protected
Reimplemented in ZipProvider, and DefaultProvider.
Definition at line 1574 of file __init__.py.
    def _has(self, path):
        raise NotImplementedError(
            "Can't perform this operation for unregistered loader type"
        )
_isdir()
_isdir (self, path) protected
Reimplemented in ZipProvider, and DefaultProvider.
Definition at line 1579 of file __init__.py.
    def _isdir(self, path):
        raise NotImplementedError(
            "Can't perform this operation for unregistered loader type"
        )
_listdir()
_listdir (self, path) protected
Reimplemented in ZipProvider, DefaultProvider, and EmptyProvider.
Definition at line 1584 of file __init__.py.
    def _listdir(self, path):
        raise NotImplementedError(
            "Can't perform this operation for unregistered loader type"
        )
_validate_resource_path()
_validate_resource_path (path) static protected
Validate the resource paths according to the docs.
https://setuptools.pypa.io/en/latest/pkg_resources.html#basic-resource-access
>>> warned = getfixture('recwarn')
>>> warnings.simplefilter('always')
>>> vrp = NullProvider._validate_resource_path
>>> vrp('foo/bar.txt')
>>> bool(warned)
False
>>> vrp('../foo/bar.txt')
>>> bool(warned)
True
>>> warned.clear()
>>> vrp('/foo/bar.txt')
>>> bool(warned)
True
>>> vrp('foo/../../bar.txt')
>>> bool(warned)
True
>>> warned.clear()
>>> vrp('foo/f../bar.txt')
>>> bool(warned)
False
Windows path separators are straight-up disallowed.
>>> vrp(r'\\foo/bar.txt')
Traceback (most recent call last):
...
ValueError: Use of .. or absolute path in a resource path \
is not allowed.
>>> vrp(r'C:\\foo/bar.txt')
Traceback (most recent call last):
...
ValueError: Use of .. or absolute path in a resource path \
is not allowed.
Blank values are allowed
>>> vrp('')
>>> bool(warned)
False
Non-string values are not.
>>> vrp(None)
Traceback (most recent call last):
...
AttributeError: ...
Definition at line 1596 of file __init__.py.
    def _validate_resource_path(path):
        """
        Validate the resource paths according to the docs.
        https://setuptools.pypa.io/en/latest/pkg_resources.html#basic-resource-access
        >>> warned = getfixture('recwarn')
        >>> warnings.simplefilter('always')
        >>> vrp = NullProvider._validate_resource_path
        >>> vrp('foo/bar.txt')
        >>> bool(warned)
        False
        >>> vrp('../foo/bar.txt')
        >>> bool(warned)
        True
        >>> warned.clear()
        >>> vrp('/foo/bar.txt')
        >>> bool(warned)
        True
        >>> vrp('foo/../../bar.txt')
        >>> bool(warned)
        True
        >>> warned.clear()
        >>> vrp('foo/f../bar.txt')
        >>> bool(warned)
        False
        Windows path separators are straight-up disallowed.
        >>> vrp(r'\\foo/bar.txt')
        Traceback (most recent call last):
        ...
        ValueError: Use of .. or absolute path in a resource path \
is not allowed.
        >>> vrp(r'C:\\foo/bar.txt')
        Traceback (most recent call last):
        ...
        ValueError: Use of .. or absolute path in a resource path \
is not allowed.
        Blank values are allowed
        >>> vrp('')
        >>> bool(warned)
        False
        Non-string values are not.
        >>> vrp(None)
        Traceback (most recent call last):
        ...
        AttributeError: ...
        """
        invalid = (
            os.path.pardir in path.split(posixpath.sep)
            or posixpath.isabs(path)
            or ntpath.isabs(path)
        )
        if not invalid:
            return
        msg = "Use of .. or absolute path in a resource path is not allowed."
        # Aggressively disallow Windows absolute paths
        if ntpath.isabs(path) and not posixpath.isabs(path):
            raise ValueError(msg)
        # for compatibility, warn; in future
        # raise ValueError(msg)
        issue_warning(
            msg[:-1] + " and will raise exceptions in a future release.",
            DeprecationWarning,
        )
get_metadata()
get_metadata (self, name)
Reimplemented in FileMetadata.
Definition at line 1515 of file __init__.py.
    def get_metadata(self, name):
        if not self.egg_info:
            return ""
        path = self._get_metadata_path(name)
        value = self._get(path)
        try:
            return value.decode('utf-8')
        except UnicodeDecodeError as exc:
            # Include the path in the error message to simplify
            # troubleshooting, and without changing the exception type.
            exc.reason += ' in {} file at path: {}'.format(name, path)
            raise
Referenced by InMemoryMetadata.get_metadata_lines().
get_metadata_lines()
get_metadata_lines (self, name)
Reimplemented in FileMetadata.
Definition at line 1528 of file __init__.py.
    def get_metadata_lines(self, name):
        return yield_lines(self.get_metadata(name))
get_resource_filename()
get_resource_filename (self, manager, resource_name)
Reimplemented in ZipProvider.
Definition at line 1493 of file __init__.py.
    def get_resource_filename(self, manager, resource_name):
        return self._fn(self.module_path, resource_name)
get_resource_stream()
get_resource_stream (self, manager, resource_name)
Reimplemented in DefaultProvider.
Definition at line 1496 of file __init__.py.
    def get_resource_stream(self, manager, resource_name):
        return io.BytesIO(self.get_resource_string(manager, resource_name))
get_resource_string()
get_resource_string (self, manager, resource_name)
Definition at line 1499 of file __init__.py.
    def get_resource_string(self, manager, resource_name):
        return self._get(self._fn(self.module_path, resource_name))
has_metadata()
has_metadata (self, name)
Reimplemented in FileMetadata.
Definition at line 1508 of file __init__.py.
    def has_metadata(self, name):
        if not self.egg_info:
            return self.egg_info
        path = self._get_metadata_path(name)
        return self._has(path)
has_resource()
has_resource (self, resource_name)
Definition at line 1502 of file __init__.py.
    def has_resource(self, resource_name):
        return self._has(self._fn(self.module_path, resource_name))
metadata_isdir()
metadata_isdir (self, name)
Definition at line 1534 of file __init__.py.
    def metadata_isdir(self, name):
        return self.egg_info and self._isdir(self._fn(self.egg_info, name))
metadata_listdir()
metadata_listdir (self, name)
Definition at line 1540 of file __init__.py.
    def metadata_listdir(self, name):
        if self.egg_info:
            return self._listdir(self._fn(self.egg_info, name))
        return []
resource_isdir()
resource_isdir (self, resource_name)
Definition at line 1531 of file __init__.py.
    def resource_isdir(self, resource_name):
        return self._isdir(self._fn(self.module_path, resource_name))
resource_listdir()
resource_listdir (self, resource_name)
Definition at line 1537 of file __init__.py.
    def resource_listdir(self, resource_name):
        return self._listdir(self._fn(self.module_path, resource_name))
run_script()
run_script (self, script_name, namespace)
Definition at line 1545 of file __init__.py.
    def run_script(self, script_name, namespace):
        script = 'scripts/' + script_name
        if not self.has_metadata(script):
            raise ResolutionError(
                "Script {script!r} not found in metadata at {self.egg_info!r}".format(
                    **locals()
                ),
            )
        script_text = self.get_metadata(script).replace('\r\n', '\n')
        script_text = script_text.replace('\r', '\n')
        script_filename = self._fn(self.egg_info, script)
        namespace['__file__'] = script_filename
        if os.path.exists(script_filename):
            with open(script_filename) as fid:
                source = fid.read()
            code = compile(source, script_filename, 'exec')
            exec(code, namespace, namespace)
        else:
            from linecache import cache
            cache[script_filename] = (
                len(script_text),
                0,
                script_text.split('\n'),
                script_filename,
            )
            script_code = compile(script_text, script_filename, 'exec')
            exec(script_code, namespace, namespace)
Field Documentation
egg_info
egg_info = None static
Definition at line 1486 of file __init__.py.
egg_name
egg_name = None static
Definition at line 1485 of file __init__.py.
loader
loader = None static
Definition at line 1487 of file __init__.py.
Referenced by ZipResourceFinder.__init__(), ZipResourceFinder._find(), ZipResourceFinder.get_bytes(), and ZipResourceFinder.get_cache_info().
module_path
module_path
Definition at line 1491 of file __init__.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py