Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Requirement Class Reference
Requirement Class Reference
Public Member Functions
NormalizedName project_name (self)
str name (self)
bool is_satisfied_by (self, "Candidate" candidate)
CandidateLookup get_candidate_lookup (self)
str format_for_error (self)
Detailed Description
Definition at line 62 of file base.py.
Member Function Documentation
format_for_error()
str format_for_error (self)
Reimplemented in ExplicitRequirement, RequiresPythonRequirement, SpecifierRequirement, and UnsatisfiableRequirement.
Definition at line 88 of file base.py.
    def format_for_error(self) -> str:
        raise NotImplementedError("Subclass should override")
get_candidate_lookup()
CandidateLookup get_candidate_lookup (self)
Reimplemented in ExplicitRequirement, RequiresPythonRequirement, SpecifierRequirement, and UnsatisfiableRequirement.
Definition at line 85 of file base.py.
    def get_candidate_lookup(self) -> CandidateLookup:
        raise NotImplementedError("Subclass should override")
is_satisfied_by()
bool is_satisfied_by (self, "Candidate" candidate)
Reimplemented in ExplicitRequirement, RequiresPythonRequirement, SpecifierRequirement, and UnsatisfiableRequirement.
Definition at line 82 of file base.py.
    def is_satisfied_by(self, candidate: "Candidate") -> bool:
        return False
name()
str name (self)
The name identifying this requirement in the resolver.
This is different from ``project_name`` if this requirement contains
extras, where ``project_name`` would not contain the ``[...]`` part.
Reimplemented in ExplicitRequirement, RequiresPythonRequirement, SpecifierRequirement, and UnsatisfiableRequirement.
Definition at line 74 of file base.py.
    def name(self) -> str:
        """The name identifying this requirement in the resolver.
        This is different from ``project_name`` if this requirement contains
        extras, where ``project_name`` would not contain the ``[...]`` part.
        """
        raise NotImplementedError("Subclass should override")
Referenced by ParserElement.__str__(), Tag.__str__(), SpecifierRequirement.is_satisfied_by(), and LinuxDistribution.linux_distribution().
project_name()
NormalizedName project_name (self)
The "project name" of a requirement.
This is different from ``name`` if this requirement contains extras,
in which case ``name`` would contain the ``[...]`` part, while this
refers to the name of the project.
Reimplemented in ExplicitRequirement, RequiresPythonRequirement, SpecifierRequirement, and UnsatisfiableRequirement.
Definition at line 64 of file base.py.
    def project_name(self) -> NormalizedName:
        """The "project name" of a requirement.
        This is different from ``name`` if this requirement contains extras,
        in which case ``name`` would contain the ``[...]`` part, while this
        refers to the name of the project.
        """
        raise NotImplementedError("Subclass should override")
Referenced by _InstallRequirementBackedCandidate.name(), and AlreadyInstalledCandidate.name().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/base.py