Let us walk on the 3-isogeny graph: Mounter Class Reference
Mounter Class Reference
Public Member Functions
__init__ (self)
add (self, pathname, extensions)
remove (self, pathname)
find_module (self, fullname, path=None)
load_module (self, fullname)
Data Fields
impure_wheels
libs
Detailed Description
Definition at line 129 of file wheel.py.
Constructor & Destructor Documentation
__init__()
__init__ (self)
Definition at line 130 of file wheel.py.
    def __init__(self):
        self.impure_wheels = {}
        self.libs = {}
Referenced by Protocol.__init_subclass__().
Member Function Documentation
add()
add (self, pathname, extensions)
Definition at line 134 of file wheel.py.
    def add(self, pathname, extensions):
        self.impure_wheels[pathname] = extensions
        self.libs.update(extensions)
References Mounter.impure_wheels, and Mounter.libs.
Referenced by UninstallPathSet.add(), Manifest.add_many(), HTTPHeaderDict.extend(), and BuildTracker.track().
find_module()
find_module (self, fullname, path = None)
Definition at line 144 of file wheel.py.
    def find_module(self, fullname, path=None):
        if fullname in self.libs:
            result = self
        else:
            result = None
        return result
References Mounter.libs.
load_module()
load_module (self, fullname)
Definition at line 151 of file wheel.py.
    def load_module(self, fullname):
        if fullname in sys.modules:
            result = sys.modules[fullname]
        else:
            if fullname not in self.libs:
                raise ImportError('unable to find extension for %s' % fullname)
            result = _load_dynamic(fullname, self.libs[fullname])
            result.__loader__ = self
            parts = fullname.rsplit('.', 1)
            if len(parts) > 1:
                result.__package__ = parts[0]
        return result
References pip._vendor.distlib.wheel._load_dynamic(), i, and Mounter.libs.
Referenced by _SixMetaPathImporter.create_module().
remove()
remove (self, pathname)
Definition at line 138 of file wheel.py.
    def remove(self, pathname):
        extensions = self.impure_wheels.pop(pathname)
        for k, v in extensions:
            if k in self.libs:
                del self.libs[k]
References Mounter.impure_wheels, and Mounter.libs.
Referenced by Sequencer.remove_node(), and BuildTracker.track().
Field Documentation
impure_wheels
impure_wheels
Definition at line 131 of file wheel.py.
Referenced by Mounter.add(), and Mounter.remove().
libs
libs
Definition at line 132 of file wheel.py.
Referenced by Mounter.add(), Mounter.find_module(), Mounter.load_module(), and Mounter.remove().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/wheel.py