Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: _NamedTupleMeta Class Reference
_NamedTupleMeta Class Reference
Public Member Functions
__new__ (cls, typename, bases, ns)
Detailed Description
Definition at line 2611 of file typing_extensions.py.
Member Function Documentation
__new__()
__new__ (cls, typename, bases, ns)
Definition at line 2612 of file typing_extensions.py.
        def __new__(cls, typename, bases, ns):
            assert _NamedTuple in bases
            for base in bases:
                if base is not _NamedTuple and base is not typing.Generic:
                    raise TypeError(
                        'can only inherit from a NamedTuple type and Generic')
            bases = tuple(tuple if base is _NamedTuple else base for base in bases)
            types = ns.get('__annotations__', {})
            default_names = []
            for field_name in types:
                if field_name in ns:
                    default_names.append(field_name)
                elif default_names:
                    raise TypeError(f"Non-default namedtuple field {field_name} "
                                    f"cannot follow default field"
                                    f"{'s' if len(default_names) > 1 else ''} "
                                    f"{', '.join(default_names)}")
            nm_tpl = _make_nmtuple(
                typename, types.items(),
                defaults=[ns[n] for n in default_names],
                module=ns['__module__']
            )
            nm_tpl.__bases__ = bases
            if typing.Generic in bases:
                if hasattr(typing, '_generic_class_getitem'):  # 3.12+
                    nm_tpl.__class_getitem__ = classmethod(typing._generic_class_getitem)
                else:
                    class_getitem = typing.Generic.__class_getitem__.__func__
                    nm_tpl.__class_getitem__ = classmethod(class_getitem)
            # update from user namespace without overriding special namedtuple attributes
            for key in ns:
                if key in _prohibited_namedtuple_fields:
                    raise AttributeError("Cannot overwrite NamedTuple attribute " + key)
                elif key not in _special_namedtuple_fields and key not in nm_tpl._fields:
                    setattr(nm_tpl, key, ns[key])
            if typing.Generic in bases:
                nm_tpl.__init_subclass__()
            return nm_tpl
    _NamedTuple = type.__new__(_NamedTupleMeta, 'NamedTuple', (), {})
References pip._vendor.typing_extensions._make_nmtuple().
Referenced by Style._add(), Style.clear_meta_and_links(), Style.copy(), Style.from_color(), JSON.from_data(), Style.from_meta(), Style.update_link(), and Style.without_color().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/typing_extensions.py