Let us walk on the 3-isogeny graph: pip._vendor.msgpack.fallback Namespace Reference
pip._vendor.msgpack.fallback Namespace Reference
Data Structures
class Packer
class StringIO
class Unpacker
Functions
dict_iteritems (d)
_is_recursionerror (e)
_check_type_strict (obj, t, type=type, tuple=tuple)
_get_data_from_buffer (obj)
unpackb (packed, **kwargs)
_unpack_from (f, b, o=0)
Variables
int PY2 = 2
tuple int_types = (int, long)
unicode = str
xrange = range
RecursionError = RuntimeError
bool USING_STRINGBUILDER = True
newlist_hint = lambda size: []
int EX_SKIP = 0
int EX_CONSTRUCT = 1
int EX_READ_ARRAY_HEADER = 2
int EX_READ_MAP_HEADER = 3
int TYPE_IMMEDIATE = 0
int TYPE_ARRAY = 1
int TYPE_MAP = 2
int TYPE_RAW = 3
int TYPE_BIN = 4
int TYPE_EXT = 5
int DEFAULT_RECURSE_LIMIT = 511
_unpack_from = struct.unpack_from
str _NO_FORMAT_USED = ""
dict _MSGPACK_HEADERS
Detailed Description
Fallback pure Python implementation of msgpack
Function Documentation
_check_type_strict()
_check_type_strict (obj, t, type = type, tuple = tuple) protected
Definition at line 96 of file fallback.py.
def _check_type_strict(obj, t, type=type, tuple=tuple):
    if type(t) is tuple:
        return type(obj) in t
    else:
        return type(obj) is t
_get_data_from_buffer()
_get_data_from_buffer (obj) protected
Definition at line 103 of file fallback.py.
def _get_data_from_buffer(obj):
    view = memoryview(obj)
    if view.itemsize != 1:
        raise ValueError("cannot unpack from multi-byte object")
    return view
References i.
Referenced by Unpacker.feed().
_is_recursionerror()
_is_recursionerror (e) protected
Definition at line 27 of file fallback.py.
    def _is_recursionerror(e):
        return (
            len(e.args) == 1
            and isinstance(e.args[0], str)
            and e.args[0].startswith("maximum recursion depth exceeded")
        )
References i.
Referenced by pip._vendor.msgpack.fallback.unpackb().
_unpack_from()
_unpack_from (f, b, o = 0) protected
Explicit type cast for legacy struct.unpack_from
Definition at line 139 of file fallback.py.
    def _unpack_from(f, b, o=0):
        """Explicit type cast for legacy struct.unpack_from"""
        return struct.unpack_from(f, bytes(b), o)
References i.
dict_iteritems()
dict_iteritems (d)
Definition at line 11 of file fallback.py.
    def dict_iteritems(d):
        return d.iteritems()
References i.
Referenced by Packer._pack().
unpackb()
unpackb (packed, ** kwargs)
Unpack an object from `packed`.
Raises ``ExtraData`` when *packed* contains extra bytes.
Raises ``ValueError`` when *packed* is incomplete.
Raises ``FormatError`` when *packed* is not valid msgpack.
Raises ``StackError`` when *packed* contains too nested.
Other exceptions can be raised during unpacking.
See :class:`Unpacker` for options.
Definition at line 110 of file fallback.py.
def unpackb(packed, **kwargs):
    """
    Unpack an object from `packed`.
    Raises ``ExtraData`` when *packed* contains extra bytes.
    Raises ``ValueError`` when *packed* is incomplete.
    Raises ``FormatError`` when *packed* is not valid msgpack.
    Raises ``StackError`` when *packed* contains too nested.
    Other exceptions can be raised during unpacking.
    See :class:`Unpacker` for options.
    """
    unpacker = Unpacker(None, max_buffer_size=len(packed), **kwargs)
    unpacker.feed(packed)
    try:
        ret = unpacker._unpack()
    except OutOfData:
        raise ValueError("Unpack failed: incomplete input")
    except RecursionError as e:
        if _is_recursionerror(e):
            raise StackError
        raise
    if unpacker._got_extradata():
        raise ExtraData(ret, unpacker._get_extradata())
    return ret
References pip._vendor.msgpack.fallback._is_recursionerror(), and i.
Variable Documentation
_MSGPACK_HEADERS
dict _MSGPACK_HEADERS protected
Initial value:
=  {
    0xC4: (1, _NO_FORMAT_USED, TYPE_BIN),
    0xC5: (2, ">H", TYPE_BIN),
    0xC6: (4, ">I", TYPE_BIN),
    0xC7: (2, "Bb", TYPE_EXT),
    0xC8: (3, ">Hb", TYPE_EXT),
    0xC9: (5, ">Ib", TYPE_EXT),
    0xCA: (4, ">f"),
    0xCB: (8, ">d"),
    0xCC: (1, _NO_FORMAT_USED),
    0xCD: (2, ">H"),
    0xCE: (4, ">I"),
    0xCF: (8, ">Q"),
    0xD0: (1, "b"),
    0xD1: (2, ">h"),
    0xD2: (4, ">i"),
    0xD3: (8, ">q"),
    0xD4: (1, "b1s", TYPE_EXT),
    0xD5: (2, "b2s", TYPE_EXT),
    0xD6: (4, "b4s", TYPE_EXT),
    0xD7: (8, "b8s", TYPE_EXT),
    0xD8: (16, "b16s", TYPE_EXT),
    0xD9: (1, _NO_FORMAT_USED, TYPE_RAW),
    0xDA: (2, ">H", TYPE_RAW),
    0xDB: (4, ">I", TYPE_RAW),
    0xDC: (2, ">H", TYPE_ARRAY),
    0xDD: (4, ">I", TYPE_ARRAY),
    0xDE: (2, ">H", TYPE_MAP),
    0xDF: (4, ">I", TYPE_MAP),
}
Definition at line 147 of file fallback.py.
_NO_FORMAT_USED
str _NO_FORMAT_USED = "" protected
Definition at line 146 of file fallback.py.
_unpack_from
_unpack_from = struct.unpack_from protected
Definition at line 144 of file fallback.py.
Referenced by Unpacker._read_header().
DEFAULT_RECURSE_LIMIT
int DEFAULT_RECURSE_LIMIT = 511
Definition at line 93 of file fallback.py.
EX_CONSTRUCT
int EX_CONSTRUCT = 1
Definition at line 82 of file fallback.py.
EX_READ_ARRAY_HEADER
int EX_READ_ARRAY_HEADER = 2
Definition at line 83 of file fallback.py.
EX_READ_MAP_HEADER
int EX_READ_MAP_HEADER = 3
Definition at line 84 of file fallback.py.
EX_SKIP
int EX_SKIP = 0
Definition at line 81 of file fallback.py.
int_types
int_types = (int, long)
Definition at line 9 of file fallback.py.
newlist_hint
newlist_hint = lambda size: []
Definition at line 73 of file fallback.py.
PY2
int PY2 = 2
Definition at line 7 of file fallback.py.
RecursionError
RecursionError = RuntimeError
Definition at line 25 of file fallback.py.
TYPE_ARRAY
int TYPE_ARRAY = 1
Definition at line 87 of file fallback.py.
TYPE_BIN
int TYPE_BIN = 4
Definition at line 90 of file fallback.py.
TYPE_EXT
int TYPE_EXT = 5
Definition at line 91 of file fallback.py.
TYPE_IMMEDIATE
int TYPE_IMMEDIATE = 0
Definition at line 86 of file fallback.py.
TYPE_MAP
int TYPE_MAP = 2
Definition at line 88 of file fallback.py.
TYPE_RAW
int TYPE_RAW = 3
Definition at line 89 of file fallback.py.
unicode
unicode = str
Definition at line 16 of file fallback.py.
USING_STRINGBUILDER
USING_STRINGBUILDER = True
Definition at line 49 of file fallback.py.
xrange
xrange = range
Definition at line 17 of file fallback.py.
Referenced by Packer._pack(), and Unpacker._unpack().