Let us walk on the 3-isogeny graph: HookMissing Class Reference
HookMissing Class Reference
Public Member Functions
__init__ (self, hook_name)
Data Fields
hook_name
Detailed Description
Will be raised on missing hooks (if a fallback can't be used).
Definition at line 37 of file _impl.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, hook_name)
Definition at line 39 of file _impl.py.
    def __init__(self, hook_name):
        super().__init__(hook_name)
        self.hook_name = hook_name
References HookMissing.__init__(), and i.
Referenced by HookMissing.__init__(), and Protocol.__init_subclass__().
Field Documentation
hook_name
hook_name
Definition at line 41 of file _impl.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyproject_hooks/_impl.py