Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: pip._vendor.rich.diagnose Namespace Reference
pip._vendor.rich.diagnose Namespace Reference
Functions
None report ()
Function Documentation
report()
None report ()
Print a report to the terminal with debugging information
Definition at line 10 of file diagnose.py.
def report() -> None:  # pragma: no cover
    """Print a report to the terminal with debugging information"""
    console = Console()
    inspect(console)
    features = get_windows_console_features()
    inspect(features)
    env_names = (
        "TERM",
        "COLORTERM",
        "CLICOLOR",
        "NO_COLOR",
        "TERM_PROGRAM",
        "COLUMNS",
        "LINES",
        "JUPYTER_COLUMNS",
        "JUPYTER_LINES",
        "JPY_PARENT_PID",
        "VSCODE_VERBOSE_LOGGING",
    )
    env = {name: os.getenv(name) for name in env_names}
    console.print(Panel.fit((Pretty(env)), title="[b]Environment Variables"))
    console.print(f'platform="{platform.system()}"')
References pip._vendor.rich.inspect(), and report().
Referenced by report().