Let us walk on the 3-isogeny graph: Distribution Class Reference
Distribution Class Reference
Public Member Functions
__init__ (self, location=None, metadata=None, project_name=None, version=None, py_version=PY_MAJOR, platform=None, precedence=EGG_DIST)
from_location (cls, location, basename, metadata=None, **kw)
hashcmp (self)
__hash__ (self)
__lt__ (self, other)
__le__ (self, other)
__gt__ (self, other)
__ge__ (self, other)
__eq__ (self, other)
__ne__ (self, other)
key (self)
parsed_version (self)
version (self)
requires (self, extras=())
activate (self, path=None, replace=False)
egg_name (self)
__repr__ (self)
__str__ (self)
__getattr__ (self, attr)
__dir__ (self)
from_filename (cls, filename, metadata=None, **kw)
as_requirement (self)
load_entry_point (self, group, name)
get_entry_map (self, group=None)
get_entry_info (self, group, name)
insert_on (self, path, loc=None, replace=False)
check_version_conflict (self)
has_version (self)
clone (self, **kw)
extras (self)
Data Fields
project_name
py_version
platform
location
precedence
key
hashcmp
PKG_INFO
version
parsed_version
Static Public Attributes
str PKG_INFO = 'PKG-INFO'
Protected Member Functions
_reload_version (self)
_forgiving_parsed_version (self)
_dep_map (self)
_build_dep_map (self)
_get_metadata_path_for_display (self, name)
_get_metadata (self, name)
_get_version (self)
Static Protected Member Functions
_filter_extras (dm)
Protected Attributes
_version
_provider
_forgiving_parsed_version
_key
_parsed_version
Detailed Description
Wrap an actual or potential sys.path entry w/metadata
Definition at line 2629 of file __init__.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, location = None, metadata = None, project_name = None, version = None, py_version = PY_MAJOR, platform = None, precedence = EGG_DIST)
Definition at line 2634 of file __init__.py.
    ):
        self.project_name = safe_name(project_name or 'Unknown')
        if version is not None:
            self._version = safe_version(version)
        self.py_version = py_version
        self.platform = platform
        self.location = location
        self.precedence = precedence
        self._provider = metadata or empty_provider
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__dir__()
__dir__ (self)
Definition at line 2905 of file __init__.py.
    def __dir__(self):
        return list(
            set(super(Distribution, self).__dir__())
            | set(attr for attr in self._provider.__dir__() if not attr.startswith('_'))
        )
__eq__()
__eq__ (self, other)
Definition at line 2704 of file __init__.py.
    def __eq__(self, other):
        if not isinstance(other, self.__class__):
            # It's not a Distribution, so they are not equal
            return False
        return self.hashcmp == other.hashcmp
Referenced by Version.__ge__(), Version.__gt__(), Version.__le__(), Version.__ne__(), Matcher.__ne__(), Timestamp.__ne__(), and HTTPHeaderDict.__ne__().
__ge__()
__ge__ (self, other)
Definition at line 2701 of file __init__.py.
    def __ge__(self, other):
        return self.hashcmp >= other.hashcmp
__getattr__()
__getattr__ (self, attr)
Delegate all unrecognized public attributes to .metadata provider
Definition at line 2899 of file __init__.py.
    def __getattr__(self, attr):
        """Delegate all unrecognized public attributes to .metadata provider"""
        if attr.startswith('_'):
            raise AttributeError(attr)
        return getattr(self._provider, attr)
__gt__()
__gt__ (self, other)
Definition at line 2698 of file __init__.py.
    def __gt__(self, other):
        return self.hashcmp > other.hashcmp
Referenced by Version.__ge__().
__hash__()
__hash__ (self)
Definition at line 2689 of file __init__.py.
    def __hash__(self):
        return hash(self.hashcmp)
Referenced by Style.__eq__(), and Style.__ne__().
__le__()
__le__ (self, other)
Definition at line 2695 of file __init__.py.
    def __le__(self, other):
        return self.hashcmp <= other.hashcmp
__lt__()
__lt__ (self, other)
Definition at line 2692 of file __init__.py.
    def __lt__(self, other):
        return self.hashcmp < other.hashcmp
Referenced by Version.__gt__(), and Version.__le__().
__ne__()
__ne__ (self, other)
Definition at line 2710 of file __init__.py.
    def __ne__(self, other):
        return not self == other
__repr__()
__repr__ (self)
Definition at line 2885 of file __init__.py.
    def __repr__(self):
        if self.location:
            return "%s (%s)" % (self, self.location)
        else:
            return str(self)
__str__()
__str__ (self)
Definition at line 2891 of file __init__.py.
    def __str__(self):
        try:
            version = getattr(self, 'version', None)
        except ValueError:
            version = None
        version = version or "[unknown version]"
        return "%s %s" % (self.project_name, version)
_build_dep_map()
_build_dep_map (self) protected
Definition at line 2813 of file __init__.py.
    def _build_dep_map(self):
        dm = {}
        for name in 'requires.txt', 'depends.txt':
            for extra, reqs in split_sections(self._get_metadata(name)):
                dm.setdefault(extra, []).extend(parse_requirements(reqs))
        return dm
_dep_map()
_dep_map (self) protected
A map of extra to its list of (direct) requirements
for this distribution, including the null extra.
Reimplemented in DistInfoDistribution.
Definition at line 2781 of file __init__.py.
    def _dep_map(self):
        """
        A map of extra to its list of (direct) requirements
        for this distribution, including the null extra.
        """
        try:
            return self.__dep_map
        except AttributeError:
            self.__dep_map = self._filter_extras(self._build_dep_map())
        return self.__dep_map
_filter_extras()
_filter_extras (dm) static protected
Given a mapping of extras to dependencies, strip off
environment markers and filter out any dependencies
not matching the markers.
Definition at line 2793 of file __init__.py.
    def _filter_extras(dm):
        """
        Given a mapping of extras to dependencies, strip off
        environment markers and filter out any dependencies
        not matching the markers.
        """
        for extra in list(filter(None, dm)):
            new_extra = extra
            reqs = dm.pop(extra)
            new_extra, _, marker = extra.partition(':')
            fails_marker = marker and (
                invalid_marker(marker) or not evaluate_marker(marker)
            )
            if fails_marker:
                reqs = []
            new_extra = safe_extra(new_extra) or None
            dm.setdefault(new_extra, []).extend(reqs)
        return dm
_forgiving_parsed_version()
_forgiving_parsed_version (self) protected
Definition at line 2740 of file __init__.py.
    def _forgiving_parsed_version(self):
        try:
            return self.parsed_version
        except packaging.version.InvalidVersion as ex:
            self._parsed_version = parse_version(_forgiving_version(self.version))
            notes = "\n".join(getattr(ex, "__notes__", []))  # PEP 678
            msg = f"""!!\n\n
            *************************************************************************
            {str(ex)}\n{notes}
            This is a long overdue deprecation.
            For the time being, `pkg_resources` will use `{self._parsed_version}`
            as a replacement to avoid breaking existing environments,
            but no future compatibility is guaranteed.
            If you maintain package {self.project_name} you should implement
            the relevant changes to adequate the project to PEP 440 immediately.
            *************************************************************************
            \n\n!!
            """
            warnings.warn(msg, DeprecationWarning)
            return self._parsed_version
_get_metadata()
_get_metadata (self, name) protected
Definition at line 2851 of file __init__.py.
    def _get_metadata(self, name):
        if self.has_metadata(name):
            for line in self.get_metadata_lines(name):
                yield line
_get_metadata_path_for_display()
_get_metadata_path_for_display (self, name) protected
Return the path to the given metadata file, if available.
Definition at line 2834 of file __init__.py.
    def _get_metadata_path_for_display(self, name):
        """
        Return the path to the given metadata file, if available.
        """
        try:
            # We need to access _get_metadata_path() on the provider object
            # directly rather than through this class's __getattr__()
            # since _get_metadata_path() is marked private.
            path = self._provider._get_metadata_path(name)
        # Handle exceptions e.g. in case the distribution's metadata
        # provider doesn't support _get_metadata_path().
        except Exception:
            return '[could not detect]'
        return path
_get_version()
_get_version (self) protected
Definition at line 2856 of file __init__.py.
    def _get_version(self):
        lines = self._get_metadata(self.PKG_INFO)
        version = _version_from_file(lines)
        return version
_reload_version()
_reload_version (self) protected
Reimplemented in EggInfoDistribution.
Definition at line 2675 of file __init__.py.
    def _reload_version(self):
        return self
activate()
activate (self, path = None, replace = False)
Ensure distribution is importable on `path` (default=sys.path)
Definition at line 2862 of file __init__.py.
    def activate(self, path=None, replace=False):
        """Ensure distribution is importable on `path` (default=sys.path)"""
        if path is None:
            path = sys.path
        self.insert_on(path, replace=replace)
        if path is sys.path:
            fixup_namespace_packages(self.location)
            for pkg in self._get_metadata('namespace_packages.txt'):
                if pkg in sys.modules:
                    declare_namespace(pkg)
as_requirement()
as_requirement (self)
Return a ``Requirement`` that matches this distribution exactly
Definition at line 2917 of file __init__.py.
    def as_requirement(self):
        """Return a ``Requirement`` that matches this distribution exactly"""
        if isinstance(self.parsed_version, packaging.version.Version):
            spec = "%s==%s" % (self.project_name, self.parsed_version)
        else:
            spec = "%s===%s" % (self.project_name, self.parsed_version)
        return Requirement.parse(spec)
check_version_conflict()
check_version_conflict (self)
Definition at line 3018 of file __init__.py.
    def check_version_conflict(self):
        if self.key == 'setuptools':
            # ignore the inevitable setuptools self-conflicts  :(
            return
        nsp = dict.fromkeys(self._get_metadata('namespace_packages.txt'))
        loc = normalize_path(self.location)
        for modname in self._get_metadata('top_level.txt'):
            if (
                modname not in sys.modules
                or modname in nsp
                or modname in _namespace_packages
            ):
                continue
            if modname in ('pkg_resources', 'setuptools', 'site'):
                continue
            fn = getattr(sys.modules[modname], '__file__', None)
            if fn and (
                normalize_path(fn).startswith(loc) or fn.startswith(self.location)
            ):
                continue
            issue_warning(
                "Module %s was already imported from %s, but %s is being added"
                " to sys.path" % (modname, fn, self.location),
            )
clone()
clone (self, ** kw)
Copy this distribution, substituting in any changed keyword args
Definition at line 3055 of file __init__.py.
    def clone(self, **kw):
        """Copy this distribution, substituting in any changed keyword args"""
        names = 'project_name version py_version platform location precedence'
        for attr in names.split():
            kw.setdefault(attr, getattr(self, attr, None))
        kw.setdefault('metadata', self._provider)
        return self.__class__(**kw)
egg_name()
egg_name (self)
Return what this distribution's standard .egg filename should be
Definition at line 2873 of file __init__.py.
    def egg_name(self):
        """Return what this distribution's standard .egg filename should be"""
        filename = "%s-%s-py%s" % (
            to_filename(self.project_name),
            to_filename(self.version),
            self.py_version or PY_MAJOR,
        )
        if self.platform:
            filename += '-' + self.platform
        return filename
extras()
extras (self)
Definition at line 3064 of file __init__.py.
    def extras(self):
        return [dep for dep in self._dep_map if dep]
Referenced by ExtrasCandidate.__eq__(), ExtrasCandidate.__hash__(), ExtrasCandidate.__repr__(), ExtrasCandidate.__str__(), Requirement.__str__(), Distribution._get_requirements(), Metadata._to_legacy(), ExtrasCandidate.format_for_error(), Metadata.get_requirements(), ExtrasCandidate.iter_dependencies(), and ExtrasCandidate.name().
from_filename()
from_filename (cls, filename, metadata = None, ** kw)
Definition at line 2912 of file __init__.py.
    def from_filename(cls, filename, metadata=None, **kw):
        return cls.from_location(
            _normalize_cached(filename), os.path.basename(filename), metadata, **kw
        )
from_location()
from_location (cls, location, basename, metadata = None, ** kw)
Definition at line 2654 of file __init__.py.
    def from_location(cls, location, basename, metadata=None, **kw):
        project_name, version, py_version, platform = [None] * 4
        basename, ext = os.path.splitext(basename)
        if ext.lower() in _distributionImpl:
            cls = _distributionImpl[ext.lower()]
            match = EGG_NAME(basename)
            if match:
                project_name, version, py_version, platform = match.group(
                    'name', 'ver', 'pyver', 'plat'
                )
        return cls(
            location,
            metadata,
            project_name=project_name,
            version=version,
            py_version=py_version,
            platform=platform,
            **kw,
        )._reload_version()
get_entry_info()
get_entry_info (self, group, name)
Return the EntryPoint object for `group`+`name`, or ``None``
Definition at line 2945 of file __init__.py.
    def get_entry_info(self, group, name):
        """Return the EntryPoint object for `group`+`name`, or ``None``"""
        return self.get_entry_map(group).get(name)
get_entry_map()
get_entry_map (self, group = None)
Return the entry point map for `group`, or the full entry map
Definition at line 2933 of file __init__.py.
    def get_entry_map(self, group=None):
        """Return the entry point map for `group`, or the full entry map"""
        try:
            ep_map = self._ep_map
        except AttributeError:
            ep_map = self._ep_map = EntryPoint.parse_map(
                self._get_metadata('entry_points.txt'), self
            )
        if group is not None:
            return ep_map.get(group, {})
        return ep_map
has_version()
has_version (self)
Definition at line 3044 of file __init__.py.
    def has_version(self):
        try:
            self.version
        except ValueError:
            issue_warning("Unbuilt egg for " + repr(self))
            return False
        except SystemError:
            # TODO: remove this except clause when python/cpython#103632 is fixed.
            return False
        return True
hashcmp()
hashcmp (self)
Definition at line 2679 of file __init__.py.
    def hashcmp(self):
        return (
            self._forgiving_parsed_version,
            self.precedence,
            self.key,
            self.location,
            self.py_version or '',
            self.platform or '',
        )
insert_on()
insert_on (self, path, loc = None, replace = False)
Ensure self.location is on path
If replace=False (default):
    - If location is already in path anywhere, do nothing.
    - Else:
      - If it's an egg and its parent directory is on path,
        insert just ahead of the parent.
      - Else: add to the end of path.
If replace=True:
    - If location is already on path anywhere (not eggs)
      or higher priority than its parent (eggs)
      do nothing.
    - Else:
      - If it's an egg and its parent directory is on path,
        insert just ahead of the parent,
        removing any lower-priority entries.
      - Else: add it to the front of path.
Definition at line 2950 of file __init__.py.
    def insert_on(self, path, loc=None, replace=False):  # noqa: C901
        """Ensure self.location is on path
        If replace=False (default):
            - If location is already in path anywhere, do nothing.
            - Else:
              - If it's an egg and its parent directory is on path,
                insert just ahead of the parent.
              - Else: add to the end of path.
        If replace=True:
            - If location is already on path anywhere (not eggs)
              or higher priority than its parent (eggs)
              do nothing.
            - Else:
              - If it's an egg and its parent directory is on path,
                insert just ahead of the parent,
                removing any lower-priority entries.
              - Else: add it to the front of path.
        """
        loc = loc or self.location
        if not loc:
            return
        nloc = _normalize_cached(loc)
        bdir = os.path.dirname(nloc)
        npath = [(p and _normalize_cached(p) or p) for p in path]
        for p, item in enumerate(npath):
            if item == nloc:
                if replace:
                    break
                else:
                    # don't modify path (even removing duplicates) if
                    # found and not replace
                    return
            elif item == bdir and self.precedence == EGG_DIST:
                # if it's an .egg, give it precedence over its directory
                # UNLESS it's already been added to sys.path and replace=False
                if (not replace) and nloc in npath[p:]:
                    return
                if path is sys.path:
                    self.check_version_conflict()
                path.insert(p, loc)
                npath.insert(p, nloc)
                break
        else:
            if path is sys.path:
                self.check_version_conflict()
            if replace:
                path.insert(0, loc)
            else:
                path.append(loc)
            return
        # p is the spot where we found or inserted loc; now remove duplicates
        while True:
            try:
                np = npath.index(nloc, p + 1)
            except ValueError:
                break
            else:
                del npath[np], path[np]
                # ha!
                p = np
        return
key()
key (self)
Definition at line 2718 of file __init__.py.
    def key(self):
        try:
            return self._key
        except AttributeError:
            self._key = key = self.project_name.lower()
            return key
Referenced by Matcher.__eq__(), Matcher.__hash__(), and SelfCheckState.set().
load_entry_point()
load_entry_point (self, group, name)
Return the `name` entry point of `group` or raise ImportError
Definition at line 2926 of file __init__.py.
    def load_entry_point(self, group, name):
        """Return the `name` entry point of `group` or raise ImportError"""
        ep = self.get_entry_info(group, name)
        if ep is None:
            raise ImportError("Entry point %r not found" % ((group, name),))
        return ep.load()
parsed_version()
parsed_version (self)
Definition at line 2726 of file __init__.py.
    def parsed_version(self):
        if not hasattr(self, "_parsed_version"):
            try:
                self._parsed_version = parse_version(self.version)
            except packaging.version.InvalidVersion as ex:
                info = f"(package: {self.project_name})"
                if hasattr(ex, "add_note"):
                    ex.add_note(info)  # PEP 678
                    raise
                raise packaging.version.InvalidVersion(f"{str(ex)} {info}") from None
        return self._parsed_version
requires()
requires (self, extras = ())
List of Requirements needed for this distro if `extras` are used
Definition at line 2820 of file __init__.py.
    def requires(self, extras=()):
        """List of Requirements needed for this distro if `extras` are used"""
        dm = self._dep_map
        deps = []
        deps.extend(dm.get(None, ()))
        for ext in extras:
            try:
                deps.extend(dm[safe_extra(ext)])
            except KeyError as e:
                raise UnknownExtra(
                    "%s has no such extra feature %r" % (self, ext)
                ) from e
        return deps
version()
version (self)
Definition at line 2766 of file __init__.py.
    def version(self):
        try:
            return self._version
        except AttributeError as e:
            version = self._get_version()
            if version is None:
                path = self._get_metadata_path_for_display(self.PKG_INFO)
                msg = ("Missing 'Version:' header and/or {} file at path: {}").format(
                    self.PKG_INFO, path
                )
                raise ValueError(msg, self) from e
            return version
Referenced by AlreadyInstalledCandidate.__eq__(), Distribution.__eq__(), Distribution.__hash__(), InstallationCandidate.__repr__(), Distribution.__repr__(), Metadata.__repr__(), InstallationCandidate.__str__(), InstalledDistribution.__str__(), EggInfoDistribution.__str__(), PlatformDirsABC._append_app_name_and_version(), WrappedSocket._custom_validate(), Wheel._get_extensions(), Wheel.build(), Wheel.filename(), InstalledDistribution.get_distinfo_file(), Wheel.get_wheel_metadata(), LinuxDistribution.info(), Wheel.install(), LinuxDistribution.linux_distribution(), Wheel.metadata(), LinuxDistribution.name(), Distribution.name_and_version(), Distribution.provides(), Metadata.provides(), Wheel.update(), Wheel.verify(), and LinuxDistribution.version_parts().
Field Documentation
_forgiving_parsed_version
_forgiving_parsed_version protected
Definition at line 2681 of file __init__.py.
_key
_key protected
Definition at line 2722 of file __init__.py.
Referenced by _BaseVersion.__eq__(), _BaseVersion.__ge__(), _BaseVersion.__gt__(), _BaseVersion.__le__(), _BaseVersion.__lt__(), and _BaseVersion.__ne__().
_parsed_version
_parsed_version protected
Definition at line 2729 of file __init__.py.
_provider
_provider protected
Definition at line 2651 of file __init__.py.
_version
_version protected
Definition at line 2646 of file __init__.py.
Referenced by LegacyVersion.__str__(), _InstallRequirementBackedCandidate._check_metadata_consistency(), LegacyVersion.base_version(), Version.dev(), Version.epoch(), Version.local(), Version.post(), Version.pre(), LegacyVersion.public(), Version.release(), _InstallRequirementBackedCandidate.version(), AlreadyInstalledCandidate.version(), and RequiresPythonCandidate.version().
hashcmp
hashcmp
Definition at line 2690 of file __init__.py.
key
key
Definition at line 2683 of file __init__.py.
Referenced by Matcher.__eq__(), Matcher.__hash__(), and SelfCheckState.set().
location
location
Definition at line 2649 of file __init__.py.
Referenced by BaseDistribution._iter_declared_entries_from_legacy(), Distribution._metadata_impl(), FilesystemWheel.as_zipfile(), BaseDistribution.editable_project_location(), BaseDistribution.installed_as_egg(), and Distribution.installed_location().
parsed_version
parsed_version
Definition at line 2919 of file __init__.py.
PKG_INFO [1/2]
str PKG_INFO = 'PKG-INFO' static
Definition at line 2632 of file __init__.py.
PKG_INFO [2/2]
PKG_INFO
Definition at line 2774 of file __init__.py.
platform
platform
Definition at line 2648 of file __init__.py.
precedence
precedence
Definition at line 2650 of file __init__.py.
project_name
project_name
Definition at line 2644 of file __init__.py.
Referenced by SimpleScrapingLocator._process_download(), _InstallRequirementBackedCandidate.name(), and AlreadyInstalledCandidate.name().
py_version
py_version
Definition at line 2647 of file __init__.py.
version
version
Definition at line 2877 of file __init__.py.
Referenced by AlreadyInstalledCandidate.__eq__(), Distribution.__eq__(), Distribution.__hash__(), InstallationCandidate.__repr__(), Distribution.__repr__(), Metadata.__repr__(), InstallationCandidate.__str__(), InstalledDistribution.__str__(), EggInfoDistribution.__str__(), PlatformDirsABC._append_app_name_and_version(), WrappedSocket._custom_validate(), Wheel._get_extensions(), Wheel.build(), Wheel.filename(), InstalledDistribution.get_distinfo_file(), Wheel.get_wheel_metadata(), LinuxDistribution.info(), Wheel.install(), LinuxDistribution.linux_distribution(), Wheel.metadata(), LinuxDistribution.name(), Distribution.name_and_version(), Distribution.provides(), Metadata.provides(), Wheel.update(), Wheel.verify(), and LinuxDistribution.version_parts().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py