Let us walk on the 3-isogeny graph: pip._internal.utils.virtualenv Namespace Reference
pip._internal.utils.virtualenv Namespace Reference
Functions
bool _running_under_venv ()
bool _running_under_legacy_virtualenv ()
bool running_under_virtualenv ()
Optional[List[str]] _get_pyvenv_cfg_lines ()
bool _no_global_under_venv ()
bool _no_global_under_legacy_virtualenv ()
bool virtualenv_no_global ()
Variables
logger = logging.getLogger(__name__)
_INCLUDE_SYSTEM_SITE_PACKAGES_REGEX
Function Documentation
_get_pyvenv_cfg_lines()
Optional[List[str]] _get_pyvenv_cfg_lines () protected
Reads {sys.prefix}/pyvenv.cfg and returns its contents as list of lines
Returns None, if it could not read/access the file.
Definition at line 36 of file virtualenv.py.
def _get_pyvenv_cfg_lines() -> Optional[List[str]]:
    """Reads {sys.prefix}/pyvenv.cfg and returns its contents as list of lines
    Returns None, if it could not read/access the file.
    """
    pyvenv_cfg_file = os.path.join(sys.prefix, "pyvenv.cfg")
    try:
        # Although PEP 405 does not specify, the built-in venv module always
        # writes with UTF-8. (pypa/pip#8717)
        with open(pyvenv_cfg_file, encoding="utf-8") as f:
            return f.read().splitlines()  # avoids trailing newlines
    except OSError:
        return None
References i.
Referenced by pip._internal.utils.virtualenv._no_global_under_venv().
_no_global_under_legacy_virtualenv()
bool _no_global_under_legacy_virtualenv () protected
Check if "no-global-site-packages.txt" exists beside site.py
This mirrors logic in pypa/virtualenv for determining whether system
site-packages are visible in the virtual environment.
Definition at line 80 of file virtualenv.py.
def _no_global_under_legacy_virtualenv() -> bool:
    """Check if "no-global-site-packages.txt" exists beside site.py
    This mirrors logic in pypa/virtualenv for determining whether system
    site-packages are visible in the virtual environment.
    """
    site_mod_dir = os.path.dirname(os.path.abspath(site.__file__))
    no_global_site_packages_file = os.path.join(
        site_mod_dir,
        "no-global-site-packages.txt",
    )
    return os.path.exists(no_global_site_packages_file)
References i.
Referenced by pip._internal.utils.virtualenv.virtualenv_no_global().
_no_global_under_venv()
bool _no_global_under_venv () protected
Check `{sys.prefix}/pyvenv.cfg` for system site-packages inclusion
PEP 405 specifies that when system site-packages are not supposed to be
visible from a virtual environment, `pyvenv.cfg` must contain the following
line:
    include-system-site-packages = false
Additionally, log a warning if accessing the file fails.
Definition at line 51 of file virtualenv.py.
def _no_global_under_venv() -> bool:
    """Check `{sys.prefix}/pyvenv.cfg` for system site-packages inclusion
    PEP 405 specifies that when system site-packages are not supposed to be
    visible from a virtual environment, `pyvenv.cfg` must contain the following
    line:
        include-system-site-packages = false
    Additionally, log a warning if accessing the file fails.
    """
    cfg_lines = _get_pyvenv_cfg_lines()
    if cfg_lines is None:
        # We're not in a "sane" venv, so assume there is no system
        # site-packages access (since that's PEP 405's default state).
        logger.warning(
            "Could not access 'pyvenv.cfg' despite a virtual environment "
            "being active. Assuming global site-packages is not accessible "
            "in this environment."
        )
        return True
    for line in cfg_lines:
        match = _INCLUDE_SYSTEM_SITE_PACKAGES_REGEX.match(line)
        if match is not None and match.group("value") == "false":
            return True
    return False
References pip._internal.utils.virtualenv._get_pyvenv_cfg_lines(), and i.
Referenced by pip._internal.utils.virtualenv.virtualenv_no_global().
_running_under_legacy_virtualenv()
bool _running_under_legacy_virtualenv () protected
Checks if sys.real_prefix is set.
This handles virtual environments created with pypa's virtualenv.
Definition at line 22 of file virtualenv.py.
def _running_under_legacy_virtualenv() -> bool:
    """Checks if sys.real_prefix is set.
    This handles virtual environments created with pypa's virtualenv.
    """
    # pypa/virtualenv case
    return hasattr(sys, "real_prefix")
References i.
Referenced by pip._internal.utils.virtualenv.running_under_virtualenv(), and pip._internal.utils.virtualenv.virtualenv_no_global().
_running_under_venv()
bool _running_under_venv () protected
Checks if sys.base_prefix and sys.prefix match.
This handles PEP 405 compliant virtual environments.
Definition at line 14 of file virtualenv.py.
def _running_under_venv() -> bool:
    """Checks if sys.base_prefix and sys.prefix match.
    This handles PEP 405 compliant virtual environments.
    """
    return sys.prefix != getattr(sys, "base_prefix", sys.prefix)
References i.
Referenced by pip._internal.utils.virtualenv.running_under_virtualenv(), and pip._internal.utils.virtualenv.virtualenv_no_global().
running_under_virtualenv()
bool running_under_virtualenv ()
True if we're running inside a virtual environment, False otherwise.
Definition at line 31 of file virtualenv.py.
def running_under_virtualenv() -> bool:
    """True if we're running inside a virtual environment, False otherwise."""
    return _running_under_venv() or _running_under_legacy_virtualenv()
References pip._internal.utils.virtualenv._running_under_legacy_virtualenv(), and pip._internal.utils.virtualenv._running_under_venv().
virtualenv_no_global()
bool virtualenv_no_global ()
Returns a boolean, whether running in venv with no system site-packages.
Definition at line 94 of file virtualenv.py.
def virtualenv_no_global() -> bool:
    """Returns a boolean, whether running in venv with no system site-packages."""
    # PEP 405 compliance needs to be checked first since virtualenv >=20 would
    # return True for both checks, but is only able to use the PEP 405 config.
    if _running_under_venv():
        return _no_global_under_venv()
    if _running_under_legacy_virtualenv():
        return _no_global_under_legacy_virtualenv()
    return False
References pip._internal.utils.virtualenv._no_global_under_legacy_virtualenv(), pip._internal.utils.virtualenv._no_global_under_venv(), pip._internal.utils.virtualenv._running_under_legacy_virtualenv(), and pip._internal.utils.virtualenv._running_under_venv().
Variable Documentation
_INCLUDE_SYSTEM_SITE_PACKAGES_REGEX
_INCLUDE_SYSTEM_SITE_PACKAGES_REGEX protected
Initial value:
=  re.compile(
    r"include-system-site-packages\s*=\s*(?P<value>true|false)"
)
Definition at line 9 of file virtualenv.py.
logger
logger = logging.getLogger(__name__)
Definition at line 8 of file virtualenv.py.