Let us walk on the 3-isogeny graph: E:/pqc-engineering-ssec-23/c-code/src/cgl_hash.h File Reference
cgl_hash.h File Reference
#include "isogeny_walks.h"
Data Structures
struct cgl_hash_2_ctx
struct cgl_hash_3_ctx
Typedefs
typedef struct cgl_hash_2_ctx cgl_hash_2_ctx
typedef struct cgl_hash_3_ctx cgl_hash_3_ctx
Functions
void cgl_hash_init_2 (cgl_hash_2_ctx *ctx, fp2_t input_A)
void cgl_hash_digest_2 (fp2_t *output, const cgl_hash_2_ctx *ctx, const uint8_t *input_bitstring)
void cgl_hash_init_3 (cgl_hash_3_ctx *ctx, fp2_t input_A, uint8_t choice)
void cgl_hash_digest_3 (fp2_t *output, const cgl_hash_3_ctx *ctx, const uint8_t *input_trit_string)
Typedef Documentation
cgl_hash_2_ctx
typedef struct cgl_hash_2_ctx cgl_hash_2_ctx
cgl_hash_3_ctx
typedef struct cgl_hash_3_ctx cgl_hash_3_ctx
Function Documentation
cgl_hash_digest_2()
void cgl_hash_digest_2 (fp2_t * output, const cgl_hash_2_ctx * ctx, const uint8_t * input_bitstring)
Definition at line 9 of file cgl_hash.c.
{
    fp2_set_to_zero(output);
    isogeny_walks_2(output, ctx->j_, ctx->j0, input_bitstring, BIT_LENGTH_PATH);
}
References BIT_LENGTH_PATH, fp2_set_to_zero(), isogeny_walks_2(), cgl_hash_2_ctx::j0, and cgl_hash_2_ctx::j_.
Referenced by main().
cgl_hash_digest_3()
void cgl_hash_digest_3 (fp2_t * output, const cgl_hash_3_ctx * ctx, const uint8_t * input_trit_string)
Definition at line 23 of file cgl_hash.c.
{
    fp2_t a1, a3;
    fp2_set_to_zero(output);
    isogeny_walks_3(&a1, &a3, ctx->a1, ctx->a3, input_trit_string, TRITLENGTH_PATH);
    isogeny_walks_switch_from_model_3(output, a1, a3);
}
References a1, cgl_hash_3_ctx::a1, a3, cgl_hash_3_ctx::a3, fp2_set_to_zero(), isogeny_walks_3(), isogeny_walks_switch_from_model_3(), and TRITLENGTH_PATH.
Referenced by main().
cgl_hash_init_2()
void cgl_hash_init_2 (cgl_hash_2_ctx * ctx, fp2_t input_A)
Definition at line 16 of file cgl_hash.c.
{
    isogeny_walks_from_montgomery_model_2(&ctx->j0, input_A);
    isogeny_walks_get_previous_step_2(&ctx->j_, input_A);
}
References isogeny_walks_from_montgomery_model_2(), isogeny_walks_get_previous_step_2(), cgl_hash_2_ctx::j0, and cgl_hash_2_ctx::j_.
Referenced by main().
cgl_hash_init_3()
void cgl_hash_init_3 (cgl_hash_3_ctx * ctx, fp2_t input_A, uint8_t choice)
Definition at line 32 of file cgl_hash.c.
{
    fp2_t xP[4];
    isogeny_walks_get_points_3(xP, input_A);
    isogeny_walks_from_montgomery_model_3(&ctx->a1, &ctx->a3, input_A, xP[choice % 4]);
}
References cgl_hash_3_ctx::a1, cgl_hash_3_ctx::a3, isogeny_walks_from_montgomery_model_3(), and isogeny_walks_get_points_3().
Referenced by main().