Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: LinkType Class Reference
LinkType Class Reference
Static Public Attributes
candidate = enum.auto()
different_project = enum.auto()
yanked = enum.auto()
format_unsupported = enum.auto()
format_invalid = enum.auto()
platform_mismatch = enum.auto()
requires_python_mismatch = enum.auto()
Detailed Description
Definition at line 98 of file package_finder.py.
Field Documentation
candidate
candidate = enum.auto() static
Definition at line 99 of file package_finder.py.
Referenced by ExplicitRequirement.__repr__(), ExplicitRequirement.__str__(), InconsistentCandidate.__str__(), ExplicitRequirement.format_for_error(), ExplicitRequirement.get_candidate_lookup(), ExplicitRequirement.is_satisfied_by(), ExplicitRequirement.name(), and ExplicitRequirement.project_name().
different_project
different_project = enum.auto() static
Definition at line 100 of file package_finder.py.
format_invalid
format_invalid = enum.auto() static
Definition at line 103 of file package_finder.py.
format_unsupported
format_unsupported = enum.auto() static
Definition at line 102 of file package_finder.py.
platform_mismatch
platform_mismatch = enum.auto() static
Definition at line 104 of file package_finder.py.
requires_python_mismatch
requires_python_mismatch = enum.auto() static
Definition at line 105 of file package_finder.py.
yanked
yanked = enum.auto() static
Definition at line 101 of file package_finder.py.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/index/package_finder.py