Let us walk on the 3-isogeny graph: /home/liwuen/projects_dev/pqc-engineering-ssec-23/dCTIDH/src/common/fp/gmp/fp-gmp.h File Reference
fp-gmp.h File Reference
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <immintrin.h>
#include <assert.h>
#include <inttypes.h>
#include <stddef.h>
#include "../../rng.h"
#include "../../namespace.h"
#include "../fp-counters.h"
#include "../../primes.h"
Data Structures
struct uintbig
Macros
#define uintbig_1 COMMON(uintbig_1)
#define r_squared_mod_p COMMON(r_squared_mod_p)
#define p_minus_2 COMMON(p_minus_2)
#define inv_min_p_mod_r COMMON(inv_min_p_mod_r)
#define uintbig_bit COMMON(uintbig_bit)
#define uintbig_add COMMON(uintbig_add)
#define uintbig_sub COMMON(uintbig_sub)
#define p COMMON(p)
#define fp_1 COMMON(fp_1)
#define fp_0 COMMON(fp_0)
#define fp_enc COMMON(fp_enc)
#define fp_dec COMMON(fp_dec)
#define fp_pow COMMON(fp_pow)
#define fp_add COMMON(fp_add)
#define fp_sub COMMON(fp_sub)
#define fp_mul COMMON(fp_mul)
#define fp_sqr COMMON(fp_sqr)
#define fp_issquare COMMON(fp_issquare)
#define fp_copy COMMON(fp_copy)
#define fp_cswap COMMON(fp_cswap)
#define fp_random COMMON(fp_random)
#define fp_inv COMMON(fp_inv)
#define UBITS 2048
#define UINTBIG_LIMBS ((UBITS+63)/64)
#define uintbig_p COMMON(uintbig_p)
#define uintbig_four_sqrt_p COMMON(uintbig_four_sqrt_p)
#define uintbig_set COMMON(uintbig_set)
#define uintbig_mul3_64 COMMON(uintbig_mul3_64)
#define fp_2 COMMON(fp_2)
#define uintbig_1_ctidh COMMON(uintbig_1_ctidh)
#define fp_cmov COMMON(fp_cmov)
Typedefs
typedef uint64_t fp[NUMBER_OF_WORDS]
typedef struct uintbig uintbig
Functions
bool uintbig_add (fp x, fp const y, fp const z)
bool uintbig_sub (fp x, fp const y, fp const z)
void fp_enc (fp a, fp const b)
void fp_dec (fp a, fp const b)
void fp_pow (fp b, const fp e, const fp a)
void fp_add (fp c, const fp a, const fp b)
void fp_sub (fp c, const fp a, const fp b)
void fp_mul (fp c, const fp a, const fp b)
void fp_sqr (fp b, const fp a)
bool fp_issquare (fp const a)
void fp_copy (fp b, const fp a)
void fp_cswap (fp x, fp y, uint8_t c)
void fp_random (fp a)
void fp_inv (fp a)
long long uintbig_bit (uintbig const *x, uint64_t k)
void uintbig_set (uintbig *x, uint64_t y)
void uintbig_mul3_64 (fp *x, fp const *y, uint64_t z)
void fp_cmov (fp *a, const fp *b, uint8_t c)
Variables
const fp uintbig_1
const fp r_squared_mod_p
const fp p_minus_2
const fp inv_min_p_mod_r
const fp p
const fp fp_1
const fp fp_0
const uintbig uintbig_p
const fp uintbig_four_sqrt_p
const fp fp_2
const uintbig uintbig_1_ctidh
Macro Definition Documentation
fp_0
#define fp_0 COMMON(fp_0)
Definition at line 50 of file fp-gmp.h.
fp_1
const fp fp_1 COMMON(fp_1)
Definition at line 48 of file fp-gmp.h.
Referenced by action(), elligator(), elligator_seeded(), fulltorsion_points(), validate(), xISOG_matryoshka(), and xMUL().
fp_2
#define fp_2 COMMON(fp_2)
Definition at line 317 of file fp-gmp.h.
fp_add
#define fp_add COMMON(fp_add)
Definition at line 64 of file fp-gmp.h.
fp_cmov
#define fp_cmov COMMON(fp_cmov)
Definition at line 323 of file fp-gmp.h.
fp_copy
#define fp_copy COMMON(fp_copy)
Definition at line 79 of file fp-gmp.h.
fp_cswap
#define fp_cswap COMMON(fp_cswap)
Definition at line 82 of file fp-gmp.h.
fp_dec
#define fp_dec COMMON(fp_dec)
Definition at line 58 of file fp-gmp.h.
fp_enc
#define fp_enc COMMON(fp_enc)
Definition at line 55 of file fp-gmp.h.
fp_inv
#define fp_inv COMMON(fp_inv)
Definition at line 88 of file fp-gmp.h.
fp_issquare
#define fp_issquare COMMON(fp_issquare)
Definition at line 76 of file fp-gmp.h.
fp_mul
#define fp_mul COMMON(fp_mul)
Definition at line 70 of file fp-gmp.h.
fp_pow
#define fp_pow COMMON(fp_pow)
Definition at line 61 of file fp-gmp.h.
fp_random
#define fp_random COMMON(fp_random)
Definition at line 85 of file fp-gmp.h.
fp_sqr
#define fp_sqr COMMON(fp_sqr)
Definition at line 73 of file fp-gmp.h.
fp_sub
#define fp_sub COMMON(fp_sub)
Definition at line 67 of file fp-gmp.h.
inv_min_p_mod_r
const fp inv_min_p_mod_r COMMON(inv_min_p_mod_r)
Definition at line 33 of file fp-gmp.h.
p
const fp p COMMON(p)
Definition at line 44 of file fp-gmp.h.
Referenced by fp_add(), fp_inv(), fp_issquare(), fp_mont_redc(), fp_mul(), fp_pow(), fp_random(), fp_sqr(), fp_sub(), and AnsiToWin32Test::test_native_windows_ansi().
p_minus_2
const fp p_minus_2 COMMON(p_minus_2)
Definition at line 31 of file fp-gmp.h.
r_squared_mod_p
#define r_squared_mod_p COMMON(r_squared_mod_p)
Definition at line 29 of file fp-gmp.h.
UBITS
#define UBITS 2048
Definition at line 247 of file fp-gmp.h.
uintbig_1
#define uintbig_1 COMMON(uintbig_1)
Definition at line 26 of file fp-gmp.h.
uintbig_1_ctidh
#define uintbig_1_ctidh COMMON(uintbig_1_ctidh)
Definition at line 320 of file fp-gmp.h.
uintbig_add
#define uintbig_add COMMON(uintbig_add)
Definition at line 38 of file fp-gmp.h.
uintbig_bit
#define uintbig_bit COMMON(uintbig_bit)
Definition at line 36 of file fp-gmp.h.
uintbig_four_sqrt_p
#define uintbig_four_sqrt_p COMMON(uintbig_four_sqrt_p)
Definition at line 278 of file fp-gmp.h.
UINTBIG_LIMBS
#define UINTBIG_LIMBS ((UBITS+63)/64)
Definition at line 263 of file fp-gmp.h.
uintbig_mul3_64
#define uintbig_mul3_64 COMMON(uintbig_mul3_64)
Definition at line 285 of file fp-gmp.h.
uintbig_p
#define uintbig_p COMMON(uintbig_p)
Definition at line 272 of file fp-gmp.h.
uintbig_set
#define uintbig_set COMMON(uintbig_set)
Definition at line 281 of file fp-gmp.h.
uintbig_sub
#define uintbig_sub COMMON(uintbig_sub)
Definition at line 40 of file fp-gmp.h.
Typedef Documentation
fp
typedef uint64_t fp[NUMBER_OF_WORDS]
Definition at line 22 of file fp-gmp.h.
uintbig
typedef struct uintbig uintbig
Function Documentation
fp_add()
void fp_add (fp c, const fp a, const fp b)
Definition at line 864 of file fp-gmp.c.
{
    // (void)mpn_add_n(c, a, b, NUMBER_OF_WORDS);
    // CNT_FP_ADD_INC();
    // reduce_once(c);
    (void)mpn_add_n(c, a, b, NUMBER_OF_WORDS);
    mpn_cnd_sub_n(mpn_cmp(c, p, NUMBER_OF_WORDS) > 0, c, c, p, NUMBER_OF_WORDS);
    CNT_FP_ADD_INC();
}
fp_cmov()
void fp_cmov (fp * a, const fp * b, uint8_t c)
fp_copy()
void fp_copy (fp b, const fp a)
Definition at line 856 of file fp-gmp.c.
{
    for (uint8_t i = 0; i < NUMBER_OF_WORDS; i++)
    {
        b[i] = a[i];
    }
}
fp_cswap()
void fp_cswap (fp x, fp y, uint8_t c)
Definition at line 840 of file fp-gmp.c.
{
    // uint64_t tmp, c64;
    // c64 = (uint64_t)-c;
    // for (int i = 0; i < NUMBER_OF_WORDS; i++)
    // {
    //     tmp = (y[i] ^ x[i]) & c64;
    //     x[i] ^= tmp;
    //     y[i] ^= tmp;
    // }
    mpn_cnd_swap(c, x, y, NUMBER_OF_WORDS);
}
fp_dec()
void fp_dec (fp a, fp const b)
Definition at line 800 of file fp-gmp.c.
{
#ifdef MONTGOMERY
    fp_mul(a, b, uintbig_1);
    CNT_FP_MUL_DEC();
#else
    //(void) a;
    //(void) b;
    fp_copy(a, b);
#endif
}
fp_enc()
void fp_enc (fp a, fp const b)
Definition at line 789 of file fp-gmp.c.
{
#ifdef MONTGOMERY
    fp_mul(a, b, r_squared_mod_p);
    CNT_FP_MUL_DEC();
#else
    //(void) a;
    //(void) b;
    fp_copy(a, b);
#endif
}
fp_inv()
void fp_inv (fp a)
Definition at line 12 of file fp_inv2047m1l226.c.
{
  fp r0;
  fp_copy(r0, x);
  fp r1;
  fp_sqr(r1,r0);
  fp r2;
  fp_mul(r2,r0,r1);
  fp r3;
  fp_mul(r3,r1,r2);
  fp r4;
  fp_mul(r4,r1,r3);
  fp r5;
  fp_mul(r5,r1,r4);
  fp r6;
  fp_mul(r6,r1,r5);
  fp r7;
  fp_mul(r7,r1,r6);
  fp r8;
  fp_mul(r8,r1,r7);
  fp r9;
  fp_mul(r9,r1,r8);
  fp r10;
  fp_mul(r10,r1,r9);
  fp r11;
  fp_mul(r11,r1,r10);
  fp r12;
  fp_mul(r12,r1,r11);
  fp r13;
  fp_mul(r13,r1,r12);
  fp r14;
  fp_mul(r14,r1,r13);
  fp r15;
  fp_mul(r15,r1,r14);
  fp r16;
  fp_mul(r16,r1,r15);
  fp r17;
  fp_mul(r17,r1,r16);
  fp r18;
  fp_mul(r18,r1,r17);
  fp r19;
  fp_mul(r19,r1,r18);
  fp r20;
  fp_mul(r20,r1,r19);
  fp r21;
  fp_mul(r21,r1,r20);
  fp r22;
  fp_mul(r22,r1,r21);
  fp r23;
  fp_mul(r23,r1,r22);
  fp r24;
  fp_mul(r24,r1,r23);
  fp r25;
  fp_mul(r25,r1,r24);
  fp r26;
  fp_mul(r26,r1,r25);
  fp r27;
  fp_mul(r27,r1,r26);
  fp r28;
  fp_mul(r28,r1,r27);
  fp r29;
  fp_mul(r29,r1,r28);
  fp r30;
  fp_mul(r30,r1,r29);
  fp r31;
  fp_mul(r31,r1,r30);
  fp r32;
  fp_mul(r32,r1,r31);
  fp r33;
  fp_mul(r33,r1,r32);
  fp r34;
  fp_mul(r34,r1,r33);
  fp r35;
  fp_mul(r35,r1,r34);
  fp r36;
  fp_mul(r36,r1,r35);
  fp r37;
  fp_mul(r37,r1,r36);
  fp r38;
  fp_mul(r38,r1,r37);
  fp r39;
  fp_mul(r39,r1,r38);
  fp r40;
  fp_mul(r40,r1,r39);
  fp r41;
  fp_mul(r41,r1,r40);
  fp r42;
  fp_mul(r42,r1,r41);
  fp r43;
  fp_mul(r43,r1,r42);
  fp r44;
  fp_mul(r44,r1,r43);
  fp r45;
  fp_mul(r45,r1,r44);
  fp r46;
  fp_mul(r46,r1,r45);
  fp_mul(r46,r46,r1);
  fp r47;
  fp_mul(r47,r1,r46);
  fp r48;
  fp_mul(r48,r1,r47);
  fp r49;
  fp_mul(r49,r1,r48);
  fp r50;
  fp_mul(r50,r1,r49);
  fp r51;
  fp_mul(r51,r1,r50);
  fp r52;
  fp_mul(r52,r1,r51);
  fp r53;
  fp_mul(r53,r1,r52);
  fp r54;
  fp_mul(r54,r1,r53);
  fp r55;
  fp_mul(r55,r1,r54);
  fp r56;
  fp_mul(r56,r1,r55);
  fp r57;
  fp_mul(r57,r1,r56);
  fp r58;
  fp_mul(r58,r1,r57);
  fp r59;
  fp_mul(r59,r1,r58);
  fp_mul(r1,r1,r59);
  fp r60;
  fp_mul(r60,r12,r1);
  fp_sq1_rep(r60,4);
  fp_mul(r60,r60,r53);
  fp_sq1_rep(r60,10);
  fp_mul(r60,r60,r33);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r58);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r13);
  fp_sq1_rep(r60,9);
  fp_mul(r60,r60,r58);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r22);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r1);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r50);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r46);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r7);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r32);
  fp_sq1_rep(r60,10);
  fp_mul(r60,r60,r2);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r20);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r31);
  fp_sq1_rep(r60,10);
  fp_mul(r60,r60,r55);
  fp_sq1_rep(r60,14);
  fp_mul(r60,r60,r35);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r21);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r55);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r39);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r51);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r12);
  fp_sq1_rep(r60,9);
  fp_mul(r60,r60,r50);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r21);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r4);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r1);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r22);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r43);
  fp_sq1_rep(r60,12);
  fp_mul(r60,r60,r52);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r56);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r57);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r13);
  fp_sq1_rep(r60,9);
  fp_mul(r60,r60,r26);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r14);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r26);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r32);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r10);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r30);
  fp_sq1_rep(r60,13);
  fp_mul(r60,r60,r33);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r3);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r29);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r10);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r47);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r35);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r38);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r5);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r36);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r4);
  fp_sq1_rep(r60,9);
  fp_mul(r60,r60,r44);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r25);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r14);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r41);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r10);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r25);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r59);
  fp_sq1_rep(r60,9);
  fp_mul(r60,r60,r58);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r11);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r22);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r14);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r47);
  fp_sq1_rep(r60,8);
  fp_mul(r60,r60,r19);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r19);
  fp_sq1_rep(r60,7);
  fp_mul(r60,r60,r4);
  fp_sq1_rep(r60,7);
  fp_mul(r15,r15,r60);
  fp_sq1_rep(r15,6);
  fp_mul(r15,r15,r32);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r36);
  fp_sq1_rep(r15,11);
  fp_mul(r15,r15,r28);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r6);
  fp_sq1_rep(r15,10);
  fp_mul(r15,r15,r22);
  fp_sq1_rep(r15,10);
  fp_mul(r15,r15,r36);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r40);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r56);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r31);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r59);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r48);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r31);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r21);
  fp_sq1_rep(r15,14);
  fp_mul(r15,r15,r57);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r4);
  fp_sq1_rep(r15,12);
  fp_mul(r15,r15,r39);
  fp_sq1_rep(r15,11);
  fp_mul(r15,r15,r17);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r23);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r40);
  fp_sq1_rep(r15,9);
  fp_mul(r15,r15,r42);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r2);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r45);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r19);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r21);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r43);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r1);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r25);
  fp_sq1_rep(r15,6);
  fp_mul(r15,r15,r32);
  fp_sq1_rep(r15,10);
  fp_mul(r15,r15,r41);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r30);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r50);
  fp_sq1_rep(r15,9);
  fp_mul(r15,r15,r4);
  fp_sq1_rep(r15,16);
  fp_mul(r15,r15,r54);
  fp_sq1_rep(r15,9);
  fp_mul(r15,r15,r37);
  fp_sq1_rep(r15,6);
  fp_mul(r15,r15,r31);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r12);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r41);
  fp_sq1_rep(r15,10);
  fp_mul(r15,r15,r3);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r51);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r58);
  fp_sq1_rep(r15,11);
  fp_mul(r15,r15,r46);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r53);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r4);
  fp_sq1_rep(r15,11);
  fp_mul(r15,r15,r42);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r1);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r58);
  fp_sq1_rep(r15,8);
  fp_mul(r15,r15,r16);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r52);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r40);
  fp_sq1_rep(r15,7);
  fp_mul(r15,r15,r45);
  fp_sq1_rep(r15,7);
  fp_mul(r4,r4,r15);
  fp_sq1_rep(r4,7);
  fp_mul(r4,r4,r48);
  fp_sq1_rep(r4,9);
  fp_mul(r4,r4,r33);
  fp_sq1_rep(r4,12);
  fp_mul(r4,r4,r1);
  fp_sq1_rep(r4,7);
  fp_mul(r4,r4,r46);
  fp_sq1_rep(r4,10);
  fp_mul(r3,r3,r4);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r51);
  fp_sq1_rep(r3,6);
  fp_mul(r3,r3,r31);
  fp_sq1_rep(r3,9);
  fp_mul(r3,r3,r24);
  fp_sq1_rep(r3,8);
  fp_mul(r3,r3,r59);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r11);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r24);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r29);
  fp_sq1_rep(r3,10);
  fp_mul(r3,r3,r21);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r24);
  fp_sq1_rep(r3,9);
  fp_mul(r3,r3,r14);
  fp_sq1_rep(r3,8);
  fp_mul(r3,r3,r18);
  fp_sq1_rep(r3,8);
  fp_mul(r3,r3,r37);
  fp_sq1_rep(r3,9);
  fp_mul(r3,r3,r53);
  fp_sq1_rep(r3,8);
  fp_mul(r3,r3,r36);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r1);
  fp_sq1_rep(r3,6);
  fp_mul(r3,r3,r30);
  fp_sq1_rep(r3,9);
  fp_mul(r3,r3,r43);
  fp_sq1_rep(r3,8);
  fp_mul(r3,r3,r54);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r33);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r28);
  fp_sq1_rep(r3,6);
  fp_mul(r3,r3,r30);
  fp_sq1_rep(r3,9);
  fp_mul(r3,r3,r38);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r17);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r40);
  fp_sq1_rep(r3,12);
  fp_mul(r3,r3,r5);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r7);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r32);
  fp_sq1_rep(r3,6);
  fp_mul(r3,r3,r32);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r51);
  fp_sq1_rep(r3,8);
  fp_mul(r3,r3,r7);
  fp_sq1_rep(r3,9);
  fp_mul(r3,r3,r38);
  fp_sq1_rep(r3,8);
  fp_mul(r3,r3,r29);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r2);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r32);
  fp_sq1_rep(r3,7);
  fp_mul(r3,r3,r49);
  fp_sq1_rep(r3,13);
  fp_mul(r3,r3,r35);
  fp_sq1_rep(r3,9);
  fp_mul(r3,r3,r28);
  fp_sq1_rep(r3,7);
  fp_mul(r0,r0,r3);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r17);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r38);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r50);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r43);
  fp_sq1_rep(r0,11);
  fp_mul(r0,r0,r25);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r58);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r29);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r36);
  fp_sq1_rep(r0,10);
  fp_mul(r0,r0,r48);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r36);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r37);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r37);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r34);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r56);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r6);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r10);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r27);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r5);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r11);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r34);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r38);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r31);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r50);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r19);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r40);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r14);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r37);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r20);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r53);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r54);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r53);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r1);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r20);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r45);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r13);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r31);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r14);
  fp_sq1_rep(r0,13);
  fp_mul(r0,r0,r10);
  fp_sq1_rep(r0,17);
  fp_mul(r0,r0,r2);
  fp_sq1_rep(r0,12);
  fp_mul(r0,r0,r51);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r8);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r9);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r25);
  fp_sq1_rep(r0,10);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r49);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r36);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r1);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r42);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r58);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r49);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r42);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r45);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r57);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r1);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r5);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r21);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r40);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r24);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r25);
  fp_sq1_rep(r0,11);
  fp_mul(r0,r0,r6);
  fp_sq1_rep(r0,10);
  fp_mul(r0,r0,r58);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r56);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r11);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r55);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r43);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r1);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r33);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,12);
  fp_mul(r0,r0,r38);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r44);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r47);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r21);
  fp_sq1_rep(r0,11);
  fp_mul(r0,r0,r41);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r58);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r34);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r30);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r42);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r33);
  fp_sq1_rep(r0,13);
  fp_mul(r0,r0,r30);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r57);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r21);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r48);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r38);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r28);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r13);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r59);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r44);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r12);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r24);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r31);
  fp_copy(x, r0);
}
fp_issquare()
bool fp_issquare (fp const a)
Definition at line 12 of file fp_sqrt2047m1l226.c.
{
  fp origx;
  fp_copy(origx,x);
  fp r0;
  fp_copy(r0, x);
  fp r1;
  fp_sqr(r1,r0);
  fp r2;
  fp_mul(r2,r0,r1);
  fp r3;
  fp_mul(r3,r1,r2);
  fp r4;
  fp_mul(r4,r1,r3);
  fp r5;
  fp_mul(r5,r1,r4);
  fp r6;
  fp_mul(r6,r1,r5);
  fp r7;
  fp_mul(r7,r1,r6);
  fp r8;
  fp_mul(r8,r1,r7);
  fp r9;
  fp_mul(r9,r1,r8);
  fp r10;
  fp_mul(r10,r1,r9);
  fp r11;
  fp_mul(r11,r1,r10);
  fp r12;
  fp_mul(r12,r1,r11);
  fp r13;
  fp_mul(r13,r1,r12);
  fp r14;
  fp_mul(r14,r1,r13);
  fp r15;
  fp_mul(r15,r1,r14);
  fp r16;
  fp_mul(r16,r1,r15);
  fp r17;
  fp_mul(r17,r1,r16);
  fp r18;
  fp_mul(r18,r1,r17);
  fp r19;
  fp_mul(r19,r1,r18);
  fp r20;
  fp_mul(r20,r1,r19);
  fp r21;
  fp_mul(r21,r1,r20);
  fp r22;
  fp_mul(r22,r1,r21);
  fp r23;
  fp_mul(r23,r1,r22);
  fp r24;
  fp_mul(r24,r1,r23);
  fp r25;
  fp_mul(r25,r1,r24);
  fp r26;
  fp_mul(r26,r1,r25);
  fp r27;
  fp_mul(r27,r1,r26);
  fp r28;
  fp_mul(r28,r1,r27);
  fp r29;
  fp_mul(r29,r1,r28);
  fp r30;
  fp_mul(r30,r1,r29);
  fp r31;
  fp_mul(r31,r1,r30);
  fp r32;
  fp_mul(r32,r1,r31);
  fp r33;
  fp_mul(r33,r1,r32);
  fp r34;
  fp_mul(r34,r1,r33);
  fp r35;
  fp_mul(r35,r1,r34);
  fp r36;
  fp_mul(r36,r1,r35);
  fp r37;
  fp_mul(r37,r1,r36);
  fp r38;
  fp_mul(r38,r1,r37);
  fp r39;
  fp_mul(r39,r1,r38);
  fp r40;
  fp_mul(r40,r1,r39);
  fp r41;
  fp_mul(r41,r1,r40);
  fp_mul(r1,r1,r41);
  fp r42;
  fp_mul(r42,r23,r1);
  fp_sqr(r42,r42);
  fp_mul(r42,r42,r23);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r25);
  fp_sq1_rep(r42,10);
  fp_mul(r42,r42,r12);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r1);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r20);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r21);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r24);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r26);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r38);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r15);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r7);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r32);
  fp_sq1_rep(r42,9);
  fp_mul(r42,r42,r0);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r1);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r20);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r41);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r24);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r0);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r11);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r20);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r16);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r28);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r29);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r29);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r19);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r21);
  fp_sq1_rep(r42,11);
  fp_mul(r42,r42,r32);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r37);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r12);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r11);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r2);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r38);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r18);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r26);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r13);
  fp_sq1_rep(r42,9);
  fp_mul(r42,r42,r26);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r14);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r26);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r32);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r10);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r30);
  fp_sq1_rep(r42,13);
  fp_mul(r42,r42,r33);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r3);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r29);
  fp_sq1_rep(r42,9);
  fp_mul(r42,r42,r39);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r16);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r35);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r38);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r5);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r18);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r34);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r19);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r30);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r10);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r27);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r9);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r14);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r12);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r29);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r27);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r11);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r22);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r28);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r16);
  fp_sq1_rep(r42,8);
  fp_mul(r42,r42,r19);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r19);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r4);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r15);
  fp_sq1_rep(r42,6);
  fp_mul(r42,r42,r32);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r36);
  fp_sq1_rep(r42,11);
  fp_mul(r42,r42,r28);
  fp_sq1_rep(r42,7);
  fp_mul(r42,r42,r6);
  fp_sq1_rep(r42,10);
  fp_mul(r42,r42,r22);
  fp_sq1_rep(r42,8);
  fp_mul(r9,r9,r42);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r29);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r32);
  fp_sq1_rep(r9,8);
  fp_mul(r9,r9,r12);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r22);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r24);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r17);
  fp_sq1_rep(r9,8);
  fp_mul(r9,r9,r31);
  fp_sq1_rep(r9,7);
  fp_mul(r9,r9,r21);
  fp_sq1_rep(r9,8);
  fp_mul(r9,r9,r0);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r26);
  fp_sq1_rep(r9,8);
  fp_mul(r9,r9,r4);
  fp_sq1_rep(r9,12);
  fp_mul(r9,r9,r39);
  fp_sq1_rep(r9,11);
  fp_mul(r9,r9,r17);
  fp_sq1_rep(r9,7);
  fp_mul(r9,r9,r23);
  fp_sq1_rep(r9,7);
  fp_mul(r9,r9,r40);
  fp_sq1_rep(r9,9);
  fp_mul(r9,r9,r1);
  fp_sq1_rep(r9,9);
  fp_mul(r9,r9,r4);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r13);
  fp_sq1_rep(r9,7);
  fp_mul(r9,r9,r19);
  fp_sq1_rep(r9,7);
  fp_mul(r9,r9,r21);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r11);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r12);
  fp_sq1_rep(r9,7);
  fp_mul(r9,r9,r38);
  fp_sq1_rep(r9,8);
  fp_mul(r9,r9,r16);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r25);
  fp_sq1_rep(r9,8);
  fp_mul(r9,r9,r35);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r28);
  fp_sq1_rep(r9,6);
  fp_mul(r9,r9,r19);
  fp_sq1_rep(r9,9);
  fp_mul(r9,r9,r4);
  fp_sq1_rep(r9,10);
  fp_mul(r0,r0,r9);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r23);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r37);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r31);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r12);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r41);
  fp_sq1_rep(r0,11);
  fp_mul(r0,r0,r6);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r20);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r15);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r17);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r15);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r27);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r34);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r17);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r40);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r27);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r1);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r16);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r13);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r8);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r17);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r33);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r2);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r15);
  fp_sq1_rep(r0,12);
  fp_mul(r0,r0,r12);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r41);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r31);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r28);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r11);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r24);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r29);
  fp_sq1_rep(r0,10);
  fp_mul(r0,r0,r21);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r24);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r14);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r18);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r37);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r27);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r41);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r31);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r19);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r11);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r23);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r33);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r28);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r30);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r38);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r17);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r40);
  fp_sq1_rep(r0,12);
  fp_mul(r0,r0,r5);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r27);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r20);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r7);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r38);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r29);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r7);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r18);
  fp_sq1_rep(r0,13);
  fp_mul(r0,r0,r35);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r28);
  fp_sq1_rep(r0,10);
  fp_mul(r0,r0,r5);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r3);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r12);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r38);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r11);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r2);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r31);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r36);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r41);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r25);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r34);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r8);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r19);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r10);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r7);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r25);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r6);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r10);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r27);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r5);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r22);
  fp_sq1_rep(r0,10);
  fp_mul(r0,r0,r29);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r16);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r21);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r19);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r19);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r40);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r14);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r37);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r40);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r22);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r14);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r15);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r16);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r37);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r15);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r13);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r13);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r31);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r14);
  fp_sq1_rep(r0,13);
  fp_mul(r0,r0,r10);
  fp_sq1_rep(r0,17);
  fp_mul(r0,r0,r2);
  fp_sq1_rep(r0,11);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r18);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r25);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r6);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r17);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r39);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r36);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r39);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r16);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r1);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r15);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r15);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r20);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r39);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r29);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r5);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r21);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r40);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r24);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r25);
  fp_sq1_rep(r0,10);
  fp_mul(r0,r0,r3);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r36);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r24);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r5);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r12);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r31);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r22);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r29);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r33);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r32);
  fp_sq1_rep(r0,12);
  fp_mul(r0,r0,r38);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r22);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r28);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r27);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r17);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r18);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r27);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r34);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r30);
  fp_sq1_rep(r0,8);
  fp_mul(r0,r0,r1);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r33);
  fp_sq1_rep(r0,10);
  fp_mul(r0,r0,r4);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r14);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r39);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r20);
  fp_sq1_rep(r0,9);
  fp_mul(r0,r0,r13);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r14);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r29);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r19);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r28);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,7);
  fp_mul(r0,r0,r22);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r19);
  fp_sq1_rep(r0,6);
  fp_mul(r0,r0,r26);
  fp_sq1_rep(r0,62);
  fp_copy(x, r0);
  fp check; fp_sqr(check,x);
  return fp_isequal(check,origx);
}
fp_mul()
void fp_mul (fp c, const fp a, const fp b)
Definition at line 891 of file fp-gmp.c.
{
#ifdef MONTGOMERY
    static __thread uint64_t tp[itch_size];
    // mp_size_t size = mpn_sec_mul_itch(NUMBER_OF_WORDS, 1) ;
    uint64_t A[NUMBER_OF_WORDS + 1] = {0x0};
    uint64_t tmp_1[NUMBER_OF_WORDS + 1] = {0x0};
    uint64_t tmp_2[NUMBER_OF_WORDS + 2] = {0x0};
    uint64_t a_i[1] = {0x0};
    for (int i = 0; i < NUMBER_OF_WORDS; i++)
    {
        // tmp_1 = x_i * y
        a_i[0] = a[i];
        mpn_sec_mul(tmp_1, b, NUMBER_OF_WORDS, a_i, 1, tp);
        // tmp_2 = A + x_i * y
        mpn_add(tmp_2, A, NUMBER_OF_WORDS + 1, tmp_1, NUMBER_OF_WORDS + 1);
        // tmp_1 = u_i * m
        mpn_sec_mul(tmp_1, p, NUMBER_OF_WORDS, tmp_2, 1, tp);
        // tmp_1 = A + x_i * y + u_i * m
        mpn_add(tmp_1, tmp_1, NUMBER_OF_WORDS + 1, tmp_2, NUMBER_OF_WORDS + 2);
        // A = (A + x_i * y + u_i * m) / r
        mpn_copyd(A, tmp_1 + 1, NUMBER_OF_WORDS);
        A[NUMBER_OF_WORDS] = 0;
    }
    mpn_cnd_sub_n(mpn_cmp(A, p, NUMBER_OF_WORDS) > 0, c, A, p, NUMBER_OF_WORDS);
#else
#ifndef USE_GMP_SEC_FUNCTIONS
    uint64_t tmp[NUMBER_OF_WORDS * 2];
    uint64_t thrash[NUMBER_OF_WORDS + 1];
    mpn_mul_n(tmp, a, b, NUMBER_OF_WORDS);
    mpn_tdiv_qr(thrash, c, 0, tmp, 2 * NUMBER_OF_WORDS, p, NUMBER_OF_WORDS);
#else
    static __thread uint64_t tp[itch_size];
    uint64_t tmp[NUMBER_OF_WORDS * 2];
    mpn_sec_mul(tmp, a, NUMBER_OF_WORDS, b, NUMBER_OF_WORDS, tp);
    mpn_sec_div_r(tmp, 2 * NUMBER_OF_WORDS, p, NUMBER_OF_WORDS, tp);
    fp_copy(c, tmp);
#endif
#endif
    CNT_FP_MUL_INC();
}
fp_pow()
void fp_pow (fp b, const fp e, const fp a)
Definition at line 812 of file fp-gmp.c.
{
    // It is required that e > 0.
    if (fp_iszero(e))
    {
        fp_set1(b);
    }
    else
    {
        fp tmp;
        fp_copy(tmp, a);
        fp_dec(tmp, tmp);
        mp_size_t pow_size = mpn_sec_powm_itch(NUMBER_OF_WORDS, NUMBER_OF_WORDS, NUMBER_OF_WORDS);
        uint64_t tp_pow[pow_size];
        mpn_sec_powm(b, tmp, NUMBER_OF_WORDS, e, NUMBER_OF_WORDS, p, NUMBER_OF_WORDS, tp_pow);
        fp_enc(b, b);
    }
}
fp_random()
void fp_random (fp a)
Definition at line 1047 of file fp-gmp.c.
{
    while (1)
    {
        randombytes(x, sizeof(fp));
        uint64_t m = ((uint64_t)1 << pbits % 64) - 1;
        x[NUMBER_OF_WORDS - 1] &= m;
        for (size_t i = NUMBER_OF_WORDS - 1; i < NUMBER_OF_WORDS; --i)
            if (x[i] < p[i])
                return;
            else if (x[i] > p[i])
                break;
    }
}
fp_sqr()
void fp_sqr (fp b, const fp a)
Definition at line 942 of file fp-gmp.c.
{
#ifdef MONTGOMERY
    // fp_mul(b, a, a);
    // CNT_FP_MUL_DEC();
    uint64_t tmp[NUMBER_OF_WORDS * 2];
    mpn_sqr(tmp, a, NUMBER_OF_WORDS);
    fp_mont_redc(b, tmp);
#else
#ifndef USE_GMP_SEC_FUNCTIONS
    uint64_t tmp[NUMBER_OF_WORDS * 2];
    uint64_t thrash[NUMBER_OF_WORDS + 1];
    mpn_sqr(tmp, a, NUMBER_OF_WORDS);
    mpn_tdiv_qr(thrash, b, 0, tmp, 2 * NUMBER_OF_WORDS, p, NUMBER_OF_WORDS);
#else
    fp_mul(b, a, a);
    CNT_FP_MUL_DEC();
//     mpn_sec_sqr(tmp, a, NUMBER_OF_WORDS, tp);
//     mpn_sec_div_r(tmp, 2 * NUMBER_OF_WORDS, p, NUMBER_OF_WORDS, tp);
#endif
#endif
    CNT_FP_SQR_INC();
}
fp_sub()
void fp_sub (fp c, const fp a, const fp b)
Definition at line 874 of file fp-gmp.c.
{
    // mp_limb_t borrow = mpn_sub_n(c, a, b, NUMBER_OF_WORDS);
    // CNT_FP_ADD_INC();
    // if (borrow)
    // {
    //     mpn_add_n(c, c, p, NUMBER_OF_WORDS);
    // }
    mpn_cnd_add_n(mpn_sub_n(c, a, b, NUMBER_OF_WORDS), c, c, p, NUMBER_OF_WORDS);
    CNT_FP_ADD_INC();
}
uintbig_add()
bool uintbig_add (fp x, fp const y, fp const z)
uintbig_bit()
long long uintbig_bit (uintbig const * x, uint64_t k)
uintbig_mul3_64()
void uintbig_mul3_64 (fp * x, fp const * y, uint64_t z)
uintbig_set()
void uintbig_set (uintbig * x, uint64_t y)
uintbig_sub()
bool uintbig_sub (fp x, fp const y, fp const z)
Variable Documentation
fp_0
const fp fp_0 extern
Definition at line 787 of file fp-gmp.c.
{0x0};
fp_1
const fp fp_1 extern
fp_2
const fp fp_2 extern
inv_min_p_mod_r
const fp inv_min_p_mod_r extern
p
const fp p extern
p_minus_2
const fp p_minus_2 extern
r_squared_mod_p
const fp r_squared_mod_p extern
uintbig_1
const fp uintbig_1 extern
uintbig_1_ctidh
const uintbig uintbig_1_ctidh extern
uintbig_four_sqrt_p
const fp uintbig_four_sqrt_p extern
uintbig_p
const uintbig uintbig_p extern