Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: pip._internal.network.cache Namespace Reference
pip._internal.network.cache Namespace Reference
Data Structures
class SafeFileCache
Functions
bool is_from_cache (Response response)
Generator[None, None, None] suppressed_cache_errors ()
Detailed Description
HTTP cache implementation.
Function Documentation
is_from_cache()
bool is_from_cache (Response response)
Definition at line 16 of file cache.py.
def is_from_cache(response: Response) -> bool:
    return getattr(response, "from_cache", False)
@contextmanager
suppressed_cache_errors()
Generator[None, None, None] suppressed_cache_errors ()
If we can't access the cache then we can just skip caching and process
requests as if caching wasn't enabled.
Definition at line 21 of file cache.py.
def suppressed_cache_errors() -> Generator[None, None, None]:
    """If we can't access the cache then we can just skip caching and process
    requests as if caching wasn't enabled.
    """
    try:
        yield
    except OSError:
        pass
Referenced by SafeFileCache.delete(), SafeFileCache.get(), and SafeFileCache.set().