Let us walk on the 3-isogeny graph: BaseSpecifier Class Reference
BaseSpecifier Class Reference
Public Member Functions
str __str__ (self)
int __hash__ (self)
bool __eq__ (self, object other)
Optional[bool] prereleases (self)
None prereleases (self, bool value)
bool contains (self, str item, Optional[bool] prereleases=None)
Iterable[VersionTypeVar] filter (self, Iterable[VersionTypeVar] iterable, Optional[bool] prereleases=None)
Detailed Description
Definition at line 39 of file specifiers.py.
Member Function Documentation
__eq__()
bool __eq__ (self, object other)
Returns a boolean representing whether or not the two Specifier like
objects are equal.
Reimplemented in _IndividualSpecifier, and SpecifierSet.
Definition at line 54 of file specifiers.py.
    def __eq__(self, other: object) -> bool:
        """
        Returns a boolean representing whether or not the two Specifier like
        objects are equal.
        """
Referenced by Version.__ge__(), Version.__gt__(), Version.__le__(), Version.__ne__(), Matcher.__ne__(), Timestamp.__ne__(), and HTTPHeaderDict.__ne__().
__hash__()
int __hash__ (self)
Returns a hash value for this Specifier like object.
Reimplemented in _IndividualSpecifier, and SpecifierSet.
Definition at line 48 of file specifiers.py.
    def __hash__(self) -> int:
        """
        Returns a hash value for this Specifier like object.
        """
Referenced by Style.__eq__(), and Style.__ne__().
__str__()
str __str__ (self)
Returns the str representation of this Specifier like object. This
should be representative of the Specifier itself.
Reimplemented in _IndividualSpecifier, and SpecifierSet.
Definition at line 41 of file specifiers.py.
    def __str__(self) -> str:
        """
        Returns the str representation of this Specifier like object. This
        should be representative of the Specifier itself.
        """
contains()
bool contains (self, str item, Optional[bool] prereleases = None)
Determines if the given item is contained within this specifier.
Reimplemented in _IndividualSpecifier, and SpecifierSet.
Definition at line 75 of file specifiers.py.
    def contains(self, item: str, prereleases: Optional[bool] = None) -> bool:
        """
        Determines if the given item is contained within this specifier.
        """
Referenced by _IndividualSpecifier.__contains__(), SpecifierSet.__contains__(), and _IndividualSpecifier.filter().
filter()
Iterable[VersionTypeVar] filter (self, Iterable[VersionTypeVar] iterable, Optional[bool] prereleases = None)
Takes an iterable of items and filters them so that only items which
are contained within this specifier are allowed in it.
Reimplemented in _IndividualSpecifier, and SpecifierSet.
Definition at line 81 of file specifiers.py.
    ) -> Iterable[VersionTypeVar]:
        """
        Takes an iterable of items and filters them so that only items which
        are contained within this specifier are allowed in it.
        """
prereleases() [1/2]
Optional[bool] prereleases (self)
Returns whether or not pre-releases as a whole are allowed by this
specifier.
Reimplemented in _IndividualSpecifier, Specifier, SpecifierSet, _IndividualSpecifier, Specifier, and SpecifierSet.
Definition at line 61 of file specifiers.py.
    def prereleases(self) -> Optional[bool]:
        """
        Returns whether or not pre-releases as a whole are allowed by this
        specifier.
        """
Referenced by _IndividualSpecifier.contains(), SpecifierSet.contains(), _IndividualSpecifier.filter(), and SpecifierSet.filter().
prereleases() [2/2]
None prereleases (self, bool value)
Sets whether or not pre-releases as a whole are allowed by this
specifier.
Reimplemented in _IndividualSpecifier, Specifier, SpecifierSet, _IndividualSpecifier, Specifier, and SpecifierSet.
Definition at line 68 of file specifiers.py.
    def prereleases(self, value: bool) -> None:
        """
        Sets whether or not pre-releases as a whole are allowed by this
        specifier.
        """
Referenced by _IndividualSpecifier.contains(), SpecifierSet.contains(), _IndividualSpecifier.filter(), and SpecifierSet.filter().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/packaging/specifiers.py