Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: ServerProxy Class Reference
ServerProxy Class Reference
Public Member Functions
__init__ (self, uri, **kwargs)
Data Fields
timeout = kwargs.pop('timeout', None)
transport = t
Detailed Description
Definition at line 1536 of file util.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, uri, ** kwargs)
Definition at line 1537 of file util.py.
    def __init__(self, uri, **kwargs):
        self.timeout = timeout = kwargs.pop('timeout', None)
        # The above classes only come into play if a timeout
        # is specified
        if timeout is not None:
            # scheme = splittype(uri)  # deprecated as of Python 3.8
            scheme = urlparse(uri)[0]
            use_datetime = kwargs.get('use_datetime', 0)
            if scheme == 'https':
                tcls = SafeTransport
            else:
                tcls = Transport
            kwargs['transport'] = t = tcls(timeout, use_datetime=use_datetime)
            self.transport = t
        xmlrpclib.ServerProxy.__init__(self, uri, **kwargs)
#
# CSV functionality. This is provided because on 2.x, the csv module can't
# handle Unicode. However, we need to deal with Unicode in e.g. RECORD files.
#
Field Documentation
timeout
timeout = kwargs.pop('timeout', None)
Definition at line 1538 of file util.py.
Referenced by HTTPConnection._new_conn(), HTTPSConnection.connect(), and HTTPConnection.request().
transport
transport = t
Definition at line 1550 of file util.py.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/util.py