Let us walk on the 3-isogeny graph: StreamWrapper Class Reference
StreamWrapper Class Reference
Public Member Functions
__init__ (self, wrapped, converter)
__getattr__ (self, name)
__enter__ (self, *args, **kwargs)
__exit__ (self, *args, **kwargs)
__setstate__ (self, state)
__getstate__ (self)
write (self, text)
isatty (self)
closed (self)
Detailed Description
Wraps a stream (such as stdout), acting as a transparent proxy for all
attribute access apart from method 'write()', which is delegated to our
Converter instance.
Definition at line 16 of file ansitowin32.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, wrapped, converter)
Definition at line 22 of file ansitowin32.py.
    def __init__(self, wrapped, converter):
        # double-underscore everything to prevent clashes with names of
        # attributes on the wrapped stream object.
        self.__wrapped = wrapped
        self.__convertor = converter
References StreamWrapper.__convertor, and StreamWrapper.__wrapped.
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__enter__()
__enter__ (self, * args, ** kwargs)
Definition at line 31 of file ansitowin32.py.
    def __enter__(self, *args, **kwargs):
        # special method lookup bypasses __getattr__/__getattribute__, see
        # https://stackoverflow.com/questions/12632894/why-doesnt-getattr-work-with-exit
        # thus, contextlib magic methods are not proxied via __getattr__
        return self.__wrapped.__enter__(*args, **kwargs)
References StreamWrapper.__enter__(), and StreamWrapper.__wrapped.
Referenced by StreamWrapper.__enter__().
__exit__()
__exit__ (self, * args, ** kwargs)
Definition at line 37 of file ansitowin32.py.
    def __exit__(self, *args, **kwargs):
        return self.__wrapped.__exit__(*args, **kwargs)
References StreamWrapper.__exit__(), and StreamWrapper.__wrapped.
Referenced by StreamWrapper.__exit__().
__getattr__()
__getattr__ (self, name)
Definition at line 28 of file ansitowin32.py.
    def __getattr__(self, name):
        return getattr(self.__wrapped, name)
References StreamWrapper.__wrapped, and i.
__getstate__()
__getstate__ (self)
Definition at line 43 of file ansitowin32.py.
    def __getstate__(self):
        return self.__dict__
References StreamWrapper.__dict__.
__setstate__()
__setstate__ (self, state)
Definition at line 40 of file ansitowin32.py.
    def __setstate__(self, state):
        self.__dict__ = state
References StreamWrapper.__dict__.
closed()
closed (self)
Definition at line 62 of file ansitowin32.py.
    def closed(self):
        stream = self.__wrapped
        try:
            return stream.closed
        # AttributeError in the case that the stream doesn't support being closed
        # ValueError for the case that the stream has already been detached when atexit runs
        except (AttributeError, ValueError):
            return True
References StreamWrapper.__wrapped, and i.
Referenced by HTTPResponse.close().
isatty()
isatty (self)
Definition at line 49 of file ansitowin32.py.
    def isatty(self):
        stream = self.__wrapped
        if 'PYCHARM_HOSTED' in os.environ:
            if stream is not None and (stream is sys.__stdout__ or stream is sys.__stderr__):
                return True
        try:
            stream_isatty = stream.isatty
        except AttributeError:
            return False
        else:
            return stream_isatty()
References StreamWrapper.__wrapped, and i.
write()
write (self, text)
Definition at line 46 of file ansitowin32.py.
    def write(self, text):
        self.__convertor.write(text)
References StreamWrapper.__convertor, and StreamWrapper.write().
Referenced by StreamWrapper.write(), and LegacyWindowsTerm.write_text().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/colorama/ansitowin32.py