Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: CSVWriter Class Reference
CSVWriter Class Reference
Public Member Functions
__init__ (self, fn, **kwargs)
writerow (self, row)
Data Fields
stream = _csv_open(fn, 'w')
writer = csv.writer(self.stream, **self.defaults)
Detailed Description
Definition at line 1608 of file util.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, fn, ** kwargs)
Definition at line 1609 of file util.py.
    def __init__(self, fn, **kwargs):
        self.stream = _csv_open(fn, 'w')
        self.writer = csv.writer(self.stream, **self.defaults)
Member Function Documentation
writerow()
writerow (self, row)
Definition at line 1613 of file util.py.
    def writerow(self, row):
        if sys.version_info[0] < 3:
            r = []
            for item in row:
                if isinstance(item, text_type):
                    item = item.encode('utf-8')
                r.append(item)
            row = r
        self.writer.writerow(row)
#
#   Configurator functionality
#
References writer, and writerow().
Referenced by writerow().
Field Documentation
stream
stream = _csv_open(fn, 'w')
Definition at line 1610 of file util.py.
Referenced by HTTPResponse.__iter__(), Session.merge_environment_settings(), and Session.send().
writer
writer = csv.writer(self.stream, **self.defaults)
Definition at line 1611 of file util.py.
Referenced by writerow().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/util.py