Let us walk on the 3-isogeny graph: pip._vendor.platformdirs.android Namespace Reference
pip._vendor.platformdirs.android Namespace Reference
Data Structures
class Android
Functions
str|None _android_folder ()
str _android_documents_folder ()
str _android_downloads_folder ()
str _android_pictures_folder ()
str _android_videos_folder ()
str _android_music_folder ()
Detailed Description
Android.
Function Documentation
_android_documents_folder()
str _android_documents_folder () protected
:return: documents folder for the Android OS
Definition at line 129 of file android.py.
def _android_documents_folder() -> str:
    """:return: documents folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        documents_dir: str = context.getExternalFilesDir(environment.DIRECTORY_DOCUMENTS).getAbsolutePath()
    except Exception:  # noqa: BLE001
        documents_dir = "/storage/emulated/0/Documents"
    return documents_dir
@lru_cache(maxsize=1)
References i.
Referenced by Android.user_documents_dir().
_android_downloads_folder()
str _android_downloads_folder () protected
:return: downloads folder for the Android OS
Definition at line 145 of file android.py.
def _android_downloads_folder() -> str:
    """:return: downloads folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        downloads_dir: str = context.getExternalFilesDir(environment.DIRECTORY_DOWNLOADS).getAbsolutePath()
    except Exception:  # noqa: BLE001
        downloads_dir = "/storage/emulated/0/Downloads"
    return downloads_dir
@lru_cache(maxsize=1)
References i.
Referenced by Android.user_downloads_dir().
_android_folder()
str | None _android_folder () protected
:return: base folder for the Android OS or None if it cannot be found
Definition at line 108 of file android.py.
def _android_folder() -> str | None:
    """:return: base folder for the Android OS or None if it cannot be found"""
    try:
        # First try to get path to android app via pyjnius
        from jnius import autoclass
        context = autoclass("android.content.Context")
        result: str | None = context.getFilesDir().getParentFile().getAbsolutePath()
    except Exception:  # noqa: BLE001
        # if fails find an android folder looking path on the sys.path
        pattern = re.compile(r"/data/(data|user/\d+)/(.+)/files")
        for path in sys.path:
            if pattern.match(path):
                result = path.split("/files")[0]
                break
        else:
            result = None
    return result
@lru_cache(maxsize=1)
References i.
Referenced by Android.user_cache_dir(), Android.user_config_dir(), and Android.user_data_dir().
_android_music_folder()
str _android_music_folder () protected
:return: music folder for the Android OS
Definition at line 193 of file android.py.
def _android_music_folder() -> str:
    """:return: music folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        music_dir: str = context.getExternalFilesDir(environment.DIRECTORY_MUSIC).getAbsolutePath()
    except Exception:  # noqa: BLE001
        music_dir = "/storage/emulated/0/Music"
    return music_dir
References i.
Referenced by Android.user_music_dir().
_android_pictures_folder()
str _android_pictures_folder () protected
:return: pictures folder for the Android OS
Definition at line 161 of file android.py.
def _android_pictures_folder() -> str:
    """:return: pictures folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        pictures_dir: str = context.getExternalFilesDir(environment.DIRECTORY_PICTURES).getAbsolutePath()
    except Exception:  # noqa: BLE001
        pictures_dir = "/storage/emulated/0/Pictures"
    return pictures_dir
@lru_cache(maxsize=1)
References i.
Referenced by Android.user_pictures_dir().
_android_videos_folder()
str _android_videos_folder () protected
:return: videos folder for the Android OS
Definition at line 177 of file android.py.
def _android_videos_folder() -> str:
    """:return: videos folder for the Android OS"""
    # Get directories with pyjnius
    try:
        from jnius import autoclass
        context = autoclass("android.content.Context")
        environment = autoclass("android.os.Environment")
        videos_dir: str = context.getExternalFilesDir(environment.DIRECTORY_DCIM).getAbsolutePath()
    except Exception:  # noqa: BLE001
        videos_dir = "/storage/emulated/0/DCIM/Camera"
    return videos_dir
@lru_cache(maxsize=1)
References i.
Referenced by Android.user_videos_dir().