Let us walk on the 3-isogeny graph: Palette Class Reference
Palette Class Reference
Public Member Functions
__init__ (self, Sequence[Tuple[int, int, int]] colors)
ColorTriplet __getitem__ (self, int number)
"Table" __rich__ (self)
int match (self, Tuple[int, int, int] color)
Protected Attributes
_colors
Detailed Description
A palette of available colors.
Definition at line 11 of file palette.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, Sequence[Tuple[int, int, int]] colors)
Definition at line 14 of file palette.py.
    def __init__(self, colors: Sequence[Tuple[int, int, int]]):
        self._colors = colors
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__getitem__()
ColorTriplet __getitem__ (self, int number)
Definition at line 17 of file palette.py.
    def __getitem__(self, number: int) -> ColorTriplet:
        return ColorTriplet(*self._colors[number])
References Palette._colors.
__rich__()
"Table" __rich__ (self)
Definition at line 20 of file palette.py.
    def __rich__(self) -> "Table":
        from pip._vendor.rich.color import Color
        from pip._vendor.rich.style import Style
        from pip._vendor.rich.text import Text
        from pip._vendor.rich.table import Table
        table = Table(
            "index",
            "RGB",
            "Color",
            title="Palette",
            caption=f"{len(self._colors)} colors",
            highlight=True,
            caption_justify="right",
        )
        for index, color in enumerate(self._colors):
            table.add_row(
                str(index),
                repr(color),
                Text(" " * 16, style=Style(bgcolor=Color.from_rgb(*color))),
            )
        return table
References Palette._colors, and i.
match()
int match (self, Tuple[int, int, int] color)
Find a color from a palette that most closely matches a given color.
Args:
    color (Tuple[int, int, int]): RGB components in range 0 > 255.
Returns:
    int: Index of closes matching color.
Definition at line 45 of file palette.py.
    def match(self, color: Tuple[int, int, int]) -> int:
        """Find a color from a palette that most closely matches a given color.
        Args:
            color (Tuple[int, int, int]): RGB components in range 0 > 255.
        Returns:
            int: Index of closes matching color.
        """
        red1, green1, blue1 = color
        _sqrt = sqrt
        get_color = self._colors.__getitem__
        def get_color_distance(index: int) -> float:
            """Get the distance to a color."""
            red2, green2, blue2 = get_color(index)
            red_mean = (red1 + red2) // 2
            red = red1 - red2
            green = green1 - green2
            blue = blue1 - blue2
            return _sqrt(
                (((512 + red_mean) * red * red) >> 8)
                + 4 * green * green
                + (((767 - red_mean) * blue * blue) >> 8)
            )
        min_index = min(range(len(self._colors)), key=get_color_distance)
        return min_index
References Palette._colors, and i.
Referenced by Literal.__init__(), Literal._generateDefaultName(), Keyword._generateDefaultName(), Literal.parseImpl(), _SingleCharLiteral.parseImpl(), Keyword.parseImpl(), CaselessLiteral.parseImpl(), and Scanner.scan().
Field Documentation
_colors
_colors protected
Definition at line 15 of file palette.py.
Referenced by Palette.__getitem__(), Palette.__rich__(), and Palette.match().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/rich/palette.py