Let us walk on the 3-isogeny graph: OneDayCache Class Reference
OneDayCache Class Reference
Public Member Functions
update_headers (self, response)
Public Member Functions inherited from BaseHeuristic
warning (self, response)
apply (self, response)
Detailed Description
Cache the response by providing an expires 1 day in the
future.
Definition at line 58 of file heuristics.py.
Member Function Documentation
update_headers()
update_headers (self, response)
Update the response headers with any new headers.
NOTE: This SHOULD always include some Warning header to
      signify that the response was cached by the client, not
      by way of the provided headers.
Reimplemented from BaseHeuristic.
Definition at line 64 of file heuristics.py.
    def update_headers(self, response):
        headers = {}
        if "expires" not in response.headers:
            date = parsedate(response.headers["date"])
            expires = expire_after(timedelta(days=1), date=datetime(*date[:6]))
            headers["expires"] = datetime_to_header(expires)
            headers["cache-control"] = "public"
        return headers
References pip._vendor.cachecontrol.heuristics.datetime_to_header(), pip._vendor.cachecontrol.heuristics.expire_after(), and i.
Referenced by BaseHeuristic.apply().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/cachecontrol/heuristics.py