Let us walk on the 3-isogeny graph: Future Class Reference
Future Class Reference
Public Member Functions
None __init__ (self, int attempt_number)
bool failed (self)
"Future" construct (cls, int attempt_number, t.Any value, bool has_exception)
Data Fields
attempt_number
Detailed Description
Encapsulates a (future or past) attempted call to a target function.
Definition at line 402 of file __init__.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, int attempt_number)
Definition at line 405 of file __init__.py.
    def __init__(self, attempt_number: int) -> None:
        super().__init__()
        self.attempt_number = attempt_number
References Future.__init__(), and i.
Referenced by Future.__init__(), and Protocol.__init_subclass__().
Member Function Documentation
construct()
"Future" construct (cls, int attempt_number, t.Any value, bool has_exception)
Construct a new Future object.
Definition at line 415 of file __init__.py.
    def construct(cls, attempt_number: int, value: t.Any, has_exception: bool) -> "Future":
        """Construct a new Future object."""
        fut = cls(attempt_number)
        if has_exception:
            fut.set_exception(value)
        else:
            fut.set_result(value)
        return fut
References i.
failed()
bool failed (self)
Return whether a exception is being held in this future.
Definition at line 410 of file __init__.py.
    def failed(self) -> bool:
        """Return whether a exception is being held in this future."""
        return self.exception() is not None
References RaiseOnErrorTokenFilter.exception.
Field Documentation
attempt_number
attempt_number
Definition at line 407 of file __init__.py.
Referenced by RetryCallState.set_exception(), and RetryCallState.set_result().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/tenacity/__init__.py