Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: BaseCache Class Reference
BaseCache Class Reference
Public Member Functions
get (self, key)
set (self, key, value, expires=None)
delete (self, key)
close (self)
Detailed Description
Definition at line 12 of file cache.py.
Member Function Documentation
close()
close (self)
Reimplemented in RedisCache.
Definition at line 23 of file cache.py.
    def close(self):
        pass
Referenced by ZipExtFile.__exit__(), ZipFile.__exit__(), Response.__exit__(), Session.__exit__(), _Reader.__exit__(), ConnectionPool.__exit__(), SSLTransport.__exit__(), WrappedSocket._custom_validate(), WrappedSocket._decref_socketios(), WrappedSocket._drop(), WrappedSocket._raise_on_error(), HTTPResponse._update_chunk_length(), and WrappedSocket.recv_into().
delete()
delete (self, key)
Reimplemented in SafeFileCache, DictCache, FileCache, SeparateBodyFileCache, and RedisCache.
Definition at line 20 of file cache.py.
    def delete(self, key):
        raise NotImplementedError()
get()
get (self, key)
Reimplemented in SafeFileCache, DictCache, and RedisCache.
Definition at line 14 of file cache.py.
    def get(self, key):
        raise NotImplementedError()
Referenced by LegacyMetadata.__getitem__(), Layout.__getitem__(), LegacyMetadata.check(), and LegacyMetadata.write_file().
set()
set (self, key, value, expires = None)
Reimplemented in SafeFileCache, DictCache, and RedisCache.
Definition at line 17 of file cache.py.
    def set(self, key, value, expires=None):
        raise NotImplementedError()
Referenced by LegacyMetadata.__setitem__(), RequestsCookieJar.__setitem__(), Flags.finalize_pending(), LegacyMetadata.read_file(), and LegacyMetadata.update().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/cachecontrol/cache.py