Let us walk on the 3-isogeny graph: ZipProvider Class Reference
ZipProvider Class Reference
Public Member Functions
__init__ (self, module)
zipinfo (self)
get_resource_filename (self, manager, resource_name)
Public Member Functions inherited from NullProvider
get_resource_stream (self, manager, resource_name)
get_resource_string (self, manager, resource_name)
has_resource (self, resource_name)
has_metadata (self, name)
get_metadata (self, name)
get_metadata_lines (self, name)
resource_isdir (self, resource_name)
metadata_isdir (self, name)
resource_listdir (self, resource_name)
metadata_listdir (self, name)
run_script (self, script_name, namespace)
Data Fields
zip_pre
egg_root
module_path
Data Fields inherited from EggProvider
egg_name
egg_info
egg_root
Data Fields inherited from NullProvider
module_path
Static Public Attributes
eagers = None
Static Public Attributes inherited from NullProvider
egg_name = None
egg_info = None
loader = None
Protected Member Functions
_zipinfo_name (self, fspath)
_parts (self, zip_path)
_extract_resource (self, manager, zip_path)
_is_current (self, file_path, zip_path)
_get_eager_resources (self)
_index (self)
_has (self, fspath)
_isdir (self, fspath)
_listdir (self, fspath)
_eager_to_zip (self, resource_name)
_resource_to_zip (self, resource_name)
Protected Member Functions inherited from EggProvider
_setup_prefix (self)
_set_egg (self, path)
Protected Member Functions inherited from NullProvider
_get_metadata_path (self, name)
_fn (self, base, resource_name)
_get (self, path)
Static Protected Member Functions
_get_date_and_size (zip_stat)
Static Protected Member Functions inherited from NullProvider
_validate_resource_path (path)
Protected Attributes
_dirindex
Static Protected Attributes
_zip_manifests = MemoizedZipManifests()
Detailed Description
Resource support for zips and eggs
Definition at line 1812 of file __init__.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, module)
Reimplemented from EggProvider.
Reimplemented in EggMetadata.
Definition at line 1818 of file __init__.py.
    def __init__(self, module):
        super().__init__(module)
        self.zip_pre = self.loader.archive + os.sep
Referenced by Protocol.__init_subclass__().
Member Function Documentation
_eager_to_zip()
_eager_to_zip (self, resource_name) protected
Definition at line 1969 of file __init__.py.
    def _eager_to_zip(self, resource_name):
        return self._zipinfo_name(self._fn(self.egg_root, resource_name))
_extract_resource()
_extract_resource (self, manager, zip_path) protected
Definition at line 1867 of file __init__.py.
    def _extract_resource(self, manager, zip_path):  # noqa: C901
        if zip_path in self._index():
            for name in self._index()[zip_path]:
                last = self._extract_resource(manager, os.path.join(zip_path, name))
            # return the extracted directory name
            return os.path.dirname(last)
        timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
        if not WRITE_SUPPORT:
            raise IOError(
                '"os.rename" and "os.unlink" are not supported ' 'on this platform'
            )
        try:
            real_path = manager.get_cache_path(self.egg_name, self._parts(zip_path))
            if self._is_current(real_path, zip_path):
                return real_path
            outf, tmpnam = _mkstemp(
                ".$extract",
                dir=os.path.dirname(real_path),
            )
            os.write(outf, self.loader.get_data(zip_path))
            os.close(outf)
            utime(tmpnam, (timestamp, timestamp))
            manager.postprocess(tmpnam, real_path)
            try:
                rename(tmpnam, real_path)
            except os.error:
                if os.path.isfile(real_path):
                    if self._is_current(real_path, zip_path):
                        # the file became current since it was checked above,
                        #  so proceed.
                        return real_path
                    # Windows, del old file and retry
                    elif os.name == 'nt':
                        unlink(real_path)
                        rename(tmpnam, real_path)
                        return real_path
                raise
        except os.error:
            # report a user-friendly error
            manager.extraction_error()
        return real_path
_get_date_and_size()
_get_date_and_size (zip_stat) static protected
Definition at line 1858 of file __init__.py.
    def _get_date_and_size(zip_stat):
        size = zip_stat.file_size
        # ymdhms+wday, yday, dst
        date_time = zip_stat.date_time + (0, 0, -1)
        # 1980 offset already done
        timestamp = time.mktime(date_time)
        return timestamp, size
_get_eager_resources()
_get_eager_resources (self) protected
Definition at line 1933 of file __init__.py.
    def _get_eager_resources(self):
        if self.eagers is None:
            eagers = []
            for name in ('native_libs.txt', 'eager_resources.txt'):
                if self.has_metadata(name):
                    eagers.extend(self.get_metadata_lines(name))
            self.eagers = eagers
        return self.eagers
_has()
_has (self, fspath) protected
Reimplemented from NullProvider.
Definition at line 1959 of file __init__.py.
    def _has(self, fspath):
        zip_path = self._zipinfo_name(fspath)
        return zip_path in self.zipinfo or zip_path in self._index()
_index()
_index (self) protected
Definition at line 1942 of file __init__.py.
    def _index(self):
        try:
            return self._dirindex
        except AttributeError:
            ind = {}
            for path in self.zipinfo:
                parts = path.split(os.sep)
                while parts:
                    parent = os.sep.join(parts[:-1])
                    if parent in ind:
                        ind[parent].append(parts[-1])
                        break
                    else:
                        ind[parent] = [parts.pop()]
            self._dirindex = ind
            return ind
_is_current()
_is_current (self, file_path, zip_path) protected
Return True if the file_path is current for this zip_path
Definition at line 1917 of file __init__.py.
    def _is_current(self, file_path, zip_path):
        """
        Return True if the file_path is current for this zip_path
        """
        timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
        if not os.path.isfile(file_path):
            return False
        stat = os.stat(file_path)
        if stat.st_size != size or stat.st_mtime != timestamp:
            return False
        # check that the contents match
        zip_contents = self.loader.get_data(zip_path)
        with open(file_path, 'rb') as f:
            file_contents = f.read()
        return zip_contents == file_contents
_isdir()
_isdir (self, fspath) protected
Reimplemented from NullProvider.
Definition at line 1963 of file __init__.py.
    def _isdir(self, fspath):
        return self._zipinfo_name(fspath) in self._index()
_listdir()
_listdir (self, fspath) protected
Reimplemented from NullProvider.
Definition at line 1966 of file __init__.py.
    def _listdir(self, fspath):
        return list(self._index().get(self._zipinfo_name(fspath), ()))
_parts()
_parts (self, zip_path) protected
Definition at line 1832 of file __init__.py.
    def _parts(self, zip_path):
        # Convert a zipfile subpath into an egg-relative path part list.
        # pseudo-fs path
        fspath = self.zip_pre + zip_path
        if fspath.startswith(self.egg_root + os.sep):
            return fspath[len(self.egg_root) + 1 :].split(os.sep)
        raise AssertionError("%s is not a subpath of %s" % (fspath, self.egg_root))
Referenced by Version.__eq__(), Matcher.__eq__(), Version.__hash__(), Matcher.__hash__(), Version.__lt__(), Matcher.exact_version(), NormalizedVersion.is_prerelease(), LegacyVersion.is_prerelease(), SemanticVersion.is_prerelease(), and Matcher.match().
_resource_to_zip()
_resource_to_zip (self, resource_name) protected
Definition at line 1972 of file __init__.py.
    def _resource_to_zip(self, resource_name):
        return self._zipinfo_name(self._fn(self.module_path, resource_name))
_zipinfo_name()
_zipinfo_name (self, fspath) protected
Definition at line 1822 of file __init__.py.
    def _zipinfo_name(self, fspath):
        # Convert a virtual filename (full path to file) into a zipfile subpath
        # usable with the zipimport directory cache for our target archive
        fspath = fspath.rstrip(os.sep)
        if fspath == self.loader.archive:
            return ''
        if fspath.startswith(self.zip_pre):
            return fspath[len(self.zip_pre) :]
        raise AssertionError("%s is not a subpath of %s" % (fspath, self.zip_pre))
get_resource_filename()
get_resource_filename (self, manager, resource_name)
Reimplemented from NullProvider.
Definition at line 1844 of file __init__.py.
    def get_resource_filename(self, manager, resource_name):
        if not self.egg_name:
            raise NotImplementedError(
                "resource_filename() only supported for .egg, not .zip"
            )
        # no need to lock for extraction, since we use temp names
        zip_path = self._resource_to_zip(resource_name)
        eagers = self._get_eager_resources()
        if '/'.join(self._parts(zip_path)) in eagers:
            for name in eagers:
                self._extract_resource(manager, self._eager_to_zip(name))
        return self._extract_resource(manager, zip_path)
zipinfo()
zipinfo (self)
Definition at line 1841 of file __init__.py.
    def zipinfo(self):
        return self._zip_manifests.load(self.loader.archive)
Field Documentation
_dirindex
_dirindex protected
Definition at line 1956 of file __init__.py.
_zip_manifests
_zip_manifests = MemoizedZipManifests() static protected
Definition at line 1816 of file __init__.py.
eagers
eagers = None static
Definition at line 1815 of file __init__.py.
egg_root
egg_root
Definition at line 1837 of file __init__.py.
module_path
module_path
Definition at line 1973 of file __init__.py.
zip_pre
zip_pre
Definition at line 1820 of file __init__.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pkg_resources/__init__.py