Let us walk on the 3-isogeny graph: pip._vendor.certifi.core Namespace Reference
pip._vendor.certifi.core Namespace Reference
Functions
str where ()
str contents ()
str read_text (Package package, Resource resource, str encoding='utf-8', str errors='strict')
Variables
_CACERT_CTX = None
_CACERT_PATH = None
Package = Union[types.ModuleType, str]
Resource = Union[str, "os.PathLike"]
Detailed Description
certifi.py
~~~~~~~~~~
This module returns the installation location of cacert.pem or its contents.
Function Documentation
contents()
str contents ()
Definition at line 41 of file core.py.
    def contents() -> str:
        return files("pip._vendor.certifi").joinpath("cacert.pem").read_text(encoding="ascii")
References i, and pip._vendor.certifi.core.read_text().
read_text()
str read_text (Package package, Resource resource, str encoding = 'utf-8', str errors = 'strict')
Definition at line 91 of file core.py.
    ) -> str:
        with open(where(), encoding=encoding) as data:
            return data.read()
References i, pip._vendor.certifi.core.read_text(), and pip._vendor.certifi.core.where().
Referenced by pip._vendor.certifi.core.contents(), and pip._vendor.certifi.core.read_text().
where()
str where ()
Definition at line 17 of file core.py.
    def where() -> str:
        # This is slightly terrible, but we want to delay extracting the file
        # in cases where we're inside of a zipimport situation until someone
        # actually calls where(), but we don't want to re-extract the file
        # on every call of where(), so we'll do it once then store it in a
        # global variable.
        global _CACERT_CTX
        global _CACERT_PATH
        if _CACERT_PATH is None:
            # This is slightly janky, the importlib.resources API wants you to
            # manage the cleanup of this file, so it doesn't actually return a
            # path, it returns a context manager that will give you the path
            # when you enter it and will do any cleanup when you leave it. In
            # the common case of not needing a temporary file, it will just
            # return the file system location and the __exit__() is a no-op.
            #
            # We also have to hold onto the actual context manager, because
            # it will do the cleanup whenever it gets garbage collected, so
            # we will also store that at the global level as well.
            _CACERT_CTX = as_file(files("pip._vendor.certifi").joinpath("cacert.pem"))
            _CACERT_PATH = str(_CACERT_CTX.__enter__())
        return _CACERT_PATH
References i.
Referenced by pip._vendor.certifi.core.read_text().
Variable Documentation
_CACERT_CTX
_CACERT_CTX = None protected
Definition at line 14 of file core.py.
_CACERT_PATH
_CACERT_PATH = None protected
Definition at line 15 of file core.py.
Package
Package = Union[types.ModuleType, str]
Definition at line 84 of file core.py.
Resource
Resource = Union[str, "os.PathLike"]
Definition at line 85 of file core.py.