Let us walk on the 3-isogeny graph: JOHABDistributionAnalysis Class Reference
JOHABDistributionAnalysis Class Reference
Public Member Functions
None __init__ (self)
int get_order (self, Union[bytes, bytearray] byte_str)
Public Member Functions inherited from CharDistributionAnalysis
None reset (self)
None feed (self, Union[bytes, bytearray] char, int char_len)
float get_confidence (self)
bool got_enough_data (self)
Data Fields
typical_distribution_ratio
Data Fields inherited from CharDistributionAnalysis
typical_distribution_ratio
Protected Attributes
_char_to_freq_order
_table_size
Protected Attributes inherited from CharDistributionAnalysis
_table_size
_done
_total_chars
_freq_chars
Additional Inherited Members
Static Public Attributes inherited from CharDistributionAnalysis
int ENOUGH_DATA_THRESHOLD = 1024
float SURE_YES = 0.99
float SURE_NO = 0.01
int MINIMUM_DATA_THRESHOLD = 3
Detailed Description
Definition at line 168 of file chardistribution.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Reimplemented from CharDistributionAnalysis.
Definition at line 169 of file chardistribution.py.
    def __init__(self) -> None:
        super().__init__()
        self._char_to_freq_order = EUCKR_CHAR_TO_FREQ_ORDER
        self._table_size = EUCKR_TABLE_SIZE
        self.typical_distribution_ratio = EUCKR_TYPICAL_DISTRIBUTION_RATIO
References JOHABDistributionAnalysis.__init__(), and i.
Referenced by JOHABDistributionAnalysis.__init__(), and Protocol.__init_subclass__().
Member Function Documentation
get_order()
int get_order (self, Union[bytes, bytearray] byte_str)
Reimplemented from CharDistributionAnalysis.
Definition at line 175 of file chardistribution.py.
    def get_order(self, byte_str: Union[bytes, bytearray]) -> int:
        first_char = byte_str[0]
        if 0x88 <= first_char < 0xD4:
            code = first_char * 256 + byte_str[1]
            return JOHAB_TO_EUCKR_ORDER_TABLE.get(code, -1)
        return -1
References i.
Referenced by JapaneseContextAnalysis.feed(), and CharDistributionAnalysis.feed().
Field Documentation
_char_to_freq_order
_char_to_freq_order protected
Definition at line 171 of file chardistribution.py.
Referenced by CharDistributionAnalysis.__init__(), and CharDistributionAnalysis.feed().
_table_size
_table_size protected
Definition at line 172 of file chardistribution.py.
Referenced by CharDistributionAnalysis.feed().
typical_distribution_ratio
typical_distribution_ratio
Definition at line 173 of file chardistribution.py.
Referenced by CharDistributionAnalysis.get_confidence().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/chardet/chardistribution.py