Let us walk on the 3-isogeny graph: RetryError Class Reference
RetryError Class Reference
Public Member Functions
None __init__ (self, "Future" last_attempt)
"t.NoReturn" reraise (self)
str __str__ (self)
Data Fields
last_attempt
Detailed Description
Encapsulates the last attempt instance right before giving up.
Definition at line 151 of file __init__.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, "Future" last_attempt)
Definition at line 154 of file __init__.py.
    def __init__(self, last_attempt: "Future") -> None:
        self.last_attempt = last_attempt
        super().__init__(last_attempt)
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__str__()
str __str__ (self)
Definition at line 163 of file __init__.py.
    def __str__(self) -> str:
        return f"{self.__class__.__name__}[{self.last_attempt}]"
reraise()
"t.NoReturn" reraise (self)
Definition at line 158 of file __init__.py.
    def reraise(self) -> "t.NoReturn":
        if self.last_attempt.failed:
            raise self.last_attempt.result()
        raise self
References RetryError.last_attempt.
Referenced by BaseRetrying.copy(), and BaseRetrying.iter().
Field Documentation
last_attempt
last_attempt
Definition at line 155 of file __init__.py.
Referenced by RetryError.reraise().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/tenacity/__init__.py