Let us walk on the 3-isogeny graph: FoundCandidates Class Reference
FoundCandidates Class Reference
Public Member Functions
__init__ (self, Callable[[], Iterator[IndexCandidateInfo]] get_infos, Optional[Candidate] installed, bool prefers_installed, Set[int] incompatible_ids)
Any __getitem__ (self, Any index)
Iterator[Candidate] __iter__ (self)
int __len__ (self)
bool __bool__ (self)
Protected Attributes
_get_infos
_installed
_prefers_installed
_incompatible_ids
Detailed Description
A lazy sequence to provide candidates to the resolver.
The intended usage is to return this from `find_matches()` so the resolver
can iterate through the sequence multiple times, but only access the index
page when remote packages are actually needed. This improve performances
when suitable candidates are already installed on disk.
Definition at line 108 of file found_candidates.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, Callable[[], Iterator[IndexCandidateInfo]] get_infos, Optional[Candidate] installed, bool prefers_installed, Set[int] incompatible_ids)
Definition at line 117 of file found_candidates.py.
    ):
        self._get_infos = get_infos
        self._installed = installed
        self._prefers_installed = prefers_installed
        self._incompatible_ids = incompatible_ids
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__bool__()
bool __bool__ (self)
Definition at line 152 of file found_candidates.py.
    def __bool__(self) -> bool:
        if self._prefers_installed and self._installed:
            return True
        return any(self)
References FoundCandidates._installed, FoundCandidates._prefers_installed, and i.
__getitem__()
Any __getitem__ (self, Any index)
Definition at line 129 of file found_candidates.py.
    def __getitem__(self, index: Any) -> Any:
        # Implemented to satisfy the ABC check. This is not needed by the
        # resolver, and should not be used by the provider either (for
        # performance reasons).
        raise NotImplementedError("don't do this")
References i.
__iter__()
Iterator[Candidate] __iter__ (self)
Definition at line 135 of file found_candidates.py.
    def __iter__(self) -> Iterator[Candidate]:
        infos = self._get_infos()
        if not self._installed:
            iterator = _iter_built(infos)
        elif self._prefers_installed:
            iterator = _iter_built_with_prepended(self._installed, infos)
        else:
            iterator = _iter_built_with_inserted(self._installed, infos)
        return (c for c in iterator if id(c) not in self._incompatible_ids)
References FoundCandidates._get_infos, FoundCandidates._incompatible_ids, FoundCandidates._installed, pip._internal.resolution.resolvelib.found_candidates._iter_built(), pip._internal.resolution.resolvelib.found_candidates._iter_built_with_inserted(), pip._internal.resolution.resolvelib.found_candidates._iter_built_with_prepended(), and FoundCandidates._prefers_installed.
__len__()
int __len__ (self)
Definition at line 145 of file found_candidates.py.
    def __len__(self) -> int:
        # Implemented to satisfy the ABC check. This is not needed by the
        # resolver, and should not be used by the provider either (for
        # performance reasons).
        raise NotImplementedError("don't do this")
References i.
Field Documentation
_get_infos
_get_infos protected
Definition at line 124 of file found_candidates.py.
Referenced by FoundCandidates.__iter__().
_incompatible_ids
_incompatible_ids protected
Definition at line 127 of file found_candidates.py.
Referenced by FoundCandidates.__iter__().
_installed
_installed protected
Definition at line 125 of file found_candidates.py.
Referenced by FoundCandidates.__bool__(), and FoundCandidates.__iter__().
_prefers_installed
_prefers_installed protected
Definition at line 126 of file found_candidates.py.
Referenced by FoundCandidates.__bool__(), and FoundCandidates.__iter__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py