Let us walk on the 3-isogeny graph: InitTest Class Reference
InitTest Class Reference
Public Member Functions
setUp (self)
tearDown (self)
assertWrapped (self)
assertNotWrapped (self)
testInitWrapsOnWindows (self, _)
testInitDoesntWrapOnEmulatedWindows (self, _)
testInitDoesntWrapOnNonWindows (self)
testInitDoesntWrapIfNone (self)
testInitAutoresetOnWrapsOnAllPlatforms (self)
testInitWrapOffDoesntWrapOnWindows (self)
testInitWrapOffIncompatibleWithAutoresetOn (self)
testAutoResetPassedOn (self, mockATW32, _)
testAutoResetChangeable (self, mockATW32)
testAtexitRegisteredOnlyOnce (self, mockRegister)
Detailed Description
Definition at line 18 of file initialise_test.py.
Member Function Documentation
assertNotWrapped()
assertNotWrapped (self)
Definition at line 38 of file initialise_test.py.
    def assertNotWrapped(self):
        self.assertIs(sys.stdout, orig_stdout, 'stdout should not be wrapped')
        self.assertIs(sys.stderr, orig_stderr, 'stderr should not be wrapped')
References i.
Referenced by InitTest.setUp(), InitTest.testInitDoesntWrapOnEmulatedWindows(), InitTest.testInitDoesntWrapOnNonWindows(), and InitTest.testInitWrapOffDoesntWrapOnWindows().
assertWrapped()
assertWrapped (self)
Definition at line 30 of file initialise_test.py.
    def assertWrapped(self):
        self.assertIsNot(sys.stdout, orig_stdout, 'stdout should be wrapped')
        self.assertIsNot(sys.stderr, orig_stderr, 'stderr should be wrapped')
        self.assertTrue(isinstance(sys.stdout, StreamWrapper),
            'bad stdout wrapper')
        self.assertTrue(isinstance(sys.stderr, StreamWrapper),
            'bad stderr wrapper')
References i.
Referenced by InitTest.testInitAutoresetOnWrapsOnAllPlatforms(), and InitTest.testInitWrapsOnWindows().
setUp()
setUp (self)
Definition at line 21 of file initialise_test.py.
    def setUp(self):
        # sanity check
        self.assertNotWrapped()
References InitTest.assertNotWrapped().
tearDown()
tearDown (self)
Definition at line 25 of file initialise_test.py.
    def tearDown(self):
        _wipe_internal_state_for_tests()
        sys.stdout = orig_stdout
        sys.stderr = orig_stderr
References i.
testAtexitRegisteredOnlyOnce()
testAtexitRegisteredOnlyOnce (self, mockRegister)
Definition at line 111 of file initialise_test.py.
    def testAtexitRegisteredOnlyOnce(self, mockRegister):
        init()
        self.assertTrue(mockRegister.called)
        mockRegister.reset_mock()
        init()
        self.assertFalse(mockRegister.called)
References i.
testAutoResetChangeable()
testAutoResetChangeable (self, mockATW32)
Definition at line 93 of file initialise_test.py.
    def testAutoResetChangeable(self, mockATW32):
        with osname("nt"):
            init()
            init(autoreset=True)
            self.assertEqual(len(mockATW32.call_args_list), 4)
            self.assertEqual(mockATW32.call_args_list[2][1]['autoreset'], True)
            self.assertEqual(mockATW32.call_args_list[3][1]['autoreset'], True)
            init()
            self.assertEqual(len(mockATW32.call_args_list), 6)
            self.assertEqual(
                mockATW32.call_args_list[4][1]['autoreset'], False)
            self.assertEqual(
                mockATW32.call_args_list[5][1]['autoreset'], False)
References i.
testAutoResetPassedOn()
testAutoResetPassedOn (self, mockATW32, _)
Definition at line 85 of file initialise_test.py.
    def testAutoResetPassedOn(self, mockATW32, _):
        with osname("nt"):
            init(autoreset=True)
            self.assertEqual(len(mockATW32.call_args_list), 2)
            self.assertEqual(mockATW32.call_args_list[1][1]['autoreset'], True)
            self.assertEqual(mockATW32.call_args_list[0][1]['autoreset'], True)
References i.
testInitAutoresetOnWrapsOnAllPlatforms()
testInitAutoresetOnWrapsOnAllPlatforms (self)
Definition at line 70 of file initialise_test.py.
    def testInitAutoresetOnWrapsOnAllPlatforms(self):
        with osname("posix"):
            init(autoreset=True)
            self.assertWrapped()
References InitTest.assertWrapped().
testInitDoesntWrapIfNone()
testInitDoesntWrapIfNone (self)
Definition at line 62 of file initialise_test.py.
    def testInitDoesntWrapIfNone(self):
        with replace_by(None):
            init()
            # We can't use assertNotWrapped here because replace_by(None)
            # changes stdout/stderr already.
            self.assertIsNone(sys.stdout)
            self.assertIsNone(sys.stderr)
References i.
testInitDoesntWrapOnEmulatedWindows()
testInitDoesntWrapOnEmulatedWindows (self, _)
Definition at line 52 of file initialise_test.py.
    def testInitDoesntWrapOnEmulatedWindows(self, _):
        with osname("nt"):
            init()
            self.assertNotWrapped()
References InitTest.assertNotWrapped().
testInitDoesntWrapOnNonWindows()
testInitDoesntWrapOnNonWindows (self)
Definition at line 57 of file initialise_test.py.
    def testInitDoesntWrapOnNonWindows(self):
        with osname("posix"):
            init()
            self.assertNotWrapped()
References InitTest.assertNotWrapped().
testInitWrapOffDoesntWrapOnWindows()
testInitWrapOffDoesntWrapOnWindows (self)
Definition at line 75 of file initialise_test.py.
    def testInitWrapOffDoesntWrapOnWindows(self):
        with osname("nt"):
            init(wrap=False)
            self.assertNotWrapped()
References InitTest.assertNotWrapped().
testInitWrapOffIncompatibleWithAutoresetOn()
testInitWrapOffIncompatibleWithAutoresetOn (self)
Definition at line 80 of file initialise_test.py.
    def testInitWrapOffIncompatibleWithAutoresetOn(self):
        self.assertRaises(ValueError, lambda: init(autoreset=True, wrap=False))
testInitWrapsOnWindows()
testInitWrapsOnWindows (self, _)
Definition at line 45 of file initialise_test.py.
    def testInitWrapsOnWindows(self, _):
        with osname("nt"):
            init()
            self.assertWrapped()
References InitTest.assertWrapped().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/colorama/tests/initialise_test.py