Let us walk on the 3-isogeny graph: pip._vendor.rich.pretty Namespace Reference
pip._vendor.rich.pretty Namespace Reference
Data Structures
class _Line
class BrokenRepr
class Node
class Pretty
class StockKeepingUnit
class Thing
Functions
bool _is_attr_object (Any obj)
Sequence["_attr_module.Attribute[Any]"] _get_attr_fields (Any obj)
bool _is_dataclass_repr (object obj)
bool _has_default_namedtuple_repr (object obj)
Union[str, None] _ipy_display_hook (Any value, Optional["Console"] console=None, "OverflowMethod" overflow="ignore", bool crop=False, bool indent_guides=False, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None, bool expand_all=False)
bool _safe_isinstance (object obj, Union[type, Tuple[type,...]] class_or_tuple)
None install (Optional["Console"] console=None, "OverflowMethod" overflow="ignore", bool crop=False, bool indent_guides=False, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None, bool expand_all=False)
Tuple[str, str, str] _get_braces_for_defaultdict (DefaultDict[Any, Any] _object)
Tuple[str, str, str] _get_braces_for_array ("array[Any]" _object)
bool is_expandable (Any obj)
bool _is_namedtuple (Any obj)
Node traverse (Any _object, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None)
str pretty_repr (Any _object, *int max_width=80, int indent_size=4, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None, bool expand_all=False)
None pprint (Any _object, *Optional["Console"] console=None, bool indent_guides=True, Optional[int] max_length=None, Optional[int] max_string=None, Optional[int] max_depth=None, bool expand_all=False)
Variables
_has_attrs = hasattr(_attr_module, "ib")
_dummy_namedtuple = collections.namedtuple("_dummy_namedtuple", [])
dict _BRACES
_CONTAINERS = tuple(_BRACES.keys())
tuple _MAPPING_CONTAINERS = (dict, os._Environ, MappingProxyType, UserDict)
d
dict data
Function Documentation
_get_attr_fields()
Sequence["_attr_module.Attribute[Any]"] _get_attr_fields (Any obj) protected
Get fields for an attrs object.
Definition at line 63 of file pretty.py.
def _get_attr_fields(obj: Any) -> Sequence["_attr_module.Attribute[Any]"]:
    """Get fields for an attrs object."""
    return _attr_module.fields(type(obj)) if _has_attrs else []
References i.
Referenced by pip._vendor.rich.pretty.traverse().
_get_braces_for_array()
Tuple[str, str, str] _get_braces_for_array ("array[Any]" _object) protected
Definition at line 355 of file pretty.py.
def _get_braces_for_array(_object: "array[Any]") -> Tuple[str, str, str]:
    return (f"array({_object.typecode!r}, [", "])", f"array({_object.typecode!r})")
_get_braces_for_defaultdict()
Tuple[str, str, str] _get_braces_for_defaultdict (DefaultDict[Any, Any] _object) protected
Definition at line 347 of file pretty.py.
def _get_braces_for_defaultdict(_object: DefaultDict[Any, Any]) -> Tuple[str, str, str]:
    return (
        f"defaultdict({_object.default_factory!r}, {{",
        "})",
        f"defaultdict({_object.default_factory!r}, {{}})",
    )
_has_default_namedtuple_repr()
bool _has_default_namedtuple_repr (object obj) protected
Check if an instance of namedtuple contains the default repr
Args:
    obj (object): A namedtuple
Returns:
    bool: True if the default repr is used, False if there's a custom repr.
Definition at line 88 of file pretty.py.
def _has_default_namedtuple_repr(obj: object) -> bool:
    """Check if an instance of namedtuple contains the default repr
    Args:
        obj (object): A namedtuple
    Returns:
        bool: True if the default repr is used, False if there's a custom repr.
    """
    obj_file = None
    try:
        obj_file = inspect.getfile(obj.__repr__)
    except (OSError, TypeError):
        # OSError handles case where object is defined in __main__ scope, e.g. REPL - no filename available.
        # TypeError trapped defensively, in case of object without filename slips through.
        pass
    default_repr_file = inspect.getfile(_dummy_namedtuple.__repr__)
    return obj_file == default_repr_file
References i.
Referenced by pip._vendor.rich.pretty.traverse().
_ipy_display_hook()
Union[str, None] _ipy_display_hook (Any value, Optional["Console"] console = None, "OverflowMethod" overflow = "ignore", bool crop = False, bool indent_guides = False, Optional[int] max_length = None, Optional[int] max_string = None, Optional[int] max_depth = None, bool expand_all = False) protected
Definition at line 108 of file pretty.py.
) -> Union[str, None]:
    # needed here to prevent circular import:
    from .console import ConsoleRenderable
    # always skip rich generated jupyter renderables or None values
    if _safe_isinstance(value, JupyterRenderable) or value is None:
        return None
    console = console or get_console()
    with console.capture() as capture:
        # certain renderables should start on a new line
        if _safe_isinstance(value, ConsoleRenderable):
            console.line()
        console.print(
            value
            if _safe_isinstance(value, RichRenderable)
            else Pretty(
                value,
                overflow=overflow,
                indent_guides=indent_guides,
                max_length=max_length,
                max_string=max_string,
                max_depth=max_depth,
                expand_all=expand_all,
                margin=12,
            ),
            crop=crop,
            new_line_start=True,
            end="",
        )
    # strip trailing newline, not usually part of a text repr
    # I'm not sure if this should be prevented at a lower level
    return capture.get().rstrip("\n")
References pip._vendor.rich.pretty._safe_isinstance(), and i.
Referenced by pip._vendor.rich.pretty.install().
_is_attr_object()
bool _is_attr_object (Any obj) protected
Check if an object was created with attrs module.
Definition at line 58 of file pretty.py.
def _is_attr_object(obj: Any) -> bool:
    """Check if an object was created with attrs module."""
    return _has_attrs and _attr_module.has(type(obj))
References i.
Referenced by pip._vendor.rich.pretty.is_expandable(), and pip._vendor.rich.pretty.traverse().
_is_dataclass_repr()
bool _is_dataclass_repr (object obj) protected
Check if an instance of a dataclass contains the default repr.
Args:
    obj (object): A dataclass instance.
Returns:
    bool: True if the default repr is used, False if there is a custom repr.
Definition at line 68 of file pretty.py.
def _is_dataclass_repr(obj: object) -> bool:
    """Check if an instance of a dataclass contains the default repr.
    Args:
        obj (object): A dataclass instance.
    Returns:
        bool: True if the default repr is used, False if there is a custom repr.
    """
    # Digging in to a lot of internals here
    # Catching all exceptions in case something is missing on a non CPython implementation
    try:
        return obj.__repr__.__code__.co_filename == dataclasses.__file__
    except Exception:  # pragma: no coverage
        return False
References i.
Referenced by pip._vendor.rich.pretty.traverse().
_is_namedtuple()
bool _is_namedtuple (Any obj) protected
Checks if an object is most likely a namedtuple. It is possible
to craft an object that passes this check and isn't a namedtuple, but
there is only a minuscule chance of this happening unintentionally.
Args:
    obj (Any): The object to test
Returns:
    bool: True if the object is a namedtuple. False otherwise.
Definition at line 541 of file pretty.py.
def _is_namedtuple(obj: Any) -> bool:
    """Checks if an object is most likely a namedtuple. It is possible
    to craft an object that passes this check and isn't a namedtuple, but
    there is only a minuscule chance of this happening unintentionally.
    Args:
        obj (Any): The object to test
    Returns:
        bool: True if the object is a namedtuple. False otherwise.
    """
    try:
        fields = getattr(obj, "_fields", None)
    except Exception:
        # Being very defensive - if we cannot get the attr then its not a namedtuple
        return False
    return isinstance(obj, tuple) and isinstance(fields, tuple)
References i.
Referenced by pip._vendor.rich.pretty.traverse().
_safe_isinstance()
bool _safe_isinstance (object obj, Union[type, Tuple[type, ...]] class_or_tuple) protected
isinstance can fail in rare cases, for example types with no __class__
Definition at line 154 of file pretty.py.
) -> bool:
    """isinstance can fail in rare cases, for example types with no __class__"""
    try:
        return isinstance(obj, class_or_tuple)
    except Exception:
        return False
References i.
Referenced by pip._vendor.rich.pretty._ipy_display_hook(), pip._vendor.rich.pretty.install(), pip._vendor.rich.pretty.is_expandable(), pip._vendor.rich.pretty.pretty_repr(), and pip._vendor.rich.pretty.traverse().
install()
None install (Optional["Console"] console = None, "OverflowMethod" overflow = "ignore", bool crop = False, bool indent_guides = False, Optional[int] max_length = None, Optional[int] max_string = None, Optional[int] max_depth = None, bool expand_all = False)
Install automatic pretty printing in the Python REPL.
Args:
    console (Console, optional): Console instance or ``None`` to use global console. Defaults to None.
    overflow (Optional[OverflowMethod], optional): Overflow method. Defaults to "ignore".
    crop (Optional[bool], optional): Enable cropping of long lines. Defaults to False.
    indent_guides (bool, optional): Enable indentation guides. Defaults to False.
    max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
        Defaults to None.
    max_string (int, optional): Maximum length of string before truncating, or None to disable. Defaults to None.
    max_depth (int, optional): Maximum depth of nested data structures, or None for no maximum. Defaults to None.
    expand_all (bool, optional): Expand all containers. Defaults to False.
    max_frames (int): Maximum number of frames to show in a traceback, 0 for no maximum. Defaults to 100.
Definition at line 164 of file pretty.py.
) -> None:
    """Install automatic pretty printing in the Python REPL.
    Args:
        console (Console, optional): Console instance or ``None`` to use global console. Defaults to None.
        overflow (Optional[OverflowMethod], optional): Overflow method. Defaults to "ignore".
        crop (Optional[bool], optional): Enable cropping of long lines. Defaults to False.
        indent_guides (bool, optional): Enable indentation guides. Defaults to False.
        max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
            Defaults to None.
        max_string (int, optional): Maximum length of string before truncating, or None to disable. Defaults to None.
        max_depth (int, optional): Maximum depth of nested data structures, or None for no maximum. Defaults to None.
        expand_all (bool, optional): Expand all containers. Defaults to False.
        max_frames (int): Maximum number of frames to show in a traceback, 0 for no maximum. Defaults to 100.
    """
    from pip._vendor.rich import get_console
    console = console or get_console()
    assert console is not None
    def display_hook(value: Any) -> None:
        """Replacement sys.displayhook which prettifies objects with Rich."""
        if value is not None:
            assert console is not None
            builtins._ = None  # type: ignore[attr-defined]
            console.print(
                value
                if _safe_isinstance(value, RichRenderable)
                else Pretty(
                    value,
                    overflow=overflow,
                    indent_guides=indent_guides,
                    max_length=max_length,
                    max_string=max_string,
                    max_depth=max_depth,
                    expand_all=expand_all,
                ),
                crop=crop,
            )
            builtins._ = value  # type: ignore[attr-defined]
    if "get_ipython" in globals():
        ip = get_ipython()  # type: ignore[name-defined]
        from IPython.core.formatters import BaseFormatter
        class RichFormatter(BaseFormatter):  # type: ignore[misc]
            pprint: bool = True
            def __call__(self, value: Any) -> Any:
                if self.pprint:
                    return _ipy_display_hook(
                        value,
                        console=get_console(),
                        overflow=overflow,
                        indent_guides=indent_guides,
                        max_length=max_length,
                        max_string=max_string,
                        max_depth=max_depth,
                        expand_all=expand_all,
                    )
                else:
                    return repr(value)
        # replace plain text formatter with rich formatter
        rich_formatter = RichFormatter()
        ip.display_formatter.formatters["text/plain"] = rich_formatter
    else:
        sys.displayhook = display_hook
References pip._vendor.rich.pretty._ipy_display_hook(), pip._vendor.rich.pretty._safe_isinstance(), and i.
is_expandable()
bool is_expandable (Any obj)
Check if an object may be expanded by pretty print.
Definition at line 378 of file pretty.py.
def is_expandable(obj: Any) -> bool:
    """Check if an object may be expanded by pretty print."""
    return (
        _safe_isinstance(obj, _CONTAINERS)
        or (is_dataclass(obj))
        or (hasattr(obj, "__rich_repr__"))
        or _is_attr_object(obj)
    ) and not isclass(obj)
@dataclass
References pip._vendor.rich.pretty._is_attr_object(), pip._vendor.rich.pretty._safe_isinstance(), and i.
pprint()
None pprint (Any _object, *Optional["Console"] console = None, bool indent_guides = True, Optional[int] max_length = None, Optional[int] max_string = None, Optional[int] max_depth = None, bool expand_all = False)
A convenience function for pretty printing.
Args:
    _object (Any): Object to pretty print.
    console (Console, optional): Console instance, or None to use default. Defaults to None.
    max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
        Defaults to None.
    max_string (int, optional): Maximum length of strings before truncating, or None to disable. Defaults to None.
    max_depth (int, optional): Maximum depth for nested data structures, or None for unlimited depth. Defaults to None.
    indent_guides (bool, optional): Enable indentation guides. Defaults to True.
    expand_all (bool, optional): Expand all containers. Defaults to False.
Definition at line 896 of file pretty.py.
) -> None:
    """A convenience function for pretty printing.
    Args:
        _object (Any): Object to pretty print.
        console (Console, optional): Console instance, or None to use default. Defaults to None.
        max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
            Defaults to None.
        max_string (int, optional): Maximum length of strings before truncating, or None to disable. Defaults to None.
        max_depth (int, optional): Maximum depth for nested data structures, or None for unlimited depth. Defaults to None.
        indent_guides (bool, optional): Enable indentation guides. Defaults to True.
        expand_all (bool, optional): Expand all containers. Defaults to False.
    """
    _console = get_console() if console is None else console
    _console.print(
        Pretty(
            _object,
            max_length=max_length,
            max_string=max_string,
            max_depth=max_depth,
            indent_guides=indent_guides,
            expand_all=expand_all,
            overflow="ignore",
        ),
        soft_wrap=True,
    )
References i.
pretty_repr()
str pretty_repr (Any _object, *int max_width = 80, int indent_size = 4, Optional[int] max_length = None, Optional[int] max_string = None, Optional[int] max_depth = None, bool expand_all = False)
Prettify repr string by expanding on to new lines to fit within a given width.
Args:
    _object (Any): Object to repr.
    max_width (int, optional): Desired maximum width of repr string. Defaults to 80.
    indent_size (int, optional): Number of spaces to indent. Defaults to 4.
    max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
        Defaults to None.
    max_string (int, optional): Maximum length of string before truncating, or None to disable truncating.
        Defaults to None.
    max_depth (int, optional): Maximum depth of nested data structure, or None for no depth.
        Defaults to None.
    expand_all (bool, optional): Expand all containers regardless of available width. Defaults to False.
Returns:
    str: A possibly multi-line representation of the object.
Definition at line 856 of file pretty.py.
) -> str:
    """Prettify repr string by expanding on to new lines to fit within a given width.
    Args:
        _object (Any): Object to repr.
        max_width (int, optional): Desired maximum width of repr string. Defaults to 80.
        indent_size (int, optional): Number of spaces to indent. Defaults to 4.
        max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
            Defaults to None.
        max_string (int, optional): Maximum length of string before truncating, or None to disable truncating.
            Defaults to None.
        max_depth (int, optional): Maximum depth of nested data structure, or None for no depth.
            Defaults to None.
        expand_all (bool, optional): Expand all containers regardless of available width. Defaults to False.
    Returns:
        str: A possibly multi-line representation of the object.
    """
    if _safe_isinstance(_object, Node):
        node = _object
    else:
        node = traverse(
            _object, max_length=max_length, max_string=max_string, max_depth=max_depth
        )
    repr_str: str = node.render(
        max_width=max_width, indent_size=indent_size, expand_all=expand_all
    )
    return repr_str
References pip._vendor.rich.pretty._safe_isinstance(), i, and pip._vendor.rich.pretty.traverse().
Referenced by Pretty.__rich_console__(), and Pretty.__rich_measure__().
traverse()
Node traverse (Any _object, Optional[int] max_length = None, Optional[int] max_string = None, Optional[int] max_depth = None)
Traverse object and generate a tree.
Args:
    _object (Any): Object to be traversed.
    max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
        Defaults to None.
    max_string (int, optional): Maximum length of string before truncating, or None to disable truncating.
        Defaults to None.
    max_depth (int, optional): Maximum depth of data structures, or None for no maximum.
        Defaults to None.
Returns:
    Node: The root of a tree structure which can be used to render a pretty repr.
Definition at line 560 of file pretty.py.
) -> Node:
    """Traverse object and generate a tree.
    Args:
        _object (Any): Object to be traversed.
        max_length (int, optional): Maximum length of containers before abbreviating, or None for no abbreviation.
            Defaults to None.
        max_string (int, optional): Maximum length of string before truncating, or None to disable truncating.
            Defaults to None.
        max_depth (int, optional): Maximum depth of data structures, or None for no maximum.
            Defaults to None.
    Returns:
        Node: The root of a tree structure which can be used to render a pretty repr.
    """
    def to_repr(obj: Any) -> str:
        """Get repr string for an object, but catch errors."""
        if (
            max_string is not None
            and _safe_isinstance(obj, (bytes, str))
            and len(obj) > max_string
        ):
            truncated = len(obj) - max_string
            obj_repr = f"{obj[:max_string]!r}+{truncated}"
        else:
            try:
                obj_repr = repr(obj)
            except Exception as error:
                obj_repr = f"<repr-error {str(error)!r}>"
        return obj_repr
    visited_ids: Set[int] = set()
    push_visited = visited_ids.add
    pop_visited = visited_ids.remove
    def _traverse(obj: Any, root: bool = False, depth: int = 0) -> Node:
        """Walk the object depth first."""
        obj_id = id(obj)
        if obj_id in visited_ids:
            # Recursion detected
            return Node(value_repr="...")
        obj_type = type(obj)
        children: List[Node]
        reached_max_depth = max_depth is not None and depth >= max_depth
        def iter_rich_args(rich_args: Any) -> Iterable[Union[Any, Tuple[str, Any]]]:
            for arg in rich_args:
                if _safe_isinstance(arg, tuple):
                    if len(arg) == 3:
                        key, child, default = arg
                        if default == child:
                            continue
                        yield key, child
                    elif len(arg) == 2:
                        key, child = arg
                        yield key, child
                    elif len(arg) == 1:
                        yield arg[0]
                else:
                    yield arg
        try:
            fake_attributes = hasattr(
                obj, "awehoi234_wdfjwljet234_234wdfoijsdfmmnxpi492"
            )
        except Exception:
            fake_attributes = False
        rich_repr_result: Optional[RichReprResult] = None
        if not fake_attributes:
            try:
                if hasattr(obj, "__rich_repr__") and not isclass(obj):
                    rich_repr_result = obj.__rich_repr__()
            except Exception:
                pass
        if rich_repr_result is not None:
            push_visited(obj_id)
            angular = getattr(obj.__rich_repr__, "angular", False)
            args = list(iter_rich_args(rich_repr_result))
            class_name = obj.__class__.__name__
            if args:
                children = []
                append = children.append
                if reached_max_depth:
                    if angular:
                        node = Node(value_repr=f"<{class_name}...>")
                    else:
                        node = Node(value_repr=f"{class_name}(...)")
                else:
                    if angular:
                        node = Node(
                            open_brace=f"<{class_name} ",
                            close_brace=">",
                            children=children,
                            last=root,
                            separator=" ",
                        )
                    else:
                        node = Node(
                            open_brace=f"{class_name}(",
                            close_brace=")",
                            children=children,
                            last=root,
                        )
                    for last, arg in loop_last(args):
                        if _safe_isinstance(arg, tuple):
                            key, child = arg
                            child_node = _traverse(child, depth=depth + 1)
                            child_node.last = last
                            child_node.key_repr = key
                            child_node.key_separator = "="
                            append(child_node)
                        else:
                            child_node = _traverse(arg, depth=depth + 1)
                            child_node.last = last
                            append(child_node)
            else:
                node = Node(
                    value_repr=f"<{class_name}>" if angular else f"{class_name}()",
                    children=[],
                    last=root,
                )
            pop_visited(obj_id)
        elif _is_attr_object(obj) and not fake_attributes:
            push_visited(obj_id)
            children = []
            append = children.append
            attr_fields = _get_attr_fields(obj)
            if attr_fields:
                if reached_max_depth:
                    node = Node(value_repr=f"{obj.__class__.__name__}(...)")
                else:
                    node = Node(
                        open_brace=f"{obj.__class__.__name__}(",
                        close_brace=")",
                        children=children,
                        last=root,
                    )
                    def iter_attrs() -> Iterable[
                        Tuple[str, Any, Optional[Callable[[Any], str]]]
                    ]:
                        """Iterate over attr fields and values."""
                        for attr in attr_fields:
                            if attr.repr:
                                try:
                                    value = getattr(obj, attr.name)
                                except Exception as error:
                                    # Can happen, albeit rarely
                                    yield (attr.name, error, None)
                                else:
                                    yield (
                                        attr.name,
                                        value,
                                        attr.repr if callable(attr.repr) else None,
                                    )
                    for last, (name, value, repr_callable) in loop_last(iter_attrs()):
                        if repr_callable:
                            child_node = Node(value_repr=str(repr_callable(value)))
                        else:
                            child_node = _traverse(value, depth=depth + 1)
                        child_node.last = last
                        child_node.key_repr = name
                        child_node.key_separator = "="
                        append(child_node)
            else:
                node = Node(
                    value_repr=f"{obj.__class__.__name__}()", children=[], last=root
                )
            pop_visited(obj_id)
        elif (
            is_dataclass(obj)
            and not _safe_isinstance(obj, type)
            and not fake_attributes
            and _is_dataclass_repr(obj)
        ):
            push_visited(obj_id)
            children = []
            append = children.append
            if reached_max_depth:
                node = Node(value_repr=f"{obj.__class__.__name__}(...)")
            else:
                node = Node(
                    open_brace=f"{obj.__class__.__name__}(",
                    close_brace=")",
                    children=children,
                    last=root,
                    empty=f"{obj.__class__.__name__}()",
                )
                for last, field in loop_last(
                    field for field in fields(obj) if field.repr
                ):
                    child_node = _traverse(getattr(obj, field.name), depth=depth + 1)
                    child_node.key_repr = field.name
                    child_node.last = last
                    child_node.key_separator = "="
                    append(child_node)
            pop_visited(obj_id)
        elif _is_namedtuple(obj) and _has_default_namedtuple_repr(obj):
            push_visited(obj_id)
            class_name = obj.__class__.__name__
            if reached_max_depth:
                # If we've reached the max depth, we still show the class name, but not its contents
                node = Node(
                    value_repr=f"{class_name}(...)",
                )
            else:
                children = []
                append = children.append
                node = Node(
                    open_brace=f"{class_name}(",
                    close_brace=")",
                    children=children,
                    empty=f"{class_name}()",
                )
                for last, (key, value) in loop_last(obj._asdict().items()):
                    child_node = _traverse(value, depth=depth + 1)
                    child_node.key_repr = key
                    child_node.last = last
                    child_node.key_separator = "="
                    append(child_node)
            pop_visited(obj_id)
        elif _safe_isinstance(obj, _CONTAINERS):
            for container_type in _CONTAINERS:
                if _safe_isinstance(obj, container_type):
                    obj_type = container_type
                    break
            push_visited(obj_id)
            open_brace, close_brace, empty = _BRACES[obj_type](obj)
            if reached_max_depth:
                node = Node(value_repr=f"{open_brace}...{close_brace}")
            elif obj_type.__repr__ != type(obj).__repr__:
                node = Node(value_repr=to_repr(obj), last=root)
            elif obj:
                children = []
                node = Node(
                    open_brace=open_brace,
                    close_brace=close_brace,
                    children=children,
                    last=root,
                )
                append = children.append
                num_items = len(obj)
                last_item_index = num_items - 1
                if _safe_isinstance(obj, _MAPPING_CONTAINERS):
                    iter_items = iter(obj.items())
                    if max_length is not None:
                        iter_items = islice(iter_items, max_length)
                    for index, (key, child) in enumerate(iter_items):
                        child_node = _traverse(child, depth=depth + 1)
                        child_node.key_repr = to_repr(key)
                        child_node.last = index == last_item_index
                        append(child_node)
                else:
                    iter_values = iter(obj)
                    if max_length is not None:
                        iter_values = islice(iter_values, max_length)
                    for index, child in enumerate(iter_values):
                        child_node = _traverse(child, depth=depth + 1)
                        child_node.last = index == last_item_index
                        append(child_node)
                if max_length is not None and num_items > max_length:
                    append(Node(value_repr=f"... +{num_items - max_length}", last=True))
            else:
                node = Node(empty=empty, children=[], last=root)
            pop_visited(obj_id)
        else:
            node = Node(value_repr=to_repr(obj), last=root)
        node.is_tuple = _safe_isinstance(obj, tuple)
        node.is_namedtuple = _is_namedtuple(obj)
        return node
    node = _traverse(_object, root=True)
    return node
References pip._vendor.rich.pretty._get_attr_fields(), pip._vendor.rich.pretty._has_default_namedtuple_repr(), pip._vendor.rich.pretty._is_attr_object(), pip._vendor.rich.pretty._is_dataclass_repr(), pip._vendor.rich.pretty._is_namedtuple(), pip._vendor.rich.pretty._safe_isinstance(), and i.
Referenced by pip._vendor.rich.pretty.pretty_repr().
Variable Documentation
_BRACES
dict _BRACES protected
Initial value:
=  {
    os._Environ: lambda _object: ("environ({", "})", "environ({})"),
    array: _get_braces_for_array,
    defaultdict: _get_braces_for_defaultdict,
    Counter: lambda _object: ("Counter({", "})", "Counter()"),
    deque: lambda _object: ("deque([", "])", "deque()"),
    dict: lambda _object: ("{", "}", "{}"),
    UserDict: lambda _object: ("{", "}", "{}"),
    frozenset: lambda _object: ("frozenset({", "})", "frozenset()"),
    list: lambda _object: ("[", "]", "[]"),
    UserList: lambda _object: ("[", "]", "[]"),
    set: lambda _object: ("{", "}", "set()"),
    tuple: lambda _object: ("(", ")", "()"),
    MappingProxyType: lambda _object: ("mappingproxy({", "})", "mappingproxy({})"),
}
Definition at line 359 of file pretty.py.
_CONTAINERS
_CONTAINERS = tuple(_BRACES.keys()) protected
Definition at line 374 of file pretty.py.
_dummy_namedtuple
_dummy_namedtuple = collections.namedtuple("_dummy_namedtuple", []) protected
Definition at line 85 of file pretty.py.
_has_attrs
bool _has_attrs = hasattr(_attr_module, "ib") protected
Definition at line 33 of file pretty.py.
_MAPPING_CONTAINERS
tuple _MAPPING_CONTAINERS = (dict, os._Environ, MappingProxyType, UserDict) protected
Definition at line 375 of file pretty.py.
d
d
Definition at line 949 of file pretty.py.
data
dict data
Definition at line 951 of file pretty.py.