Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: _AnnotatedAlias Class Reference
_AnnotatedAlias Class Reference
Public Member Functions
__init__ (self, origin, metadata)
copy_with (self, params)
__repr__ (self)
__reduce__ (self)
__eq__ (self, other)
__hash__ (self)
Detailed Description
Runtime representation of an annotated type.
At its core 'Annotated[t, dec1, dec2, ...]' is an alias for the type 't'
with extra annotations. The alias behaves like a normal typing alias,
instantiating is the same as instantiating the underlying type, binding
it to types is also the same.
Definition at line 1284 of file typing_extensions.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, origin, metadata)
Definition at line 1292 of file typing_extensions.py.
        def __init__(self, origin, metadata):
            if isinstance(origin, _AnnotatedAlias):
                metadata = origin.__metadata__ + metadata
                origin = origin.__origin__
            super().__init__(origin, origin)
            self.__metadata__ = metadata
References __init__(), and __metadata__.
Referenced by __init__().
Member Function Documentation
__eq__()
__eq__ (self, other)
Definition at line 1313 of file typing_extensions.py.
        def __eq__(self, other):
            if not isinstance(other, _AnnotatedAlias):
                return NotImplemented
            if self.__origin__ != other.__origin__:
                return False
            return self.__metadata__ == other.__metadata__
References __metadata__, and __origin__.
Referenced by HTTPHeaderDict.__ne__().
__hash__()
__hash__ (self)
Definition at line 1320 of file typing_extensions.py.
        def __hash__(self):
            return hash((self.__origin__, self.__metadata__))
    class Annotated:
References __metadata__, and __origin__.
__reduce__()
__reduce__ (self)
Definition at line 1308 of file typing_extensions.py.
        def __reduce__(self):
            return operator.getitem, (
                Annotated, (self.__origin__,) + self.__metadata__
            )
References __metadata__, and __origin__.
__repr__()
__repr__ (self)
Definition at line 1304 of file typing_extensions.py.
        def __repr__(self):
            return (f"typing_extensions.Annotated[{typing._type_repr(self.__origin__)}, "
                    f"{', '.join(repr(a) for a in self.__metadata__)}]")
copy_with()
copy_with (self, params)
Definition at line 1299 of file typing_extensions.py.
        def copy_with(self, params):
            assert len(params) == 1
            new_type = params[0]
            return _AnnotatedAlias(new_type, self.__metadata__)
References __metadata__.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/typing_extensions.py