Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: pip._internal.index.sources Namespace Reference
pip._internal.index.sources Namespace Reference
Data Structures
class _FlatDirectorySource
class _IndexDirectorySource
class _LocalFileSource
class _RemoteFileSource
class LinkSource
Functions
bool _is_html_file (str file_url)
Tuple[Optional[str], Optional[LinkSource]] build_source (str location, *, CandidatesFromPage candidates_from_page, PageValidator page_validator, bool expand_dir, bool cache_link_parsing)
Variables
logger = logging.getLogger(__name__)
FoundCandidates = Iterable[InstallationCandidate]
FoundLinks = Iterable[Link]
CandidatesFromPage = Callable[[Link], Iterable[InstallationCandidate]]
PageValidator = Callable[[Link], bool]
Function Documentation
_is_html_file()
bool _is_html_file (str file_url) protected
Definition at line 35 of file sources.py.
def _is_html_file(file_url: str) -> bool:
    return mimetypes.guess_type(file_url, strict=False)[0] == "text/html"
Referenced by _FlatDirectorySource.file_links(), _LocalFileSource.file_links(), _FlatDirectorySource.page_candidates(), and _LocalFileSource.page_candidates().
build_source()
Tuple[Optional[str], Optional[LinkSource]] build_source (str location, * , CandidatesFromPage candidates_from_page, PageValidator page_validator, bool expand_dir, bool cache_link_parsing)
Definition at line 166 of file sources.py.
) -> Tuple[Optional[str], Optional[LinkSource]]:
    path: Optional[str] = None
    url: Optional[str] = None
    if os.path.exists(location):  # Is a local path.
        url = path_to_url(location)
        path = location
    elif location.startswith("file:"):  # A file: URL.
        url = location
        path = url_to_path(location)
    elif is_url(location):
        url = location
    if url is None:
        msg = (
            "Location '%s' is ignored: "
            "it is either a non-existing path or lacks a specific scheme."
        )
        logger.warning(msg, location)
        return (None, None)
    if path is None:
        source: LinkSource = _RemoteFileSource(
            candidates_from_page=candidates_from_page,
            page_validator=page_validator,
            link=Link(url, cache_link_parsing=cache_link_parsing),
        )
        return (url, source)
    if os.path.isdir(path):
        if expand_dir:
            source = _FlatDirectorySource(
                candidates_from_page=candidates_from_page,
                path=path,
            )
        else:
            source = _IndexDirectorySource(
                candidates_from_page=candidates_from_page,
                link=Link(url, cache_link_parsing=cache_link_parsing),
            )
        return (url, source)
    elif os.path.isfile(path):
        source = _LocalFileSource(
            candidates_from_page=candidates_from_page,
            link=Link(url, cache_link_parsing=cache_link_parsing),
        )
        return (url, source)
    logger.warning(
        "Location '%s' is ignored: it is neither a file nor a directory.",
        location,
    )
    return (url, None)
Variable Documentation
CandidatesFromPage
CandidatesFromPage = Callable[[Link], Iterable[InstallationCandidate]]
Definition at line 16 of file sources.py.
FoundCandidates
FoundCandidates = Iterable[InstallationCandidate]
Definition at line 14 of file sources.py.
FoundLinks
FoundLinks = Iterable[Link]
Definition at line 15 of file sources.py.
logger
logger = logging.getLogger(__name__)
Definition at line 12 of file sources.py.
PageValidator
PageValidator = Callable[[Link], bool]
Definition at line 17 of file sources.py.