Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: CacheControlAdapter Class Reference
CacheControlAdapter Class Reference
Public Member Functions
__init__ (self, cache=None, cache_etags=True, controller_class=None, serializer=None, heuristic=None, cacheable_methods=None, *args, **kw)
send (self, request, cacheable_methods=None, **kw)
build_response (self, request, response, from_cache=False, cacheable_methods=None)
close (self)
Public Member Functions inherited from HTTPAdapter
__init__ (self, pool_connections=DEFAULT_POOLSIZE, pool_maxsize=DEFAULT_POOLSIZE, max_retries=DEFAULT_RETRIES, pool_block=DEFAULT_POOLBLOCK)
__getstate__ (self)
__setstate__ (self, state)
init_poolmanager (self, connections, maxsize, block=DEFAULT_POOLBLOCK, **pool_kwargs)
proxy_manager_for (self, proxy, **proxy_kwargs)
cert_verify (self, conn, url, verify, cert)
get_connection (self, url, proxies=None)
request_url (self, request, proxies)
add_headers (self, request, **kwargs)
proxy_headers (self, proxy)
Public Member Functions inherited from BaseAdapter
__init__ (self)
Data Fields
cache = DictCache() if cache is None else cache
heuristic = heuristic
cacheable_methods = cacheable_methods or ("GET",)
controller
int chunk_left = 0:
Data Fields inherited from HTTPAdapter
max_retries = Retry(0, read=False)
dict config = {}
dict proxy_manager = {}
poolmanager
Static Public Attributes
dict invalidating_methods = {"PUT", "PATCH", "DELETE"}
Additional Inherited Members
Protected Attributes inherited from HTTPAdapter
_pool_connections = pool_connections
_pool_maxsize = pool_maxsize
_pool_block = pool_block
Detailed Description
Definition at line 16 of file adapter.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, cache = None, cache_etags = True, controller_class = None, serializer = None, heuristic = None, cacheable_methods = None, * args, ** kw)
Definition at line 19 of file adapter.py.
    ):
        super(CacheControlAdapter, self).__init__(*args, **kw)
        self.cache = DictCache() if cache is None else cache
        self.heuristic = heuristic
        self.cacheable_methods = cacheable_methods or ("GET",)
        controller_factory = controller_class or CacheController
        self.controller = controller_factory(
            self.cache, cache_etags=cache_etags, serializer=serializer
        )
References __init__().
Referenced by __init__().
Member Function Documentation
build_response()
build_response (self, request, response, from_cache = False, cacheable_methods = None)
Build a response by making a request or using the cache.
This will end up calling send and returning a potentially
cached response
Reimplemented from HTTPAdapter.
Definition at line 61 of file adapter.py.
    ):
        """
        Build a response by making a request or using the cache.
        This will end up calling send and returning a potentially
        cached response
        """
        cacheable = cacheable_methods or self.cacheable_methods
        if not from_cache and request.method in cacheable:
            # Check for any heuristics that might update headers
            # before trying to cache.
            if self.heuristic:
                response = self.heuristic.apply(response)
            # apply any expiration heuristics
            if response.status == 304:
                # We must have sent an ETag request. This could mean
                # that we've been expired already or that we simply
                # have an etag. In either case, we want to try and
                # update the cache if that is the case.
                cached_response = self.controller.update_cached_response(
                    request, response
                )
                if cached_response is not response:
                    from_cache = True
                # We are done with the server response, read a
                # possible response body (compliant servers will
                # not return one, but we cannot be 100% sure) and
                # release the connection back to the pool.
                response.read(decode_content=False)
                response.release_conn()
                response = cached_response
            # We always cache the 301 responses
            elif int(response.status) in PERMANENT_REDIRECT_STATUSES:
                self.controller.cache_response(request, response)
            else:
                # Wrap the response file with a wrapper that will cache the
                #   response when the stream has been consumed.
                response._fp = CallbackFileWrapper(
                    response._fp,
                    functools.partial(
                        self.controller.cache_response, request, response
                    ),
                )
                if response.chunked:
                    super_update_chunk_length = response._update_chunk_length
                    def _update_chunk_length(self):
                        super_update_chunk_length()
                        if self.chunk_left == 0:
                            self._fp._close()
                    response._update_chunk_length = types.MethodType(
                        _update_chunk_length, response
                    )
        resp = super(CacheControlAdapter, self).build_response(request, response)
        # See if we should invalidate the cache.
        if request.method in self.invalidating_methods and resp.ok:
            cache_url = self.controller.cache_url(request.url)
            self.cache.delete(cache_url)
        # Give the request a from_cache attr to let people use it
        resp.from_cache = from_cache
        return resp
References cacheable_methods, controller, and heuristic.
Referenced by send().
close()
close (self)
Disposes of any internal state.
Currently, this closes the PoolManager and any active ProxyManager,
which closes any pooled connections.
Reimplemented from HTTPAdapter.
Definition at line 135 of file adapter.py.
    def close(self):
        self.cache.close()
        super(CacheControlAdapter, self).close()
References cache, and close().
Referenced by ZipExtFile.__exit__(), ZipFile.__exit__(), Response.__exit__(), Session.__exit__(), _Reader.__exit__(), ConnectionPool.__exit__(), SSLTransport.__exit__(), WrappedSocket._custom_validate(), WrappedSocket._decref_socketios(), WrappedSocket._drop(), WrappedSocket._raise_on_error(), HTTPResponse._update_chunk_length(), close(), and WrappedSocket.recv_into().
send()
send (self, request, cacheable_methods = None, ** kw)
Send a request. Use the request information to see if it
exists in the cache and cache the response if we need to and can.
Reimplemented from HTTPAdapter.
Definition at line 40 of file adapter.py.
    def send(self, request, cacheable_methods=None, **kw):
        """
        Send a request. Use the request information to see if it
        exists in the cache and cache the response if we need to and can.
        """
        cacheable = cacheable_methods or self.cacheable_methods
        if request.method in cacheable:
            try:
                cached_response = self.controller.cached_request(request)
            except zlib.error:
                cached_response = None
            if cached_response:
                return self.build_response(request, cached_response, from_cache=True)
            # check for etags and add headers if appropriate
            request.headers.update(self.controller.conditional_headers(request))
        resp = super(CacheControlAdapter, self).send(request, **kw)
        return resp
References build_response(), cacheable_methods, controller, and send().
Referenced by Session.request(), HTTPConnection.request_chunked(), send(), WrappedSocket.sendall(), and SSLTransport.sendall().
Field Documentation
cache
cache = DictCache() if cache is None else cache
Definition at line 31 of file adapter.py.
Referenced by CacheController._cache_set(), CacheController.cache_response(), CacheController.cached_request(), close(), CacheController.conditional_headers(), and CacheController.update_cached_response().
cacheable_methods
cacheable_methods = cacheable_methods or ("GET",)
Definition at line 33 of file adapter.py.
Referenced by build_response(), and send().
chunk_left
int chunk_left = 0:
Definition at line 116 of file adapter.py.
Referenced by HTTPResponse._handle_chunk(), HTTPResponse._update_chunk_length(), and HTTPResponse.read_chunked().
controller
controller
Initial value:
=  controller_factory(
            self.cache, cache_etags=cache_etags, serializer=serializer
        )
Definition at line 36 of file adapter.py.
Referenced by build_response(), and send().
heuristic
heuristic = heuristic
Definition at line 32 of file adapter.py.
Referenced by build_response().
invalidating_methods
dict invalidating_methods = {"PUT", "PATCH", "DELETE"} static
Definition at line 17 of file adapter.py.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/cachecontrol/adapter.py