Let us walk on the 3-isogeny graph: BaseResolver Class Reference
BaseResolver Class Reference
Public Member Functions
RequirementSet resolve (self, List[InstallRequirement] root_reqs, bool check_supported_wheels)
List[InstallRequirement] get_installation_order (self, RequirementSet req_set)
Detailed Description
Definition at line 11 of file base.py.
Member Function Documentation
get_installation_order()
List[InstallRequirement] get_installation_order (self, RequirementSet req_set)
Reimplemented in Resolver, and Resolver.
Definition at line 17 of file base.py.
    ) -> List[InstallRequirement]:
        raise NotImplementedError()
References i.
resolve()
RequirementSet resolve (self, List[InstallRequirement] root_reqs, bool check_supported_wheels)
Reimplemented in Resolver, and Resolver.
Definition at line 12 of file base.py.
    ) -> RequirementSet:
        raise NotImplementedError()
References i.
Referenced by BaseConfigurator.configure_custom(), Configurator.configure_custom(), and BaseConfigurator.ext_convert().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/resolution/base.py