Let us walk on the 3-isogeny graph: pip._internal.models.direct_url Namespace Reference
pip._internal.models.direct_url Namespace Reference
Data Structures
class ArchiveInfo
class DirectUrl
class DirectUrlValidationError
class DirInfo
class VcsInfo
Functions
Optional[T] _get (Dict[str, Any] d, Type[T] expected_type, str key, Optional[T] default=None)
T _get_required (Dict[str, Any] d, Type[T] expected_type, str key, Optional[T] default=None)
"InfoType" _exactly_one_of (Iterable[Optional["InfoType"]] infos)
Dict[str, Any] _filter_none (**Any kwargs)
Variables
T = TypeVar("T")
str DIRECT_URL_METADATA_NAME = "direct_url.json"
ENV_VAR_RE = re.compile(r"^\$\{[A-Za-z0-9-_]+\}(:\$\{[A-Za-z0-9-_]+\})?$")
InfoType = Union[ArchiveInfo, DirInfo, VcsInfo]
Detailed Description
 PEP 610
Function Documentation
_exactly_one_of()
"InfoType" _exactly_one_of (Iterable[Optional["InfoType"]] infos) protected
Definition at line 50 of file direct_url.py.
def _exactly_one_of(infos: Iterable[Optional["InfoType"]]) -> "InfoType":
    infos = [info for info in infos if info is not None]
    if not infos:
        raise DirectUrlValidationError(
            "missing one of archive_info, dir_info, vcs_info"
        )
    if len(infos) > 1:
        raise DirectUrlValidationError(
            "more than one of archive_info, dir_info, vcs_info"
        )
    assert infos[0] is not None
    return infos[0]
References i.
Referenced by DirectUrl.from_dict().
_filter_none()
Dict[str, Any] _filter_none (**Any kwargs) protected
Make dict excluding None values.
Definition at line 64 of file direct_url.py.
def _filter_none(**kwargs: Any) -> Dict[str, Any]:
    """Make dict excluding None values."""
    return {k: v for k, v in kwargs.items() if v is not None}
References i.
Referenced by VcsInfo._to_dict(), ArchiveInfo._to_dict(), DirInfo._to_dict(), and DirectUrl.to_dict().
_get()
Optional[T] _get (Dict[str, Any] d, Type[T] expected_type, str key, Optional[T] default = None) protected
Get value from dictionary and verify expected type.
Definition at line 25 of file direct_url.py.
) -> Optional[T]:
    """Get value from dictionary and verify expected type."""
    if key not in d:
        return default
    value = d[key]
    if not isinstance(value, expected_type):
        raise DirectUrlValidationError(
            "{!r} has unexpected type for {} (expected {})".format(
                value, key, expected_type
            )
        )
    return value
Referenced by VcsInfo._from_dict(), ArchiveInfo._from_dict(), pip._internal.models.direct_url._get_required(), and DirectUrl.from_dict().
_get_required()
T _get_required (Dict[str, Any] d, Type[T] expected_type, str key, Optional[T] default = None) protected
Definition at line 41 of file direct_url.py.
) -> T:
    value = _get(d, expected_type, key, default)
    if value is None:
        raise DirectUrlValidationError(f"{key} must have a value")
    return value
References pip._internal.models.direct_url._get().
Referenced by VcsInfo._from_dict(), DirInfo._from_dict(), and DirectUrl.from_dict().
Variable Documentation
DIRECT_URL_METADATA_NAME
str DIRECT_URL_METADATA_NAME = "direct_url.json"
Definition at line 17 of file direct_url.py.
ENV_VAR_RE
ENV_VAR_RE = re.compile(r"^\$\{[A-Za-z0-9-_]+\}(:\$\{[A-Za-z0-9-_]+\})?$")
Definition at line 18 of file direct_url.py.
InfoType
InfoType = Union[ArchiveInfo, DirInfo, VcsInfo]
Definition at line 163 of file direct_url.py.
T
T = TypeVar("T")
Definition at line 15 of file direct_url.py.