Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: LegacyWindowsTerm Class Reference
LegacyWindowsTerm Class Reference
Public Member Functions
None __init__ (self, "IO[str]" file)
WindowsCoordinates cursor_position (self)
WindowsCoordinates screen_size (self)
None write_text (self, str text)
None write_styled (self, str text, Style style)
None move_cursor_to (self, WindowsCoordinates new_position)
None erase_line (self)
None erase_end_of_line (self)
None erase_start_of_line (self)
None move_cursor_up (self)
None move_cursor_down (self)
None move_cursor_forward (self)
None move_cursor_to_column (self, int column)
None move_cursor_backward (self)
None hide_cursor (self)
None show_cursor (self)
None set_title (self, str title)
Data Fields
write = file.write
flush = file.flush
Static Public Attributes
int BRIGHT_BIT = 8
list ANSI_TO_WINDOWS
Protected Member Functions
int _get_cursor_size (self)
Protected Attributes
_handle = handle
_default_text = default_text
int _default_fore = default_text & 7
tuple _default_back = (default_text >> 4) & 7
int _default_attrs = self._default_fore | (self._default_back << 4)
_file = file
Detailed Description
This class allows interaction with the legacy Windows Console API. It should only be used in the context
of environments where virtual terminal processing is not available. However, if it is used in a Windows environment,
the entire API should work.
Args:
    file (IO[str]): The file which the Windows Console API HANDLE is retrieved from, defaults to sys.stdout.
Definition at line 330 of file _win32_console.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, "IO[str]" file)
Definition at line 361 of file _win32_console.py.
    def __init__(self, file: "IO[str]") -> None:
        handle = GetStdHandle(STDOUT)
        self._handle = handle
        default_text = GetConsoleScreenBufferInfo(handle).wAttributes
        self._default_text = default_text
        self._default_fore = default_text & 7
        self._default_back = (default_text >> 4) & 7
        self._default_attrs = self._default_fore | (self._default_back << 4)
        self._file = file
        self.write = file.write
        self.flush = file.flush
References pip._vendor.rich._win32_console.GetStdHandle().
Member Function Documentation
_get_cursor_size()
int _get_cursor_size (self) protected
Get the percentage of the character cell that is filled by the cursor
Definition at line 569 of file _win32_console.py.
    def _get_cursor_size(self) -> int:
        """Get the percentage of the character cell that is filled by the cursor"""
        cursor_info = CONSOLE_CURSOR_INFO()
        GetConsoleCursorInfo(self._handle, cursor_info=cursor_info)
        return int(cursor_info.dwSize)
cursor_position()
WindowsCoordinates cursor_position (self)
Returns the current position of the cursor (0-based)
Returns:
    WindowsCoordinates: The current cursor position.
Definition at line 376 of file _win32_console.py.
    def cursor_position(self) -> WindowsCoordinates:
        """Returns the current position of the cursor (0-based)
        Returns:
            WindowsCoordinates: The current cursor position.
        """
        coord: COORD = GetConsoleScreenBufferInfo(self._handle).dwCursorPosition
        return WindowsCoordinates(row=cast(int, coord.Y), col=cast(int, coord.X))
References _handle, and pip._vendor.rich._win32_console.GetConsoleScreenBufferInfo().
Referenced by erase_end_of_line(), erase_line(), erase_start_of_line(), move_cursor_backward(), move_cursor_down(), move_cursor_forward(), move_cursor_to_column(), and move_cursor_up().
erase_end_of_line()
None erase_end_of_line (self)
Erase all content from the cursor position to the end of that line
Definition at line 471 of file _win32_console.py.
    def erase_end_of_line(self) -> None:
        """Erase all content from the cursor position to the end of that line"""
        cursor_position = self.cursor_position
        cells_to_erase = self.screen_size.col - cursor_position.col
        FillConsoleOutputCharacter(
            self._handle, " ", length=cells_to_erase, start=cursor_position
        )
        FillConsoleOutputAttribute(
            self._handle,
            self._default_attrs,
            length=cells_to_erase,
            start=cursor_position,
        )
References _default_attrs, _handle, cursor_position(), pip._vendor.rich._win32_console.FillConsoleOutputAttribute(), pip._vendor.rich._win32_console.FillConsoleOutputCharacter(), and screen_size().
erase_line()
None erase_line (self)
Erase all content on the line the cursor is currently located at
Definition at line 455 of file _win32_console.py.
    def erase_line(self) -> None:
        """Erase all content on the line the cursor is currently located at"""
        screen_size = self.screen_size
        cursor_position = self.cursor_position
        cells_to_erase = screen_size.col
        start_coordinates = WindowsCoordinates(row=cursor_position.row, col=0)
        FillConsoleOutputCharacter(
            self._handle, " ", length=cells_to_erase, start=start_coordinates
        )
        FillConsoleOutputAttribute(
            self._handle,
            self._default_attrs,
            length=cells_to_erase,
            start=start_coordinates,
        )
References _default_attrs, _handle, cursor_position(), pip._vendor.rich._win32_console.FillConsoleOutputAttribute(), pip._vendor.rich._win32_console.FillConsoleOutputCharacter(), and screen_size().
erase_start_of_line()
None erase_start_of_line (self)
Erase all content from the cursor position to the start of that line
Definition at line 485 of file _win32_console.py.
    def erase_start_of_line(self) -> None:
        """Erase all content from the cursor position to the start of that line"""
        row, col = self.cursor_position
        start = WindowsCoordinates(row, 0)
        FillConsoleOutputCharacter(self._handle, " ", length=col, start=start)
        FillConsoleOutputAttribute(
            self._handle, self._default_attrs, length=col, start=start
        )
References _default_attrs, _handle, cursor_position(), pip._vendor.rich._win32_console.FillConsoleOutputAttribute(), and pip._vendor.rich._win32_console.FillConsoleOutputCharacter().
hide_cursor()
None hide_cursor (self)
Hide the cursor
Definition at line 548 of file _win32_console.py.
    def hide_cursor(self) -> None:
        """Hide the cursor"""
        current_cursor_size = self._get_cursor_size()
        invisible_cursor = CONSOLE_CURSOR_INFO(dwSize=current_cursor_size, bVisible=0)
        SetConsoleCursorInfo(self._handle, cursor_info=invisible_cursor)
move_cursor_backward()
None move_cursor_backward (self)
Move the cursor backward a single cell. Wrap to the previous line if required.
Definition at line 536 of file _win32_console.py.
    def move_cursor_backward(self) -> None:
        """Move the cursor backward a single cell. Wrap to the previous line if required."""
        row, col = self.cursor_position
        if col == 0:
            row -= 1
            col = self.screen_size.col - 1
        else:
            col -= 1
        SetConsoleCursorPosition(
            self._handle, coords=WindowsCoordinates(row=row, col=col)
        )
References _handle, cursor_position(), screen_size(), and pip._vendor.rich._win32_console.SetConsoleCursorPosition().
move_cursor_down()
None move_cursor_down (self)
Move the cursor down a single cell
Definition at line 504 of file _win32_console.py.
    def move_cursor_down(self) -> None:
        """Move the cursor down a single cell"""
        cursor_position = self.cursor_position
        SetConsoleCursorPosition(
            self._handle,
            coords=WindowsCoordinates(
                row=cursor_position.row + 1,
                col=cursor_position.col,
            ),
        )
References _handle, cursor_position(), and pip._vendor.rich._win32_console.SetConsoleCursorPosition().
move_cursor_forward()
None move_cursor_forward (self)
Move the cursor forward a single cell. Wrap to the next line if required.
Definition at line 515 of file _win32_console.py.
    def move_cursor_forward(self) -> None:
        """Move the cursor forward a single cell. Wrap to the next line if required."""
        row, col = self.cursor_position
        if col == self.screen_size.col - 1:
            row += 1
            col = 0
        else:
            col += 1
        SetConsoleCursorPosition(
            self._handle, coords=WindowsCoordinates(row=row, col=col)
        )
References _handle, cursor_position(), screen_size(), and pip._vendor.rich._win32_console.SetConsoleCursorPosition().
move_cursor_to()
None move_cursor_to (self, WindowsCoordinates new_position)
Set the position of the cursor
Args:
    new_position (WindowsCoordinates): The WindowsCoordinates representing the new position of the cursor.
Definition at line 445 of file _win32_console.py.
    def move_cursor_to(self, new_position: WindowsCoordinates) -> None:
        """Set the position of the cursor
        Args:
            new_position (WindowsCoordinates): The WindowsCoordinates representing the new position of the cursor.
        """
        if new_position.col < 0 or new_position.row < 0:
            return
        SetConsoleCursorPosition(self._handle, coords=new_position)
References _handle, and pip._vendor.rich._win32_console.SetConsoleCursorPosition().
move_cursor_to_column()
None move_cursor_to_column (self, int column)
Move cursor to the column specified by the zero-based column index, staying on the same row
Args:
    column (int): The zero-based column index to move the cursor to.
Definition at line 527 of file _win32_console.py.
    def move_cursor_to_column(self, column: int) -> None:
        """Move cursor to the column specified by the zero-based column index, staying on the same row
        Args:
            column (int): The zero-based column index to move the cursor to.
        """
        row, _ = self.cursor_position
        SetConsoleCursorPosition(self._handle, coords=WindowsCoordinates(row, column))
References _handle, cursor_position(), and pip._vendor.rich._win32_console.SetConsoleCursorPosition().
move_cursor_up()
None move_cursor_up (self)
Move the cursor up a single cell
Definition at line 494 of file _win32_console.py.
    def move_cursor_up(self) -> None:
        """Move the cursor up a single cell"""
        cursor_position = self.cursor_position
        SetConsoleCursorPosition(
            self._handle,
            coords=WindowsCoordinates(
                row=cursor_position.row - 1, col=cursor_position.col
            ),
        )
References _handle, cursor_position(), and pip._vendor.rich._win32_console.SetConsoleCursorPosition().
screen_size()
WindowsCoordinates screen_size (self)
Returns the current size of the console screen buffer, in character columns and rows
Returns:
    WindowsCoordinates: The width and height of the screen as WindowsCoordinates.
Definition at line 386 of file _win32_console.py.
    def screen_size(self) -> WindowsCoordinates:
        """Returns the current size of the console screen buffer, in character columns and rows
        Returns:
            WindowsCoordinates: The width and height of the screen as WindowsCoordinates.
        """
        screen_size: COORD = GetConsoleScreenBufferInfo(self._handle).dwSize
        return WindowsCoordinates(
            row=cast(int, screen_size.Y), col=cast(int, screen_size.X)
        )
References _handle, and pip._vendor.rich._win32_console.GetConsoleScreenBufferInfo().
Referenced by erase_end_of_line(), erase_line(), move_cursor_backward(), and move_cursor_forward().
set_title()
None set_title (self, str title)
Set the title of the terminal window
Args:
    title (str): The new title of the console window
Definition at line 560 of file _win32_console.py.
    def set_title(self, title: str) -> None:
        """Set the title of the terminal window
        Args:
            title (str): The new title of the console window
        """
        assert len(title) < 255, "Console title must be less than 255 characters"
        SetConsoleTitle(title)
show_cursor()
None show_cursor (self)
Show the cursor
Definition at line 554 of file _win32_console.py.
    def show_cursor(self) -> None:
        """Show the cursor"""
        current_cursor_size = self._get_cursor_size()
        visible_cursor = CONSOLE_CURSOR_INFO(dwSize=current_cursor_size, bVisible=1)
        SetConsoleCursorInfo(self._handle, cursor_info=visible_cursor)
write_styled()
None write_styled (self, str text, Style style)
Write styled text to the terminal.
Args:
    text (str): The text to write
    style (Style): The style of the text
Definition at line 406 of file _win32_console.py.
    def write_styled(self, text: str, style: Style) -> None:
        """Write styled text to the terminal.
        Args:
            text (str): The text to write
            style (Style): The style of the text
        """
        color = style.color
        bgcolor = style.bgcolor
        if style.reverse:
            color, bgcolor = bgcolor, color
        if color:
            fore = color.downgrade(ColorSystem.WINDOWS).number
            fore = fore if fore is not None else 7  # Default to ANSI 7: White
            if style.bold:
                fore = fore | self.BRIGHT_BIT
            if style.dim:
                fore = fore & ~self.BRIGHT_BIT
            fore = self.ANSI_TO_WINDOWS[fore]
        else:
            fore = self._default_fore
        if bgcolor:
            back = bgcolor.downgrade(ColorSystem.WINDOWS).number
            back = back if back is not None else 0  # Default to ANSI 0: Black
            back = self.ANSI_TO_WINDOWS[back]
        else:
            back = self._default_back
        assert fore is not None
        assert back is not None
        SetConsoleTextAttribute(
            self._handle, attributes=ctypes.c_ushort(fore | (back << 4))
        )
        self.write_text(text)
        SetConsoleTextAttribute(self._handle, attributes=self._default_text)
References WinTerm._default_back, _default_back, WinTerm._default_fore, _default_fore, _default_text, _handle, ANSI_TO_WINDOWS, BRIGHT_BIT, pip._vendor.rich._win32_console.SetConsoleTextAttribute(), and write_text().
write_text()
None write_text (self, str text)
Write text directly to the terminal without any modification of styles
Args:
    text (str): The text to write to the console
Definition at line 397 of file _win32_console.py.
    def write_text(self, text: str) -> None:
        """Write text directly to the terminal without any modification of styles
        Args:
            text (str): The text to write to the console
        """
        self.write(text)
        self.flush()
References flush, and write.
Referenced by write_styled().
Field Documentation
_default_attrs
_default_attrs = self._default_fore | (self._default_back << 4) protected
Definition at line 369 of file _win32_console.py.
Referenced by erase_end_of_line(), erase_line(), and erase_start_of_line().
_default_back
tuple _default_back = (default_text >> 4) & 7 protected
Definition at line 368 of file _win32_console.py.
Referenced by write_styled().
_default_fore
int _default_fore = default_text & 7 protected
Definition at line 367 of file _win32_console.py.
Referenced by write_styled().
_default_text
_default_text = default_text protected
Definition at line 365 of file _win32_console.py.
Referenced by write_styled().
_file
_file = file protected
Definition at line 371 of file _win32_console.py.
Referenced by Console.file(), and Console.file().
_handle
_handle = handle protected
Definition at line 363 of file _win32_console.py.
Referenced by cursor_position(), erase_end_of_line(), erase_line(), erase_start_of_line(), move_cursor_backward(), move_cursor_down(), move_cursor_forward(), move_cursor_to(), move_cursor_to_column(), move_cursor_up(), screen_size(), and write_styled().
ANSI_TO_WINDOWS
list ANSI_TO_WINDOWS static
Initial value:
=  [
        0,  # black                      The Windows colours are defined in wincon.h as follows:
        4,  # red                         define FOREGROUND_BLUE            0x0001 -- 0000 0001
        2,  # green                       define FOREGROUND_GREEN           0x0002 -- 0000 0010
        6,  # yellow                      define FOREGROUND_RED             0x0004 -- 0000 0100
        1,  # blue                        define FOREGROUND_INTENSITY       0x0008 -- 0000 1000
        5,  # magenta                     define BACKGROUND_BLUE            0x0010 -- 0001 0000
        3,  # cyan                        define BACKGROUND_GREEN           0x0020 -- 0010 0000
        7,  # white                       define BACKGROUND_RED             0x0040 -- 0100 0000
        8,  # bright black (grey)         define BACKGROUND_INTENSITY       0x0080 -- 1000 0000
        12,  # bright red
        10,  # bright green
        14,  # bright yellow
        9,  # bright blue
        13,  # bright magenta
        11,  # bright cyan
        15,  # bright white
    ]
Definition at line 342 of file _win32_console.py.
Referenced by write_styled().
BRIGHT_BIT
int BRIGHT_BIT = 8 static
Definition at line 339 of file _win32_console.py.
Referenced by write_styled().
flush
flush = file.flush
Definition at line 373 of file _win32_console.py.
Referenced by UnclosingTextIOWrapper.close(), and write_text().
write
write = file.write
Definition at line 372 of file _win32_console.py.
Referenced by write_text().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/rich/_win32_console.py