Let us walk on the 3-isogeny graph: EventMixin Class Reference
EventMixin Class Reference
Public Member Functions
__init__ (self)
add (self, event, subscriber, append=True)
remove (self, event, subscriber)
get_subscribers (self, event)
publish (self, event, *args, **kwargs)
Protected Attributes
_subscribers
Detailed Description
A very simple publish/subscribe system.
Definition at line 991 of file util.py.
Constructor & Destructor Documentation
__init__()
__init__ (self)
Definition at line 995 of file util.py.
    def __init__(self):
        self._subscribers = {}
Referenced by Protocol.__init_subclass__().
Member Function Documentation
add()
add (self, event, subscriber, append = True)
Add a subscriber for an event.
:param event: The name of an event.
:param subscriber: The subscriber to be added (and called when the
                   event is published).
:param append: Whether to append or prepend the subscriber to an
               existing subscriber list for the event.
Definition at line 998 of file util.py.
    def add(self, event, subscriber, append=True):
        """
        Add a subscriber for an event.
        :param event: The name of an event.
        :param subscriber: The subscriber to be added (and called when the
                           event is published).
        :param append: Whether to append or prepend the subscriber to an
                       existing subscriber list for the event.
        """
        subs = self._subscribers
        if event not in subs:
            subs[event] = deque([subscriber])
        else:
            sq = subs[event]
            if append:
                sq.append(subscriber)
            else:
                sq.appendleft(subscriber)
References EventMixin._subscribers, and i.
Referenced by UninstallPathSet.add(), Manifest.add_many(), HTTPHeaderDict.extend(), and BuildTracker.track().
get_subscribers()
get_subscribers (self, event)
Return an iterator for the subscribers for an event.
:param event: The event to return subscribers for.
Definition at line 1030 of file util.py.
    def get_subscribers(self, event):
        """
        Return an iterator for the subscribers for an event.
        :param event: The event to return subscribers for.
        """
        return iter(self._subscribers.get(event, ()))
References EventMixin._subscribers.
Referenced by EventMixin.publish().
publish()
publish (self, event, * args, ** kwargs)
Publish a event and return a list of values returned by its
subscribers.
:param event: The event to publish.
:param args: The positional arguments to pass to the event's
             subscribers.
:param kwargs: The keyword arguments to pass to the event's
               subscribers.
Definition at line 1037 of file util.py.
    def publish(self, event, *args, **kwargs):
        """
        Publish a event and return a list of values returned by its
        subscribers.
        :param event: The event to publish.
        :param args: The positional arguments to pass to the event's
                     subscribers.
        :param kwargs: The keyword arguments to pass to the event's
                       subscribers.
        """
        result = []
        for subscriber in self.get_subscribers(event):
            try:
                value = subscriber(event, *args, **kwargs)
            except Exception:
                logger.exception('Exception during event publication')
                value = None
            result.append(value)
        logger.debug('publish %s: args = %s, kwargs = %s, result = %s',
                     event, args, kwargs, result)
        return result
#
# Simple sequencing
#
References EventMixin.get_subscribers(), and i.
remove()
remove (self, event, subscriber)
Remove a subscriber for an event.
:param event: The name of an event.
:param subscriber: The subscriber to be removed.
Definition at line 1018 of file util.py.
    def remove(self, event, subscriber):
        """
        Remove a subscriber for an event.
        :param event: The name of an event.
        :param subscriber: The subscriber to be removed.
        """
        subs = self._subscribers
        if event not in subs:
            raise ValueError('No subscribers: %r' % event)
        subs[event].remove(subscriber)
References EventMixin._subscribers, and EventMixin.remove().
Referenced by EventMixin.remove(), Sequencer.remove_node(), and BuildTracker.track().
Field Documentation
_subscribers
_subscribers protected
Definition at line 996 of file util.py.
Referenced by EventMixin.add(), EventMixin.get_subscribers(), and EventMixin.remove().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/distlib/util.py