Let us walk on the 3-isogeny graph: InvalidPyProjectBuildRequires Class Reference
InvalidPyProjectBuildRequires Class Reference
Public Member Functions
None __init__ (self, *str package, str reason)
Public Member Functions inherited from DiagnosticPipError
str __repr__ (self)
RenderResult __rich_console__ (self, Console console, ConsoleOptions options)
Static Public Attributes
str reference = "invalid-pyproject-build-system-requires"
Static Public Attributes inherited from DiagnosticPipError
str reference
Additional Inherited Members
Data Fields inherited from DiagnosticPipError
kind
reference
message
context
note_stmt
hint_stmt
link
Detailed Description
Raised when pyproject.toml an invalid `build-system.requires`.
Definition at line 208 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, *str package, str reason)
Reimplemented from DiagnosticPipError.
Definition at line 213 of file exceptions.py.
    def __init__(self, *, package: str, reason: str) -> None:
        super().__init__(
            message=f"Can not process {escape(package)}",
            context=Text(
                "This package has an invalid `build-system.requires` key in "
                f"pyproject.toml.\n{reason}"
            ),
            note_stmt="This is an issue with the package mentioned above, not pip.",
            hint_stmt=Text("See PEP 518 for the detailed specification."),
        )
References InvalidPyProjectBuildRequires.__init__(), and i.
Referenced by InvalidPyProjectBuildRequires.__init__(), and Protocol.__init_subclass__().
Field Documentation
reference
str reference = "invalid-pyproject-build-system-requires" static
Definition at line 211 of file exceptions.py.
Referenced by DiagnosticPipError.__init__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/exceptions.py