Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Measurement Class Reference
Measurement Class Reference
Public Member Functions
int span (self)
"Measurement" normalize (self)
"Measurement" with_maximum (self, int width)
"Measurement" with_minimum (self, int width)
"Measurement" clamp (self, Optional[int] min_width=None, Optional[int] max_width=None)
"Measurement" get (cls, "Console" console, "ConsoleOptions" options, "RenderableType" renderable)
Detailed Description
Stores the minimum and maximum widths (in characters) required to render an object.
Definition at line 11 of file measure.py.
Member Function Documentation
clamp()
"Measurement" clamp (self, Optional[int] min_width = None, Optional[int] max_width = None)
Clamp a measurement within the specified range.
Args:
    min_width (int): Minimum desired width, or ``None`` for no minimum. Defaults to None.
    max_width (int): Maximum desired width, or ``None`` for no maximum. Defaults to None.
Returns:
    Measurement: New Measurement object.
Definition at line 59 of file measure.py.
    ) -> "Measurement":
        """Clamp a measurement within the specified range.
        Args:
            min_width (int): Minimum desired width, or ``None`` for no minimum. Defaults to None.
            max_width (int): Maximum desired width, or ``None`` for no maximum. Defaults to None.
        Returns:
            Measurement: New Measurement object.
        """
        measurement = self
        if min_width is not None:
            measurement = measurement.with_minimum(min_width)
        if max_width is not None:
            measurement = measurement.with_maximum(max_width)
        return measurement
get()
"Measurement" get (cls, "Console" console, "ConsoleOptions" options, "RenderableType" renderable)
Get a measurement for a renderable.
Args:
    console (~rich.console.Console): Console instance.
    options (~rich.console.ConsoleOptions): Console options.
    renderable (RenderableType): An object that may be rendered with Rich.
Raises:
    errors.NotRenderableError: If the object is not renderable.
Returns:
    Measurement: Measurement object containing range of character widths required to render the object.
Definition at line 79 of file measure.py.
    ) -> "Measurement":
        """Get a measurement for a renderable.
        Args:
            console (~rich.console.Console): Console instance.
            options (~rich.console.ConsoleOptions): Console options.
            renderable (RenderableType): An object that may be rendered with Rich.
        Raises:
            errors.NotRenderableError: If the object is not renderable.
        Returns:
            Measurement: Measurement object containing range of character widths required to render the object.
        """
        _max_width = options.max_width
        if _max_width < 1:
            return Measurement(0, 0)
        if isinstance(renderable, str):
            renderable = console.render_str(
                renderable, markup=options.markup, highlight=False
            )
        renderable = rich_cast(renderable)
        if is_renderable(renderable):
            get_console_width: Optional[
                Callable[["Console", "ConsoleOptions"], "Measurement"]
            ] = getattr(renderable, "__rich_measure__", None)
            if get_console_width is not None:
                render_width = (
                    get_console_width(console, options)
                    .normalize()
                    .with_maximum(_max_width)
                )
                if render_width.maximum < 1:
                    return Measurement(0, 0)
                return render_width.normalize()
            else:
                return Measurement(0, _max_width)
        else:
            raise errors.NotRenderableError(
                f"Unable to get render width for {renderable!r}; "
                "a str, Segment, or object with __rich_console__ method is required"
            )
References normalize(), and with_maximum().
normalize()
"Measurement" normalize (self)
Get measurement that ensures that minimum <= maximum and minimum >= 0
Returns:
    Measurement: A normalized measurement.
Definition at line 24 of file measure.py.
    def normalize(self) -> "Measurement":
        """Get measurement that ensures that minimum <= maximum and minimum >= 0
        Returns:
            Measurement: A normalized measurement.
        """
        minimum, maximum = self
        minimum = min(max(0, minimum), maximum)
        return Measurement(max(0, minimum), max(0, max(minimum, maximum)))
Referenced by get().
span()
int span (self)
Get difference between maximum and minimum.
Definition at line 20 of file measure.py.
    def span(self) -> int:
        """Get difference between maximum and minimum."""
        return self.maximum - self.minimum
References Progress.maximum().
with_maximum()
"Measurement" with_maximum (self, int width)
Get a RenderableWith where the widths are <= width.
Args:
    width (int): Maximum desired width.
Returns:
    Measurement: New Measurement object.
Definition at line 34 of file measure.py.
    def with_maximum(self, width: int) -> "Measurement":
        """Get a RenderableWith where the widths are <= width.
        Args:
            width (int): Maximum desired width.
        Returns:
            Measurement: New Measurement object.
        """
        minimum, maximum = self
        return Measurement(min(minimum, width), min(maximum, width))
Referenced by get().
with_minimum()
"Measurement" with_minimum (self, int width)
Get a RenderableWith where the widths are >= width.
Args:
    width (int): Minimum desired width.
Returns:
    Measurement: New Measurement object.
Definition at line 46 of file measure.py.
    def with_minimum(self, width: int) -> "Measurement":
        """Get a RenderableWith where the widths are >= width.
        Args:
            width (int): Minimum desired width.
        Returns:
            Measurement: New Measurement object.
        """
        minimum, maximum = self
        width = max(0, width)
        return Measurement(max(minimum, width), max(maximum, width))
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/rich/measure.py