Let us walk on the 3-isogeny graph: pip._vendor.distlib.wheel Namespace Reference
pip._vendor.distlib.wheel Namespace Reference
Data Structures
class Mounter
class Wheel
Functions
_derive_abi ()
_get_suffixes ()
_load_dynamic (name, path)
_get_glibc_version ()
compatible_tags ()
is_compatible (wheel, tags=None)
Variables
logger = logging.getLogger(__name__)
cache = None
str IMP_PREFIX = 'pp'
VER_SUFFIX = sysconfig.get_config_var('py_version_nodot')
str PYVER = 'py' + VER_SUFFIX
str IMPVER = IMP_PREFIX + VER_SUFFIX
ARCH = get_platform().replace('-', '_').replace('.', '_')
ABI = sysconfig.get_config_var('SOABI')
FILENAME_RE = re.compile(, re.IGNORECASE | re.VERBOSE)
NAME_VERSION_RE = re.compile(, re.IGNORECASE | re.VERBOSE)
SHEBANG_RE = re.compile(br'\s*#![^\r\n]*')
SHEBANG_DETAIL_RE = re.compile(br'^(\s*#!("[^"]+"|\S+))\s+(.*)$')
str SHEBANG_PYTHON = b'#!python'
str SHEBANG_PYTHONW = b'#!pythonw'
o to_posix = lambda o
imp = None
_hook = Mounter()
COMPATIBLE_TAGS = compatible_tags()
Function Documentation
_derive_abi()
_derive_abi () protected
Definition at line 59 of file wheel.py.
    def _derive_abi():
        parts = ['cp', VER_SUFFIX]
        if sysconfig.get_config_var('Py_DEBUG'):
            parts.append('d')
        if IMP_PREFIX == 'cp':
            vi = sys.version_info[:2]
            if vi < (3, 8):
                wpm = sysconfig.get_config_var('WITH_PYMALLOC')
                if wpm is None:
                    wpm = True
                if wpm:
                    parts.append('m')
                if vi < (3, 3):
                    us = sysconfig.get_config_var('Py_UNICODE_SIZE')
                    if us == 4 or (us is None and sys.maxunicode == 0x10FFFF):
                        parts.append('u')
        return ''.join(parts)
References pip._vendor.distlib.wheel._derive_abi(), and i.
Referenced by pip._vendor.distlib.wheel._derive_abi().
_get_glibc_version()
_get_glibc_version () protected
Definition at line 977 of file wheel.py.
def _get_glibc_version():
    import platform
    ver = platform.libc_ver()
    result = []
    if ver[0] == 'glibc':
        for s in ver[1].split('.'):
            result.append(int(s) if s.isdigit() else 0)
        result = tuple(result)
    return result
References i.
Referenced by pip._vendor.distlib.wheel.compatible_tags().
_get_suffixes()
_get_suffixes () protected
Definition at line 112 of file wheel.py.
def _get_suffixes():
    if imp:
        return [s[0] for s in imp.get_suffixes()]
    else:
        return importlib.machinery.EXTENSION_SUFFIXES
References i.
Referenced by pip._vendor.distlib.wheel.compatible_tags().
_load_dynamic()
_load_dynamic (name, path) protected
Definition at line 118 of file wheel.py.
def _load_dynamic(name, path):
    # https://docs.python.org/3/library/importlib.html#importing-a-source-file-directly
    if imp:
        return imp.load_dynamic(name, path)
    else:
        spec = importlib.util.spec_from_file_location(name, path)
        module = importlib.util.module_from_spec(spec)
        sys.modules[name] = module
        spec.loader.exec_module(module)
        return module
References i.
Referenced by Mounter.load_module().
compatible_tags()
compatible_tags ()
Return (pyver, abi, arch) tuples compatible with this Python.
Definition at line 987 of file wheel.py.
def compatible_tags():
    """
    Return (pyver, abi, arch) tuples compatible with this Python.
    """
    versions = [VER_SUFFIX]
    major = VER_SUFFIX[0]
    for minor in range(sys.version_info[1] - 1, - 1, -1):
        versions.append(''.join([major, str(minor)]))
    abis = []
    for suffix in _get_suffixes():
        if suffix.startswith('.abi'):
            abis.append(suffix.split('.', 2)[1])
    abis.sort()
    if ABI != 'none':
        abis.insert(0, ABI)
    abis.append('none')
    result = []
    arches = [ARCH]
    if sys.platform == 'darwin':
        m = re.match(r'(\w+)_(\d+)_(\d+)_(\w+)$', ARCH)
        if m:
            name, major, minor, arch = m.groups()
            minor = int(minor)
            matches = [arch]
            if arch in ('i386', 'ppc'):
                matches.append('fat')
            if arch in ('i386', 'ppc', 'x86_64'):
                matches.append('fat3')
            if arch in ('ppc64', 'x86_64'):
                matches.append('fat64')
            if arch in ('i386', 'x86_64'):
                matches.append('intel')
            if arch in ('i386', 'x86_64', 'intel', 'ppc', 'ppc64'):
                matches.append('universal')
            while minor >= 0:
                for match in matches:
                    s = '%s_%s_%s_%s' % (name, major, minor, match)
                    if s != ARCH:   # already there
                        arches.append(s)
                minor -= 1
    # Most specific - our Python version, ABI and arch
    for abi in abis:
        for arch in arches:
            result.append((''.join((IMP_PREFIX, versions[0])), abi, arch))
            # manylinux
            if abi != 'none' and sys.platform.startswith('linux'):
                arch = arch.replace('linux_', '')
                parts = _get_glibc_version()
                if len(parts) == 2:
                    if parts >= (2, 5):
                        result.append((''.join((IMP_PREFIX, versions[0])), abi,
                                       'manylinux1_%s' % arch))
                    if parts >= (2, 12):
                        result.append((''.join((IMP_PREFIX, versions[0])), abi,
                                       'manylinux2010_%s' % arch))
                    if parts >= (2, 17):
                        result.append((''.join((IMP_PREFIX, versions[0])), abi,
                                       'manylinux2014_%s' % arch))
                    result.append((''.join((IMP_PREFIX, versions[0])), abi,
                                   'manylinux_%s_%s_%s' % (parts[0], parts[1],
                                                           arch)))
    # where no ABI / arch dependency, but IMP_PREFIX dependency
    for i, version in enumerate(versions):
        result.append((''.join((IMP_PREFIX, version)), 'none', 'any'))
        if i == 0:
            result.append((''.join((IMP_PREFIX, version[0])), 'none', 'any'))
    # no IMP_PREFIX, ABI or arch dependency
    for i, version in enumerate(versions):
        result.append((''.join(('py', version)), 'none', 'any'))
        if i == 0:
            result.append((''.join(('py', version[0])), 'none', 'any'))
    return set(result)
References pip._vendor.distlib.wheel._get_glibc_version(), pip._vendor.distlib.wheel._get_suffixes(), and i.
is_compatible()
is_compatible (wheel, tags = None)
Definition at line 1072 of file wheel.py.
def is_compatible(wheel, tags=None):
    if not isinstance(wheel, Wheel):
        wheel = Wheel(wheel)    # assume it's a filename
    result = False
    if tags is None:
        tags = COMPATIBLE_TAGS
    for ver, abi, arch in tags:
        if ver in wheel.pyver and abi in wheel.abi and arch in wheel.arch:
            result = True
            break
    return result
References i.
Variable Documentation
_hook
_hook = Mounter() protected
Definition at line 164 of file wheel.py.
ABI
ABI = sysconfig.get_config_var('SOABI')
Definition at line 55 of file wheel.py.
ARCH
ARCH = get_platform().replace('-', '_').replace('.', '_')
Definition at line 53 of file wheel.py.
cache
cache = None
Definition at line 36 of file wheel.py.
COMPATIBLE_TAGS
COMPATIBLE_TAGS = compatible_tags()
Definition at line 1067 of file wheel.py.
FILENAME_RE
FILENAME_RE = re.compile(, re.IGNORECASE | re.VERBOSE)
Definition at line 79 of file wheel.py.
imp
imp = None
Definition at line 108 of file wheel.py.
IMP_PREFIX
str IMP_PREFIX = 'pp'
Definition at line 39 of file wheel.py.
IMPVER
str IMPVER = IMP_PREFIX + VER_SUFFIX
Definition at line 51 of file wheel.py.
logger
logger = logging.getLogger(__name__)
Definition at line 34 of file wheel.py.
NAME_VERSION_RE
NAME_VERSION_RE = re.compile(, re.IGNORECASE | re.VERBOSE)
Definition at line 89 of file wheel.py.
PYVER
str PYVER = 'py' + VER_SUFFIX
Definition at line 50 of file wheel.py.
SHEBANG_DETAIL_RE
SHEBANG_DETAIL_RE = re.compile(br'^(\s*#!("[^"]+"|\S+))\s+(.*)$')
Definition at line 96 of file wheel.py.
SHEBANG_PYTHON
str SHEBANG_PYTHON = b'#!python'
Definition at line 97 of file wheel.py.
SHEBANG_PYTHONW
str SHEBANG_PYTHONW = b'#!pythonw'
Definition at line 98 of file wheel.py.
SHEBANG_RE
SHEBANG_RE = re.compile(br'\s*#![^\r\n]*')
Definition at line 95 of file wheel.py.
to_posix
o to_posix = lambda o
Definition at line 101 of file wheel.py.
Referenced by Wheel.build(), and Wheel.write_records().
VER_SUFFIX
str VER_SUFFIX = sysconfig.get_config_var('py_version_nodot')
Definition at line 47 of file wheel.py.