Let us walk on the 3-isogeny graph: SJISContextAnalysis Class Reference
SJISContextAnalysis Class Reference
Public Member Functions
None __init__ (self)
str charset_name (self)
Tuple[int, int] get_order (self, Union[bytes, bytearray] byte_str)
Public Member Functions inherited from JapaneseContextAnalysis
None reset (self)
None feed (self, Union[bytes, bytearray] byte_str, int num_bytes)
bool got_enough_data (self)
float get_confidence (self)
Protected Attributes
_charset_name
Protected Attributes inherited from JapaneseContextAnalysis
_total_rel
_need_to_skip_char_num
_last_char_order
_done
_rel_sample
Additional Inherited Members
Static Public Attributes inherited from JapaneseContextAnalysis
int NUM_OF_CATEGORY = 6
int DONT_KNOW = -1
int ENOUGH_REL_THRESHOLD = 100
int MAX_REL_THRESHOLD = 1000
int MINIMUM_DATA_THRESHOLD = 4
Detailed Description
Definition at line 189 of file jpcntx.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Reimplemented from JapaneseContextAnalysis.
Definition at line 190 of file jpcntx.py.
    def __init__(self) -> None:
        super().__init__()
        self._charset_name = "SHIFT_JIS"
References SJISContextAnalysis.__init__(), and i.
Referenced by SJISContextAnalysis.__init__(), and Protocol.__init_subclass__().
Member Function Documentation
charset_name()
str charset_name (self)
Definition at line 195 of file jpcntx.py.
    def charset_name(self) -> str:
        return self._charset_name
References SJISContextAnalysis._charset_name.
get_order()
Tuple[int, int] get_order (self, Union[bytes, bytearray] byte_str)
Reimplemented from JapaneseContextAnalysis.
Definition at line 198 of file jpcntx.py.
    def get_order(self, byte_str: Union[bytes, bytearray]) -> Tuple[int, int]:
        if not byte_str:
            return -1, 1
        # find out current char's byte length
        first_char = byte_str[0]
        if (0x81 <= first_char <= 0x9F) or (0xE0 <= first_char <= 0xFC):
            char_len = 2
            if (first_char == 0x87) or (0xFA <= first_char <= 0xFC):
                self._charset_name = "CP932"
        else:
            char_len = 1
        # return its order if it is hiragana
        if len(byte_str) > 1:
            second_char = byte_str[1]
            if (first_char == 202) and (0x9F <= second_char <= 0xF1):
                return second_char - 0x9F, char_len
        return -1, char_len
References SJISContextAnalysis._charset_name, and i.
Referenced by JapaneseContextAnalysis.feed(), and CharDistributionAnalysis.feed().
Field Documentation
_charset_name
_charset_name protected
Definition at line 192 of file jpcntx.py.
Referenced by SJISContextAnalysis.charset_name(), and SJISContextAnalysis.get_order().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/chardet/jpcntx.py