Let us walk on the 3-isogeny graph: _AnyMeta Class Reference
_AnyMeta Class Reference
Public Member Functions
__instancecheck__ (self, obj)
__repr__ (self)
Detailed Description
Definition at line 217 of file typing_extensions.py.
Member Function Documentation
__instancecheck__()
__instancecheck__ (self, obj)
Definition at line 218 of file typing_extensions.py.
        def __instancecheck__(self, obj):
            if self is Any:
                raise TypeError("typing_extensions.Any cannot be used with isinstance()")
            return super().__instancecheck__(obj)
References _AnyMeta.__instancecheck__(), and i.
Referenced by _AnyMeta.__instancecheck__().
__repr__()
__repr__ (self)
Definition at line 223 of file typing_extensions.py.
        def __repr__(self):
            if self is Any:
                return "typing_extensions.Any"
            return super().__repr__()
    class Any(metaclass=_AnyMeta):
References _AnyMeta.__repr__(), and i.
Referenced by _AnyMeta.__repr__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/typing_extensions.py