Let us walk on the 3-isogeny graph: pip._vendor.packaging.markers Namespace Reference
pip._vendor.packaging.markers Namespace Reference
Data Structures
class InvalidMarker
class Marker
class Node
class Op
class Undefined
class UndefinedComparison
class UndefinedEnvironmentName
class Value
class Variable
Functions
List[Any] _coerce_parse_result (Union[ParseResults, List[Any]] results)
str _format_marker (Union[List[str], Tuple[Node,...], str] marker, Optional[bool] first=True)
bool _eval_op (str lhs, Op op, str rhs)
str _get_env (Dict[str, str] environment, str name)
bool _evaluate_markers (List[Any] markers, Dict[str, str] environment)
str format_full_version ("sys._version_info" info)
Dict[str, str] default_environment ()
Variables
Operator = Callable[[str, str], bool]
tuple VARIABLE
dict ALIASES
tuple VERSION_CMP
tuple MARKER_OP = VERSION_CMP | L("not in") | L("in")
MARKER_VALUE = QuotedString("'") | QuotedString('"')
BOOLOP = L("and") | L("or")
tuple MARKER_VAR = VARIABLE | MARKER_VALUE
MARKER_ITEM = Group(MARKER_VAR + MARKER_OP + MARKER_VAR)
LPAREN = L("(").suppress()
RPAREN = L(")").suppress()
MARKER_EXPR = Forward()
MARKER_ATOM = MARKER_ITEM | Group(LPAREN + MARKER_EXPR + RPAREN)
MARKER = stringStart + MARKER_EXPR + stringEnd
dict _operators
_undefined = Undefined()
Function Documentation
_coerce_parse_result()
List[Any] _coerce_parse_result (Union[ParseResults, List[Any]] results) protected
Definition at line 141 of file markers.py.
def _coerce_parse_result(results: Union[ParseResults, List[Any]]) -> List[Any]:
    if isinstance(results, ParseResults):
        return [_coerce_parse_result(i) for i in results]
    else:
        return results
References pip._vendor.packaging.markers._coerce_parse_result(), and i.
Referenced by pip._vendor.packaging.markers._coerce_parse_result().
_eval_op()
bool _eval_op (str lhs, Op op, str rhs) protected
Definition at line 189 of file markers.py.
def _eval_op(lhs: str, op: Op, rhs: str) -> bool:
    try:
        spec = Specifier("".join([op.serialize(), rhs]))
    except InvalidSpecifier:
        pass
    else:
        return spec.contains(lhs)
    oper: Optional[Operator] = _operators.get(op.serialize())
    if oper is None:
        raise UndefinedComparison(f"Undefined {op!r} on {lhs!r} and {rhs!r}.")
    return oper(lhs, rhs)
References i.
Referenced by pip._vendor.packaging.markers._evaluate_markers().
_evaluate_markers()
bool _evaluate_markers (List[Any] markers, Dict[str, str] environment) protected
Definition at line 222 of file markers.py.
def _evaluate_markers(markers: List[Any], environment: Dict[str, str]) -> bool:
    groups: List[List[bool]] = [[]]
    for marker in markers:
        assert isinstance(marker, (list, tuple, str))
        if isinstance(marker, list):
            groups[-1].append(_evaluate_markers(marker, environment))
        elif isinstance(marker, tuple):
            lhs, op, rhs = marker
            if isinstance(lhs, Variable):
                lhs_value = _get_env(environment, lhs.value)
                rhs_value = rhs.value
            else:
                lhs_value = lhs.value
                rhs_value = _get_env(environment, rhs.value)
            groups[-1].append(_eval_op(lhs_value, op, rhs_value))
        else:
            assert marker in ["and", "or"]
            if marker == "or":
                groups.append([])
    return any(all(item) for item in groups)
References pip._vendor.packaging.markers._eval_op(), pip._vendor.packaging.markers._evaluate_markers(), pip._vendor.packaging.markers._get_env(), and i.
Referenced by pip._vendor.packaging.markers._evaluate_markers(), and Marker.evaluate().
_format_marker()
str _format_marker (Union[List[str], Tuple[Node, ...], str] marker, Optional[bool] first = True) protected
Definition at line 148 of file markers.py.
) -> str:
    assert isinstance(marker, (list, tuple, str))
    # Sometimes we have a structure like [[...]] which is a single item list
    # where the single item is itself it's own list. In that case we want skip
    # the rest of this function so that we don't get extraneous () on the
    # outside.
    if (
        isinstance(marker, list)
        and len(marker) == 1
        and isinstance(marker[0], (list, tuple))
    ):
        return _format_marker(marker[0])
    if isinstance(marker, list):
        inner = (_format_marker(m, first=False) for m in marker)
        if first:
            return " ".join(inner)
        else:
            return "(" + " ".join(inner) + ")"
    elif isinstance(marker, tuple):
        return " ".join([m.serialize() for m in marker])
    else:
        return marker
References pip._vendor.packaging.markers._format_marker(), and i.
Referenced by Marker.__str__(), and pip._vendor.packaging.markers._format_marker().
_get_env()
str _get_env (Dict[str, str] environment, str name) protected
Definition at line 211 of file markers.py.
def _get_env(environment: Dict[str, str], name: str) -> str:
    value: Union[str, Undefined] = environment.get(name, _undefined)
    if isinstance(value, Undefined):
        raise UndefinedEnvironmentName(
            f"{name!r} does not exist in evaluation environment."
        )
    return value
References i.
Referenced by pip._vendor.packaging.markers._evaluate_markers().
default_environment()
Dict[str, str] default_environment ()
Definition at line 257 of file markers.py.
def default_environment() -> Dict[str, str]:
    iver = format_full_version(sys.implementation.version)
    implementation_name = sys.implementation.name
    return {
        "implementation_name": implementation_name,
        "implementation_version": iver,
        "os_name": os.name,
        "platform_machine": platform.machine(),
        "platform_release": platform.release(),
        "platform_system": platform.system(),
        "platform_version": platform.version(),
        "python_full_version": platform.python_version(),
        "platform_python_implementation": platform.python_implementation(),
        "python_version": ".".join(platform.python_version_tuple()[:2]),
        "sys_platform": sys.platform,
    }
References pip._vendor.packaging.markers.format_full_version(), and i.
Referenced by Marker.evaluate().
format_full_version()
str format_full_version ("sys._version_info" info)
Definition at line 249 of file markers.py.
def format_full_version(info: "sys._version_info") -> str:
    version = "{0.major}.{0.minor}.{0.micro}".format(info)
    kind = info.releaselevel
    if kind != "final":
        version += kind[0] + str(info.serial)
    return version
References i.
Referenced by pip._vendor.packaging.markers.default_environment().
Variable Documentation
_operators
dict _operators protected
Initial value:
=  {
    "in": lambda lhs, rhs: lhs in rhs,
    "not in": lambda lhs, rhs: lhs not in rhs,
    "<": operator.lt,
    "<=": operator.le,
    "==": operator.eq,
    "!=": operator.ne,
    ">=": operator.ge,
    ">": operator.gt,
}
Definition at line 177 of file markers.py.
_undefined
_undefined = Undefined() protected
Definition at line 208 of file markers.py.
ALIASES
dict ALIASES
Initial value:
=  {
    "os.name": "os_name",
    "sys.platform": "sys_platform",
    "platform.version": "platform_version",
    "platform.machine": "platform_machine",
    "platform.python_implementation": "platform_python_implementation",
    "python_implementation": "platform_python_implementation",
}
Definition at line 104 of file markers.py.
BOOLOP
BOOLOP = L("and") | L("or")
Definition at line 124 of file markers.py.
LPAREN
LPAREN = L("(").suppress()
Definition at line 131 of file markers.py.
MARKER
MARKER = stringStart + MARKER_EXPR + stringEnd
Definition at line 138 of file markers.py.
MARKER_ATOM
MARKER_ATOM = MARKER_ITEM | Group(LPAREN + MARKER_EXPR + RPAREN)
Definition at line 135 of file markers.py.
MARKER_EXPR
MARKER_EXPR = Forward()
Definition at line 134 of file markers.py.
MARKER_ITEM
MARKER_ITEM = Group(MARKER_VAR + MARKER_OP + MARKER_VAR)
Definition at line 128 of file markers.py.
MARKER_OP
tuple MARKER_OP = VERSION_CMP | L("not in") | L("in")
Definition at line 118 of file markers.py.
MARKER_VALUE
MARKER_VALUE = QuotedString("'") | QuotedString('"')
Definition at line 121 of file markers.py.
MARKER_VAR
tuple MARKER_VAR = VARIABLE | MARKER_VALUE
Definition at line 126 of file markers.py.
Operator
Operator = Callable[[str, str], bool]
Definition at line 33 of file markers.py.
RPAREN
RPAREN = L(")").suppress()
Definition at line 132 of file markers.py.
VARIABLE
tuple VARIABLE
Initial value:
=  (
    L("implementation_version")
    | L("platform_python_implementation")
    | L("implementation_name")
    | L("python_full_version")
    | L("platform_release")
    | L("platform_version")
    | L("platform_machine")
    | L("platform_system")
    | L("python_version")
    | L("sys_platform")
    | L("os_name")
    | L("os.name")  # PEP-345
    | L("sys.platform")  # PEP-345
    | L("platform.version")  # PEP-345
    | L("platform.machine")  # PEP-345
    | L("platform.python_implementation")  # PEP-345
    | L("python_implementation")  # undocumented setuptools legacy
    | L("extra")  # PEP-508
)
Definition at line 84 of file markers.py.
VERSION_CMP
tuple VERSION_CMP
Initial value:
=  (
    L("===") | L("==") | L(">=") | L("<=") | L("!=") | L("~=") | L(">") | L("<")
)
Definition at line 114 of file markers.py.