Let us walk on the 3-isogeny graph: MissingCallableSuffix Class Reference
MissingCallableSuffix Class Reference
Public Member Functions
None __init__ (self, str entry_point)
Detailed Description
Definition at line 408 of file wheel.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, str entry_point)
Definition at line 409 of file wheel.py.
    def __init__(self, entry_point: str) -> None:
        super().__init__(
            "Invalid script entry point: {} - A callable "
            "suffix is required. Cf https://packaging.python.org/"
            "specifications/entry-points/#use-for-scripts for more "
            "information.".format(entry_point)
        )
References MissingCallableSuffix.__init__(), and i.
Referenced by MissingCallableSuffix.__init__(), and Protocol.__init_subclass__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/operations/install/wheel.py