Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: CacheablePageContent Class Reference
CacheablePageContent Class Reference
Public Member Functions
None __init__ (self, "IndexContent" page)
bool __eq__ (self, object other)
int __hash__ (self)
Data Fields
page = page
Detailed Description
Definition at line 191 of file collector.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, "IndexContent" page)
Definition at line 192 of file collector.py.
    def __init__(self, page: "IndexContent") -> None:
        assert page.cache_link_parsing
        self.page = page
Member Function Documentation
__eq__()
bool __eq__ (self, object other)
Definition at line 196 of file collector.py.
    def __eq__(self, other: object) -> bool:
        return isinstance(other, type(self)) and self.page.url == other.page.url
References page.
Referenced by Version.__ge__(), Version.__gt__(), Version.__le__(), Matcher.__ne__(), Version.__ne__(), Timestamp.__ne__(), and HTTPHeaderDict.__ne__().
__hash__()
int __hash__ (self)
Definition at line 199 of file collector.py.
    def __hash__(self) -> int:
        return hash(self.page.url)
References page.
Referenced by Style.__eq__(), and Style.__ne__().
Field Documentation
page
page = page
Definition at line 194 of file collector.py.
Referenced by __eq__(), and __hash__().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/index/collector.py