Let us walk on the 3-isogeny graph: TempDirectory Class Reference
TempDirectory Class Reference
Public Member Functions
__init__ (self, Optional[str] path=None, Union[bool, None, _Default] delete=_default, str kind="temp", bool globally_managed=False)
str path (self)
str __repr__ (self)
_T __enter__ (_T self)
None __exit__ (self, Any exc, Any value, Any tb)
None cleanup (self)
Data Fields
delete
kind
Protected Member Functions
str _create (self, str kind)
Protected Attributes
_path
_deleted
Detailed Description
Helper class that owns and cleans up a temporary directory.
This class can be used as a context manager or as an OO representation of a
temporary directory.
Attributes:
    path
        Location to the created temporary directory
    delete
        Whether the directory should be deleted when exiting
        (when used as a contextmanager)
Methods:
    cleanup()
        Deletes the temporary directory
When used as a context manager, if the delete attribute is True, on
exiting the context the temporary directory is deleted.
Definition at line 82 of file temp_dir.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, Optional[str] path = None, Union[bool, None, _Default] delete = _default, str kind = "temp", bool globally_managed = False)
Reimplemented in AdjacentTempDirectory.
Definition at line 103 of file temp_dir.py.
    ):
        super().__init__()
        if delete is _default:
            if path is not None:
                # If we were given an explicit directory, resolve delete option
                # now.
                delete = False
            else:
                # Otherwise, we wait until cleanup and see what
                # tempdir_registry says.
                delete = None
        # The only time we specify path is in for editables where it
        # is the value of the --src option.
        if path is None:
            path = self._create(kind)
        self._path = path
        self._deleted = False
        self.delete = delete
        self.kind = kind
        if globally_managed:
            assert _tempdir_manager is not None
            _tempdir_manager.enter_context(self)
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__enter__()
_T __enter__ (_T self)
Definition at line 144 of file temp_dir.py.
    def __enter__(self: _T) -> _T:
        return self
__exit__()
None __exit__ (self, Any exc, Any value, Any tb)
Definition at line 147 of file temp_dir.py.
    def __exit__(self, exc: Any, value: Any, tb: Any) -> None:
        if self.delete is not None:
            delete = self.delete
        elif _tempdir_registry:
            delete = _tempdir_registry.get_delete(self.kind)
        else:
            delete = True
        if delete:
            self.cleanup()
__repr__()
str __repr__ (self)
Definition at line 141 of file temp_dir.py.
    def __repr__(self) -> str:
        return f"<{self.__class__.__name__} {self.path!r}>"
_create()
str _create (self, str kind) protected
Create a temporary directory and store its path in self.path
Reimplemented in AdjacentTempDirectory.
Definition at line 158 of file temp_dir.py.
    def _create(self, kind: str) -> str:
        """Create a temporary directory and store its path in self.path"""
        # We realpath here because some systems have their default tmpdir
        # symlinked to another directory.  This tends to confuse build
        # scripts, so we canonicalize the path by traversing potential
        # symlinks here.
        path = os.path.realpath(tempfile.mkdtemp(prefix=f"pip-{kind}-"))
        logger.debug("Created temporary directory: %s", path)
        return path
cleanup()
None cleanup (self)
Remove the temporary directory created and reset state
Definition at line 168 of file temp_dir.py.
    def cleanup(self) -> None:
        """Remove the temporary directory created and reset state"""
        self._deleted = True
        if not os.path.exists(self._path):
            return
        rmtree(self._path)
Referenced by BuildTracker.__exit__().
path()
str path (self)
Definition at line 137 of file temp_dir.py.
    def path(self) -> str:
        assert not self._deleted, f"Attempted to access deleted path: {self._path}"
        return self._path
Referenced by InstalledDistribution.__eq__(), EggInfoDistribution.__eq__(), DistributionPath._yield_distributions(), _Cache.add(), InstalledDistribution.check_installed_files(), EggInfoDistribution.check_installed_files(), _Cache.clear(), Link.filename(), InstalledDistribution.get_distinfo_file(), InstalledDistribution.get_distinfo_resource(), InstalledDistribution.list_distinfo_files(), EggInfoDistribution.list_distinfo_files(), EggInfoDistribution.list_installed_files(), Url.request_uri(), InstalledDistribution.shared_locations(), Link.splitext(), InstalledDistribution.write_installed_files(), and InstalledDistribution.write_shared_locations().
Field Documentation
_deleted
_deleted protected
Definition at line 128 of file temp_dir.py.
_path
_path protected
Definition at line 127 of file temp_dir.py.
Referenced by _FlatDirectorySource.file_links(), and _FlatDirectorySource.page_candidates().
delete
delete
Definition at line 129 of file temp_dir.py.
kind
kind
Definition at line 130 of file temp_dir.py.
Referenced by DiagnosticPipError.__rich_console__().
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/utils/temp_dir.py