Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: Resolver Class Reference
Resolver Class Reference
Public Member Functions
__init__ (self, RequirementPreparer preparer, PackageFinder finder, Optional[WheelCache] wheel_cache, InstallRequirementProvider make_install_req, bool use_user_site, bool ignore_dependencies, bool ignore_installed, bool ignore_requires_python, bool force_reinstall, str upgrade_strategy, Optional[Tuple[int,...]] py_version_info=None)
RequirementSet resolve (self, List[InstallRequirement] root_reqs, bool check_supported_wheels)
List[InstallRequirement] get_installation_order (self, RequirementSet req_set)
Data Fields
factory
ignore_dependencies = ignore_dependencies
upgrade_strategy = upgrade_strategy
Protected Attributes
Optional[Result] _result = None
Static Protected Attributes
dict _allowed_strategies = {"eager", "only-if-needed", "to-satisfy-only"}
Detailed Description
Definition at line 35 of file resolver.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, RequirementPreparer preparer, PackageFinder finder, Optional[WheelCache] wheel_cache, InstallRequirementProvider make_install_req, bool use_user_site, bool ignore_dependencies, bool ignore_installed, bool ignore_requires_python, bool force_reinstall, str upgrade_strategy, Optional[Tuple[int, ...]] py_version_info = None)
Definition at line 38 of file resolver.py.
    ):
        super().__init__()
        assert upgrade_strategy in self._allowed_strategies
        self.factory = Factory(
            finder=finder,
            preparer=preparer,
            make_install_req=make_install_req,
            wheel_cache=wheel_cache,
            use_user_site=use_user_site,
            force_reinstall=force_reinstall,
            ignore_installed=ignore_installed,
            ignore_requires_python=ignore_requires_python,
            py_version_info=py_version_info,
        )
        self.ignore_dependencies = ignore_dependencies
        self.upgrade_strategy = upgrade_strategy
        self._result: Optional[Result] = None
References __init__(), and _allowed_strategies.
Referenced by __init__().
Member Function Documentation
get_installation_order()
List[InstallRequirement] get_installation_order (self, RequirementSet req_set)
Get order for installation of requirements in RequirementSet.
The returned list contains a requirement before another that depends on
it. This helps ensure that the environment is kept consistent as they
get installed one-by-one.
The current implementation creates a topological ordering of the
dependency graph, giving more weight to packages with less
or no dependencies, while breaking any cycles in the graph at
arbitrary points. We make no guarantees about where the cycle
would be broken, other than it *would* be broken.
Reimplemented from BaseResolver.
Definition at line 167 of file resolver.py.
    ) -> List[InstallRequirement]:
        """Get order for installation of requirements in RequirementSet.
        The returned list contains a requirement before another that depends on
        it. This helps ensure that the environment is kept consistent as they
        get installed one-by-one.
        The current implementation creates a topological ordering of the
        dependency graph, giving more weight to packages with less
        or no dependencies, while breaking any cycles in the graph at
        arbitrary points. We make no guarantees about where the cycle
        would be broken, other than it *would* be broken.
        """
        assert self._result is not None, "must call resolve() first"
        if not req_set.requirements:
            # Nothing is left to install, so we do not need an order.
            return []
        graph = self._result.graph
        weights = get_topological_weights(graph, set(req_set.requirements.keys()))
        sorted_items = sorted(
            req_set.requirements.items(),
            key=functools.partial(_req_set_item_sorter, weights=weights),
            reverse=True,
        )
        return [ireq for _, ireq in sorted_items]
References _result, and pip._internal.resolution.resolvelib.resolver.get_topological_weights().
resolve()
RequirementSet resolve (self, List[InstallRequirement] root_reqs, bool check_supported_wheels)
Reimplemented from BaseResolver.
Definition at line 70 of file resolver.py.
    ) -> RequirementSet:
        collected = self.factory.collect_root_requirements(root_reqs)
        provider = PipProvider(
            factory=self.factory,
            constraints=collected.constraints,
            ignore_dependencies=self.ignore_dependencies,
            upgrade_strategy=self.upgrade_strategy,
            user_requested=collected.user_requested,
        )
        if "PIP_RESOLVER_DEBUG" in os.environ:
            reporter: BaseReporter = PipDebuggingReporter()
        else:
            reporter = PipReporter()
        resolver: RLResolver[Requirement, Candidate, str] = RLResolver(
            provider,
            reporter,
        )
        try:
            limit_how_complex_resolution_can_be = 200000
            result = self._result = resolver.resolve(
                collected.requirements, max_rounds=limit_how_complex_resolution_can_be
            )
        except ResolutionImpossible as e:
            error = self.factory.get_installation_error(
                cast("ResolutionImpossible[Requirement, Candidate]", e),
                collected.constraints,
            )
            raise error from e
        req_set = RequirementSet(check_supported_wheels=check_supported_wheels)
        for candidate in result.mapping.values():
            ireq = candidate.get_install_requirement()
            if ireq is None:
                continue
            # Check if there is already an installation under the same name,
            # and set a flag for later stages to uninstall it, if needed.
            installed_dist = self.factory.get_dist_to_uninstall(candidate)
            if installed_dist is None:
                # There is no existing installation -- nothing to uninstall.
                ireq.should_reinstall = False
            elif self.factory.force_reinstall:
                # The --force-reinstall flag is set -- reinstall.
                ireq.should_reinstall = True
            elif installed_dist.version != candidate.version:
                # The installation is different in version -- reinstall.
                ireq.should_reinstall = True
            elif candidate.is_editable or installed_dist.editable:
                # The incoming distribution is editable, or different in
                # editable-ness to installation -- reinstall.
                ireq.should_reinstall = True
            elif candidate.source_link and candidate.source_link.is_file:
                # The incoming distribution is under file://
                if candidate.source_link.is_wheel:
                    # is a local wheel -- do nothing.
                    logger.info(
                        "%s is already installed with the same version as the "
                        "provided wheel. Use --force-reinstall to force an "
                        "installation of the wheel.",
                        ireq.name,
                    )
                    continue
                # is a local sdist or path -- reinstall
                ireq.should_reinstall = True
            else:
                continue
            link = candidate.source_link
            if link and link.is_yanked:
                # The reason can contain non-ASCII characters, Unicode
                # is required for Python 2.
                msg = (
                    "The candidate selected for download or install is a "
                    "yanked version: {name!r} candidate (version {version} "
                    "at {link})\nReason for being yanked: {reason}"
                ).format(
                    name=candidate.name,
                    version=candidate.version,
                    link=link,
                    reason=link.yanked_reason or "<none given>",
                )
                logger.warning(msg)
            req_set.add_named_requirement(ireq)
        reqs = req_set.all_requirements
        self.factory.preparer.prepare_linked_requirements_more(reqs)
        for req in reqs:
            req.prepared = True
            req.needs_more_preparation = False
        return req_set
References _result, factory, ignore_dependencies, and upgrade_strategy.
Referenced by BaseConfigurator.configure_custom(), Configurator.configure_custom(), and BaseConfigurator.ext_convert().
Field Documentation
_allowed_strategies
dict _allowed_strategies = {"eager", "only-if-needed", "to-satisfy-only"} static protected
Definition at line 36 of file resolver.py.
Referenced by __init__().
_result
Optional[Result] _result = None protected
Definition at line 68 of file resolver.py.
Referenced by Capture.__exit__(), Capture.get(), get_installation_order(), and resolve().
factory
factory
Initial value:
=  Factory(
            finder=finder,
            preparer=preparer,
            make_install_req=make_install_req,
            wheel_cache=wheel_cache,
            use_user_site=use_user_site,
            force_reinstall=force_reinstall,
            ignore_installed=ignore_installed,
            ignore_requires_python=ignore_requires_python,
            py_version_info=py_version_info,
        )
Definition at line 55 of file resolver.py.
Referenced by resolve().
ignore_dependencies
ignore_dependencies = ignore_dependencies
Definition at line 66 of file resolver.py.
Referenced by resolve().
upgrade_strategy
upgrade_strategy = upgrade_strategy
Definition at line 67 of file resolver.py.
Referenced by resolve().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/resolution/resolvelib/resolver.py