Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: ParseExpression Class Reference
ParseExpression Class Reference
Public Member Functions
__init__ (self, typing.Iterable[ParserElement] exprs, bool savelist=False)
List[ParserElement] recurse (self)
ParserElement append (self, other)
ParserElement leave_whitespace (self, bool recursive=True)
ParserElement ignore_whitespace (self, bool recursive=True)
ParserElement ignore (self, other)
ParserElement streamline (self)
None validate (self, validateTrace=None)
ParserElement copy (self)
leaveWhitespace (self)
ignoreWhitespace (self)
Public Member Functions inherited from ParserElement
using_each (cls, seq, **class_kwargs)
__init__ (self, bool savelist=False)
"ParserElement" suppress_warning (self, Diagnostics warning_type)
visit_all (self)
"ParserElement" set_results_name (self, str name, bool list_all_matches=False, *, bool listAllMatches=False)
"ParserElement" set_break (self, bool break_flag=True)
"ParserElement" set_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_parse_action (self, *ParseAction fns, **kwargs)
"ParserElement" add_condition (self, *ParseCondition fns, **kwargs)
"ParserElement" set_fail_action (self, ParseFailAction fn)
int preParse (self, str instring, int loc)
parseImpl (self, instring, loc, doActions=True)
postParse (self, instring, loc, tokenlist)
int try_parse (self, str instring, int loc, *, bool raise_fatal=False, bool do_actions=False)
bool can_parse_next (self, str instring, int loc, bool do_actions=False)
ParseResults parse_string (self, str instring, bool parse_all=False, *, bool parseAll=False)
Generator[Tuple[ParseResults, int, int], None, None] scan_string (self, str instring, int max_matches=_MAX_INT, bool overlap=False, *, bool debug=False, int maxMatches=_MAX_INT)
str transform_string (self, str instring, *, bool debug=False)
ParseResults search_string (self, str instring, int max_matches=_MAX_INT, *, bool debug=False, int maxMatches=_MAX_INT)
Generator[str, None, None] split (self, str instring, int maxsplit=_MAX_INT, bool include_separators=False, *, includeSeparators=False)
"ParserElement" __add__ (self, other)
"ParserElement" __radd__ (self, other)
"ParserElement" __sub__ (self, other)
"ParserElement" __rsub__ (self, other)
"ParserElement" __mul__ (self, other)
"ParserElement" __rmul__ (self, other)
"ParserElement" __or__ (self, other)
"ParserElement" __ror__ (self, other)
"ParserElement" __xor__ (self, other)
"ParserElement" __rxor__ (self, other)
"ParserElement" __and__ (self, other)
"ParserElement" __rand__ (self, other)
"ParserElement" __invert__ (self)
__getitem__ (self, key)
"ParserElement" __call__ (self, typing.Optional[str] name=None)
"ParserElement" suppress (self)
"ParserElement" set_whitespace_chars (self, Union[Set[str], str] chars, bool copy_defaults=False)
"ParserElement" parse_with_tabs (self)
"ParserElement" set_debug_actions (self, DebugStartAction start_action, DebugSuccessAction success_action, DebugExceptionAction exception_action)
"ParserElement" set_debug (self, bool flag=True, bool recurse=False)
str default_name (self)
"ParserElement" set_name (self, str name)
str name (self)
str __str__ (self)
str __repr__ (self)
ParseResults parse_file (self, Union[str, Path, TextIO] file_or_filename, str encoding="utf-8", bool parse_all=False, *, bool parseAll=False)
__eq__ (self, other)
__hash__ (self)
bool matches (self, str test_string, bool parse_all=True, *, bool parseAll=True)
Tuple[bool, List[Tuple[str, Union[ParseResults, Exception]]]] run_tests (self, Union[str, List[str]] tests, bool parse_all=True, typing.Optional[Union["ParserElement", str]] comment="#", bool full_dump=True, bool print_results=True, bool failure_tests=False, typing.Optional[Callable[[str, ParseResults], str]] post_parse=None, typing.Optional[TextIO] file=None, bool with_line_numbers=False, *, bool parseAll=True, bool fullDump=True, bool printResults=True, bool failureTests=False, typing.Optional[Callable[[str, ParseResults], str]] postParse=None)
None create_diagram (self, Union[TextIO, Path, str] output_html, int vertical=3, bool show_results_names=False, bool show_groups=False, bool embed=False, **kwargs)
setResultsName (self)
setBreak (self)
setParseAction (self)
addParseAction (self)
addCondition (self)
setFailAction (self)
tryParse (self)
parseString (self)
scanString (self)
transformString (self)
searchString (self)
setWhitespaceChars (self)
parseWithTabs (self)
setDebugActions (self)
setDebug (self)
setName (self)
parseFile (self)
runTests (self)
Data Fields
List[ParserElement] exprs
Data Fields inherited from ParserElement
List[ParseAction] parseAction = list()
typing.Optional[ParseFailAction] failAction = None
str customName = None
str resultsName = None
saveAsList = savelist
bool skipWhitespace = True
whiteChars = set(ParserElement.DEFAULT_WHITE_CHARS)
bool copyDefaultWhiteChars = True
bool mayReturnEmpty = False
bool keepTabs = False
List[] ignoreExprs = list()
bool debug = False
bool streamlined = False
bool mayIndexError = True
str errmsg = ""
bool modalResults = True
debugActions = self.DebugActions(None, None, None)
bool callPreparse = True
bool callDuringTry = False
list suppress_warnings_ = []
Protected Member Functions
str _generateDefaultName (self)
_setResultsName (self, name, listAllMatches=False)
Protected Member Functions inherited from ParserElement
int _skipIgnorables (self, str instring, int loc)
Tuple[int, ParseResults] _parseNoCache (self, instring, loc, doActions=True, callPreParse=True)
Tuple[int, ParseResults] _parseCache (self, instring, loc, doActions=True, callPreParse=True)
_checkRecursion (self, parseElementList)
Additional Inherited Members
Static Public Member Functions inherited from ParserElement
None set_default_whitespace_chars (str chars)
None inline_literals_using (type cls)
None reset_cache ()
None disable_memoization ()
None enable_left_recursion (typing.Optional[int] cache_size_limit=None, *, force=False)
None enable_packrat (int cache_size_limit=128, *, bool force=False)
inlineLiteralsUsing ()
setDefaultWhitespaceChars ()
enableLeftRecursion ()
enablePackrat ()
Static Public Attributes inherited from ParserElement
str DEFAULT_WHITE_CHARS = " \n\t\r"
bool verbose_stacktrace = False
recursion_lock = RLock()
dict recursion_memos = {}
tuple packrat_cache
packrat_cache_lock = RLock()
list packrat_cache_stats = [0, 0]
bool canParseNext = can_parse_next
None resetCache = reset_cache
str defaultName = default_name
Protected Attributes inherited from ParserElement
typing.Optional[str] _defaultName = None
Static Protected Attributes inherited from ParserElement
type _literalStringClass = None
Tuple[int, ParseResults] _parse = _parseNoCache
bool _packratEnabled = False
bool _left_recursion_enabled = False
Detailed Description
Abstract subclass of ParserElement, for combining and
post-processing parsed tokens.
Definition at line 3728 of file core.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, typing.Iterable[ParserElement] exprs, bool savelist = False)
Definition at line 3733 of file core.py.
    def __init__(self, exprs: typing.Iterable[ParserElement], savelist: bool = False):
        super().__init__(savelist)
        self.exprs: List[ParserElement]
        if isinstance(exprs, _generatorType):
            exprs = list(exprs)
        if isinstance(exprs, str_type):
            self.exprs = [self._literalStringClass(exprs)]
        elif isinstance(exprs, ParserElement):
            self.exprs = [exprs]
        elif isinstance(exprs, Iterable):
            exprs = list(exprs)
            # if sequence of strings provided, wrap with Literal
            if any(isinstance(expr, str_type) for expr in exprs):
                exprs = (
                    self._literalStringClass(e) if isinstance(e, str_type) else e
                    for e in exprs
                )
            self.exprs = list(exprs)
        else:
            try:
                self.exprs = list(exprs)
            except TypeError:
                self.exprs = [exprs]
        self.callPreparse = False
References __init__().
Referenced by __init__().
Member Function Documentation
_generateDefaultName()
str _generateDefaultName (self) protected
Child classes must define this method, which defines how the ``default_name`` is set.
Reimplemented from ParserElement.
Reimplemented in And, Each, MatchFirst, and Or.
Definition at line 3804 of file core.py.
    def _generateDefaultName(self) -> str:
        return f"{self.__class__.__name__}:({str(self.exprs)})"
_setResultsName()
_setResultsName (self, name, listAllMatches = False) protected
Reimplemented from ParserElement.
Reimplemented in MatchFirst, and Or.
Definition at line 3865 of file core.py.
    def _setResultsName(self, name, listAllMatches=False):
        if (
            __diag__.warn_ungrouped_named_tokens_in_collection
            and Diagnostics.warn_ungrouped_named_tokens_in_collection
            not in self.suppress_warnings_
        ):
            for e in self.exprs:
                if (
                    isinstance(e, ParserElement)
                    and e.resultsName
                    and Diagnostics.warn_ungrouped_named_tokens_in_collection
                    not in e.suppress_warnings_
                ):
                    warnings.warn(
                        "{}: setting results name {!r} on {} expression "
                        "collides with {!r} on contained expression".format(
                            "warn_ungrouped_named_tokens_in_collection",
                            name,
                            type(self).__name__,
                            e.resultsName,
                        ),
                        stacklevel=3,
                    )
        return super()._setResultsName(name, listAllMatches)
References _setResultsName(), exprs, and ParserElement.suppress_warnings_.
Referenced by _setResultsName().
append()
ParserElement append (self, other)
Definition at line 3762 of file core.py.
    def append(self, other) -> ParserElement:
        self.exprs.append(other)
        self._defaultName = None
        return self
References append(), and exprs.
Referenced by And.__iadd__(), Each.__iand__(), MatchFirst.__ior__(), Or.__ixor__(), append(), and Stack.push().
copy()
ParserElement copy (self)
Make a copy of this :class:`ParserElement`.  Useful for defining
different parse actions for the same parsing pattern, using copies of
the original parse element.
Example::
    integer = Word(nums).set_parse_action(lambda toks: int(toks[0]))
    integerK = integer.copy().add_parse_action(lambda toks: toks[0] * 1024) + Suppress("K")
    integerM = integer.copy().add_parse_action(lambda toks: toks[0] * 1024 * 1024) + Suppress("M")
    print((integerK | integerM | integer)[1, ...].parse_string("5K 100 640K 256M"))
prints::
    [5120, 100, 655360, 268435456]
Equivalent form of ``expr.copy()`` is just ``expr()``::
    integerM = integer().add_parse_action(lambda toks: toks[0] * 1024 * 1024) + Suppress("M")
Reimplemented from ParserElement.
Definition at line 3859 of file core.py.
    def copy(self) -> ParserElement:
        ret = super().copy()
        ret = typing.cast(ParseExpression, ret)
        ret.exprs = [e.copy() for e in self.exprs]
        return ret
References copy(), and exprs.
Referenced by ParseResults.__add__(), Text.__add__(), ParseResults.__radd__(), copy(), ParseResults.deepcopy(), Text.divide(), ConsoleOptions.reset_height(), Text.split(), ConsoleOptions.update(), ConsoleOptions.update_dimensions(), ConsoleOptions.update_height(), ConsoleOptions.update_width(), Text.with_indent_guides(), and BaseRetrying.wraps().
ignore()
ParserElement ignore (self, other)
Define expression to be ignored (e.g., comments) while doing pattern
matching; may be called repeatedly, to define multiple comment or other
ignorable patterns.
Example::
    patt = Word(alphas)[1, ...]
    patt.parse_string('ablaj /* comment */ lskjd')
    # -> ['ablaj']
    patt.ignore(c_style_comment)
    patt.parse_string('ablaj /* comment */ lskjd')
    # -> ['ablaj', 'lskjd']
Reimplemented from ParserElement.
Definition at line 3792 of file core.py.
    def ignore(self, other) -> ParserElement:
        if isinstance(other, Suppress):
            if other not in self.ignoreExprs:
                super().ignore(other)
                for e in self.exprs:
                    e.ignore(self.ignoreExprs[-1])
        else:
            super().ignore(other)
            for e in self.exprs:
                e.ignore(self.ignoreExprs[-1])
        return self
ignore_whitespace()
ParserElement ignore_whitespace (self, bool recursive = True)
Extends ``ignore_whitespace`` defined in base class, and also invokes ``leave_whitespace`` on
   all contained expressions.
Reimplemented from ParserElement.
Definition at line 3780 of file core.py.
    def ignore_whitespace(self, recursive: bool = True) -> ParserElement:
        """
        Extends ``ignore_whitespace`` defined in base class, and also invokes ``leave_whitespace`` on
           all contained expressions.
        """
        super().ignore_whitespace(recursive)
        if recursive:
            self.exprs = [e.copy() for e in self.exprs]
            for e in self.exprs:
                e.ignore_whitespace(recursive)
        return self
References exprs, and ignore_whitespace().
Referenced by ignore_whitespace().
ignoreWhitespace()
ignoreWhitespace (self)
Reimplemented from ParserElement.
Definition at line 3897 of file core.py.
    def ignoreWhitespace(self): ...
leave_whitespace()
ParserElement leave_whitespace (self, bool recursive = True)
Extends ``leave_whitespace`` defined in base class, and also invokes ``leave_whitespace`` on
   all contained expressions.
Reimplemented from ParserElement.
Definition at line 3767 of file core.py.
    def leave_whitespace(self, recursive: bool = True) -> ParserElement:
        """
        Extends ``leave_whitespace`` defined in base class, and also invokes ``leave_whitespace`` on
           all contained expressions.
        """
        super().leave_whitespace(recursive)
        if recursive:
            self.exprs = [e.copy() for e in self.exprs]
            for e in self.exprs:
                e.leave_whitespace(recursive)
        return self
References exprs, and leave_whitespace().
Referenced by leave_whitespace().
leaveWhitespace()
leaveWhitespace (self)
Reimplemented from ParserElement.
Definition at line 3894 of file core.py.
    def leaveWhitespace(self): ...
recurse()
List[ParserElement] recurse (self)
Reimplemented from ParserElement.
Definition at line 3759 of file core.py.
    def recurse(self) -> List[ParserElement]:
        return self.exprs[:]
References exprs.
streamline()
ParserElement streamline (self)
Reimplemented from ParserElement.
Reimplemented in And, Each, MatchFirst, and Or.
Definition at line 3807 of file core.py.
    def streamline(self) -> ParserElement:
        if self.streamlined:
            return self
        super().streamline()
        for e in self.exprs:
            e.streamline()
        # collapse nested :class:`And`'s of the form ``And(And(And(a, b), c), d)`` to ``And(a, b, c, d)``
        # but only if there are no parse actions or resultsNames on the nested And's
        # (likewise for :class:`Or`'s and :class:`MatchFirst`'s)
        if len(self.exprs) == 2:
            other = self.exprs[0]
            if (
                isinstance(other, self.__class__)
                and not other.parseAction
                and other.resultsName is None
                and not other.debug
            ):
                self.exprs = other.exprs[:] + [self.exprs[1]]
                self._defaultName = None
                self.mayReturnEmpty |= other.mayReturnEmpty
                self.mayIndexError |= other.mayIndexError
            other = self.exprs[-1]
            if (
                isinstance(other, self.__class__)
                and not other.parseAction
                and other.resultsName is None
                and not other.debug
            ):
                self.exprs = self.exprs[:-1] + other.exprs[:]
                self._defaultName = None
                self.mayReturnEmpty |= other.mayReturnEmpty
                self.mayIndexError |= other.mayIndexError
        self.errmsg = "Expected " + str(self)
        return self
validate()
None validate (self, validateTrace = None)
Check defined expressions for valid structure, check for infinite recursive definitions.
Reimplemented from ParserElement.
Definition at line 3848 of file core.py.
    def validate(self, validateTrace=None) -> None:
        warnings.warn(
            "ParserElement.validate() is deprecated, and should not be used to check for left recursion",
            DeprecationWarning,
            stacklevel=2,
        )
        tmp = (validateTrace if validateTrace is not None else [])[:] + [self]
        for e in self.exprs:
            e.validate(tmp)
        self._checkRecursion([])
References ParserElement._checkRecursion(), and exprs.
Field Documentation
exprs
exprs
Definition at line 3735 of file core.py.
Referenced by And._checkRecursion(), And._generateDefaultName(), Each._generateDefaultName(), MatchFirst._generateDefaultName(), Or._generateDefaultName(), MatchFirst._setResultsName(), Or._setResultsName(), _setResultsName(), append(), copy(), ignore_whitespace(), leave_whitespace(), And.parseImpl(), MatchFirst.parseImpl(), Or.parseImpl(), recurse(), And.streamline(), Each.streamline(), Or.streamline(), and validate().
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/core.py