Let us walk on the 3-isogeny graph: _NotAPIContent Class Reference
_NotAPIContent Class Reference
Public Member Functions
None __init__ (self, str content_type, str request_desc)
Data Fields
content_type
request_desc
Detailed Description
Definition at line 66 of file collector.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self, str content_type, str request_desc)
Definition at line 67 of file collector.py.
    def __init__(self, content_type: str, request_desc: str) -> None:
        super().__init__(content_type, request_desc)
        self.content_type = content_type
        self.request_desc = request_desc
References _NotAPIContent.__init__(), and i.
Referenced by _NotAPIContent.__init__(), and Protocol.__init_subclass__().
Field Documentation
content_type
content_type
Definition at line 69 of file collector.py.
request_desc
request_desc
Definition at line 70 of file collector.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/index/collector.py