Let us walk on the 3-isogeny graph: pip._vendor.webencodings.mklabels Namespace Reference
pip._vendor.webencodings.mklabels Namespace Reference
Functions
assert_lower (string)
generate (url)
Detailed Description
    webencodings.mklabels
    ~~~~~~~~~~~~~~~~~~~~~
    Regenarate the webencodings.labels module.
    :copyright: Copyright 2012 by Simon Sapin
    :license: BSD, see LICENSE for details.
Function Documentation
assert_lower()
assert_lower (string)
Definition at line 20 of file mklabels.py.
def assert_lower(string):
    assert string == string.lower()
    return string
References i.
Referenced by pip._vendor.webencodings.mklabels.generate().
generate()
generate (url)
Definition at line 25 of file mklabels.py.
def generate(url):
    parts = ['''\
"""
    webencodings.labels
    ~~~~~~~~~~~~~~~~~~~
    Map encoding labels to their name.
    :copyright: Copyright 2012 by Simon Sapin
    :license: BSD, see LICENSE for details.
"""
# XXX Do not edit!
# This file is automatically generated by mklabels.py
LABELS = {
''']
    labels = [
        (repr(assert_lower(label)).lstrip('u'),
         repr(encoding['name']).lstrip('u'))
        for category in json.loads(urlopen(url).read().decode('ascii'))
        for encoding in category['encodings']
        for label in encoding['labels']]
    max_len = max(len(label) for label, name in labels)
    parts.extend(
        '    %s:%s %s,\n' % (label, ' ' * (max_len - len(label)), name)
        for label, name in labels)
    parts.append('}')
    return ''.join(parts)
References pip._vendor.webencodings.mklabels.assert_lower(), pip._vendor.webencodings.mklabels.generate(), and i.
Referenced by pip._vendor.webencodings.mklabels.generate().