Let us walk on the 3-isogeny graph: HashErrors Class Reference
HashErrors Class Reference
Public Member Functions
None __init__ (self)
None append (self, "HashError" error)
str __str__ (self)
bool __bool__ (self)
Data Fields
errors
head
Detailed Description
Multiple HashError instances rolled into one for reporting
Definition at line 424 of file exceptions.py.
Constructor & Destructor Documentation
__init__()
None __init__ (self)
Definition at line 427 of file exceptions.py.
    def __init__(self) -> None:
        self.errors: List["HashError"] = []
Referenced by Protocol.__init_subclass__().
Member Function Documentation
__bool__()
bool __bool__ (self)
Definition at line 443 of file exceptions.py.
    def __bool__(self) -> bool:
        return bool(self.errors)
__str__()
str __str__ (self)
Definition at line 433 of file exceptions.py.
    def __str__(self) -> str:
        lines = []
        self.errors.sort(key=lambda e: e.order)
        for cls, errors_of_cls in groupby(self.errors, lambda e: e.__class__):
            lines.append(cls.head)
            lines.extend(e.body() for e in errors_of_cls)
        if lines:
            return "\n".join(lines)
        return ""
append()
None append (self, "HashError" error)
Definition at line 430 of file exceptions.py.
    def append(self, error: "HashError") -> None:
        self.errors.append(error)
Referenced by And.__iadd__(), Each.__iand__(), MatchFirst.__ior__(), Or.__ixor__(), and Stack.push().
Field Documentation
errors
errors
Definition at line 436 of file exceptions.py.
Referenced by SimpleScrapingLocator._fetch(), PyPIJSONLocator._get_project(), and Locator.get_errors().
head
head
Definition at line 437 of file exceptions.py.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_internal/exceptions.py