Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: MacOS Class Reference
MacOS Class Reference
Public Member Functions
str user_data_dir (self)
str site_data_dir (self)
str user_config_dir (self)
str site_config_dir (self)
str user_cache_dir (self)
str site_cache_dir (self)
str user_state_dir (self)
str user_log_dir (self)
str user_documents_dir (self)
str user_downloads_dir (self)
str user_pictures_dir (self)
str user_videos_dir (self)
str user_music_dir (self)
str user_runtime_dir (self)
Public Member Functions inherited from PlatformDirsABC
None __init__ (self, str|None appname=None, str|None|Literal[False] appauthor=None, str|None version=None, bool roaming=False, bool multipath=False, bool opinion=True, bool ensure_exists=False)
Path user_data_path (self)
Path site_data_path (self)
Path user_config_path (self)
Path site_config_path (self)
Path user_cache_path (self)
Path site_cache_path (self)
Path user_state_path (self)
Path user_log_path (self)
Path user_documents_path (self)
Path user_downloads_path (self)
Path user_pictures_path (self)
Path user_videos_path (self)
Path user_music_path (self)
Path user_runtime_path (self)
Additional Inherited Members
Data Fields inherited from PlatformDirsABC
appname = appname
appauthor = appauthor
version = version
roaming = roaming
multipath = multipath
opinion = opinion
ensure_exists = ensure_exists
Protected Member Functions inherited from PlatformDirsABC
str _append_app_name_and_version (self, *str base)
None _optionally_create_directory (self, str path)
Detailed Description
Platform directories for the macOS operating system. Follows the guidance from `Apple documentation
<https://developer.apple.com/library/archive/documentation/FileManagement/Conceptual/FileSystemProgrammingGuide/MacOSXDirectories/MacOSXDirectories.html>`_.
Makes use of the `appname <platformdirs.api.PlatformDirsABC.appname>`,
`version <platformdirs.api.PlatformDirsABC.version>`,
`ensure_exists <platformdirs.api.PlatformDirsABC.ensure_exists>`.
Definition at line 9 of file macos.py.
Member Function Documentation
site_cache_dir()
str site_cache_dir (self)
:return: cache directory shared by users, e.g. ``/Library/Caches/$appname/$version``
Reimplemented from PlatformDirsABC.
Definition at line 44 of file macos.py.
    def site_cache_dir(self) -> str:
        """:return: cache directory shared by users, e.g. ``/Library/Caches/$appname/$version``"""
        return self._append_app_name_and_version("/Library/Caches")
References PlatformDirsABC._append_app_name_and_version().
site_config_dir()
str site_config_dir (self)
:return: config directory shared by the users, same as `site_data_dir`
Reimplemented from PlatformDirsABC.
Definition at line 34 of file macos.py.
    def site_config_dir(self) -> str:
        """:return: config directory shared by the users, same as `site_data_dir`"""
        return self.site_data_dir
References PlatformDirsABC.site_data_dir.
site_data_dir()
str site_data_dir (self)
:return: data directory shared by users, e.g. ``/Library/Application Support/$appname/$version``
Reimplemented from PlatformDirsABC.
Definition at line 24 of file macos.py.
    def site_data_dir(self) -> str:
        """:return: data directory shared by users, e.g. ``/Library/Application Support/$appname/$version``"""
        return self._append_app_name_and_version("/Library/Application Support")
References PlatformDirsABC._append_app_name_and_version().
user_cache_dir()
str user_cache_dir (self)
:return: cache directory tied to the user, e.g. ``~/Library/Caches/$appname/$version``
Reimplemented from PlatformDirsABC.
Definition at line 39 of file macos.py.
    def user_cache_dir(self) -> str:
        """:return: cache directory tied to the user, e.g. ``~/Library/Caches/$appname/$version``"""
        return self._append_app_name_and_version(os.path.expanduser("~/Library/Caches"))  # noqa: PTH111
References PlatformDirsABC._append_app_name_and_version().
user_config_dir()
str user_config_dir (self)
:return: config directory tied to the user, same as `user_data_dir`
Reimplemented from PlatformDirsABC.
Definition at line 29 of file macos.py.
    def user_config_dir(self) -> str:
        """:return: config directory tied to the user, same as `user_data_dir`"""
        return self.user_data_dir
References PlatformDirsABC.user_data_dir.
user_data_dir()
str user_data_dir (self)
:return: data directory tied to the user, e.g. ``~/Library/Application Support/$appname/$version``
Reimplemented from PlatformDirsABC.
Definition at line 19 of file macos.py.
    def user_data_dir(self) -> str:
        """:return: data directory tied to the user, e.g. ``~/Library/Application Support/$appname/$version``"""
        return self._append_app_name_and_version(os.path.expanduser("~/Library/Application Support"))  # noqa: PTH111
References PlatformDirsABC._append_app_name_and_version().
user_documents_dir()
str user_documents_dir (self)
:return: documents directory tied to the user, e.g. ``~/Documents``
Reimplemented from PlatformDirsABC.
Definition at line 59 of file macos.py.
    def user_documents_dir(self) -> str:
        """:return: documents directory tied to the user, e.g. ``~/Documents``"""
        return os.path.expanduser("~/Documents")  # noqa: PTH111
user_downloads_dir()
str user_downloads_dir (self)
:return: downloads directory tied to the user, e.g. ``~/Downloads``
Reimplemented from PlatformDirsABC.
Definition at line 64 of file macos.py.
    def user_downloads_dir(self) -> str:
        """:return: downloads directory tied to the user, e.g. ``~/Downloads``"""
        return os.path.expanduser("~/Downloads")  # noqa: PTH111
user_log_dir()
str user_log_dir (self)
:return: log directory tied to the user, e.g. ``~/Library/Logs/$appname/$version``
Reimplemented from PlatformDirsABC.
Definition at line 54 of file macos.py.
    def user_log_dir(self) -> str:
        """:return: log directory tied to the user, e.g. ``~/Library/Logs/$appname/$version``"""
        return self._append_app_name_and_version(os.path.expanduser("~/Library/Logs"))  # noqa: PTH111
References PlatformDirsABC._append_app_name_and_version().
user_music_dir()
str user_music_dir (self)
:return: music directory tied to the user, e.g. ``~/Music``
Reimplemented from PlatformDirsABC.
Definition at line 79 of file macos.py.
    def user_music_dir(self) -> str:
        """:return: music directory tied to the user, e.g. ``~/Music``"""
        return os.path.expanduser("~/Music")  # noqa: PTH111
user_pictures_dir()
str user_pictures_dir (self)
:return: pictures directory tied to the user, e.g. ``~/Pictures``
Reimplemented from PlatformDirsABC.
Definition at line 69 of file macos.py.
    def user_pictures_dir(self) -> str:
        """:return: pictures directory tied to the user, e.g. ``~/Pictures``"""
        return os.path.expanduser("~/Pictures")  # noqa: PTH111
user_runtime_dir()
str user_runtime_dir (self)
:return: runtime directory tied to the user, e.g. ``~/Library/Caches/TemporaryItems/$appname/$version``
Reimplemented from PlatformDirsABC.
Definition at line 84 of file macos.py.
    def user_runtime_dir(self) -> str:
        """:return: runtime directory tied to the user, e.g. ``~/Library/Caches/TemporaryItems/$appname/$version``"""
        return self._append_app_name_and_version(os.path.expanduser("~/Library/Caches/TemporaryItems"))  # noqa: PTH111
References PlatformDirsABC._append_app_name_and_version().
user_state_dir()
str user_state_dir (self)
:return: state directory tied to the user, same as `user_data_dir`
Reimplemented from PlatformDirsABC.
Definition at line 49 of file macos.py.
    def user_state_dir(self) -> str:
        """:return: state directory tied to the user, same as `user_data_dir`"""
        return self.user_data_dir
References PlatformDirsABC.user_data_dir.
user_videos_dir()
str user_videos_dir (self)
:return: videos directory tied to the user, e.g. ``~/Movies``
Reimplemented from PlatformDirsABC.
Definition at line 74 of file macos.py.
    def user_videos_dir(self) -> str:
        """:return: videos directory tied to the user, e.g. ``~/Movies``"""
        return os.path.expanduser("~/Movies")  # noqa: PTH111
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/platformdirs/macos.py