Let us walk on the 3-isogeny graph: pip._internal.utils.setuptools_build Namespace Reference
pip._internal.utils.setuptools_build Namespace Reference
Functions
List[str] make_setuptools_shim_args (str setup_py_path, Optional[Sequence[str]] global_options=None, bool no_user_config=False, bool unbuffered_output=False)
List[str] make_setuptools_bdist_wheel_args (str setup_py_path, Sequence[str] global_options, Sequence[str] build_options, str destination_dir)
List[str] make_setuptools_clean_args (str setup_py_path, Sequence[str] global_options)
List[str] make_setuptools_develop_args (str setup_py_path, *Sequence[str] global_options, bool no_user_config, Optional[str] prefix, Optional[str] home, bool use_user_site)
List[str] make_setuptools_egg_info_args (str setup_py_path, Optional[str] egg_info_dir, bool no_user_config)
Variables
_SETUPTOOLS_SHIM
Function Documentation
make_setuptools_bdist_wheel_args()
List[str] make_setuptools_bdist_wheel_args (str setup_py_path, Sequence[str] global_options, Sequence[str] build_options, str destination_dir)
Definition at line 75 of file setuptools_build.py.
) -> List[str]:
    # NOTE: Eventually, we'd want to also -S to the flags here, when we're
    # isolating. Currently, it breaks Python in virtualenvs, because it
    # relies on site.py to find parts of the standard library outside the
    # virtualenv.
    args = make_setuptools_shim_args(
        setup_py_path, global_options=global_options, unbuffered_output=True
    )
    args += ["bdist_wheel", "-d", destination_dir]
    args += build_options
    return args
References pip._internal.utils.setuptools_build.make_setuptools_shim_args().
make_setuptools_clean_args()
List[str] make_setuptools_clean_args (str setup_py_path, Sequence[str] global_options)
Definition at line 93 of file setuptools_build.py.
) -> List[str]:
    args = make_setuptools_shim_args(
        setup_py_path, global_options=global_options, unbuffered_output=True
    )
    args += ["clean", "--all"]
    return args
References pip._internal.utils.setuptools_build.make_setuptools_shim_args().
make_setuptools_develop_args()
List[str] make_setuptools_develop_args (str setup_py_path, *Sequence[str] global_options, bool no_user_config, Optional[str] prefix, Optional[str] home, bool use_user_site)
Definition at line 104 of file setuptools_build.py.
) -> List[str]:
    assert not (use_user_site and prefix)
    args = make_setuptools_shim_args(
        setup_py_path,
        global_options=global_options,
        no_user_config=no_user_config,
    )
    args += ["develop", "--no-deps"]
    if prefix:
        args += ["--prefix", prefix]
    if home is not None:
        args += ["--install-dir", home]
    if use_user_site:
        args += ["--user", "--prefix="]
    return args
References pip._internal.utils.setuptools_build.make_setuptools_shim_args().
make_setuptools_egg_info_args()
List[str] make_setuptools_egg_info_args (str setup_py_path, Optional[str] egg_info_dir, bool no_user_config)
Definition at line 134 of file setuptools_build.py.
) -> List[str]:
    args = make_setuptools_shim_args(setup_py_path, no_user_config=no_user_config)
    args += ["egg_info"]
    if egg_info_dir:
        args += ["--egg-base", egg_info_dir]
    return args
References pip._internal.utils.setuptools_build.make_setuptools_shim_args().
make_setuptools_shim_args()
List[str] make_setuptools_shim_args (str setup_py_path, Optional[Sequence[str]] global_options = None, bool no_user_config = False, bool unbuffered_output = False)
Get setuptools command arguments with shim wrapped setup file invocation.
:param setup_py_path: The path to setup.py to be wrapped.
:param global_options: Additional global options.
:param no_user_config: If True, disables personal user configuration.
:param unbuffered_output: If True, adds the unbuffered switch to the
 argument list.
Definition at line 49 of file setuptools_build.py.
) -> List[str]:
    """
    Get setuptools command arguments with shim wrapped setup file invocation.
    :param setup_py_path: The path to setup.py to be wrapped.
    :param global_options: Additional global options.
    :param no_user_config: If True, disables personal user configuration.
    :param unbuffered_output: If True, adds the unbuffered switch to the
     argument list.
    """
    args = [sys.executable]
    if unbuffered_output:
        args += ["-u"]
    args += ["-c", _SETUPTOOLS_SHIM.format(setup_py_path)]
    if global_options:
        args += global_options
    if no_user_config:
        args += ["--no-user-cfg"]
    return args
References i.
Referenced by pip._internal.utils.setuptools_build.make_setuptools_bdist_wheel_args(), pip._internal.utils.setuptools_build.make_setuptools_clean_args(), pip._internal.utils.setuptools_build.make_setuptools_develop_args(), and pip._internal.utils.setuptools_build.make_setuptools_egg_info_args().
Variable Documentation
_SETUPTOOLS_SHIM
_SETUPTOOLS_SHIM protected
Initial value:
=  textwrap.dedent(
).rstrip()
Definition at line 8 of file setuptools_build.py.