Let us walk on the 3-isogeny graph: /home/liwuen/projects_dev/pqc-engineering-ssec-23/c-code/benchmarks/common/hal.h File Reference
hal.h File Reference
#include <stdint.h>
#include <stddef.h>
Enumerations
enum clock_mode { CLOCK_FAST , CLOCK_BENCHMARK }
Functions
void hal_setup (const enum clock_mode clock)
uint64_t hal_get_time (void)
Enumeration Type Documentation
clock_mode
enum clock_mode
Enumerator
CLOCK_FAST
CLOCK_BENCHMARK
Definition at line 7 of file hal.h.
                {
    CLOCK_FAST,
    CLOCK_BENCHMARK
};
Function Documentation
hal_get_time()
uint64_t hal_get_time (void)
Definition at line 10 of file hal-cortexa.c.
{
#if defined(AARCH64)
    uint64_t t;
    asm volatile("mrs %0, PMCCNTR_EL0":"=r"(t));
    return t;
    #elif defined(ARMV7l)
        // TODO: this is actually a 32-bit counter, so it won't work for very long running schemes
        //       need to figure out a way to get a 64-bit cycle counter
        unsigned int cc;
    asm volatile("mrc p15, 0, %0, c9, c13, 0" : "=r"(cc));
    return cc;
    #elif defined(x8664)
        uint64_t t = 0;
    return t;
#else
    uint64_t t = 0;
    return t;
#endif
}
Referenced by cshake128_simple(), cshake128_simple_absorb(), cshake128_simple_squeezeblocks(), cshake256_simple(), cshake256_simple_absorb(), cshake256_simple_squeezeblocks(), sha3_256(), sha3_256_inc_absorb(), sha3_256_inc_finalize(), sha3_256_inc_init(), sha3_384(), sha3_384_inc_absorb(), sha3_384_inc_finalize(), sha3_384_inc_init(), sha3_512(), sha3_512_inc_absorb(), sha3_512_inc_finalize(), sha3_512_inc_init(), shake128(), shake128_absorb(), shake128_inc_absorb(), shake128_inc_finalize(), shake128_inc_init(), shake128_inc_squeeze(), shake128_squeezeblocks(), shake256(), shake256_absorb(), shake256_inc_absorb(), shake256_inc_finalize(), shake256_inc_init(), shake256_inc_squeeze(), and shake256_squeezeblocks().
hal_setup()
void hal_setup (const enum clock_mode clock)
Definition at line 4 of file hal-cortexa.c.
{
    (void)clock;
    //TODO figure out if we need to do someting here
}