Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: NTLMConnectionPool Class Reference
NTLMConnectionPool Class Reference
Public Member Functions
__init__ (self, user, pw, authurl, *args, **kwargs)
urlopen (self, method, url, body=None, headers=None, retries=3, redirect=True, assert_same_host=True)
Public Member Functions inherited from HTTPSConnectionPool
__init__ (self, host, port=None, strict=False, timeout=Timeout.DEFAULT_TIMEOUT, maxsize=1, block=False, headers=None, retries=None, _proxy=None, _proxy_headers=None, key_file=None, cert_file=None, cert_reqs=None, key_password=None, ca_certs=None, ssl_version=None, assert_hostname=None, assert_fingerprint=None, ca_cert_dir=None, **conn_kw)
Public Member Functions inherited from HTTPConnectionPool
__init__ (self, host, port=None, strict=False, timeout=Timeout.DEFAULT_TIMEOUT, maxsize=1, block=False, headers=None, retries=None, _proxy=None, _proxy_headers=None, _proxy_config=None, **conn_kw)
close (self)
is_same_host (self, url)
Public Member Functions inherited from ConnectionPool
__init__ (self, host, port=None)
__str__ (self)
__enter__ (self)
__exit__ (self, exc_type, exc_val, exc_tb)
Public Member Functions inherited from RequestMethods
__init__ (self, headers=None)
request (self, method, url, fields=None, headers=None, **urlopen_kw)
request_encode_url (self, method, url, fields=None, headers=None, **urlopen_kw)
request_encode_body (self, method, url, fields=None, headers=None, encode_multipart=True, multipart_boundary=None, **urlopen_kw)
Data Fields
authurl = authurl
rawuser = user
domain = user_parts[0].upper()
user = user_parts[1]
pw = pw
Data Fields inherited from HTTPSConnectionPool
key_file = key_file
cert_file = cert_file
cert_reqs = cert_reqs
key_password = key_password
ca_certs = ca_certs
ca_cert_dir = ca_cert_dir
ssl_version = ssl_version
assert_hostname = assert_hostname
assert_fingerprint = assert_fingerprint
Data Fields inherited from HTTPConnectionPool
strict = strict
timeout = timeout
retries = retries
pool = self.QueueCls(maxsize)
block = block
proxy = _proxy
proxy_headers = _proxy_headers or {}
proxy_config = _proxy_config
int num_connections = 0
int num_requests = 0
conn_kw = conn_kw
Data Fields inherited from ConnectionPool
host = _normalize_host(host, scheme=self.scheme)
port = port
Data Fields inherited from RequestMethods
headers = headers or {}
Protected Member Functions
_new_conn (self)
Protected Member Functions inherited from HTTPSConnectionPool
_prepare_conn (self, conn)
_prepare_proxy (self, conn)
_validate_conn (self, conn)
Protected Member Functions inherited from HTTPConnectionPool
_get_conn (self, timeout=None)
_put_conn (self, conn)
_get_timeout (self, timeout)
_raise_timeout (self, err, url, timeout_value)
_make_request (self, conn, method, url, timeout=_Default, chunked=False, **httplib_request_kw)
_absolute_url (self, path)
Additional Inherited Members
Static Public Attributes inherited from HTTPConnectionPool
ConnectionCls = HTTPConnection
ResponseCls = HTTPResponse
Static Public Attributes inherited from ConnectionPool
scheme = None
QueueCls = LifoQueue
Protected Attributes inherited from ConnectionPool
_proxy_host = host.lower()
Static Protected Attributes inherited from RequestMethods
dict _encode_url_methods = {"DELETE", "GET", "HEAD", "OPTIONS"}
Detailed Description
Implements an NTLM authentication version of an urllib3 connection pool
Definition at line 27 of file ntlmpool.py.
Constructor & Destructor Documentation
__init__()
__init__ (self, user, pw, authurl, * args, ** kwargs)
authurl is a random URL on the server that is protected by NTLM.
user is the Windows user, probably in the DOMAIN\\username format.
pw is the password for the user.
Definition at line 34 of file ntlmpool.py.
    def __init__(self, user, pw, authurl, *args, **kwargs):
        """
        authurl is a random URL on the server that is protected by NTLM.
        user is the Windows user, probably in the DOMAIN\\username format.
        pw is the password for the user.
        """
        super(NTLMConnectionPool, self).__init__(*args, **kwargs)
        self.authurl = authurl
        self.rawuser = user
        user_parts = user.split("\\", 1)
        self.domain = user_parts[0].upper()
        self.user = user_parts[1]
        self.pw = pw
References __init__().
Referenced by __init__().
Member Function Documentation
_new_conn()
_new_conn (self) protected
Return a fresh :class:`http.client.HTTPSConnection`.
Reimplemented from HTTPSConnectionPool.
Definition at line 48 of file ntlmpool.py.
    def _new_conn(self):
        # Performs the NTLM handshake that secures the connection. The socket
        # must be kept open while requests are performed.
        self.num_connections += 1
        log.debug(
            "Starting NTLM HTTPS connection no. %d: https://%s%s",
            self.num_connections,
            self.host,
            self.authurl,
        )
        headers = {"Connection": "Keep-Alive"}
        req_header = "Authorization"
        resp_header = "www-authenticate"
        conn = HTTPSConnection(host=self.host, port=self.port)
        # Send negotiation message
        headers[req_header] = "NTLM %s" % ntlm.create_NTLM_NEGOTIATE_MESSAGE(
            self.rawuser
        )
        log.debug("Request headers: %s", headers)
        conn.request("GET", self.authurl, None, headers)
        res = conn.getresponse()
        reshdr = dict(res.headers)
        log.debug("Response status: %s %s", res.status, res.reason)
        log.debug("Response headers: %s", reshdr)
        log.debug("Response data: %s [...]", res.read(100))
        # Remove the reference to the socket, so that it can not be closed by
        # the response object (we want to keep the socket open)
        res.fp = None
        # Server should respond with a challenge message
        auth_header_values = reshdr[resp_header].split(", ")
        auth_header_value = None
        for s in auth_header_values:
            if s[:5] == "NTLM ":
                auth_header_value = s[5:]
        if auth_header_value is None:
            raise Exception(
                "Unexpected %s response header: %s" % (resp_header, reshdr[resp_header])
            )
        # Send authentication message
        ServerChallenge, NegotiateFlags = ntlm.parse_NTLM_CHALLENGE_MESSAGE(
            auth_header_value
        )
        auth_msg = ntlm.create_NTLM_AUTHENTICATE_MESSAGE(
            ServerChallenge, self.user, self.domain, self.pw, NegotiateFlags
        )
        headers[req_header] = "NTLM %s" % auth_msg
        log.debug("Request headers: %s", headers)
        conn.request("GET", self.authurl, None, headers)
        res = conn.getresponse()
        log.debug("Response status: %s %s", res.status, res.reason)
        log.debug("Response headers: %s", dict(res.headers))
        log.debug("Response data: %s [...]", res.read()[:100])
        if res.status != 200:
            if res.status == 401:
                raise Exception("Server rejected request: wrong username or password")
            raise Exception("Wrong server response: %s %s" % (res.status, res.reason))
        res.fp = None
        log.debug("Connection established")
        return conn
References HTTPConnectionPool.num_connections.
urlopen()
urlopen (self, method, url, body = None, headers = None, retries = 3, redirect = True, assert_same_host = True)
Get a connection from the pool and perform an HTTP request. This is the
lowest level call for making a request, so you'll need to specify all
the raw details.
.. note::
   More commonly, it's appropriate to use a convenience method provided
   by :class:`.RequestMethods`, such as :meth:`request`.
.. note::
   `release_conn` will only behave as expected if
   `preload_content=False` because we want to make
   `preload_content=False` the default behaviour someday soon without
   breaking backwards compatibility.
:param method:
    HTTP request method (such as GET, POST, PUT, etc.)
:param url:
    The URL to perform the request on.
:param body:
    Data to send in the request body, either :class:`str`, :class:`bytes`,
    an iterable of :class:`str`/:class:`bytes`, or a file-like object.
:param headers:
    Dictionary of custom headers to send, such as User-Agent,
    If-None-Match, etc. If None, pool headers are used. If provided,
    these headers completely replace any pool-specific headers.
:param retries:
    Configure the number of retries to allow before raising a
    :class:`~urllib3.exceptions.MaxRetryError` exception.
    Pass ``None`` to retry until you receive a response. Pass a
    :class:`~urllib3.util.retry.Retry` object for fine-grained control
    over different types of retries.
    Pass an integer number to retry connection errors that many times,
    but no other types of errors. Pass zero to never retry.
    If ``False``, then retries are disabled and any exception is raised
    immediately. Also, instead of raising a MaxRetryError on redirects,
    the redirect response will be returned.
:type retries: :class:`~urllib3.util.retry.Retry`, False, or an int.
:param redirect:
    If True, automatically handle redirects (status codes 301, 302,
    303, 307, 308). Each redirect counts as a retry. Disabling retries
    will disable redirect, too.
:param assert_same_host:
    If ``True``, will make sure that the host of the pool requests is
    consistent else will raise HostChangedError. When ``False``, you can
    use the pool on an HTTP proxy and request foreign hosts.
:param timeout:
    If specified, overrides the default timeout for this one
    request. It may be a float (in seconds) or an instance of
    :class:`urllib3.util.Timeout`.
:param pool_timeout:
    If set and the pool is set to block=True, then this method will
    block for ``pool_timeout`` seconds and raise EmptyPoolError if no
    connection is available within the time period.
:param release_conn:
    If False, then the urlopen call will not release the connection
    back into the pool once a response is received (but will release if
    you read the entire contents of the response such as when
    `preload_content=True`). This is useful if you're not preloading
    the response's content immediately. You will need to call
    ``r.release_conn()`` on the response ``r`` to return the connection
    back into the pool. If None, it takes the value of
    ``response_kw.get('preload_content', True)``.
:param chunked:
    If True, urllib3 will send the body using chunked transfer
    encoding. Otherwise, urllib3 will send the body using the standard
    content-length form. Defaults to False.
:param int body_pos:
    Position to seek to in file-like body in the event of a retry or
    redirect. Typically this won't need to be set because urllib3 will
    auto-populate the value when needed.
:param \\**response_kw:
    Additional parameters are passed to
    :meth:`urllib3.response.HTTPResponse.from_httplib`
Reimplemented from HTTPConnectionPool.
Definition at line 115 of file ntlmpool.py.
    ):
        if headers is None:
            headers = {}
        headers["Connection"] = "Keep-Alive"
        return super(NTLMConnectionPool, self).urlopen(
            method, url, body, headers, retries, redirect, assert_same_host
        )
References urlopen().
Referenced by RequestMethods.request_encode_body(), RequestMethods.request_encode_url(), urlopen(), and PoolManager.urlopen().
Field Documentation
authurl
authurl = authurl
Definition at line 41 of file ntlmpool.py.
domain
domain = user_parts[0].upper()
Definition at line 44 of file ntlmpool.py.
pw
pw = pw
Definition at line 46 of file ntlmpool.py.
rawuser
rawuser = user
Definition at line 42 of file ntlmpool.py.
user
user = user_parts[1]
Definition at line 45 of file ntlmpool.py.
The documentation for this class was generated from the following file:
E:/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/urllib3/contrib/ntlmpool.py