Let us walk on the 3-isogeny graph: efficient, fast, and simpleProject: pip._vendor.colorama.tests.utils Namespace Reference
pip._vendor.colorama.tests.utils Namespace Reference
Data Structures
class StreamNonTTY
class StreamTTY
Functions
osname (name)
replace_by (stream)
replace_original_by (stream)
pycharm ()
Function Documentation
osname()
osname (name)
Definition at line 17 of file utils.py.
def osname(name):
    orig = os.name
    os.name = name
    yield
    os.name = orig
@contextmanager
pycharm()
pycharm ()
Definition at line 44 of file utils.py.
def pycharm():
    os.environ["PYCHARM_HOSTED"] = "1"
    non_tty = StreamNonTTY()
    with replace_by(non_tty), replace_original_by(non_tty):
        yield
    del os.environ["PYCHARM_HOSTED"]
References replace_by(), and replace_original_by().
replace_by()
replace_by (stream)
Definition at line 24 of file utils.py.
def replace_by(stream):
    orig_stdout = sys.stdout
    orig_stderr = sys.stderr
    sys.stdout = stream
    sys.stderr = stream
    yield
    sys.stdout = orig_stdout
    sys.stderr = orig_stderr
@contextmanager
Referenced by pycharm().
replace_original_by()
replace_original_by (stream)
Definition at line 34 of file utils.py.
def replace_original_by(stream):
    orig_stdout = sys.__stdout__
    orig_stderr = sys.__stderr__
    sys.__stdout__ = stream
    sys.__stderr__ = stream
    yield
    sys.__stdout__ = orig_stdout
    sys.__stderr__ = orig_stderr
@contextmanager
Referenced by pycharm().