Let us walk on the 3-isogeny graph: pyparsing_test.TestParseResultsAsserts Class Reference
pyparsing_test.TestParseResultsAsserts Class Reference
Public Member Functions
assertParseResultsEquals (self, result, expected_list=None, expected_dict=None, msg=None)
assertParseAndCheckList (self, expr, test_string, expected_list, msg=None, verbose=True)
assertParseAndCheckDict (self, expr, test_string, expected_dict, msg=None, verbose=True)
assertRunTestResults (self, run_tests_report, expected_parse_results=None, msg=None)
assertRaisesParseException (self, exc_type=ParseException, msg=None)
Detailed Description
A mixin class to add parse results assertion methods to normal unittest.TestCase classes.
Definition at line 124 of file testing.py.
Member Function Documentation
assertParseAndCheckDict()
assertParseAndCheckDict (self, expr, test_string, expected_dict, msg = None, verbose = True)
Convenience wrapper assert to test a parser element and input string, and assert that
the resulting ``ParseResults.asDict()`` is equal to the ``expected_dict``.
Definition at line 155 of file testing.py.
        ):
            """
            Convenience wrapper assert to test a parser element and input string, and assert that
            the resulting ``ParseResults.asDict()`` is equal to the ``expected_dict``.
            """
            result = expr.parse_string(test_string, parseAll=True)
            if verbose:
                print(result.dump())
            else:
                print(result.as_list())
            self.assertParseResultsEquals(result, expected_dict=expected_dict, msg=msg)
References pyparsing_test.TestParseResultsAsserts.assertParseResultsEquals(), and i.
assertParseAndCheckList()
assertParseAndCheckList (self, expr, test_string, expected_list, msg = None, verbose = True)
Convenience wrapper assert to test a parser element and input string, and assert that
the resulting ``ParseResults.asList()`` is equal to the ``expected_list``.
Definition at line 141 of file testing.py.
        ):
            """
            Convenience wrapper assert to test a parser element and input string, and assert that
            the resulting ``ParseResults.asList()`` is equal to the ``expected_list``.
            """
            result = expr.parse_string(test_string, parse_all=True)
            if verbose:
                print(result.dump())
            else:
                print(result.as_list())
            self.assertParseResultsEquals(result, expected_list=expected_list, msg=msg)
References pyparsing_test.TestParseResultsAsserts.assertParseResultsEquals(), and i.
assertParseResultsEquals()
assertParseResultsEquals (self, result, expected_list = None, expected_dict = None, msg = None)
Unit test assertion to compare a :class:`ParseResults` object with an optional ``expected_list``,
and compare any defined results names with an optional ``expected_dict``.
Definition at line 129 of file testing.py.
        ):
            """
            Unit test assertion to compare a :class:`ParseResults` object with an optional ``expected_list``,
            and compare any defined results names with an optional ``expected_dict``.
            """
            if expected_list is not None:
                self.assertEqual(expected_list, result.as_list(), msg=msg)
            if expected_dict is not None:
                self.assertEqual(expected_dict, result.as_dict(), msg=msg)
References i.
Referenced by pyparsing_test.TestParseResultsAsserts.assertParseAndCheckDict(), pyparsing_test.TestParseResultsAsserts.assertParseAndCheckList(), and pyparsing_test.TestParseResultsAsserts.assertRunTestResults().
assertRaisesParseException()
assertRaisesParseException (self, exc_type = ParseException, msg = None)
Definition at line 233 of file testing.py.
        def assertRaisesParseException(self, exc_type=ParseException, msg=None):
            with self.assertRaises(exc_type, msg=msg):
                yield
    @staticmethod
assertRunTestResults()
assertRunTestResults (self, run_tests_report, expected_parse_results = None, msg = None)
Unit test assertion to evaluate output of ``ParserElement.runTests()``. If a list of
list-dict tuples is given as the ``expected_parse_results`` argument, then these are zipped
with the report tuples returned by ``runTests`` and evaluated using ``assertParseResultsEquals``.
Finally, asserts that the overall ``runTests()`` success value is ``True``.
:param run_tests_report: tuple(bool, [tuple(str, ParseResults or Exception)]) returned from runTests
:param expected_parse_results (optional): [tuple(str, list, dict, Exception)]
Definition at line 169 of file testing.py.
        ):
            """
            Unit test assertion to evaluate output of ``ParserElement.runTests()``. If a list of
            list-dict tuples is given as the ``expected_parse_results`` argument, then these are zipped
            with the report tuples returned by ``runTests`` and evaluated using ``assertParseResultsEquals``.
            Finally, asserts that the overall ``runTests()`` success value is ``True``.
            :param run_tests_report: tuple(bool, [tuple(str, ParseResults or Exception)]) returned from runTests
            :param expected_parse_results (optional): [tuple(str, list, dict, Exception)]
            """
            run_test_success, run_test_results = run_tests_report
            if expected_parse_results is not None:
                merged = [
                    (*rpt, expected)
                    for rpt, expected in zip(run_test_results, expected_parse_results)
                ]
                for test_string, result, expected in merged:
                    # expected should be a tuple containing a list and/or a dict or an exception,
                    # and optional failure message string
                    # an empty tuple will skip any result validation
                    fail_msg = next(
                        (exp for exp in expected if isinstance(exp, str)), None
                    )
                    expected_exception = next(
                        (
                            exp
                            for exp in expected
                            if isinstance(exp, type) and issubclass(exp, Exception)
                        ),
                        None,
                    )
                    if expected_exception is not None:
                        with self.assertRaises(
                            expected_exception=expected_exception, msg=fail_msg or msg
                        ):
                            if isinstance(result, Exception):
                                raise result
                    else:
                        expected_list = next(
                            (exp for exp in expected if isinstance(exp, list)), None
                        )
                        expected_dict = next(
                            (exp for exp in expected if isinstance(exp, dict)), None
                        )
                        if (expected_list, expected_dict) != (None, None):
                            self.assertParseResultsEquals(
                                result,
                                expected_list=expected_list,
                                expected_dict=expected_dict,
                                msg=fail_msg or msg,
                            )
                        else:
                            # warning here maybe?
                            print(f"no validation for {test_string!r}")
            # do this last, in case some specific test results can be reported instead
            self.assertTrue(
                run_test_success, msg=msg if msg is not None else "failed runTests"
            )
References pyparsing_test.TestParseResultsAsserts.assertParseResultsEquals(), and i.
The documentation for this class was generated from the following file:
/home/liwuen/projects_dev/pqc-engineering-ssec-23/venv/lib/python3.12/site-packages/pip/_vendor/pyparsing/testing.py