name: Build and testing multiple primes' targets.

on:
  push:
    branches: [ "1-create-cicd-environment" ]
  pull_request:
    branches: [ "1-create-cicd-environment" ]

jobs:
  build-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-ccode-dir=${{ github.workspace }}/c-code" >> "$GITHUB_OUTPUT"
          echo "build-output-dir=${{ github.workspace }}/c-code/cmake-build-release" >> "$GITHUB_OUTPUT"

      - name: Configuring CMake for all primes' libraries and tests targets
        run: |
          cd c-code
          cmake -B cmake-build-release -DCMAKE_C_COMPILER=gcc -DCMAKE_BUILD_TYPE=Release

      - name: Build all primes' libraries and tests targets
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          make

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cmake-build-release
          path: ${{ steps.strings.outputs.build-output-dir }}

  build-cycles:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set reusable strings
        id: strings
        shell: bash
        run: |
          echo "build-ccode-dir-cycles=${{ github.workspace }}/c-code" >> "$GITHUB_OUTPUT"
          echo "build-output-dir-cycles=${{ github.workspace }}/c-code/cmake-build-release-cycles" >> "$GITHUB_OUTPUT"

      - name: Configuring CMake for all primes' libraries and tests targets
        run: |
          cd c-code
          cmake -DCMAKE_BUILD_TYPE=Release -DBENCHMARKING=CYCLES -DARCHITECTURE=x8664 -B cmake-build-release-cycles-x8664

      - name: Build all primes' libraries and tests targets
        working-directory: ${{ steps.strings.outputs.build-output-dir-cycles }}
        run: |
          make

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cmake-build-release-cycles
          path: ${{ steps.strings.outputs.build-output-dir-cycles }}


  test-p254:
    name: Test prime 254
    runs-on: ubuntu-latest
    needs: build-all
    steps:
      - name: Downloading p254 artifact
        uses: actions/download-artifact@v4
        with:
          name: cmake-build-release
          path: ${{ steps.strings.outputs.build-output-dir }}

      - name: Restoring execution permission
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          cd tests
          chmod +x tests-ssec-p254

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          cd tests
          ./tests-ssec-p254

  benchmark-p254:
    name: Benchmark prime 254
    runs-on: ubuntu-latest
    needs: build-cycles
    steps:
      - name: Downloading p254 CYCLES artifact
        uses: actions/download-artifact@v4
        with:
          name: cmake-build-release-cycles
          path: ${{ steps.strings.outputs.build-output-dir-cycles }}

      - name: Restoring execution permission
        working-directory: ${{ steps.strings.outputs.build-output-dir-cycles }}
        run: |
          cd benchmarks
          chmod +x benchmarks-ssec-p254

      - name: Test
        working-directory: ${{ steps.strings.outputs.build-output-dir }}
        run: |
          benchmarks/benchmarks-ssec-p254