Let us walk on the 3-isogeny graph: /home/liwuen/projects_dev/pqc-engineering-ssec-23/c-code/src/rng.c File Reference
rng.c File Reference
#include "rng.h"
#include <stdlib.h>
#include <unistd.h>
#include <fcntl.h>
Functions
void randombytes (void *x, size_t l)
Function Documentation
randombytes()
void randombytes (void * x, size_t l)
Definition at line 8 of file rng.c.
{
    static int fd = -1;
    ssize_t n;
    if (fd < 0 && 0 > (fd = open("/dev/urandom", O_RDONLY)))
        exit(1);
    for (size_t i = 0; i < l; i += n)
        if (0 >= (n = read(fd, (char *) x + i, l - i)))
            exit(2);
}
References i.
Referenced by csidh_private(), fp_random(), fp_sample(), isogeny_walks_sample_bit_string(), isogeny_walks_sample_trit_string(), random_boundedl1(), random_coin(), and random_wombats().